### ISSUE TITLE
Clicking on a CSS class name in the template does not scroll to the definition and no uses are listed in the style section

### ISSUE THREAD

**Issue by angelov-a** [vuejs/language-tools#4216] opened 2024-04-05 09:44 UTC
Before it was possible to Cmd+click on a CSS class in the `<template>` section and it would scroll to the corresponding definition in the `<style>` tag.

In the `<style>` tag for each definition there were listed uses with links to the `<template>`.

These two functionalities have stopped working after the Official Vue plugin release.

**Comment by so1ve** [comment] 2024-04-06 14:30
Duplicate of https://github.com/vuejs/language-tools/issues/3986

**Closed by so1ve** 2024-04-06 14:30 UTC
