### ISSUE TITLE
vue-tsc: useCssModule() in script setup component breaks checking

### ISSUE THREAD

**Issue by tminich** [vuejs/language-tools#4960] opened 2024-10-29 12:02 UTC
### Vue - Official extension or vue-tsc version

2.1.8

### VSCode version

- (using vue-tsc CLI)

### Vue version

2.7.16

### TypeScript version

5.6.3

### Steps to reproduce

Test.vue:
```vue
<template>
    <div/>
</template>

<script setup lang="ts">
    import {useCssModule} from 'vue'

    const $style = useCssModule()
</script>

<style module lang="scss">
    .test {
        color: rebeccapurple;
    }
</style>
```

```shell
vue-tsc --noEmit --skipLibCheck -w
```

### What is expected?

No bogus issues found.

### What is actually happening?

vue-tsc reports
```
resources/js/components/common/Test.vue:8:32 - error TS1005: ',' expected.

8     const $style = useCssModule()
                                 ~

resources/js/components/common/Test.vue:8:33 - error TS1109: Expression expected.

8     const $style = useCssModule()
                                  ~
```

### Any additional comments?

Bug is new in 2.1.8, reverting to 2.1.6 fixes the issue.

**Comment by KazariEX** [comment] 2024-10-29 12:14
Duplicate of #4951

**Closed by KazariEX** 2024-10-29 12:14 UTC
Labels: pending triage

**Comment by tminich** [comment] 2024-10-29 12:16
Ah, sorry. I checked yesterday if this was known and forgot to check again today before reporting ^^'
