### ISSUE TITLE
Vue.volar crashes on startup after update 2.0.

### ISSUE THREAD

**Issue by wuhaohuang** [vuejs/language-tools#3952] opened 2024-03-03 15:44 UTC
The old version has been uninstalled.

JavaScript and TypeScript language features are enabled.

<img width="506" alt="image" src="https://github.com/vuejs/language-tools/assets/19322584/e5008460-1729-4175-ba3b-9d951c2f5095">

But as long as you downgrade back to version 1.8.27 there will be no problems. pls help!

**Comment by shahadat015** [comment] 2024-03-05 06:21
Same issue here. Vue 3 Repo on M2 Pro.
Reverting to v1.8.27 working fine, But v2.0.0 to v2.0.4 crashes for me

Output:
SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at Socket. (/Users/shahadat/.vscode/extensions/vue.volar-2.0.4/dist/server.js:10024:9777)
at Socket.emit (node:events:526:35)
at endReadableNT (node:internal/streams/readable:1359:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.17.1
[Error - 11:46:02] Server process exited with code 1.
[Info - 11:46:02] Connection to server got closed. Server will restart.

Device:
Version: 1.87.0 (Universal)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:56.944Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0

**Comment by Edge00** [comment] 2024-03-05 06:32
Same issuse. Is there any way to work around?

**Comment by luc122c** [comment] 2024-03-05 09:04
Duplicate of #3962?

**Comment by johnsoncodehk** [comment] 2024-03-05 12:46
Duplicate of #3962

**Closed by johnsoncodehk** 2024-03-05 12:46 UTC
