### ISSUE TITLE
v-for problem in highlight syntax when using type or module as item

### ISSUE THREAD

**Issue by adrianByv** [vuejs/language-tools#4129] opened 2024-03-20 11:39 UTC
When using v-for if you use the word `type` the highlight syntax crash.
![image](https://github.com/vikhyat/moondream/assets/5811567/32eec7e9-e7d5-45ac-9dd0-70cc9264292d)
With item:
![image](https://github.com/vuejs/language-tools/assets/5811567/631dc7ba-5627-4210-b6f7-b26b55ee548d)

Also crash with `module` word:
![image](https://github.com/vuejs/language-tools/assets/5811567/685f0f62-c2f9-4856-b2ce-f600e7602824)

**Comment by davidmatter** [comment] 2024-03-20 13:19
I would generally avoid using [reserved keywords](https://github.com/microsoft/TypeScript/issues/2536) as identifiers.

**Comment by davidmatter** [comment] 2024-03-20 13:56
Relevant: https://github.com/vuejs/core/issues/1266

**Comment by so1ve** [comment] 2024-03-21 02:06
Duplicate of #520

**Closed by so1ve** 2024-03-21 02:06 UTC
