### ISSUE TITLE
lsp format volar delete my code

### ISSUE THREAD

**Issue by bobbyrahmanda13** [vuejs/language-tools#4066] opened 2024-03-11 06:17 UTC
before:
![image](https://github.com/vuejs/language-tools/assets/69358107/6ca896bb-e900-4920-bd83-62fd270f4e92)

after: :lua vim.lsp.buf.format()
![image](https://github.com/vuejs/language-tools/assets/69358107/6e773593-aa9d-40fc-99f3-88254d2c75cf)

![image](https://github.com/vuejs/language-tools/assets/69358107/d89b0b64-e114-4e62-819f-5a6a15eaa6be)
![image](https://github.com/vuejs/language-tools/assets/69358107/efca8c97-0df1-449a-926e-d89caa74c3d6)

**Comment by gegoune** [comment] 2024-03-11 06:22
https://github.com/vuejs/language-tools/issues/3925#issuecomment-1977798196 (and https://github.com/vuejs/language-tools/issues/3925#issuecomment-1978244536).

**Comment by RayGuo-ergou** [comment] 2024-03-11 06:47
It's formatted by `tsserver`. Try `:LspStop tsserver` then format, you will see the code format correctly.

To resolve I think you can, 
- as @gegoune posted disabled `tsserver` format for vue files (if you still want volar)
- My personal recommendation, use a linter (prettier, eslint or biome) rather than LSP format. They are more configurable than native lsp format.

**Comment by bobbyrahmanda13** [comment] 2024-03-11 09:46
> It's formatted by `tsserver`. Try `:LspStop tsserver` then format, you will see the code format correctly.
> 
> To resolve I think you can,
> 
> * as @gegoune posted disabled `tsserver` format for vue files (if you still want volar)
> * My personal recommendation, use a linter (prettier, eslint or biome) rather than LSP format. They are more configurable than native lsp format.

if I use :LspStop tsserver then all my Lsp are inactive, so it won't work

**Comment by bobbyrahmanda13** [comment] 2024-03-11 09:50
my config tsserver
![image](https://github.com/vuejs/language-tools/assets/69358107/8c77b178-e255-4326-bd88-6aa733f6bed1)
and volar 
![image](https://github.com/vuejs/language-tools/assets/69358107/095801ee-4783-4e64-b2c2-c620b6980345)

**Comment by gegoune** [comment] 2024-03-11 09:53
You are not showing crucial part of your configuration: what and how triggers formatting, which does not happen automatically so you must have configured it somehow. You can find how to filter out `tsserver` from LSPs that receive format request in comments I linked to.

(also, what is it with people pasting screenshots here rather than code itself?)

**Comment by bobbyrahmanda13** [comment] 2024-03-11 09:57
> You are not showing crucial part of your configuration: what and how triggers formatting, which does not happen automatically so you must have configured it somehow. You can find how to filter out `tsserver` from LSPs that receive format request in comments I linked to.
> 
> (also, what is it with people pasting screenshots here rather than code itself?)

**Comment by bobbyrahmanda13** [comment] 2024-03-11 10:00
![photo_2024-03-11_16-59-12](https://github.com/vuejs/language-tools/assets/69358107/0c74927a-9dfa-4267-9f26-c0e2869e86a4)
![photo_2024-03-11_16-59-15](https://github.com/vuejs/language-tools/assets/69358107/59917a2d-c969-47e9-a8dc-de2bb5dd7811)

When using tsserver, nothing happens

**Comment by RayGuo-ergou** [comment] 2024-03-11 10:07
> if I use :LspStop tsserver then all my Lsp are inactive, so it won't work, lsp on the .ts and .js formatting extension still works but if on vue then volar will be active so that's an error, I've tried it.

Not sure what do you mean but you should pass correct param into `LspStop` otherwise it will stop all servers. E.g.

 With tsserver:
![with tsserver](https://github.com/vuejs/language-tools/assets/33137074/4e198622-4247-48f5-bb31-769d44824edc)

Without tsserver:
![without tsserver](https://github.com/vuejs/language-tools/assets/33137074/257d9f8a-c065-4ca5-acf8-12325bd8b40a)

And this should __not__ be the solution to your problem, it's just demonstrate where's the issue.

**Comment by bobbyrahmanda13** [comment] 2024-03-11 10:19
> > if I use :LspStop tsserver then all my Lsp are inactive, so it won't work, lsp on the .ts and .js formatting extension still works but if on vue then volar will be active so that's an error, I've tried it.
> 
> Not sure what do you mean but you should pass correct param into `LspStop` otherwise it will stop all servers. E.g.
> 
> With tsserver: ![with tsserver](https://private-user-images.githubusercontent.com/33137074/311662297-4e198622-4247-48f5-bb31-769d44824edc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTE5MzYsIm5iZiI6MTcxMDE1MTYzNiwicGF0aCI6Ii8zMzEzNzA3NC8zMTE2NjIyOTctNGUxOTg2MjItNDI0Ny00OGY1LWJiMzEtNzY5ZDQ0ODI0ZWRjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEwMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZWQzM2ExMjFjZTIwMTY3NzllNjcwNDBlMThhOGU0YThjMzAyMjk5NTE2MmFiZDBkMTZjZDczZDRlZDc2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8iKPs0wsJFjGzKl4s4pz3OHgmyxk8XC8QDeBSSHXhk) [ ![with tsserver](https://private-user-images.githubusercontent.com/33137074/311662297-4e198622-4247-48f5-bb31-769d44824edc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTE5MzYsIm5iZiI6MTcxMDE1MTYzNiwicGF0aCI6Ii8zMzEzNzA3NC8zMTE2NjIyOTctNGUxOTg2MjItNDI0Ny00OGY1LWJiMzEtNzY5ZDQ0ODI0ZWRjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEwMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZWQzM2ExMjFjZTIwMTY3NzllNjcwNDBlMThhOGU0YThjMzAyMjk5NTE2MmFiZDBkMTZjZDczZDRlZDc2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8iKPs0wsJFjGzKl4s4pz3OHgmyxk8XC8QDeBSSHXhk) ](https://private-user-images.githubusercontent.com/33137074/311662297-4e198622-4247-48f5-bb31-769d44824edc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTE5MzYsIm5iZiI6MTcxMDE1MTYzNiwicGF0aCI6Ii8zMzEzNzA3NC8zMTE2NjIyOTctNGUxOTg2MjItNDI0Ny00OGY1LWJiMzEtNzY5ZDQ0ODI0ZWRjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEwMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZWQzM2ExMjFjZTIwMTY3NzllNjcwNDBlMThhOGU0YThjMzAyMjk5NTE2MmFiZDBkMTZjZDczZDRlZDc2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8iKPs0wsJFjGzKl4s4pz3OHgmyxk8XC8QDeBSSHXhk) [ ](https://private-user-images.githubusercontent.com/33137074/311662297-4e198622-4247-48f5-bb31-769d44824edc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTE5MzYsIm5iZiI6MTcxMDE1MTYzNiwicGF0aCI6Ii8zMzEzNzA3NC8zMTE2NjIyOTctNGUxOTg2MjItNDI0Ny00OGY1LWJiMzEtNzY5ZDQ0ODI0ZWRjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEwMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZWQzM2ExMjFjZTIwMTY3NzllNjcwNDBlMThhOGU0YThjMzAyMjk5NTE2MmFiZDBkMTZjZDczZDRlZDc2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8iKPs0wsJFjGzKl4s4pz3OHgmyxk8XC8QDeBSSHXhk)
> 
> Without tsserver: ![without tsserver](https://private-user-images.githubusercontent.com/33137074/311663189-257d9f8a-c065-4ca5-acf8-12325bd8b40a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTE5MzYsIm5iZiI6MTcxMDE1MTYzNiwicGF0aCI6Ii8zMzEzNzA3NC8zMTE2NjMxODktMjU3ZDlmOGEtYzA2NS00Y2E1LWFjZjgtMTIzMjViZDhiNDBhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEwMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzAwYThmYzAxZTM2NTRlM2IyMWEzNzNmYzUzYzMyZWU5MmY1MDQzOGU1OTNlZWMzYzNiNjViN2MzYTQyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eiJghnesLU5A8r-Dmp_7mERb6J3BJf73Pz7rk_frW20) [ ![without tsserver](https://private-user-images.githubusercontent.com/33137074/311663189-257d9f8a-c065-4ca5-acf8-12325bd8b40a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTE5MzYsIm5iZiI6MTcxMDE1MTYzNiwicGF0aCI6Ii8zMzEzNzA3NC8zMTE2NjMxODktMjU3ZDlmOGEtYzA2NS00Y2E1LWFjZjgtMTIzMjViZDhiNDBhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEwMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzAwYThmYzAxZTM2NTRlM2IyMWEzNzNmYzUzYzMyZWU5MmY1MDQzOGU1OTNlZWMzYzNiNjViN2MzYTQyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eiJghnesLU5A8r-Dmp_7mERb6J3BJf73Pz7rk_frW20) ](https://private-user-images.githubusercontent.com/33137074/311663189-257d9f8a-c065-4ca5-acf8-12325bd8b40a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTE5MzYsIm5iZiI6MTcxMDE1MTYzNiwicGF0aCI6Ii8zMzEzNzA3NC8zMTE2NjMxODktMjU3ZDlmOGEtYzA2NS00Y2E1LWFjZjgtMTIzMjViZDhiNDBhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEwMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzAwYThmYzAxZTM2NTRlM2IyMWEzNzNmYzUzYzMyZWU5MmY1MDQzOGU1OTNlZWMzYzNiNjViN2MzYTQyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eiJghnesLU5A8r-Dmp_7mERb6J3BJf73Pz7rk_frW20) [ ](https://private-user-images.githubusercontent.com/33137074/311663189-257d9f8a-c065-4ca5-acf8-12325bd8b40a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTE5MzYsIm5iZiI6MTcxMDE1MTYzNiwicGF0aCI6Ii8zMzEzNzA3NC8zMTE2NjMxODktMjU3ZDlmOGEtYzA2NS00Y2E1LWFjZjgtMTIzMjViZDhiNDBhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEwMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzAwYThmYzAxZTM2NTRlM2IyMWEzNzNmYzUzYzMyZWU5MmY1MDQzOGU1OTNlZWMzYzNiNjViN2MzYTQyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eiJghnesLU5A8r-Dmp_7mERb6J3BJf73Pz7rk_frW20)
> 
> And this should **not** be the solution to your problem, it's just demonstrate where's the issue.

Can it be made so that both work because we also need .ts/.js to make composable, because before there was no problem?

**Comment by gegoune** [comment] 2024-03-11 10:23
@bobbyrahmanda13 You are ignoring everything that is said in this issue while people are genuinely trying to help you.
Once again, your issue is caused by some bug in tsserver or tsserver plugin for vue (I don't know). Until it's fixed you can mitigate it by filtering out tsserver from LSP formatting (see my second link in original response).

**Comment by RayGuo-ergou** [comment] 2024-03-11 10:25
> Can it be made so that both work because we also need .ts/.js to make composable, because before there was no problem

You have to config yourself to what you want.

e.g. Use volar in `*.vue` and use tsserver in `*.{js,ts}`. To achieve that you need few condition check, simply like if the filetype is vue then just use volar. Check gegoune's first comment(the 2nd link), everything you need is there just need to tweak a little bit.

**Comment by Namakete** [comment] 2024-03-24 13:23
Dd anyone fix this?

**Comment by CofCat456** [comment] 2024-03-25 00:47
> Did anyone fix this?

You may consider turning off the volar format

**Comment by RayGuo-ergou** [comment] 2024-03-25 07:07
If you go through the threat, you will find the solution. ( maybe just a work around but works ). 

Btw it's tsserver not volar.

**Comment by codymikol** [comment] 2024-04-13 13:37
Hey @johnsoncodehk, I see this is marked as completed, but I am still experiencing this on v2.0.13. Is this intended to be closed because it was fixed in https://github.com/volarjs/volar.js/commit/d4fbbd7d9cbbbdd8b12981b7ce05da85b2e24c3e or closed due to being an upstream issue?

Thanks for all your hard work on this project!

**Comment by johnsoncodehk** [comment] 2024-04-13 15:06
@codymikol Since you mentioned v2.0.13, this did not release the VSCode extension. Are you using another IDE? If so, please make sure to update `@vue/typescript-plugin` to the latest version.

**Comment by codymikol** [comment] 2024-04-13 18:03
Currently using neovim with mason, not sure how that manages the @vue/typescript plugin, I'll dig into that a little tonight.

**Comment by codymikol** [comment] 2024-04-14 00:05
@johnsoncodehk I should have known how that in particular was set up since [I made a little shim package to do that and completely forgot about it](https://github.com/codymikol/mason-vue-language-server-lazy-shim.nvim).

But essentially, that is just takes the installed version of this language-tools repository and uses the @vue/typescript-plugin package for that version.

So in my case I'm using the latest version of @vue/typescript-plugin, but I'm still experiencing this bug unfortunately :/

**Comment by codymikol** [comment] 2024-04-14 22:00
I'll do a little digging and see if I can find where exactly its happening.

**Comment by codymikol** [comment] 2024-04-16 11:46
@johnsoncodehk Apologies, after digging into this, I was all of a sudden unable to replicate my issues. I think I must have blown the cobwebs out of something cached. You can close this again, sorry for the confusion.

**Closed** 2024-05-14 05:16 UTC
Labels: bug, upstream, pending triage
