### ISSUE TITLE
The folded area will automatically expand when typing codes

### ISSUE THREAD

**Issue by tsdd** [vuejs/language-tools#4035] opened 2024-03-07 02:45 UTC

**Comment by tsdd** [comment] 2024-03-07 02:48
I hope I can use volar instead of this new vscode plugin

**Comment by warmthsea** [comment] 2024-03-07 02:49
If it currently affects you a lot, you can choose to return to version 1.8.27.
https://github.com/vuejs/language-tools/issues/4031#issuecomment-1982234947

**Comment by warmthsea** [comment] 2024-03-07 02:52
> I hope I can use volar instead of this new vscode plugin

This is not a new plugin, it just changed the nickname.

**Comment by so1ve** [comment] 2024-03-07 04:22
Duplicate of https://github.com/vuejs/language-tools/issues/4023

**Closed by so1ve** 2024-03-07 04:22 UTC
