### ISSUE TITLE
Passing not define emits，Volar and vue-tsc not check

### ISSUE THREAD

**Issue by zjtakato** [vuejs/language-tools#3848] opened 2024-01-10 03:55 UTC
### Link to minimal reproduction
https://play.vuejs.org/#eNqNU8Fu2zAM/RVOGJAErW0M3SlLgmxFDtthG7YddXFtJlVrS4JEpxkM//soefZSdy2KXCI+8vGRfG7FR2vTY4NiKVa+cMoSeKTGbqRWtTWOoAWHe+hg70wNM06dfRixaw7FuBRpxo9IJYXUhdGeoDCNJlgHgvm7hdT9b5X1jbgFPwhrW+WE/AJYBcKt0oXD3GMS69dSzBew3rCQ+L64gE4KyGI5l7xJEqDf1oA23PEWi3tIkids6F/F1v4NQ9cFoaM4cSnI81B7dUjvvNG8rjbkS1Hw1KpC982S4qGlWEJEApZXlXn4EmPkGrwc4lHlf+J3/hRiUnx36NEdeZUjRrk7IPXw7udXPPH/EaxN2VSc/QL4A72pmqCxT/vU6JJln+VFtZ/jYZU+/PK7E6H2w1BBaMjsYr4UfOhw8OdG/yf3Kr2KdVJ3vMXBJFO/QZXrAx+HmCbeosS90rirFflVO8clzAZbXIcDzRbdZh4t9ZKdbhoio2FbVKq4Z/a3yHzzKVPsGGQP8Vib9cUMPfZBb/2kzu3ECT3weA3xcwjrviWyfpllRam5rMRKHV2qkTJt62zLaZljLarGpDT1lneWvs9K5ek8nKKvkxtnHtgbTHJ2ulAfDeMSh7w6Fw77uraTsvPWE+hJ+/Gs3R+8eG/K

### What is expected?
Safety Emits should work
cant not passing not define emits?

**Comment by so1ve** [comment] 2024-01-10 04:07
Duplicate of https://github.com/vuejs/language-tools/issues/3718

**Closed by so1ve** 2024-01-10 04:07 UTC
