### ISSUE TITLE
Quick fixes not available in "Takeover mode"

### ISSUE THREAD

**Issue by OldStarchy** [vuejs/language-tools#3785] opened 2023-12-07 05:08 UTC
I just switched over to using "Takeover mode" and now a number of quick-refactors are not available, namely "Convert named export to default export".

Maybe related to this quick refactor not actually working in `.vue` files properly with the builtin typescript extension, it just appends the new import path to the end of the file, but is easy enough to identify and fix in the "changed" section of the source control view.

**Comment by so1ve** [comment] 2023-12-07 05:51
Duplicate of https://github.com/vuejs/language-tools/issues/3741

**Closed by so1ve** 2023-12-07 05:51 UTC
