### ISSUE TITLE
Client Vue: connection to server is erroring. write EPIPE

### ISSUE THREAD

**Issue by SanGuiChen** [vuejs/language-tools#4144] opened 2024-03-22 08:43 UTC
When I opened a vue project, I encountered an error like this:
![image](https://github.com/vuejs/language-tools/assets/77064828/396341d5-c4ae-40dc-9feb-fdc70e5f0766)

**It makes my vue file lose all prompt function.**
**My extension version is v2.0.7. How to solve this problem？**

**Comment by laurens94** [comment] 2024-03-22 12:17
Seems to be a duplicate of https://github.com/vuejs/language-tools/issues/4130. Using the [latest VSCode version](https://code.visualstudio.com/insiders/) or downgrading the extension to v2.0.6 should fix it.

**Comment by so1ve** [comment] 2024-03-23 02:39
Duplicate of https://github.com/vuejs/language-tools/issues/4130

**Closed by so1ve** 2024-03-23 02:39 UTC
