### ISSUE TITLE
Auto import module fails in .vue file (and .ts file in TakeOver mode)

### ISSUE THREAD

**Issue by jbmaisner** [vuejs/language-tools#2313] opened 2023-01-13 10:48 UTC
Hi,

This issue is related to this one in the VSCode repo :
[Vue not auto importing modules. False expression: Some exportInfo should match the specified moduleSymbol](https://github.com/microsoft/vscode/issues/170656)

After some tests I think this could be related to Volar.

The error below occurs when trying to import a module of Vue in .vue file.
An example when I try to use `reactive`.

<img width="825" alt="CleanShot 2023-01-13 at 11 34 57@2x" src="https://user-images.githubusercontent.com/5312996/212300506-593bb715-bf0f-4e24-a243-f61d503a12d8.png">

We can see the error in the intellisense description, which breaks auto import.

The reason I think it's related to Volar is that the same error occurs in a .ts file, **but only when TakeOver mode is enabled**.
Otherwise everything works fine in .ts files.

This issues occurs on :
- MacOS : `Ventura 13.1` (apparently on Windows too)
- VSCode : `1.74.3`
- Volar : `1.0.24`
- Typescript : `4.9.4`
- Vue : `3.2.45`

**Comment by jbmaisner** [comment] 2023-01-13 11:00
As seen in #2190 , downgrading Typescript to 4.8.4 apparently solve this issue.

**Comment by johnsoncodehk** [comment] 2023-02-11 09:56
Duplicate of #2190

**Closed by johnsoncodehk** 2023-02-11 09:56 UTC
