### ISSUE TITLE
v-else-if and v-else break intellisense on <template #slot> blocks

### ISSUE THREAD

**Issue by ludwig801** [vuejs/language-tools#2448] opened 2023-02-23 14:20 UTC
### Example & Issue Description

```vue
<template>
  <!-- Assuming <SubComponent> provides slots "slot1", "slot2" and "slot3"  -->
  <SubComponent>
    <template v-if="value == null" #slot1>{{ value }}</template>
    <template v-else-if="value.length == 0" #slot2>{{ value }}</template>
    <template v-else #slot3>{{ value }}</template>
  </SubComponent>
</template>

<script>
//@ts-check

export default {
  components: {
    SubComponent: () => null,
  },
  data: () => ({
    value: "test",
  }),
};
</script>
```

From the `<template v-else-if>` forward, no variables is recognized.
Hovering over `"value.length == 0"` provides no intellisense, the same with with `{{ value }}`.

Replacing `<template v-else-if="...">` or `<template v-else="...">` with corresponding `<template v-if="...">` fixes the issue.

**Note** that is only happens with <template #slot> type syntax. Using non-slot <template> blocks works just fine.

### Environment

- VSCode: `v1.75.1`
- Volar: `v1.1.7`
- Using takeover mode? `Yes`
- Reproducible in previous versions? `Not tested`

**Comment by johnsoncodehk** [comment] 2023-03-21 17:54
Duplicate of #625

**Closed by johnsoncodehk** 2023-03-21 17:54 UTC
