### ISSUE TITLE
Component types are missing when using Nuxt 3

### ISSUE THREAD

**Issue by yulafezmesi** [vuejs/language-tools#3188] opened 2023-05-15 17:40 UTC
I'm trying to make autocomplete available props on Nuxt 3, however the props or events can't show up. I'm not sure this could be misconfiguration or an issue.

Nuxt: "^3.4.3",
Volar: v1.2.0
Volar TS:  v1.6.5

<img width='350' src='https://github.com/vuejs/language-tools/assets/45617686/53da7d77-4a40-42ec-81fb-56448f41c8c8'/>

<img width='350' src='https://github.com/vuejs/language-tools/assets/45617686/9e087a37-fe4a-4548-865c-dc7f93adb93a'/>

**Comment by xiaoxiangmoe** [comment] 2023-05-19 05:23
Can you provide me a minimal reproduction demo?

**Comment by howard-tzw** [comment] 2023-05-22 07:38
I am encountering the same issue as well

**Comment by olivier-carre** [comment] 2023-05-22 10:48
Same issue here but downgrading Volar and Volar TS to 1.6.4 seems to solve it.

**Comment by savokiss** [comment] 2023-07-12 09:13
Same issue here. 
Volar 1.8.4 still happens.

**Comment by so1ve** [comment] 2023-07-12 10:36
Please provide a minimal reproduction or we cannot debug.

**Comment by baixiaoyu2997** [comment] 2023-07-12 10:41
i alreay send you minimal reproduction:
https://github.com/vuejs/language-tools/issues/3304

**Comment by so1ve** [comment] 2023-07-12 11:55
@baixiaoyu2997 Ah! Sorry for that.

**Comment by johnsoncodehk** [comment] 2024-05-13 17:35
Duplicate of #3304

**Closed by johnsoncodehk** 2024-05-13 17:35 UTC
Labels: bug, good reproduction ✨
