### ISSUE TITLE
wrong font color

### ISSUE THREAD

**Issue by koolcandy** [vuejs/language-tools#4178] opened 2024-03-30 05:18 UTC
<img width="529" alt="252uhuin qoq" src="https://github.com/vuejs/language-tools/assets/133551107/7dc26d59-3374-41e0-9257-55eb55bd3198">

I just clicked the enter key, and then the font color went wrong. What happened?

**Comment by koolcandy** [comment] 2024-03-30 05:22
use command + s,just save the file,
problem is gone, why?

**Comment by koolcandy** [comment] 2024-03-30 05:25
just like #685

**Comment by koolcandy** [comment] 2024-03-30 05:31
back to 2.0.6 , it works fine

**Comment by davidmatter** [comment] 2024-08-06 07:26
Closing this one as many things have changed since 2.x. Feel free to create a new issue with a minimal reproduction if you're still having issues, thanks!

**Closed by davidmatter** 2024-08-06 07:26 UTC
