### ISSUE TITLE
VSCode intellisense is wrong on type of emit

### ISSUE THREAD

**Issue by vidal7** [vuejs/language-tools#2755] opened 2023-04-28 12:22 UTC
In Vue 2.7, options API (defineComponent), TS 5, Volar 1.6.1, type of event is wrong in VSCode

![image](https://user-images.githubusercontent.com/33458053/235146486-b375c3eb-1132-4673-9523-45e0d6927383.png)

It should have been

```ts
'event-without-payload': ($event?: undefined) => void
```

Also, it would have been nice that Volar throw a typescript error on handleEventWithPayload in the template has handleEventWithPayload does not satisfy the type `(a: number, b: boolean) => void` has defined in the p-component-issue

```ts
emits: {
            'event-without-payload': (): void => { },
            'event-with-payload': (a: number, b: boolean) => { }
        }
```

For reproduction repo, you can take the same as the issue 2742 (https://github.com/vidal7/volar-issue-2742)

**Comment by johnsoncodehk** [comment] 2023-05-01 12:52
Duplicate of #1855

**Closed by johnsoncodehk** 2023-05-01 12:52 UTC

**Comment by vidal7** [comment] 2023-05-03 11:48
@johnsoncodehk , are you sure it is related to #1855 ? This issue does not involve that one of an event has an argument typed as any

**Comment by vidal7** [comment] 2023-05-03 17:36
Done here. https://github.com/vuejs/language-tools/issues/1855#issuecomment-1533441398

Thanks!
