### ISSUE TITLE
[Bug] `'i' is declared but its value is never read. ts(6133)`

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/language-tools#2503] opened 2023-03-10 12:49 UTC
<img width="766" alt="image" src="https://user-images.githubusercontent.com/28700378/224319296-d7ab95e0-3516-490c-a1b9-64bb0e30fea8.png">

[Repro Link](https://github.com/wenfangdu/vite-vue-3/tree/template-v-for)

**Comment by johnsoncodehk** [comment] 2023-03-29 07:29
Duplicate of #329

**Closed by johnsoncodehk** 2023-03-29 07:29 UTC
