### ISSUE TITLE
Broken syntax highlighting with the "as" keyword in props

### ISSUE THREAD

**Issue by douira** [vuejs/language-tools#3513] opened 2023-08-27 15:29 UTC
Syntax highlighting is broken when a prop uses the `as` keyword:
<img width="363" alt="Screenshot 2023-08-27 at 17 27 49" src="https://github.com/vuejs/language-tools/assets/17120022/82003a45-a458-4a79-949e-1cc3f1d874f0">

Reproduction code in a SFC file `test.vue`:
```vue
<template>
  <div :foo="3 as foo" :bar="3" baz="boo" />
</template>

<script setup lang="ts">
type foo = number
</script>
```

It also breaks the highlighting of markup comments.

Using Volar v1.8.8 in takeover move and VSCode 1.81.1

**Comment by so1ve** [comment] 2023-08-27 15:45
Duplicate of #520

**Comment by so1ve** [comment] 2023-08-27 15:46
As a workaround: add parentheses around your expression.

**Closed by so1ve** 2023-08-27 15:45 UTC

**Comment by douira** [comment] 2023-08-27 15:47
I now see the duplicate issue but there's no mention of a particular issue in the upstream repo. Is there an issue there or has nobody made one? This isn't going to get fixed otherwise.

**Comment by so1ve** [comment] 2023-08-27 15:54
@douira https://github.com/microsoft/TypeScript-TmLanguage/issues/985 See this issue. A guy has fired an issue, but the maintainers said these syntax are not covered by TypeScript-TmLanguage. Feel free to create an issue, but I doubt if they will fix it...

**Comment by douira** [comment] 2023-08-27 15:59
So this repo isn't responsible because it doesn't do syntax highlighting and the other repo isn't responsible because they don't feel like it or is there some other reason? I mean something must be happening that just messes up the highlighting of the entire file when you use typescript syntax in a prop. And if neither repo feels like fixing it, maybe prettier should then automatically _add_ the parens that are apparently necessary to prevent highlighting from getting messed up. But that just seems like a workaround and not a solution. If the language allows such syntax to exist without erroring, then the highlighting (whoever is responsible for it) must also at least not completely break when it encounters it.

**Comment by so1ve** [comment] 2023-08-27 16:17
I'm not sure which repo should be responsible. But here is a similar issue: https://github.com/vuejs/language-tools/issues/3400. I keep it open for further investigation.
