### ISSUE TITLE
v-bind shorthand syntax is not supported for :class

### ISSUE THREAD

**Issue by GideonMegaport** [vuejs/language-tools#4087] opened 2024-03-13 02:21 UTC
When using an attribute named `class` the v-bind shorthand produces the `'v-bind' directives require an attribute value.` error.

To reproduce:
```javascript
<script lang="ts" setup>
defineProps<{
  color: string
  class: string
}>()
</script>

<template>
  <div
    :class
    :color></div>
</template>
```
In the above code, the `color` attribute is accepted but the `class` attribute isn't.

**Comment by so1ve** [comment] 2024-03-13 04:05
Do you have a reproduction repo? I can't reproduce this on my machine.

**Comment by GideonMegaport** [comment] 2024-03-14 01:56
Here is a reproduction repo: https://github.com/GideonMegaport/vbindTest

The relevant code is in `src/components/TestComponent.vue`

I created a blank Vue 3 project with the following settings:
✔ Add TypeScript? … Yes
✔ Add JSX Support? … No 
✔ Add Vue Router for Single Page Application development? … No
✔ Add Pinia for state management? … No 
✔ Add Vitest for Unit Testing? … No 
✔ Add an End-to-End Testing Solution? › No
✔ Add ESLint for code quality? … Yes
✔ Add Prettier for code formatting? … Yes
✔ Add Vue DevTools extension for debugging? (experimental) … No

In VSCode I disabled all extensions except `Vue - Official` and `ESLint`

The error shows up no matter what order I put the attributes in.

**Comment by so1ve** [comment] 2024-04-08 03:54
![image](https://github.com/vuejs/language-tools/assets/58381667/7dfc6dbc-c757-4f8b-a4fe-1e742806b596)

It works?

**Comment by GideonMegaport** [comment] 2024-04-08 04:33
Still doesn't work for me.
<img width="334" alt="Screenshot 2024-04-08 at 2 32 34 PM" src="https://github.com/vuejs/language-tools/assets/144857580/af79c158-e2c0-41a6-a8b9-a3cf68530efd">

**Comment by so1ve** [comment] 2024-04-08 04:47
Pretty weird, what's your vue and volar's version?

**Comment by GideonMegaport** [comment] 2024-04-10 00:05
I'm using "Vue - Official" v2.0.10 and Vue 3.4.21(typescript@5.4.2)

I just downloaded the repository zip and did a `pnpm i`

**Comment by davidmatter** [comment] 2024-08-06 07:00
Hey there, as there have been many fixes in the last 2.x versions: If you're still encountering issues, please provide a minimal reproduction. Otherwise kindly close this one, thanks!

**Comment by GideonMegaport** [comment] 2024-08-06 07:26
I just tried it again with v2.0.28 and still have the same error. 

The minimal reproduction is already provided above. 

I also updated all the dependencies in my project to the latest and that made no difference.

I also downloaded the source from the repository above and set it up on a completely separate computer, and was able to reproduce the same problem.

**Comment by davidmatter** [comment] 2024-08-06 07:29
Right, I was able to reproduce this one.

**Closed** 2024-08-06 07:31 UTC
Labels: upstream
