### ISSUE TITLE
v2.1.4 reports error on global properties although properly augmented 

### ISSUE THREAD

**Issue by douglasg14b** [vuejs/language-tools#4793] opened 2024-09-02 22:21 UTC
### Vue - Official extension or vue-tsc version

v2.1.4

### VSCode version

1.92.2

### Vue version

3.4.38

### TypeScript version

5.4.5

### package.json dependencies

```json
{
    "dependencies": {
        "@mdi/font": "7.4.47",
        "@sentry/vite-plugin": "^2.16.1",
        "@sentry/vue": "^8.13.0",
        "@stripe/connect-js": "^3.3.6",
        "@stripe/stripe-js": "^3.5.0",
        "@types/cookie": "^0.6.0",
        "@vueuse/core": "^10.9.0",
        "approximate-number": "^2.1.1",
        "client-zip": "^2.4.5",
        "color-convert": "^2.0.1",
        "cookie": "^0.6.0",
        "dayjs": "^1.11.10",
        "file-type": "^19.0.0",
        "floating-vue": "^5.2.2",
        "form-data": "^4.0.0",
        "geojson": "^0.5.0",
        "grid-layout-plus": "^1.0.5",
        "just-clone": "^6.2.0",
        "maplibre-gl": "^3.6.2",
        "markdown-it": "^14.1.0",
        "maska": "^2.1.11",
        "pinia": "^2.0.23",
        "roboto-fontface": "*",
        "uuid": "^9.0.1",
        "vee-validate": "^4.12.2",
        "vue": "^3.4.0",
        "vue-i18n": "^9.8.0",
        "vue-markdown-render": "^2.1.1",
        "vue-query": "^1.26.0",
        "vue-router": "^4.4.3",
        "vue3-easy-data-table": "^1.5.47",
        "vue3-perfect-scrollbar": "^1.6.1",
        "vuetify": "^3.7.1",
        "vuetify-sonner": "^0.3.12"
    },
    "devDependencies": {
        "@babel/types": "^7.21.4",
        "@types/color-convert": "^2.0.3",
        "@types/markdown-it": "^14.0.1",
        "@types/node": "^18.15.0",
        "@types/uuid": "^9.0.7",
        "@typescript-eslint/eslint-plugin": "^6.13.1",
        "@typescript-eslint/parser": "^6.13.1",
        "@vitejs/plugin-vue": "^4.0.0",
        "@vitejs/plugin-vue-jsx": "^3.1.0",
        "@vue/eslint-config-typescript": "^11.0.0",
        "dotenv": "^16.3.1",
        "dotenv-cli": "^7.3.0",
        "dprint": "^0.43.1",
        "eslint": "^8.54.0",
        "eslint-import-resolver-alias": "^1.1.2",
        "eslint-import-resolver-typescript": "^3.6.1",
        "eslint-plugin-import": "^2.29.1",
        "eslint-plugin-vue": "^9.19.2",
        "sass": "^1.69.5",
        "stripe": "^15.10.0",
        "type-fest": "^4.9.0",
        "typescript": "^5.4.5",
        "unplugin-fonts": "^1.0.3",
        "vite": "^5.0.11",
        "vite-plugin-checker": "^0.6.4",
        "vite-plugin-vuetify": "^2.0.1",
        "vue-tsc": "^1.2.0"
    }
}
```

### Steps to reproduce

Upgrade extension to v2.1.4

### What is expected?

That global augmented propeties work

### What is actually happening?

They don't.

![image](https://github.com/user-attachments/assets/219a0c9c-e019-4133-834b-994b1f0f10f6)

### Any additional comments?

```ts
declare module 'vue' {
   export interface ComponentCustomProperties {
        $filters: {
            number: typeof formatNumber;
            percent: typeof formatPercent;
            currency: typeof formatCurrency;
            pluralize: typeof pluralize;
            abbreviate: typeof abbreviateNumber;
            date: typeof formatDate;
            bytes: typeof prettyBytes;
            timeSpan: typeof formatTimespan;
            timeDays: typeof formatTimespanDays;
        };
        $can: UserAbility['can'];
        $canExclusive: UserAbility['canExclusive'];
        $hasAtLeastRole: UserAbility['hasAtLeastRole'];
        $notImplemented: (name: string) => void;
        $triggerDialog: typeof dialogsEventBus.emit;
    }
}
```

**Comment by douglasg14b** [comment] 2024-09-02 22:21
This seems similar to: https://github.com/vuejs/language-tools/issues/3947

**Comment by douglasg14b** [comment] 2024-09-02 22:26
Also noticing that this now fails in build as well, so it's not just an issue with the language tools? Something different with a Vue update?

**Comment by douglasg14b** [comment] 2024-09-02 23:28
This also seems to be a problem for `vue-router` as well as `$route` is also not available in templates.

**Comment by KazariEX** [comment] 2024-09-03 03:53
Due to our past use of `@vue/runtime-core` to augment Vue, this caused breaks in augmentation of `vue`. We are now gradually standardizing the use of `vue` for augmentation across other libraries. If this issue still occurs in your dependencies, you can temporarily switch to `vue` and make a PR to the upstream repository.

**Comment by douglasg14b** [comment] 2024-09-03 21:59
Related? https://github.com/vuejs/language-tools/issues/4755

@KazariEX Sorry, I don't understand. This did not appear to be a problem in earlier versions, however it is a problem now. Due to some combination of dependencies & breaking changes this has regressed. If I know how to fix it, I would have 😅

Can you clarify?

**Comment by KazariEX** [comment] 2024-09-04 03:45
Anyway, I suggest that you first bump all your dependencies to the latest version, and try searching for `declare module '@vue/runtime-core'` in the node_modules directory. If you find any libraries using it to augment Vue, modify it to `declare module 'vue'`.

If the issue persists after making these changes, I believe we need a minimal reproduction to pinpoint the root cause of the problem.

**Comment by codeblockhead** [comment] 2024-09-04 11:15
I have also encountered this issue on the latest version of nuxt. Only in the template, the vscode plugin cannot correctly recognize the automatically exported functions. I don't know where the source of the problem is, and whether it is due to the vscode plugin

**Comment by Bombastickj** [comment] 2024-09-06 17:30
Here is a minimal reproduction to highlight the error coming in nuxt 3. @KazariEX

https://stackblitz.com/edit/github-vw7ht4?file=nuxt.config.ts

**Comment by douglasg14b** [comment] 2024-09-07 22:30
Does anyone have workarounds that are effective? Even builds fail right now if any `ComponentCustomProperties` are used. TS can be forced to emit regardless, but the longer it lasts the higher the chances of actual errors slipping through builds.

**Comment by douglasg14b** [comment] 2024-09-07 22:38
So, for others here the guidance appears to be this:

## Any library that use the legacy syntax `declare module '@vue/runtime-core'` will absolutel brick your applications type resolution for `ComponentCustomProperties`

To find these dependencies and fix them:
1. Open node-modules
2. Do a global search for `'@vue/runtime-core'``
3. Any dependencies that do this, try and upgrade to latest within your major

If any of these dependencies don't have updates, or are abandoned, then based on what I've learned here and in debugging **your are screwed, and so is your CI/CD pipeline**.  You would need to do global find & replace before any builds, and locally.

**Comment by andreasgangso** [comment] 2024-09-08 10:38
> So, for others here the guidance appears to be this:
> 
> ## Any library that use the legacy syntax `declare module '@vue/runtime-core'` will absolutely brick your applications type resolution for `ComponentCustomProperties`
> To find these dependencies and fix them:
> 
> 1. Open node-modules
> 2. Do a global search for `'@vue/runtime-core'``
> 3. Any dependencies that do this, try and upgrade to latest within your major
> 
> If any of these dependencies don't have updates, or are abandoned, then based on what I've learned here and in debugging **your are screwed, and so is your CI/CD pipeline**. You would need to do global find & replace before any builds, and locally.

Or make PRs to the libraries you use. While waiting for it to get merged you can point towards your own fork in package.json.

**Comment by aiqin-bao** [comment] 2024-09-26 03:31
I did not upgrade nuxt. I just switched from npm to pnpm and installed the dependencies. It was solved. It should be a problem of increased dependencies.

**Closed** 2024-09-26 03:51 UTC
Labels: need info, external
