### ISSUE TITLE
Formatting breaks code by changing styling done with @apply

### ISSUE THREAD

**Issue by ThomasWT** [vuejs/language-tools#3142] opened 2023-05-07 20:39 UTC
using Volar formatting breaks styling done with @apply.

**Formatting this**
`@apply sm:text-xl;`

Turns into this with a space
`@apply sm: text-xl;`

**Comment by so1ve** [comment] 2023-09-18 04:07
Duplicate of #1448

**Closed by so1ve** 2023-09-18 04:07 UTC
