### ISSUE TITLE
When I create a new VUE file or copy an existing VUE file, the file will say“File module not found”

### ISSUE THREAD

**Issue by cMing1997** [vuejs/language-tools#4374] opened 2024-05-13 03:32 UTC
## Problem 
1. When I create a new vue file, I introduce a module reference that says, “This module can not be found.”

2. When I copy a clean file into the same directory, there are still a lot of “Can not find this module” messages in the newly copied file

3. When I encounter this problem, restart the current vs code window, or reload the plug-in, and these error messages disappear

## Screenshot
![GIF 2024-5-13 11-18-58](https://github.com/vuejs/language-tools/assets/40878104/7eb81701-5c87-4999-9683-3ab1edf02edf)

![GIF 2024-5-13 11-20-59](https://github.com/vuejs/language-tools/assets/40878104/3911daa1-a7dd-4ea4-a247-88135e703354)

## Info
```
版本: 1.89.0 (user setup)
提交: b58957e67ee1e712cebf466b995adf4c5307b2bd
日期: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631
```

## Plugin Version
```
v2.0.8
```

**Comment by don-boldyrev** [comment] 2024-05-21 19:50
Same issue. Waiting for update

**Comment by davidmatter** [comment] 2024-06-04 12:47
Set `typescript.tsserver.experimental.useVsCodeWatcher` to `false` https://github.com/vuejs/language-tools/issues/4424

**Comment by so1ve** [comment] 2024-06-04 17:51
Duplicate of #4424

**Closed by so1ve** 2024-06-04 17:51 UTC
