### ISSUE TITLE
Language server does not recognize files that have been added or changed.

### ISSUE THREAD

**Issue by chaozwn** [vuejs/language-tools#3344] opened 2023-06-30 05:25 UTC
When we create a new component and reference it in other components, we do not receive the correct suggestions. This can be related to an issue in coc-volar.
link: https://github.com/yaegassy/coc-volar/issues/299

**Comment by so1ve** [comment] 2023-06-30 07:29
Duplicate of #3329

**Closed by so1ve** 2023-06-30 07:29 UTC
