### ISSUE TITLE
Local package (module) dependencies tracking in monorepo (npm workspaces) broken in latest version (v2.0.7) 

### ISSUE THREAD

**Issue by LifeJustDLC** [vuejs/language-tools#4158] opened 2024-03-26 09:31 UTC
When I make the following change:
```ts
// api/index.ts outside "vue project"
// (sub module in my monorepo, project structure is described later)
export type theType = number // from this
export type theType = string // to this, and ctrl+S.
```

The error in following file won't be detected before restarting Vscode (or extension host):
```vue
<script setup lang="ts">
import type { theType } from "api"
cost num: theType = 1 // won't complain any error before reload.
```

This problem only exist in (v2.0.7). It works normally in (v2.0.6) (I've downgraded to this).

Project structure:
```
root
 - api
   - index.ts
   - index.js
   - index.d.ts
   - package.json
 - fe
   - src
     - App.vue
     - ...
 - pacakge.json
```

```json
// root/api/package.json:
{
  "name": "api",
  "types": "index.d.ts",
  "devDependencies": {
    "typescript": "^5.4.3"
  },
  "scripts": {
    "build": "tsc index.ts -d",
    "dev": "tsc index.ts -d -w"
  }
}
```
```json
// root/package.json
{
  "name": "homework",
  "scripts": {},
  "workspaces": [
    "be",
    "fe",
    "api"
  ]
}

```
dev command:
```
(root) $ npm run dev -w api
```

`package.json` and `tsconfig.json` inside `fe` are all Vue defualt boilerplates, reamain untouched.

**Comment by life-is-dlc** [comment] 2024-03-26 10:10
Done editing. (Hope this will triggle some notification)

**Comment by davidmatter** [comment] 2024-08-07 07:18
Hey there, as there have been many fixes in the last 2.x versions: Please let us know if you're still encountering this issue. Otherwise kindly close this one, thanks!

**Comment by bosens-China** [comment] 2024-08-08 08:25
@davidmatter 
![image](https://github.com/user-attachments/assets/375c7ab9-a866-400c-921d-747193220296)

**Comment by KermanX** [comment] 2024-08-13 14:38
@LifeJustDLC The issue you reported seems kind of unusual. Please provide a minimal reproduction project and re-open this issue. Thanks!

@bosens-China This seems to be another issue. Please check your `tsconfig.json`, and open a new issue if there are still unexpected behaviors. Thanks!

**Closed by KermanX** 2024-08-13 14:38 UTC
Labels: need info
