### ISSUE TITLE
Generic components - unable to set regular attrs

### ISSUE THREAD

**Issue by Ericlm** [vuejs/language-tools#3436] opened 2023-07-21 19:26 UTC
Hello there! I wanted to report that I'm unable to get my generic component accepting html attributes. More broadly, I can't pass any attribute that is not part of my props, otherwise I get the following type-checking issue : 
<img width="1590" alt="Capture d’écran 2023-07-21 à 21 22 59" src="https://github.com/vuejs/language-tools/assets/19361503/cd1e50fe-7688-4baa-a7a1-8f1f1a1ba148">
It does not work whether the `inheritattrs` option is `true` or `false`.

A repo with the issue is [here](https://github.com/Ericlm/vue-generics).

Could you help me? Thank you!

**Comment by so1ve** [comment] 2023-07-21 23:03
Duplicate of #3318

**Closed by so1ve** 2023-07-21 23:03 UTC
