### ISSUE TITLE
Typeof in template v-if conditions causes syntax color issues.

### ISSUE THREAD

**Issue by ThomasBerne** [vuejs/language-tools#2348] opened 2023-01-31 07:37 UTC
Using typeof in template causes the syntax color to break:

![image](https://user-images.githubusercontent.com/23033483/215692196-5acbb45a-7f34-49a0-bc8a-473026921923.png)

I expect the syntax color to be normal. The application works well. That only seems to be a Volar issue.

**Comment by johnsoncodehk** [comment] 2023-02-19 20:16
Duplicate of #656

**Closed by johnsoncodehk** 2023-02-19 20:16 UTC
