### ISSUE TITLE
2.0.2 not support with style reference

### ISSUE THREAD

**Issue by CandyACE** [vuejs/language-tools#3933] opened 2024-03-02 09:02 UTC
![image](https://github.com/vuejs/language-tools/assets/31685984/b0ad67bd-d6a5-4c95-817c-a34c29d52bba)

**Comment by so1ve** [comment] 2024-03-07 09:06
Duplicate of https://github.com/vuejs/language-tools/issues/3986

**Closed by so1ve** 2024-03-07 09:06 UTC
