### ISSUE TITLE
vue auto complete props not show on component tag

### ISSUE THREAD

**Issue by kydner** [vuejs/language-tools#4509] opened 2024-06-27 07:51 UTC
### Vue - Official extension or vue-tsc version

2.0.22

### VSCode version

1.90.2

### Vue version

3.4.18

### TypeScript version

2.0

### System Info

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 1.34 GB / 5.72 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.19.1 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.15.4 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.114
```

### Steps to reproduce

when ctrl+space on vue component tag, all props on vue not show, but when i change to version 2.0.21 it work again

**Comment by so1ve** [comment] 2024-06-27 09:04
Duplicate of https://github.com/vuejs/language-tools/issues/4508

**Comment by so1ve** [comment] 2024-06-27 09:04
TS 2.0???

**Closed by so1ve** 2024-06-27 09:04 UTC
Labels: pending triage

**Comment by kydner** [comment] 2024-09-12 07:27
https://github.com/vuejs/language-tools/issues/4508

on new version 2.1.6 not work again,
