### ISSUE TITLE
The JS/TS language service immediately crashed 5 times

### ISSUE THREAD

**Issue by davidramosweb** [vuejs/language-tools#3971] opened 2024-03-04 14:01 UTC
Type: <b>Bug</b>

Start VSCode

Extension version: 2.0.4
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:51.279Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|25, 17, 13|
|Memory (System)|64.00GB (7.90GB free)|
|Process Argv|--crash-reporter-id 9e82fcf6-94ce-47c5-abc5-77c72b18cee6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
e3gdj431:30958358
dsvsc020:30976470

```

</details>

**Comment by newTimesNewRoman** [comment] 2024-03-04 14:15
Today I encountered the same problem. Temporarily switched the plugin to version 1.8.27. It works on this version.

MacBook M1 Pro computer

**Comment by davidmatter** [comment] 2024-03-04 14:31
Duplicate of https://github.com/vuejs/language-tools/issues/3962
Try using vscode insiders

**Comment by kitsune7** [comment] 2024-03-04 23:33
@davidmatter I'm not sure this is a duplicate issue. It's not the Vue server that crashes. It's the JS/TS language service
<img width="453" alt="Screenshot 2024-03-04 at 4 32 59 PM" src="https://github.com/vuejs/language-tools/assets/1205871/1679f34f-9328-4fb8-81e1-44441314669d">

**Comment by johnsoncodehk** [comment] 2024-03-05 04:01
Duplicate of #3962

**Closed by johnsoncodehk** 2024-03-05 04:01 UTC
