### ISSUE TITLE
Non-null assertions can only be used in TypeScript files.ts(8013)

### ISSUE THREAD

**Issue by Doston777** [vuejs/language-tools#3163] opened 2023-05-11 09:36 UTC
https://github.com/microsoft/vscode/issues/181630

We have a new issue with new updated version of VS Code:
https://github.com/microsoft/vscode/issues/181630#issuecomment-1540687359

**Comment by Hobeein** [comment] 2023-05-11 09:43
https://github.com/microsoft/vscode/issues/181630#issuecomment-1537061653

Need Help

**Comment by johnsoncodehk** [comment] 2023-05-13 06:33
Duplicate of #3121

**Closed by johnsoncodehk** 2023-05-13 06:33 UTC
