### ISSUE TITLE
TS6133: 'index' is declared but its value is never read when using <template> with headlessui

### ISSUE THREAD

**Issue by smarlhens** [vuejs/language-tools#2719] opened 2023-04-26 13:57 UTC
Hi there 👋🏻 ,

I hope you are fine, thanks for your amazing job.

I am getting this issue when I use a template to wrap an element from [headlessui](https://github.com/tailwindlabs/headlessui) lib: 

```vue
<template v-for="(person, index) in people" :key="index">
  <ListboxOption
    :value="person"
    :disabled="person.unavailable"
    as="template"
  >
    <li>
      {{ person.name }}
    </li>
  </ListboxOption>
</template>
```
![image](https://user-images.githubusercontent.com/11817371/234599917-5add63d0-38bc-458a-9294-e110488c0d4d.png)

```
Binaries:
  Node: 16.14.2
  npm: 7.17.0 
npmPackages:
  typescript: 5.0.4
  vue: 3.3.0-beta.2
  vue-tsc: 1.5.4
```

Repro repo: https://stackblitz.com/edit/vitejs-vite-fv2zbg?file=src/App.vue

Wish you a great day 🌞 
Stay safe

**Comment by johnsoncodehk** [comment] 2023-05-01 13:16
Duplicate of #329.

You can rename `index` to `_index` as a workaround.

**Closed by johnsoncodehk** 2023-05-01 13:16 UTC
