### ISSUE TITLE
VS Code self-closing `<slot />` incorrect colors

### ISSUE THREAD

**Issue by mrleblanc101** [vuejs/language-tools#2276] opened 2023-01-04 08:34 UTC
I'm not 100% sure this comes from Volar, but I think so.
Feel free to close or point me in the right direction otherwise.

`<slot></slot>` respect my VS Code color theme.
But the backslash in a self-closing `<slot />` is not the right color.

<img width="250" alt="Capture d’écran, le 2023-01-04 à 03 32 37" src="https://user-images.githubusercontent.com/17392251/210514878-02d5555b-e208-48df-8df8-30b1a1913a72.png">

**Comment by olivervorasai** [comment] 2023-01-06 05:02
Please refer to https://github.com/johnsoncodehk/volar/issues/1317

**Comment by mrleblanc101** [comment] 2023-01-06 05:40
Well, I understand for `<div />` as it's not valid HTML. But `<slot />` is valid as is a Vue component and not native HTML.

**Comment by johnsoncodehk** [comment] 2023-02-11 09:47
Duplicate of #1317

**Closed by johnsoncodehk** 2023-02-11 09:47 UTC
