### ISSUE TITLE
`importModuleSpecifierEnding` is not supported in Take Over mode

### ISSUE THREAD

**Issue by sheremet-va** [vuejs/language-tools#2518] opened 2023-03-17 14:14 UTC
We are trying to move our code base to `moduleResolution: "bundler"`, but auto import keeps importing files without the extension. I found a solution to enable `javascript.preferences.importModuleSpecifierEnding: "js"` flag, but it seems that it is ignored, if Take Over mode is enabled (the setting is grayed out in `settings.json`).

If I disable Take Over mode, auto importing appends `.ts` extension to our imports.

**Comment by sheremet-va** [comment] 2023-03-20 08:33
Reproduction: https://github.com/sheremet-va/volar-bug-extension

Would really appreciate your input here 🙏🏻 I noticed that without the take over mode, it works, but inside Vue files the extension is `.js`, but when importing inside `.ts` files the extension is `.ts`.

**Comment by sheremet-va** [comment] 2023-03-20 08:34
Reproduction: https://github.com/sheremet-va/volar-bug-extension

@johnsoncodehk Would really appreciate your input here 🙏🏻 I noticed that without the take over mode, it works, but inside Vue files the extension is `.js`, but when importing inside `.ts` files the extension is `.ts`.

**Comment by johnsoncodehk** [comment] 2023-04-14 21:58
Thanks for the repro case, but I can't reproduce the problem, Volar behavior is consistent with takeover mode disabled behavior to me.

> @johnsoncodehk Would really appreciate your input here 🙏🏻 I noticed that without the takeover mode, it works, but inside Vue files the extension is `.js`, but when importing inside `.ts` files the extension is `.ts`.

It's also consistent behavior, you can try to execute `Volar (Debug): Write Virtual Files` command, the `src/components/Cmp.vue.ts` virtual will be created to the workspace, and then you can test auto import in `Cmp.vue.ts`, the import of `#mobile/utils` is ending with `.js`.

**Comment by sheremet-va** [comment] 2023-04-15 11:21
> Thanks for the repro case, but I can't reproduce the problem, Volar behavior is consistent with takeover mode disabled behavior to me.

The issue is changed a little bit since the last report, but I can still reproduce it. Not `.js` extension is always used in Vue file, but typescript files use `.ts` extension when auto imporing. Enable these in your config file:

```
  "javascript.preferences.importModuleSpecifierEnding": "js",
  "typescript.preferences.importModuleSpecifierEnding": "js",
```

[Volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar) plugin is installed for both cases. [TypeScript Vue Plugin](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin) doesn't change the behavior.

I also moved the `base` file to components to better illustrate the difference.

Try to auto import `getName` in `components/base`. It will be autoimported like this (_with `.ts` extension_):

```ts
import { getName } from '#mobile/utils.ts';
```

Then try to auto import `getName` in `components/Cmp.vue` (notice it has `lang="ts"`). It will be auto imported like this (_with `.js` extension_):

```ts
import { getName } from '#mobile/utils.js';
```

> It's also consistent behavior, you can try to execute `Volar (Debug): Write Virtual Files` command

As a user, I don't write code in virtual files, Volar creates these virtual files, so I don't think it can be used for reference here. Volar might use a different config for all I know. As a user it is weird to me that I can import the same file, but it will have different extension depending on the current file.

**Comment by johnsoncodehk** [comment] 2023-04-17 11:37
It should be fixed by https://github.com/vuejs/language-tools/commit/f786efa3a25f6c49e5056ab389e40dac2ed93ddb, thanks.

**Closed** 2023-04-17 11:37 UTC

**Comment by sheremet-va** [comment] 2023-04-19 09:31
Thank you for the fix! It does seem to work now (also the import happens on the first line and not in the "<script>" part, which is nice).

But with v1.3.18 I noticed that when pressing "Cmd+." in Vue files to autoimport it, VS Code shows me "No actions available". But it works fine in TS files.

The reproduction is the same.

**Comment by johnsoncodehk** [comment] 2023-04-19 09:40
Unfortunately code actions is now disabled by default: #2620

**Comment by sheremet-va** [comment] 2023-04-19 09:48
> Unfortunately code actions is now disabled by default: #2620

From the description you gave in the PR, it seems that not all code actions should be disabled. Only for auto fixing and stuff, no? This sounds more like punishing people who understand the reasons for ESLint slowness. I personally don't have any auto fixers, so this issue doesn't affect me for a few years now.

I think this change will only cause new issues in the realm of "why doesn't this work" and a new wave of people who need explaining.

**Comment by johnsoncodehk** [comment] 2023-04-19 10:13
I complain a bit, but that's not to punish users. Users can actually set any code action kind other than "source.fixAll" / "source.organizeImports" in codeActionOnSave, such as "quickfix", so only disabling some code action kinds will not completely avoid the problem.

I also considered disabling code actions only if the user has ESLint installed, but that seems to be over design.

**Comment by sheremet-va** [comment] 2023-04-19 10:15
> Users can actually set any code action kind other than "source.fixAll" / "source.organizeImports" in codeActionOnSave, such as "quickfix", so only disabling some code action kinds will not completely avoid the problem.

Should we just disable running code actions on save by default then? The fact that I cannot import the variable with `Cmd+.` feels like it was not intended by this change.

**Comment by johnsoncodehk** [comment] 2023-04-19 10:22
We could read the codeActionOnSave setting to do this, but I think this would confuse users as it seems that certain codeActions are randomly disabled in different projects. Enable / disable all uniformly is a trade-off.

**Comment by johnsoncodehk** [comment] 2023-04-19 10:33
The closest solution is to judge the trigger kind on the language server to ignore the code action on save request, but there is still a problem that this will not prevent VSCode from displaying that Volar is executing code action.

**Comment by johnsoncodehk** [comment] 2023-04-19 11:46
I came up with another solution in https://github.com/vuejs/language-tools/commit/d629d76b077ab940f0eba1f03fbbd8b252968eb1, now code actions are enabled by default, and automatically disabled when the saving time is too long (default 500ms), so we don't have to care about the reason behind it or what extensions the user installed.
