### ISSUE TITLE
Cannot use <component> with variable "is" prop

### ISSUE THREAD

**Issue by mtorromeo** [vuejs/language-tools#2734] opened 2023-04-27 09:25 UTC
When trying to assign a dynamic tag to the `is` prop of `<component>` I get the error:

```
error TS2345: Argument of type '{}' is not assignable to parameter of type 'string & Record<string, unknown>'.
  Type '{}' is not assignable to type 'string'.
```

Minimal reproduction component:
```vue
<script lang="ts" setup>
const tag = 'label';
</script>

<template>
  <component :is="tag">test</component>
// ^^^^^^^^^ Type '{}' is not assignable to type 'string'.
</template>
```

[Stackblitz](https://stackblitz.com/edit/vitejs-vite-3gztnk?file=src%2Fcomponents%2FMyComp.vue)

**Comment by johnsoncodehk** [comment] 2023-04-27 09:48
Duplicate of #2725

**Closed by johnsoncodehk** 2023-04-27 09:48 UTC
