### ISSUE TITLE
Highlight of `</script>` is broken without semicolons sometimes

### ISSUE THREAD

**Issue by ForkKILLET** [vuejs/language-tools#3468] opened 2023-08-03 06:28 UTC
![image](https://github.com/vuejs/language-tools/assets/35412022/2df5a74a-321f-4428-a9f8-245460748e45)

```vue
<script lang="ts">
type T = number
</script>
```

**Comment by so1ve** [comment] 2023-08-16 17:46
@ForkKILLET lol look at Github codeblock, it also breaks :D Maybe an upstream issue

**Comment by so1ve** [comment] 2023-11-21 08:37
Duplicate of #2060

**Closed by so1ve** 2023-11-21 08:37 UTC
