### ISSUE TITLE
when set tsconfig - vueCompilerOptions.target = 3 and compilerOptions.strict = false , use Partial in defineProps, $props lose type

### ISSUE THREAD

**Issue by Kanade-Lu** [vuejs/language-tools#4839] opened 2024-09-11 07:24 UTC
### Vue - Official extension or vue-tsc version

2.0.21

### VSCode version

1.92.2 (Universal)

### Vue version

3.5.4

### TypeScript version

5.4.0

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 159.14 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 7.33.7 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 128.0.6613.121
    Safari: 16.5.1
```

### package.json dependencies

```json
"dependencies": {
    "vue": "^3.5.4"
  },
  "devDependencies": {
    "@tsconfig/node20": "^20.1.4",
    "@types/node": "^20.14.5",
    "@vitejs/plugin-vue": "^5.0.5",
    "@vue/tsconfig": "^0.5.1",
    "npm-run-all2": "^6.2.0",
    "typescript": "~5.4.0",
    "vite": "^5.3.1",
    "vue-tsc": "^2.1.6"
  }
```

### Steps to reproduce

pnpm create vue@latest
use typescript
set tsconfig - vueCompilerOptions.target = 3 and compilerOptions.strict = false

```vue
<script setup lang="ts">
import { ref, toRefs } from 'vue'

interface IGroupDetail {
    created_at: string;
}
const props = defineProps<{
    groupDetail: Partial<IGroupDetail>
}>()

// const { groupDetail } = toRefs(props) // Comment this code，groupDetail in template will unknown 

</script>

<template>
  <div>  {{ groupDetail.created_at }}</div>
   <div>  {{ props.groupDetail.created_at }}</div>
</template>

```

```json

{
  "include": [
    "vite.config.*",
    "vitest.config.*",
    "cypress.config.*",
    "nightwatch.conf.*",
    "playwright.config.*",
    "env.d.ts",
    "src/**/*",
    "src/**/*.vue"
  ],
  "vueCompilerOptions": {
    "target": 3
  },
  "compilerOptions": {
    "strict": false,
  }
}

```

### What is expected?

groupDetail should be IGroupDetail not unknown

### What is actually happening?

groupDetail type get unknown

### Link to minimal reproduction

https://github.com/Kanade-Lu/vue-bue-report

### Any additional comments?

set vueCompilerOptions.target = auto or strict = true will get right type

**Comment by KazariEX** [comment] 2024-09-11 08:01
Duplicate of #4704

**Closed** 2024-09-11 08:01 UTC
Labels: pending triage
