### ISSUE TITLE
Issues encountered when using vue-official

### ISSUE THREAD

**Issue by imddc** [vuejs/language-tools#3968] opened 2024-03-04 11:02 UTC
In the latest version 2.04, using vue-official 
1. cannot correctly display the component type
2. there is an error: "all destructured elements are unused"

**Comment by imddc** [comment] 2024-03-04 11:02
![image](https://github.com/vuejs/language-tools/assets/88233704/4fe5d83d-c84e-4e92-99c7-aab9db62ebbe)

**Comment by johnsoncodehk** [comment] 2024-03-04 11:47
Duplicate of #3942

**Closed by johnsoncodehk** 2024-03-04 11:47 UTC
