### ISSUE TITLE
Self closing slot tag get red in child component

### ISSUE THREAD

**Issue by audelqua** [vuejs/language-tools#4411] opened 2024-05-23 19:37 UTC
here is my parent component:
`
<Modal>
    <slot>im inside parent here we go</slot>
</Modal>
`
and here is my child component: 
`
<template>
    <slot />
</template>
`
here in child component **the slash** got red unexpectedly.

**Comment by RayGuo-ergou** [comment] 2024-05-24 03:36
see https://github.com/vuejs/language-tools/issues/1317

btw self close tag does not 100% equal to normal tag like `<div /> !== <div></div>` not 100% sure about slot tho

**Comment by KazariEX** [comment] 2024-10-31 12:09
Duplicate of #1317

**Closed by KazariEX** 2024-10-31 12:09 UTC
Labels: in-discuss
