### ISSUE TITLE
The syntax highlighting doesn't work

### ISSUE THREAD

**Issue by nethriis** [vuejs/language-tools#4029] opened 2024-03-06 19:10 UTC
I have recently deleted TypeScript Vue Plugin because I receive a message that says me to uninstall it, so I do it. Then my Vue Language Features doesn't hightlight anything.I try to make a TypeScript: Restart TS server but it does nothing.

**Comment by nethriis** [comment] 2024-03-06 19:10
For the context I am on nuxt 3.10.x

**Comment by nethriis** [comment] 2024-03-06 19:50
@tsukkee

**Comment by dbssman** [comment] 2024-03-06 20:38
Same here, the syntax highlighting and intellisense is not properly working for me either

**Comment by yllaw** [comment] 2024-03-06 21:25
Same here, auto-imports via nuxt are not working after enabling the built-in Typescript and Javascript Extensions (and removing deprecated volar).

**Comment by so1ve** [comment] 2024-03-07 04:25
Have you installed the `Vue - Official` Plugin?

**Comment by nethriis** [comment] 2024-03-10 11:55
Thanks, finally I have downgrade my Vue - Official Plugin to 1.8.27 and it works well.

**Comment by johnsoncodehk** [comment] 2024-03-26 23:05
Duplicate of #4029

**Closed by johnsoncodehk** 2024-03-26 23:05 UTC
Labels: bug
