### ISSUE TITLE
[Bug] 拆分视图下的变量跳转依旧在本视图而不是对应视图

### ISSUE THREAD

**Issue by fuyaozs9wl** [vuejs/language-tools#4096] opened 2024-03-14 09:37 UTC
![image](https://github.com/vuejs/language-tools/assets/132030377/a47d9409-0119-4094-9189-90fdce0f43dc)
如上图，我点击右边视图（template）中的变量，直接展开了本视图的script标签
![image](https://github.com/vuejs/language-tools/assets/132030377/1c7f3854-c7f8-4ec0-ad64-d6761ee94b66)

期望的效果是去左边的视图（script）定位

**Comment by davidmatter** [comment] 2024-08-05 21:52
Closing this one due to lack of a minimal reproduction. Feel free to create a new discussion or a new issue if you’re still having problems, thanks!

**Closed by davidmatter** 2024-08-05 21:52 UTC
Labels: pending triage
