### ISSUE TITLE
No tsconfig in newly created vue file

### ISSUE THREAD

**Issue by vincentZhang92** [vuejs/language-tools#3329] opened 2023-06-27 04:09 UTC
There is a ts problem in my project. Every time the newly created vue file is displayed "No tsconfig", the tsconfig will be obtained normally after reloading using vscode.

![image](https://github.com/vuejs/language-tools/assets/90586248/4fb753a6-7152-4da1-af0c-e9b8969790dc)

**Comment by so1ve** [comment] 2023-06-27 05:45
Duplicate of #3328

**Comment by so1ve** [comment] 2023-06-27 05:46
There is a breaking change in v1.8.2 :(

no longer parse vue files outside tsconfig include option to avoid TS performance concerns (https://github.com/vuejs/language-tools/issues/3326)

**Comment by vincentZhang92** [comment] 2023-06-27 05:59
> There is a breaking change in v1.8.2 :(
> 
> no longer parse vue files outside tsconfig include option to avoid TS performance concerns (#3326)

`"compilerOptions": {
 ......,
"verbatimModuleSyntax": true
"baseUrl": ".",
},
"include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx",
    "typings/**/*.d.ts",
    "typings/**/*.ts"
  ],
  "exclude": ["node_modules", "dist", "**/*.js"]`

I used the "include" attribute to include the vue file in the "src" directory. This problem only occurs in new files. Previous files or overloaded vscode will return to normal, and if ts is downgraded to ts@4.9.5 it will also return to normal.

**Comment by so1ve** [comment] 2023-06-27 07:15
Let's keep it open to further investigate

**Comment by alex-dow** [comment] 2023-06-29 16:51
Any newly created file fails for me. Vue file or plain TS file. Using Volar 1.8.3 in takeover mode. 

Only work around is to reload the window. Restarting Volar only is not sufficient.

**Comment by PengBoUESTC** [comment] 2023-07-26 01:32
any solution

**Comment by PengBoUESTC** [comment] 2023-07-26 03:10
it seems like that, extension can not found the files created by copy or `plop`?

**Comment by so1ve** [comment] 2023-08-16 15:43
Should it work now?

**Comment by vincentZhang92** [comment] 2023-08-17 08:57
> Should it work now?

No, still show "No tsconfig"

**Comment by yao378186268** [comment] 2023-09-14 02:25
It's a bit disgusting，How to solve it?

**Comment by so1ve** [comment] 2023-09-17 05:55
Can someone check which version introduced this regression?

**Comment by aleksey-hoffman** [comment] 2023-11-09 14:40
Any progress, guys?
It's so annoying to deal with, I'm considering switching from Vue to React😄

**Comment by so1ve** [comment] 2023-11-10 01:51
@aleksey-hoffman It seemed to be a display issue, shouldn't affect language support.

**Comment by aleksey-hoffman** [comment] 2023-11-10 08:55
@so1ve the problem is, when you create a new component file, vscode doesn't show autocomplete suggestions for the imports. So you have to restart vscode every time you create a new file or import all components manually

**Comment by so1ve** [comment] 2023-11-10 09:04
Nah! This is quite annoying. I'm looking for a solution

**Comment by zzhenryquezz** [comment] 2023-11-10 22:28
I have some info that may be useful.

I created a repo to reproduce the bug, follow the readme to see how reproduce the bug:
https://github.com/zzhenryquezz/bug-volar-3329

This repo is very similar to my real project that has this bug and I using nuxt 3 in this repo.

Looks like when I add a local module the bug start to happened.

One thing I notice is that if you comment on this part of tsconfig.json, the tsconfig.json is detected by vscode normally

![image](https://github.com/vuejs/language-tools/assets/43827016/5e1221af-f755-41d3-a9f5-5f6841388639)

And another note is that nuxt will add these paths to the extended tsconfig.json when a new module is detected
![image](https://github.com/vuejs/language-tools/assets/43827016/e1ea029b-f7e3-4332-9445-03a053ea7387)

So I guess the bug is related to tsconfig.json exclude, include paths, or it could be and invalid tsconfig.json since theses files do not exists

**Comment by vanarok** [comment] 2023-12-12 13:16
I am using vue language server with helix editor. 
tsconfig:
```
{
  "extends": "@vue/tsconfig/tsconfig.web.json",
  "compilerOptions": {
    "target": "ESNext",
    "jsx": "preserve",
    "lib": ["DOM", "ESNext"],
    "baseUrl": ".",
    "module": "ESNext",
    "moduleResolution": "node",
    "paths": {
      "@/*": ["src/*"]
    },
    "resolveJsonModule": true,
    "types": [
      "vite/client"
    ],
    "allowJs": true,
    "strict": true,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true
  },
  "include": ["*.vue", "env.d.ts", "src/**/*", "src/**/*.vue", "src/**/*.json", "src/**/*.ts"],
  "exclude": ["dist", "node_modules"]
}
```

creating new files doesn't add them to the auto import hint, and I have to restart the server all the time for the file to be noticed by it

**Comment by rennzhang** [comment] 2023-12-18 07:33
I have also encountered the same problem and do not know how to solve it. I have provided the following minimal reproducible cases, hoping to provide some help。

repo：https://github.com/rennzhang/vue3-ts-error-report

### You can follow these steps to repeat

> This project uses the `unplugin-auto-import` plug-in.

1. Create a new folder under views, Like "aaa"
2. Create `index.vue` under "aaa"
3. Enter the following code & `npm run dev`

```vue
<template>
  <div></div>
</template>

<script lang="ts" setup>
let a = ref(1);
</script>

<style scoped lang="less"></style>
```

The following error will occur

```
Name not found “ref”。ts(2304)
```

**Comment by aleksey-hoffman** [comment] 2023-12-18 11:24
@rennzhang 
You have to import `ref` function

```
<script lang="ts" setup>
  import {ref} from 'vue'
  let a = ref(1);
</script>
```

**Comment by aleksey-hoffman** [comment] 2023-12-18 11:25
@rennzhang 
You have to import `ref` function

```html
<script lang="ts" setup>
  import {ref} from 'vue'
  let a = ref(1);
</script>
```

**Closed** 2023-12-26 11:29 UTC
Labels: bug

**Comment by sharifzadesina** [comment] 2024-04-01 19:12
This still happens to me, for every single new vue file, I need to restart VSCode, otherwise nothing will work inside that file, so annoying.

**Comment by datnguyen-tech** [comment] 2024-04-05 04:35
same issue :((

**Comment by nicoroy2561** [comment] 2024-05-30 09:26
I'm having the same issue here, not sure why this was closed.

**Comment by EdoanR** [comment] 2024-06-20 16:16
This is still happening. No Intellisense, no definitions. I have to restart the TS server every new file `.vue` file I create, sometimes need to reload vscode.

**Comment by so1ve** [comment] 2024-06-21 13:38
@EdoanR This is a different issue. https://github.com/vuejs/language-tools/issues/4424
