### ISSUE TITLE
No suggestions for propreties (Options API)

### ISSUE THREAD

**Issue by haug1** [vuejs/language-tools#4074] opened 2024-03-12 02:30 UTC
As seen below the property "something" does not get suggested on the `OptionsAPIComponent`.
Also no reported error on either even though they're missing the required property.

To reproduce, use below code. I set up a project with `npm create vue` and no to everything except eslint+prettier, then add the components.

```vue
<script>
import OptionsAPIComponent from './OptionsAPIComponent.vue'
import CompositionAPIComponent from './CompositionAPIComponent.vue'
export default {
  components: {
    OptionsAPIComponent,
    CompositionAPIComponent
  }
}
</script>
<template>
  <OptionsAPIComponent />
  <CompositionAPIComponent />
</template>
```

```vue
<template>
  <div>{{ something }}</div>
</template>
<script>
export default {
  props: {
    something: {
      type: String,
      required: true
    }
  }
}
</script>
```

```vue
<script setup>
defineProps({
  something: {
    type: String,
    required: true
  }
})
</script>
<template>
  <div>{{ something }}</div>
</template>
```

# Property is not suggested externally on component reference

![image](https://github.com/vuejs/language-tools/assets/31956036/a42dee4e-52ca-424f-80d2-a55004ceddef)

![image](https://github.com/vuejs/language-tools/assets/31956036/775665d2-5e50-4072-9b43-752b143ea115)

# Property is not suggested internally in template

![image](https://github.com/vuejs/language-tools/assets/31956036/934918da-dc6f-44de-86a6-dfbcba1e36c0)

![image](https://github.com/vuejs/language-tools/assets/31956036/2cb81311-eb9b-4f38-8286-42bb5b320f81)

# Property is not suggested on component instance

![image](https://github.com/vuejs/language-tools/assets/31956036/3aeb96bf-3b7f-48a9-8737-c4ad407b4d4e)

# Method is not suggested on component instance

![image](https://github.com/vuejs/language-tools/assets/31956036/51fd2d3a-515f-42fe-ac08-4f221de0bf81)

# After adding `data()` to the component resolves a lot of LSP issues

![image](https://github.com/vuejs/language-tools/assets/31956036/11f02133-2723-45fa-8836-d4a3921f9d8f)

## But not reference to internal properties

![image](https://github.com/vuejs/language-tools/assets/31956036/075bade6-7164-4a2a-a2f6-d458607e7609)

## Properties are correctly suggested under the `$props` property (when `data()` is specified)

![image](https://github.com/vuejs/language-tools/assets/31956036/6feaa09c-625e-4e42-9546-f5002d8bd5fb)

**Comment by haug1** [comment] 2024-03-14 14:42
I see other issues labelled with "good reproduction", please let me know if I can provide any more information?

**Comment by so1ve** [comment] 2024-03-15 01:57
Duplicate of https://github.com/vuejs/language-tools/issues/3690

**Closed by so1ve** 2024-03-15 01:57 UTC
Labels: bug, duplicate, good reproduction ✨
