### ISSUE TITLE
This expression is not callable. Type '{}' has no call signatures - Dynamic slots + Generic

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/language-tools#3141] opened 2023-05-07 13:59 UTC
Hi 👋🏻 

I was playing with the generic components feature and stumbled upon this issue where I get a type error on the slot like below:
![image](https://user-images.githubusercontent.com/47495003/236681876-d93f451d-b1ff-4f12-a37b-c09c6ac59047.png)

**Reproduction:** https://github.com/jd-solanki/volar-vue-playground/blob/generic-component-type/src/bar/Bar.vue

> **Note**
> Watch out for branch

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 6.86 GB / 15.95 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vue: 3.3.0-beta.4 => 3.3.0-beta.4 
    vue-tsc: ^1.6.4 => 1.6.4
```

> P.S. It will be much easier for you if you add issue template

**Comment by jd-solanki** [comment] 2023-05-09 06:48
Upon further inspection, I found that component meta shown empty slots array:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/47495003/237016379-be9746c4-5670-4856-97c7-e67bf2cf1bbe.png">

I guess vue component meta doesn't properly handle the generics yet 🤔

**Comment by jd-solanki** [comment] 2023-05-11 19:41
@johnsoncodehk is [this](https://github.com/vuejs/core/pull/7982#issuecomment-1490299546) supported by volar ATM?

Because I think both are the same thing 🤔 

I also tried doing something like this for my actual code but doesn't seems to work:
```ts
{ [name in `col-${RowKey<Row>}`]: (_: { row: Row; colIndex: number }) => any }
```

**Comment by johnsoncodehk** [comment] 2023-05-13 07:04
This doesn't seem to be a Volar issue, you can reproduce it in script.

```html
<script lang="ts" setup generic="Row extends Record<string, unknown>">
import { objectKeys } from '../utils';
import { aTableProps, aTableSlots } from './meta';

const props = defineProps(aTableProps<Row>())

const _slots = aTableSlots<Row>(
    objectKeys(props.rows[0] || {}),
)
defineSlots<typeof _slots>()

for (const col of props.cols) {
    _slots[`header-${col.name}`]?.({ col }); // Type '{}' has no call signatures.ts(2349)
}
</script>
```

**Comment by jd-solanki** [comment] 2023-05-13 12:13
Hi @johnsoncodehk 

Thanks for your inspection. May I know how to resolve this because according to me I'm generating correct object in aTableSlots?

Awaiting your response.

**Comment by jd-solanki** [comment] 2023-05-13 16:02
Strange thing is if you comment `before-table` slot then type error went away.

Extending my previous comment, I guess I'm generating correct object but it looks like there's issue with the generated type.

**Comment by xiaoxiangmoe** [comment] 2023-05-19 05:02
@jd-solanki Hi, it seems to be this is a TypeScript's limit:

```ts
type Slots<Foo extends string> = {
  readonly "before-table": (_: any) => null;
} & Record<`header-${Foo}`, (_: { col: any }) => any>;

function foo<Foo extends string>(
  slots: Slots<Foo>,
  key: `header-${Foo}`
) {
  const slot = slots[key];
  // @ts-expect-error This expression is not callable. Type '{}' has no call signatures.ts(2349)
  slot?.({ col: 1 });
}
```

If you simplify your code:

```ts
type Slots<Foo extends string> = Record<`header-${Foo}`, (_: { col: any }) => any>;

function foo<Foo extends string>(
  slots: Slots<Foo>,
  key: `header-${Foo}`
) {
  const slot = slots[key];
  slot?.({ col: 1 });
}
```

All works well.

Maybe you should create a issue to TypeScript.

**Comment by xiaoxiangmoe** [comment] 2023-05-19 05:04
Closed this issue because it is an upstream issue, if you need any other help, or if you find any other volar issues, please feel free to raise them below.

**Comment by jd-solanki** [comment] 2023-05-19 07:47
Hi @xiaoxiangmoe 

Thanks for your response. Can you plese share your thoughts on this: https://www.typescriptlang.org/play?target=99#code/FAFwngDgpgBAygGwPYgM4B4BiSkygDxCgDsATVGVEAJwEtiBzAPhgF4YBvYGGaqAQ1JJiCMDABEAIygAzJHwC0IfpIRRxALhgAKAPpb+xMAEo2LYgFcECANzAAvjABkMAEpQAxvNLoABgAsBUihqBQASDmwke18AGh19ThgvBAMjGHtTVhZDMCY7YBkLYg8QWmEYOSR0AEFqBgoCIjIKAG1EFAwqOkYmeO76BgBdJm1uGAA6KdbUZDR4gGsoMCGtOoa8QhJyGHa5jHoZEJgovsoaQaGYAH5djrQsHDOAoJDwyJwYq61iKAA3ELAUxcHheYhUShzNiQzqtJYrAo8AD0SJgAHV5AtUABCcazFDaDjJJCpGAARgyxjs9iAA

**Comment by jd-solanki** [comment] 2023-05-19 08:19
Might be similar: https://github.com/vuejs/core/issues/8352

**Comment by xiaoxiangmoe** [comment] 2023-05-19 08:21
> Can you plese share your thoughts on this

I'm not quite sure what's going on, but I found that in your latest example, the slots and key are controlled by the same generic `Args`.

And in your original example, actually `Rows` and `key` are changed independently. 
For this reason, I extracted a simplified demo and used a function foo to demonstrate the origin of your error `Type '{}' has no call signatures.ts`.

**Comment by jd-solanki** [comment] 2023-05-19 08:26
Can we improve something at volar side considering this kind of common usage? https://github.com/vuejs/core/pull/7982#issuecomment-1490284591 https://github.com/vuejs/core/issues/8352

What's your thoughts on opening and renaming this issue?

**Comment by xiaoxiangmoe** [comment] 2023-05-19 09:10
@jd-solanki  See https://github.com/vuejs/core/issues/8352#issuecomment-1554258249

**Comment by jd-solanki** [comment] 2023-05-19 09:53
Hi @xiaoxiangmoe 

I tried doing that and it still gives `Type '{}' has no call signatures.`. However, If I remove `'before-table': (_: any) => null` slot definition just like in my reproduction it works.

```ts
// meta.ts
export function aTableSlots<Row extends Record<string, unknown>>(colKeys: RowKey<Row>[]) {
    return ({
    // If I comment below line then error in SFC is gone 🤔
    'before-table': (_: any) => null,
    
    ...colKeys.reduce((a, colKey) => (
      { ...a, [`header-${colKey}`]: Function }
    ), {} as { [K in `${RowKey<Row>}-cell`]: (props: { item: RowKey<Row>; }) => any; }),
  }) as const
}
```

```vue
<!-- script part is same -->
<template>
    <div class="wrapper">
        <div v-for="row in props.rows">
        <header v-for="(col, index) in props.cols" :key="index">
            <slot :name="`${col.name}-cell`" :col="col"></slot>
            <!--  This expression is not callable. Type '{}' has no call signatures. -->           
        </header>
        </div>
    </div>
</template>
```

In my reproduction and this example, if you comment out `'before-table': (_: any) => null,` slot will work ✨

**Comment by jd-solanki** [comment] 2023-05-19 09:56
Here's video demo:
https://github.com/vuejs/language-tools/assets/47495003/8c9460c1-7534-4c02-a31f-4768d030ed77

**Comment by pikax** [comment] 2023-05-19 15:06
I would strongly recommend not using `aTableSlots` since the return type is **not** used!

I would recommend switching to a type
```ts
type aTableSlots<T extends Record<string, unknown>> = {
  [K in keyof T as `header-${K & string}`]: (_: {
    col: ATablePropColumn<T>
  }) => any
} & {
  ['before-table']?: (_: { a: string }) => any
}
```
The reason being `defineSlots` is plainly a typescript implementation without any runtime validation.

To use this new `aTableSlots ` is fairly easy by:

```ts
const slots = defineSlots<aTableSlots<Row>>()
```

full example:
```html
<script lang="ts" setup generic="Row extends { [K: string]: any}">
interface ATablePropColumn<Row extends Record<string, unknown>> {
  name: RowKey<Row>
}
const props = defineProps<{
  rows: Row[]
  cols: ATablePropColumn<Row>[]
}>()

type RowKey<Row extends Record<string, unknown>> = keyof Row & string

type aTableSlots<T extends Record<string, unknown>> = {
  [K in keyof T as `header-${K & string}`]: (_: {
    col: ATablePropColumn<T>
  }) => any
} & {
  ['before-table']?: (_: { a: string }) => any
}

const slots = defineSlots<aTableSlots<Row>>()

for (const col of props.cols) {
  const slot = slots[`header-${String(col.name)}`]
  slot?.({ col })
}
</script>

<template>
  <div class="wrapper">
    <div v-for="row in rows">
      <header v-for="(col, index) in cols" :key="index">
        <slot :name="`header-${String(col.name)}`" :col="col"></slot>
        <!--  This expression is not callable. Type '{}' has no call signatures. -->
      </header>
    </div>
  </div>
</template>
```

**Comment by pikax** [comment] 2023-05-19 15:25
@xiaoxiangmoe  

I get an error on vue 3.3.4 🤔 
<img width="456" alt="image" src="https://github.com/vuejs/language-tools/assets/4620458/dd4a175b-4d5f-472e-bc4c-7ebcce63db3d">

**Comment by xiaoxiangmoe** [comment] 2023-05-19 16:20
Oh, you are right.

**Comment by jd-solanki** [comment] 2023-05-20 07:54
Hey @pikax and I'll try to go with full TS like below:

```ts
import { OptionalKeysOf } from 'type-fest'

export interface AlertProps {
  rows: unknown[],
  icon?: string
  appendIcon?: string
  dismissible?: boolean
  modelValue?: boolean
}

export const alertPropsDefault = {
  appendIcon: 'close',
} satisfies Pick<AlertProps, OptionalKeysOf<AlertProps>>
```
(_above is just playground component and file is `meta.ts`_)

Before refactoring the codebase 4th time I just want to comfirm that,
1. Is this fine?
2. I'll have `meta.ts `and `<Component-SFC>.vue` file
3. I'll export shared component props from `meta.ts` and reuse them.

Final out of context questions:
Can I somehow export and reuse (might need all of or few of them) props from SFC if I go with `withDefaults(defineProps<Props>(), { ... }`

Thanks.

**Comment by jd-solanki** [comment] 2023-05-23 07:07
@xiaoxiangmoe Can we remove upstream label?

**Comment by xiaoxiangmoe** [comment] 2023-05-24 12:44
@jd-solanki 

Can you see weather it fix your problem? https://github.com/vuejs/language-tools/issues/3141#issuecomment-1554669251

Is there any bug should fix in volar?

**Comment by jd-solanki** [comment] 2023-05-28 05:55
Hi @xiaoxiangmoe I was busy with some other stuff. I'll let you know once soon.

**Comment by jd-solanki** [comment] 2023-05-29 11:18
Hi @xiaoxiangmoe 👋🏻 

It works 💚 

I wanted to know is this some kind of hack to workaround volar or TS limitation.

I'm also creating new component based on this component and passing slots down to this component. Will this create any troublem because I'm having type issue in another component that uses it but I'm unable to identify if it's from volar or my side.

Thanks.

**Comment by xiaoxiangmoe** [comment] 2023-05-29 12:48
This is not hack to workaround volar, it just some workaround for TypeScript.

**Comment by jd-solanki** [comment] 2023-05-29 12:52
I wonder performing that change will make type as `header-${string}` => `string` for slot name instead of actual names like `header-name`? Is it true?

Are you interested in checking the another component (build on top of mentioned component) error after perfoming mentioned changes (that solves the type error for that component though)?

Regards.

**Comment by so1ve** [comment] 2023-12-13 13:51
Fixed by https://github.com/vuejs/language-tools/issues/3141

**Closed by so1ve** 2023-12-13 13:51 UTC
Labels: question, good reproduction ✨
