### ISSUE TITLE
When I use `v-for` on the `template`, I use the index as the `key`, and the prompt `index` is declared but its value is never read and `vue-tsc` cannot pass the verification.

### ISSUE THREAD

**Issue by aibayanyu20** [vuejs/language-tools#3850] opened 2024-01-11 01:01 UTC
### Vue version

3.4.8

### Link to minimal reproduction

https://play.vuejs.org/#eNp9UU1PwzAM/SuRTyCNTTBO1YbExw5wAATcMIeq80q2NIkSdwxV/e+4KZQhoeUS2+/Zfi9p4NL78bYmyGAWi6A9q0hce2VyW84ROCJcoC2cjayMjnyTc67m6hUtwinCqLvPvu9zBLRvaGeTfpQ0SsJUeZMzSabUkKntycoF2XCkpTTSdkm7Y6XtsARBZRv6FEbCkgwlp2lU16HaNs2b7I3/k8BIxIvulS7H6+isOGy6DoTCVV4bCg+etfhCyFRCOiw3xn3cpRqHmsRWXy/eqdj8U19HUZZJ8BgoUthSeooe4zyUxD28eL6nncQDWLllbYR9AHyi6EzdaexpV7Vdiuw9XlJ7W3kXWNvyJS52TDb+mOqEdsw28RHkm68PWP+VOx1PUx/aFtovf0S0DA==

### Steps to reproduce

![image](https://github.com/vuejs/core/assets/45655660/352565f9-6bd5-4648-9d77-72fe4a9289ba)

### What is expected?

Expect to pass vue-tsc type check

### What is actually happening?

Currently unable to pass vue-tsc type check

**Comment by so1ve** [comment] 2024-01-11 09:03
Duplicate of #329

**Closed by so1ve** 2024-01-11 09:03 UTC
