### ISSUE TITLE
Variable names in v-for mess up formatting

### ISSUE THREAD

**Issue by ericcirone** [vuejs/language-tools#4275] opened 2024-04-16 19:25 UTC
Using v2.0.12

Here is an example

<img width="349" alt="image" src="https://github.com/vuejs/language-tools/assets/10419347/4b07514f-fff2-4030-a9b5-4b2e15bb1d45">

It seems that `type` is reserved in the Language server and using it as a variable messes up coloring and formatting.

This is code migrated from Vue 2 with Vetur and it all worked as expected.

**Comment by so1ve** [comment] 2024-04-17 00:49
Duplicate of #520

**Closed by so1ve** 2024-04-17 00:49 UTC
