### ISSUE TITLE
Type error when using Generics, defineModel, and defineProps together

### ISSUE THREAD

**Issue by Robbe95** [vuejs/language-tools#3195] opened 2023-05-17 11:41 UTC
When using the **defineProps** and **defineModel** functions within a component with defined **generics**, the component will encounter an issue where it is unable to recognize the props defined within it.

This issue arises specifically when both defineProps and defineModel are present together, and generics are defined for the component. In such cases, the component fails to properly acknowledge the props.

Example: 
<img width="520" alt="image" src="https://github.com/vuejs/language-tools/assets/44748019/1f5b5356-8c9a-4320-aa09-3c0405061890">
<img width="816" alt="image" src="https://github.com/vuejs/language-tools/assets/44748019/fbc023db-bcf7-4210-a1fd-8a70306c3b95">

A similar error occurs within the component itself if you do not destructure the defineProps.

<img width="1340" alt="image" src="https://github.com/vuejs/language-tools/assets/44748019/fab7ca66-20ae-4e26-9191-11bf010a1905">

However, by removing either the **defineModel** function or the **generic** definition, the component functions as expected, and the props are recognized as intended as seen below: 

<img width="491" alt="image" src="https://github.com/vuejs/language-tools/assets/44748019/2bbd8647-55e0-40de-9a31-1c220cd39e8b">
<img width="491" alt="image" src="https://github.com/vuejs/language-tools/assets/44748019/9778b49b-af96-498b-ac84-60b70ae974af">
<img width="629" alt="image" src="https://github.com/vuejs/language-tools/assets/44748019/ed10befd-0bd4-4df0-9264-a09c0674536c">

Reproduction: [https://github.com/Robbe95/volar-generics-definemodel-bug](https://github.com/Robbe95/volar-generics-definemodel-bug)

Vue version: 3.3.2
Vue Language Features (Volar) version: 1.6.3
Typescript Vue Plugin (Volar) version: 1.6.5

**Comment by metkm** [comment] 2023-05-18 14:16
Related https://github.com/vuejs/language-tools/issues/3164#issuecomment-1543872634

**Comment by johnsoncodehk** [comment] 2023-06-07 20:07
Duplicate of #3164

**Closed by johnsoncodehk** 2023-06-07 20:07 UTC
Labels: bug
