### ISSUE TITLE
Vue intellisense does not work with PNPM & VSCODE 1.85.1

### ISSUE THREAD

**Issue by aspheresedge** [vuejs/language-tools#3802] opened 2023-12-13 22:57 UTC
Vue intellisense doesnt work on astro projects after updating vscode to the latest version when you're using pnpm as your package manager.

reproduction steps:
1 - pnpm create astro@latest
2 - pnpm astro add vue 

![image](https://github.com/vuejs/language-tools/assets/114557048/464af538-4d17-484c-ab91-b0e5fe20bc33)

**Comment by trgoofi** [comment] 2023-12-15 04:25
Encountering the same issue after update vscode and volar to the latest version but not a Astro project. 

```
- vscode

Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 21.6.0
```

```
- TypeScript Vue Plugin (Volar) and Vue Language Features (Volar)
Version: v1.8.25
```

```
- pnpm 8.10.2
- vue 3.3.8
```

**Comment by so1ve** [comment] 2023-12-15 05:15
Could you please provide a minimal reproduction?

**Comment by trgoofi** [comment] 2023-12-15 07:39
> Could you please provide a minimal reproduction?

@aspheresedge have provided the reproduction steps. I guess I just provide extra info to rule out some possibilities.

Anyway here the steps to reproduce:  (In short `npm` works `pnpm` breaks)

Follow [Vue official quick start](https://vuejs.org/guide/quick-start.html#creating-a-vue-application)  to create a vue application just replace `npm` with `pnpm`

1. `pnpm create vue@latest` gave it a project name and other options just type `enter` to use the default.
2. use `pnpm install`  to install deps.
3. open the project with vscode then start typing in `App.vue` file  intellisense breaks.
4. delete `node_modules`.
5. use `npm install` to install deps.
6. _"reopen"_ the project with vscode to repeat step `3` intellisense working just fine. (reopen: close vscode then open again)

pnpm screenshot:
![pnpm-breaks](https://github.com/vuejs/language-tools/assets/434025/74940f70-6032-42ad-b213-10d1b1d52d2c)

npm screenshot:
![npm-works](https://github.com/vuejs/language-tools/assets/434025/324f8a7d-b497-4745-b571-ac803571ecd3)

**Comment by so1ve** [comment] 2023-12-16 04:12
This seemed to be an upstream issue with auto complete

**Comment by AntonioDell** [comment] 2023-12-20 14:25
Probably a duplicate of https://github.com/vuejs/language-tools/issues/3730.
See my comment [here](https://github.com/nuxt/nuxt/discussions/22284#discussioncomment-7819500) for a workaround.

**Comment by suiyi8760** [comment] 2023-12-21 08:09
same problem too, is this problem made from volar? or vscode lsp?

**Comment by aspheresedge** [comment] 2023-12-21 13:51
> Probably a duplicate of #3730. See my comment [here](https://github.com/nuxt/nuxt/discussions/22284#discussioncomment-7819500) for a workaround.

I haven;t had time to check the duplicate issue, but I think your solution is correct, when I did my VSCODE downgrade, TS got downgraded to 5.2.2 which is what you're recommending

If anyone runs into this issue I would recommend looking at Antonio's solution.

**Closed** 2023-12-21 16:31 UTC
Labels: bug, upstream
