### ISSUE TITLE
VSCode extension loses all highlighting, auto imports, intellisense, etc.

### ISSUE THREAD

**Issue by tsi-trmorris** [vuejs/language-tools#4256] opened 2024-04-11 21:23 UTC
I seem to have lost use of essentially all the functionality I care about in the VSCode extension. I have no highlighting, auto-imported components, etc. As a minimal reproduction, I created a new Vuetify project using their generator. For this, I ran `pnpm create vuetify` with the default options and `pnpm` as my package manager

![image](https://github.com/vuejs/language-tools/assets/122816113/72900d76-62ea-44f0-9458-a1c2a7fc5922)

Running the `Vue: Restart Vue and TS servers` command in my command palette reports the following in the `Output` tab:
```
[Error - 2:19:40 PM] Server process exited with code 0.
[Vue Named Pipe Client] No server found for c:/temp/vue/vuetify-project/src/App.vue
```

**Environment:**
Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by Ludidi** [comment] 2024-04-12 02:32
Me too And the file cannot be saved :(

**Comment by Zhao-changyuan** [comment] 2024-04-12 02:58
Me too And the file cannot be saved :(

**Comment by Zhao-changyuan** [comment] 2024-04-12 03:53
> Me too And the file cannot be saved :(
Me too

**Comment by saronwei** [comment] 2024-04-12 04:56
Me too And the file cannot be saved :(

**Comment by s3xysteak** [comment] 2024-04-12 05:54
Me too in `v2.0.12` 😭

**Comment by biwchi** [comment] 2024-04-12 06:02
Same problem in sublime text. No syntax highlighting and cannot be saved

**Comment by Ludidi** [comment] 2024-04-12 06:06
Try to roll back to version v1.8.27. If there is unocss plug-in, it will be disabled. It is running normally now.

**Comment by cdenadai** [comment] 2024-04-12 13:31
Hey guys, my problem was on vscode 1.88. 
Both Microsoft VSCode and VSCodium. 

The solution for me was rollback the VSCodium version to 1.87, Microsoft VSCode don't let me rollback the version on ubuntu.

Let me know if it works.

**Comment by wmurphyrd** [comment] 2024-04-12 18:14
Our team resolved this by rolling back Vue plugin - official to v2.0.6

**Comment by astamant** [comment] 2024-04-14 16:05
> Our team resolved this by rolling back Vue plugin - official to v2.0.6

This issue has been very disruptive, rolling back Vue - Official plugin to v2.0.6 as per @wmurphyrd fixed it for me as well.

**Comment by marlemie** [comment] 2024-04-16 11:59
Using VS Code, I have the same issue but do not even get any output from "Vue Language Server". Rolling back to 2.0.6 works.

**Comment by TheVaan** [comment] 2024-04-22 15:01
I'm getting `[Vue Named Pipe Client] No server found for .....` and `[Vue Named Pipe Client] Timeout`. Rollback to 2.0.6 *is not working* for me.

Vue plugin 2.0.14
vue-tsc 2.0.14

**Comment by funny-cat-happy** [comment] 2024-04-25 01:31
it seems like the plugin conflicts with unocss plugin. If I disable unocss, it runs normally.

**Comment by wunderdaz** [comment] 2024-04-30 12:02
Just found this my side, easily reproducable by creating a new Vuetify project, opening VSCode into the solution, then hovering over any vuetify control

**Comment by rrobertobt** [comment] 2024-05-04 04:15
> Just found this my side, easily reproducable by creating a new Vuetify project, opening VSCode into the solution, then hovering over any vuetify control
> 
> @wmurphyrd How'd you roll back? My VSCode shows no previous versions
> 
> Edit: Here's a tutorial [microsoft/vscode#12764 (comment)](https://github.com/microsoft/vscode/issues/12764#issuecomment-442370545)
> 
> ```
> code --install-extension Vue.volar@2.0.6
> ```
> 
> Double edit: Downgrading doesnt work ![image](https://private-user-images.githubusercontent.com/88765081/326801420-89e68223-bd40-4272-b47a-21e4455cbf37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3OTYzODIsIm5iZiI6MTcxNDc5NjA4MiwicGF0aCI6Ii84ODc2NTA4MS8zMjY4MDE0MjAtODllNjgyMjMtYmQ0MC00MjcyLWI0N2EtMjFlNDQ1NWNiZjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDA0MTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYTYyOWRkNGQxYjM5OWE3NGJjZTdjZDIxOTY3NWZkMjU5YjQ4ZDZhZGRkZDBlMDViMzNlMTY1NTY4OGNjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AvygQ0GLkhT8XWKSWXHkBDo_wrUeTM1u0g86gN-n88o)

Can confirm this, I just created a new Vuetify project using Vuetify;s CLI and it's not working, but Nuxt projects do work without problems (imports, suggestions...)

**Comment by wsndshx** [comment] 2024-06-04 09:45
> Just found this my side, easily reproducable by creating a new Vuetify project, opening VSCode into the solution, then hovering over any vuetify control刚刚发现我这边，通过创建一个新的 Vuetify 项目，将 VSCode 打开到解决方案中，然后将鼠标悬停在任何 vuetify 控件上，可以轻松重现
> 
> @wmurphyrd How'd you roll back? My VSCode shows no previous versions你怎么回滚了？我的 VSCode 没有显示以前的版本
> 
> Edit: Here's a tutorial [microsoft/vscode#12764 (comment)](https://github.com/microsoft/vscode/issues/12764#issuecomment-442370545)编辑：这是一个教程 [microsoft/vscode#12764 (comment)](https://github.com/microsoft/vscode/issues/12764#issuecomment-442370545)
> 
> ```
> code --install-extension Vue.volar@2.0.6
> ```
> 
> Double edit: Downgrading doesnt work双重编辑：降级不起作用 ![image](https://private-user-images.githubusercontent.com/88765081/326801420-89e68223-bd40-4272-b47a-21e4455cbf37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTM4NDYsIm5iZiI6MTcxNzQ5MzU0NiwicGF0aCI6Ii84ODc2NTA4MS8zMjY4MDE0MjAtODllNjgyMjMtYmQ0MC00MjcyLWI0N2EtMjFlNDQ1NWNiZjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5MzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYjZmMWNkOGZiOGNjYjJjNmQyNzM1YzZhMzkwMTU3NTgzZjFjNzA1OGZlN2U2MzdmYjBkMGIzM2I5ZmU4NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z8h0D2DRiqIppCsaq_fIwj6WX5B9i-nSKAwRzWc6ZTo)

The same situation, but when I rolled back to version `v1.8.27`, it seemed to get a little better.

![image](https://github.com/vuejs/language-tools/assets/7829265/4ef6e33f-5a73-478e-a033-394ea4331cd5)

Could identify functions that were not implemented. In `v2.0.6`, the extension did not remind that the function did not exist. But still cannot recognize vuetify controls:

![image](https://github.com/vuejs/language-tools/assets/7829265/73e41879-567e-48f5-982b-df9ab184dec3)

**Comment by so1ve** [comment] 2024-06-04 10:51
True, since we are using ts plugins in v2, you must explicitly include vue files in your tsconfig.

**Comment by fdc-viktor-luft** [comment] 2024-06-19 07:59
I found that the plugin only started to work again when removing the `**.vue` files from the "include" section of the TS config. Resulting in other errors being reported by `vue-tsc`, but I haven't investigated these issues closely now. Seemed to be only related to usages of arrow functions in the template section where the types couldn't be correctly derived anymore.

**Comment by davidmatter** [comment] 2024-08-06 06:26
Hey there, as there have been many fixes in the last 2.x versions: If you're still encountering issues, please provide a minimal reproduction. Otherwise kindly close this one, thanks!

**Closed** 2024-08-13 12:31 UTC
Labels: need info

**Comment by sbinfo** [comment] 2024-09-15 14:56
Vue - Official just didn't work before and now it doesn't work with the VS Code version 1.93.1.
The version here does not matter at all. This extension does not work with any version. 
I just use Vetur which at least shows errors.
