### ISSUE TITLE
pkg:2.0.5 In big project, it is very slow to show the prompts. pkg:1.8.27 show smoothly

### ISSUE THREAD

**Issue by zyhnbyyds** [vuejs/language-tools#4005] opened 2024-03-06 02:22 UTC
In large projects(about dozens to hundreds of pages.), the plugin's prompts are very slow, and I'm not sure if something is blocking it. The IDE's prompts take about 5 seconds, without any errors appearing. If there are errors, it will freeze for a long time. I downgraded the version to 1.8.27, and everything is running smoothly, with timely prompts as well.😫

I test a init project, it works well.

**Comment by IVanMissAya** [comment] 2024-03-06 03:20
I also encountered the same situation

**Comment by sinpor** [comment] 2024-03-06 03:36
The performance is good after I downgraded to `2.0.4`.

**Comment by hotdogc1017** [comment] 2024-03-06 05:22
Me too

**Comment by stormzhangbx** [comment] 2024-03-06 06:31
I encountered the same situation too, downgrade to 2.0.4 will ok.

**Comment by parox2014** [comment] 2024-03-06 06:49
Me too

**Comment by yuqibin** [comment] 2024-03-06 07:41
同，代码提示出来太慢了 ，已卸载

**Comment by GabrielHangor** [comment] 2024-03-06 09:12
Can confirm that 2.0.4 works fine, issue is with 2.0.5

**Comment by medvesekg** [comment] 2024-03-06 11:49
I had the same issue, reverting to 2.0.4 solved it.

**Comment by pm0u** [comment] 2024-03-06 16:35
Same here. I was also occasionally getting TS warnings that `"Type instantiation is excessively deep and possibly infinite"` when creating types for Pinia stores. The error no longer is popping up and the speed is greatley improved in 2.0.4

**Comment by niaodan2b** [comment] 2024-03-07 03:36
In my case (project with 2700+ files in /src), v2.0.4 already slower than v1.8.27 (1 sec vs instant), and v2.0.5 is much more slower (10+ sec).
So maybe not purely 2.0.5 issue?

**Comment by so1ve** [comment] 2024-03-07 04:19
In the preview feedback thread(https://github.com/vuejs/language-tools/discussions/3789) we've received positive comments that the performance got a great improvement, however 2.0.5 upgraded volar.js and that may cause a performance regression.

**Comment by so1ve** [comment] 2024-03-07 04:24
Duplicate of https://github.com/vuejs/language-tools/issues/4024

**Closed by so1ve** 2024-03-07 04:24 UTC
