### ISSUE TITLE
edge case for highlight in vue setup

### ISSUE THREAD

**Issue by Simon-He95** [vuejs/language-tools#4589] opened 2024-07-17 02:15 UTC
### Vue - Official extension or vue-tsc version

latest

### VSCode version

latest

### Vue version

latest

### TypeScript version

latest

### Steps to reproduce

<img width="709" alt="image" src="https://github.com/user-attachments/assets/64988260-f027-4d60-9742-c961a96d1293">

## code

```code
<script setup lang="ts">
type IType = Record<string,string>
</script>
<template>
  <div id='app'>
    <div class="list1" fw600 font-size-10 color-red>
      <div class="item" mb-5>item1</div>
      <div class="item" mb-5>item2</div>
      <div class="item" mb-5>item3</div>
    </div>
    <div class="list2">
      <div class="item">item1</div>
      <div class="item">item2</div>
      <div class="item">item3</div>
    </div>
    <i fw-500 font-size-6>list2的样式写在了Custom css中</i>
    <br />
    <i fw-500 font-size-6>注释掉 config 中important:'#app'，list2的样式才会生效</i>
  </div>
</template>
<style scoped>
/* Write custom CSS here, and transformer support. For example: */
.list2 {
  @apply fw600 font-size-10 color-red;
}

.list2 > .item {
  @apply mb-5;
}
</style>

```

### What is expected?

when setup last with type xxx, will lead to highlight collapse

### What is actually happening?

when setup last with type xxx, will lead to highlight collapse

**Comment by so1ve** [comment] 2024-07-17 04:39
Duplicate of https://github.com/vuejs/language-tools/issues/2060

**Closed by so1ve** 2024-07-17 04:39 UTC
Labels: pending triage
