### ISSUE TITLE
类型“Omit<{ "XXXX": ComponentPublicInstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptio...”上不存在属性“AButton”。ts-plugin(2339)

### ISSUE THREAD

**Issue by qhl123456** [vuejs/language-tools#4044] opened 2024-03-07 09:51 UTC
每个vue页面打开都报错，同时函数提示也没有了，jsDOC的写法都没有任何提示，
类型“Omit<{ "outBoundPlan-add": ComponentPublicInstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; $watch(source: string | Function, cb: Function, options?: WatchOptio...”上不存在属性“AButton”。ts-plugin(2339),          版本为### v2.0.6

**Comment by qhl123456** [comment] 2024-03-07 09:55
回退到1.8版本是正常的

**Comment by LeoKun1231** [comment] 2024-03-07 09:57
+1

**Comment by sky124380729** [comment] 2024-03-08 01:13
The same, my version is `2.0.6`

**Comment by oliver139** [comment] 2024-03-08 01:44
`v2.0.x` is really kind of unfinished I think..
Not going to update it and keep `v1.8.27` until it is fine..

**Comment by so1ve** [comment] 2024-03-08 04:05
Duplicate of #3942

**Closed by so1ve** 2024-03-08 04:05 UTC
