### ISSUE TITLE
Distressed by using VOLAR

### ISSUE THREAD

**Issue by yunfanfan9810** [vuejs/language-tools#2260] opened 2022-12-28 07:19 UTC
During use, VScode saves the code and then saves it again. volar will delete the tag at the end.

This is the result of multiple verifications after troubleshooting. now volar is no longer used.

**Comment by xiaoxiangmoe** [comment] 2022-12-28 12:58
I can't reproduce this problem, please provide minimal reproduction.

**Comment by MeDDoS** [comment] 2023-01-02 08:49
i have the same problem as @yunfanfan9810, its unusable for me:

code before I save (vscode before pressind ctrl + s):

`<template>`
 `<div>`
    `<h1>heading</h1>`
  `</div>`
`</template>`

`<script setup>`
`</script>`

`<style lang="scss" scoped>`

`</style>`

after saving:

`<template>`
`<div>`
`<h1>heading</h1>`
`</div>`

`<script setup>`

`<style lang="scss" scoped>`

`</style>`

the closing tag just got deleted, every time i save.

**Comment by johnsoncodehk** [comment] 2023-01-03 18:55
@MeDDoS Thanks for your reproduce code but I can't reproduce with it, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Closed** 2023-02-11 09:24 UTC
Labels: need more info / repro
