### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by mohammed-alaa** [vuejs/language-tools#4168] opened 2024-03-28 07:36 UTC
Crash error:
```
TypeError: Cannot read properties of undefined (reading 'getProjectVersion')
    at synchronizeHostData (/home/night/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/extensions/node_modules/typescript/lib/typescript.js:142751:16)
    at Object.getProgram (/home/night/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/extensions/node_modules/typescript/lib/typescript.js:142923:7)
    at /home/night/.vscode-server/extensions/vue.volar-2.0.7/dist/server.js:989:23793
    at x (/home/night/.vscode-server/extensions/vue.volar-2.0.7/dist/server.js:989:24781)
    at async d (/home/night/.vscode-server/extensions/vue.volar-2.0.7/dist/server.js:989:23729)
    at async /home/night/.vscode-server/extensions/vue.volar-2.0.7/dist/server.js:3:55237
    at async hk (/home/night/.vscode-server/extensions/vue.volar-2.0.7/dist/server.js:3:18551)
    at async qj (/home/night/.vscode-server/extensions/vue.volar-2.0.7/dist/server.js:3:18009)
    at async f (/home/night/.vscode-server/extensions/vue.volar-2.0.7/dist/server.js:3:54856)
    at async Object.doValidation (/home/night/.vscode-server/extensions/vue.volar-2.0.7/dist/server.js:3:54576)
[Error - 9:28:48 AM] Client Vue: connection to server is erroring.
write EPIPE
[Error - 9:28:48 AM] Client Vue: connection to server is erroring.
write EPIPE
Shutting down server.
....
Shutting down server.
[Error - 9:28:48 AM] Client Vue: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 9:28:48 AM] Client Vue: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 9:28:48 AM] Server process exited with signal SIGKILL.
[Error - 9:28:48 AM] Connection to server got closed. Server will not be restarted.
[Error - 9:28:48 AM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:28:48 AM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
...
```

OS: WSL2 Ubuntu 20.04 on Windows 11

Extension version: `v2.0.7`
![image](https://github.com/vuejs/language-tools/assets/30788249/2f11d8b9-8ce9-4ed1-9e7c-f2b56fa960a9)

VS Code version:
![image](https://github.com/vuejs/language-tools/assets/30788249/16d42c26-38f9-47c1-9abd-83be9333b467)
```
Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by WhaleFell** [comment] 2024-03-30 12:50
Me too, I remember I was updating the volar extension to get this error, it was working before. I rummaged through stackoverflow and found that it could be fixed with a rollback version. ref: [vue-volar-extension-in-visual-studio-code-keeps-crashing-the-js-ts-language-s](https://stackoverflow.com/questions/78126814/vue-volar-extension-in-visual-studio-code-keeps-crashing-the-js-ts-language-s)

**Comment by davidmatter** [comment] 2024-08-06 07:26
Closing this one as many things have changed since 2.x. Feel free to create a new issue with a minimal reproduction if you're still having issues, thanks!

**Closed by davidmatter** 2024-08-06 07:26 UTC
