### ISSUE TITLE
Inlay hints in .js files disappear

### ISSUE THREAD

**Issue by regurgitate** [vuejs/language-tools#3746] opened 2023-11-21 11:29 UTC
Type: <b>Bug</b>

When the extension is enabled all inlay hints in .js files disappear.

Inlay hints related options in my vs code settings are:
```
"vue.inlayHints.inlineHandlerLeading": true,
"javascript.inlayHints.parameterNames.enabled": "all",
"typescript.inlayHints.parameterNames.enabled": "all",
```

This is what I see when the extension is disabled (correct output):
![image](https://github.com/vuejs/language-tools/assets/121431545/49300b48-c08b-4c78-8ea6-64cf57504779)

This is what I see when the extension is enabled (I would expect the same result as above, however the inlay hints disappear):
![image](https://github.com/vuejs/language-tools/assets/121431545/e332ed0b-dce3-4cfe-b27a-660274b1864b)

Worth noting: when the extension is enabled, the inlay hints are visible just at the beginning, after opening VS Code. However, navigating to any other file and getting back to main.js makes the inlay hints disappear.

Extension version: 1.8.22
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045

**Comment by so1ve** [comment] 2023-11-21 12:17
Duplicate of #2490

**Closed by so1ve** 2023-11-21 12:17 UTC
