### ISSUE TITLE
`align` prop wrong highlight

### ISSUE THREAD

**Issue by szulcus** [vuejs/language-tools#3236] opened 2023-05-30 06:38 UTC
I think it's VSCode's warning against old HTML.
![image](https://github.com/vuejs/language-tools/assets/48328739/7d08fb64-18fe-4c88-8d8f-a9fdb3ea8382)
![image](https://github.com/vuejs/language-tools/assets/48328739/f6d3493b-9213-41cf-b4f6-46ed49ac9f4d)

**Comment by so1ve** [comment] 2023-10-01 10:11
Duplicate of #1317

**Closed by so1ve** 2023-10-01 10:11 UTC

**Comment by so1ve** [comment] 2023-10-01 10:12
Duplicate of #1363
