### ISSUE TITLE
Alias jump file error

### ISSUE THREAD

**Issue by warmthsea** [vuejs/language-tools#3676] opened 2023-10-19 09:21 UTC
**new version 1.8.17 jump error** 

![screenshots](https://github.com/vuejs/language-tools/assets/45450994/c69f80aa-c6b4-4e6a-aa82-a4b28514aab9)

<hr/>

**version 1.2.0 jump normal** 

![screenshots](https://github.com/vuejs/language-tools/assets/45450994/c6b08646-9bdf-4dd5-9400-f5d9c531b2b5)

<hr/>

**repro case:**
https://github.com/warmthsea/test-volar-jump

![image](https://github.com/vuejs/language-tools/assets/45450994/6dfc42da-69b4-4d6d-b342-126ea0ce825f)

**Comment by so1ve** [comment] 2023-10-19 09:44
Duplicate of #3460

**Closed by so1ve** 2023-10-19 09:44 UTC
Labels: duplicate
