### ISSUE TITLE
Syntax highlighting breaks when using type assertion in template

### ISSUE THREAD

**Issue by FloEdelmann** [vuejs/language-tools#4716] opened 2024-08-23 14:54 UTC
### Vue - Official extension or vue-tsc version

Vue - Official v2.0.10

### VSCode version

1.92.2

### Vue version

3.4.38

### TypeScript version

5.5.4

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 18.26 GB / 31.02 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.13.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.2 - /usr/local/bin/npm
    pnpm: 7.18.2 - /usr/local/bin/pnpm
```

### Steps to reproduce

Create a new Vue file with these contents:

```vue
<template>
  <some-component
    :value="foo as boolean"
    :other-prop="bar"
    disabled
  />
</template>
```

### What is expected?

Its syntax should be highlighted properly.

### What is actually happening?

![grafik](https://github.com/user-attachments/assets/13822f5a-6db5-4338-9bd0-0dd3ed64be86)

Note that it works when parentheses are added:

![grafik](https://github.com/user-attachments/assets/a92641c7-f43c-4635-ae3a-1f626c6b7f2b)

**Comment by KermanX** [comment] 2024-08-23 14:58
Duplicate of #4534.

**Closed by KermanX** 2024-08-23 14:58 UTC
Labels: pending triage
