### ISSUE TITLE
@ts-ignore comment doesn't work in template

### ISSUE THREAD

**Issue by tjx666** [vuejs/language-tools#3135] opened 2023-05-06 03:19 UTC
![image](https://user-images.githubusercontent.com/41773861/236596096-b9f6b214-6d7c-4fd2-95ee-07226e965e5e.png)

```
Version: 1.78.0 (Universal)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:11:00.813Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.4.0
Sandboxed: No
Volar: v1.6.4
Take Over Mode: yes
```

**Comment by xiaowu2333** [comment] 2023-05-17 08:55
same problem

**Comment by johnsoncodehk** [comment] 2023-05-22 12:37
Duplicate of #2366

**Closed by johnsoncodehk** 2023-05-22 12:37 UTC
