### ISSUE TITLE
Request textDocument/documentSymbol failed.

### ISSUE THREAD

**Issue by DengFengYeDengNi** [vuejs/language-tools#4965] opened 2024-10-30 06:11 UTC
### Vue - Official extension or vue-tsc version

2.1.8

### VSCode version

版本: 1.95.0 (user setup) 提交: 912bb683695358a54ae0c670461738984cbb5b95 日期: 2024-10-28T20:16:24.561Z Electron: 32.2.1 ElectronBuildId: 10427718 Chromium: 128.0.6613.186 Node.js: 20.18.0 V8: 12.8.374.38-electron.0 OS: Windows_NT x64 10.0.22631

### Vue version

3.2.45

### TypeScript version

未引入

### package.json dependencies

```json
"dependencies": {
        "@element-plus/icons-vue": "^2.0.10",
        "@fingerprintjs/fingerprintjs": "^3.3.6",
        "app-info-parser": "^1.1.6",
        "axios": "^1.2.2",
        "crypto-js": "^4.1.1",
        "dayjs": "^1.11.7",
        "echarts": "^5.4.1",
        "echarts-liquidfill": "^3.1.0",
        "element-plus": "^2.2.28",
        "jquery": "^3.7.1",
        "jsencrypt": "^3.3.1",
        "mitt": "^3.0.0",
        "moment": "^2.29.4",
        "nprogress": "^0.2.0",
        "pdfjs-dist": "^2.5.207",
        "pinia": "^2.0.28",
        "pinia-plugin-persistedstate": "^3.0.2",
        "qs": "^6.11.0",
        "sm-crypto": "^0.3.11",
        "sortablejs": "^1.15.0",
        "video.js": "^7.20.3",
        "vue": "^3.2.45",
        "vue-clipboard3": "^2.0.0",
        "vue-qr": "^4.0.9",
        "vue-router": "^4.1.6"
    },
    "devDependencies": {
        "@vitejs/plugin-vue": "^4.1.0",
        "@vitejs/plugin-vue-jsx": "^3.0.1",
        "eslint": "^8.31.0",
        "eslint-plugin-vue": "^9.9.0",
        "fast-glob": "^3.2.12",
        "less": "^4.1.3",
        "sass": "^1.57.1",
        "vite": "^4.2.1",
        "vite-plugin-remove-console": "^2.1.0",
        "vite-plugin-svg-icons": "^2.0.1",
        "vite-plugin-vue-setup-extend": "^0.4.0",
        "vue-eslint-parser": "^9.1.0"
    }
```

### Steps to reproduce

安装最新版本vue-official  , 在vue 文件中书写代码时，不停的提示Request textDocument/documentSymbol failed.

### What is expected?

取消提示影响

### What is actually happening?

修改vue 文件时，出现错误提示
 Request textDocument/documentSymbol failed.
Error: selectionRange must be contained in fullRange
    at Function.validate (file:///c:/Users/86131/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:33675)
    at new Hd (file:///c:/Users/86131/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:33883)
    at dn (c:\Users\86131\.vscode\extensions\vue.volar-2.1.8\dist\client.js:37:46612)
    at o (c:\Users\86131\.vscode\extensions\vue.volar-2.1.8\dist\client.js:37:21036)
    at Object.NS [as map] (c:\Users\86131\.vscode\extensions\vue.volar-2.1.8\dist\client.js:37:21122)
    at Object.pr [as asDocumentSymbols] (c:\Users\86131\.vscode\extensions\vue.volar-2.1.8\dist\client.js:37:46579)
    at c (c:\Users\86131\.vscode\extensions\vue.volar-2.1.8\dist\client.js:41:56059)
    at OC.provideDocumentSymbols (file:///c:/Users/86131/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:125496)

**Comment by zcf0508** [comment] 2024-10-30 06:20
https://github.com/vuejs/language-tools/issues/4959#issuecomment-2444004002

https://github.com/vuejs/language-tools/issues/4959#issuecomment-2445246366

**Comment by KazariEX** [comment] 2024-10-30 06:54
Duplicate of #4959

**Comment by KazariEX** [comment] 2024-10-30 06:55
Duplicate of #4959

**Closed by KazariEX** 2024-10-30 06:54 UTC
Labels: pending triage
