### ISSUE TITLE
在v-if中使用instanceof会导致显示错误

### ISSUE THREAD

**Issue by extclp** [vuejs/language-tools#4172] opened 2024-03-28 16:36 UTC
When I use the instanceof operator in v-if, I encounter a highlighting error 

```vue
<template>
    <div v-if="a instanceof String"></div>
</template>
<script setup lang="ts">
import { ref } from 'vue';

const a = ref();
</script>
```

<img width="356" alt="1711642406842" src="https://github.com/vuejs/language-tools/assets/28455365/67dacdc8-3368-433f-9ddc-e2f1d7d54bbc">

**Comment by so1ve** [comment] 2024-03-29 01:50
Duplicate of #520

**Closed by so1ve** 2024-03-29 01:50 UTC
