### ISSUE TITLE
Definitions not working when data isn't present (Options API)

### ISSUE THREAD

**Issue by branivreyes** [vuejs/language-tools#3704] opened 2023-11-02 21:33 UTC
As the title says, when there is no data for options API "Go to Definition" isn't working. Is this an expected behavior?

Video:

https://github.com/vuejs/language-tools/assets/86134720/23fccc09-89c7-478e-b192-0ec1676a45fa

Volar: v1.8.22
VSCODE Version: 1.83.1

**Comment by so1ve** [comment] 2023-11-03 01:56
Duplicate of https://github.com/vuejs/language-tools/issues/3690

**Closed by so1ve** 2023-11-03 01:56 UTC
