### ISSUE TITLE
slot name completion doesn't work

### ISSUE THREAD

**Issue by makedopamine** [vuejs/language-tools#3222] opened 2023-05-24 09:55 UTC
`Volar version:` 1.7.8
`Vue version:` 3.3.4

Slot name completion didn't work when I typed `#`.
![image](https://github.com/vuejs/language-tools/assets/93767616/89be0e55-cd52-4570-aba4-a8fb30222965)
But if I typed a additional character `d`, code completion is triggered properly.
![image](https://github.com/vuejs/language-tools/assets/93767616/e2858bd4-8038-4fee-91fc-24cc5df8c0ec)

**Comment by so1ve** [comment] 2023-06-26 10:48
Hi @makedopamine 👋 I cannot reproduce this problem. Could you please confirm?

**Comment by makedopamine** [comment] 2023-06-27 01:44
Can confirm this is no longer reproducible in `v1.8.2`.

**Comment by so1ve** [comment] 2023-06-27 03:50
Thanks for confirming. I'll close this issue for now, feel free to ping me to reopen.

**Closed by so1ve** 2023-06-27 03:50 UTC
Labels: need info
