### ISSUE TITLE
Error: Invalid file name - Vue server Crashes after a while 

### ISSUE THREAD

**Issue by lynxionxs** [vuejs/language-tools#4253] opened 2024-04-11 10:12 UTC
After 30 minutes or so this error pops up and things stops working in vue files ```[Error - 10:13:13] The Vue server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.```

```
[Error - 10:12:57] Server process exited with code 1.
[Info  - 10:12:57] Connection to server got closed. Server will restart.
true
/home/neo/.vscode/extensions/vue.volar-2.0.7/dist/server.js:80

Error: Invalid file name
    at Object.mae [as fileNameToUri] (/home/neo/.vscode/extensions/vue.volar-2.0.7/dist/server.js:80:10905)
    at Object.c [as directoryExists] (/home/neo/.vscode/extensions/vue.volar-2.0.7/dist/server.js:85:863)
    at directoryProbablyExists (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:17066:42)
    at getPackageJsonInfo (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:40903:29)
    at loadModuleFromSpecificNodeModulesDirectory (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:41548:23)
    at loadModuleFromImmediateNodeModulesDirectory (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:41525:29)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:41513:33
    at forEachAncestorDirectory (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:6975:22)
    at lookup (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:41507:14)
    at loadModuleFromNearestNodeModulesDirectoryWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:41498:22)

Node.js v18.17.1
[Error - 10:13:13] Server process exited with code 1.
[Error - 10:13:13] The Vue server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

///////////////////////////////////////////

VSCode Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:14:59.643Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 5.15.0-100-generic

```

**Comment by KermanX** [comment] 2024-08-10 09:20
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by KermanX** 2024-08-10 09:20 UTC
Labels: pending triage
