### ISSUE TITLE
No ComponentCustomProperties  hints in A newly created vue file

### ISSUE THREAD

**Issue by sepZeng** [vuejs/language-tools#3991] opened 2024-03-05 13:41 UTC
Vue - Official v2.0.4;
No ComponentCustomProperties  hints in A newly created vue file,but exist hints in A newly created ts file.

**Comment by sepZeng** [comment] 2024-03-05 13:48
![Snipaste_2024-03-05_21-47-45](https://github.com/vuejs/language-tools/assets/110285888/a7525eac-175f-4e08-a70c-94dd7e576070)

![Uploading Snipaste_2024-03-05_21-45-58.png…]()

**Comment by sepZeng** [comment] 2024-03-05 13:49
![Snipaste_2024-03-05_21-45-58](https://github.com/vuejs/language-tools/assets/110285888/316c9c37-32b4-491c-8f1f-e8282eaa420d)
![Snipaste_2024-03-05_21-47-24](https://github.com/vuejs/language-tools/assets/110285888/bb7afb3b-5549-4e5e-841c-0d9603cd5771)

**Comment by so1ve** [comment] 2024-03-06 01:58
Duplicate of #3947

**Closed by so1ve** 2024-03-06 01:58 UTC
