### ISSUE TITLE
最新版`v4.1.2`出现类型识别失败的错误

### ISSUE THREAD

**Issue by RuanZhongNan** [vuejs/language-tools#2659] opened 2023-04-21 10:13 UTC
版本 v4.1.2

出现莫名其妙的组件库丢失类型

![2023-04-21-18-10-03](https://cdn.jsdelivr.net/gh/RuanZhongNan/img-store/img/2023-04-21-18-10-03.png)

`tsconfig.json`的注释出现错误

![2023-04-21-18-11-20](https://cdn.jsdelivr.net/gh/RuanZhongNan/img-store/img/2023-04-21-18-11-20.png)

推测是该插件 vue.vscode-typescript-vue-plugin 导致的 bug。

![2023-04-21-18-10-18](https://cdn.jsdelivr.net/gh/RuanZhongNan/img-store/img/2023-04-21-18-10-18.png)

**Comment by johnsoncodehk** [comment] 2023-04-21 10:22
Duplicate of #2647

**Closed by johnsoncodehk** 2023-04-21 10:22 UTC
