### ISSUE TITLE
Cannot find module 'file.vue' or its corresponding type declarations

### ISSUE THREAD

**Issue by nethriis** [vuejs/language-tools#4118] opened 2024-03-19 16:25 UTC
Good morning,
Everything was working fine until now, then suddenly, I opened my `./src/router/index.ts` file and I got lots of errors telling me for my view imports for my router by example :
```
import HomeView from '@/views/Home.vue'
```

I have the error:
```
Cannot find module '@/views/Home.vue' or its corresponding type declarations.
```
And the same error in my `./src/main.ts` with :
```
import App from './App.vue'
```
Only *.vue files are affected
Everything was working fine before, I don't know what happened in the meantime.

Here are my TypeScript configuration files:
`tsconfig.app.json`
```json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue", "src/**/*.ts"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",

    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

`tsconfig.node.json`
```json
{
  "extends": "@tsconfig/node20/tsconfig.json",
  "include": [
    "vite.config.*",
    "vitest.config.*",
    "cypress.config.*",
    "nightwatch.conf.*",
    "playwright.config.*"
  ],
  "compilerOptions": {
    "composite": true,
    "noEmit": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.node.tsbuildinfo",

    "module": "ESNext",
    "moduleResolution": "Bundler",
    "types": ["node"]
  }
}
```

`tsconfig.json`
```json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    }
  ]
}
```

I'm on Vue version 3.4.21

**Comment by arpadgabor** [comment] 2024-03-20 09:59
Same issue here. Fixed it with `allowJs: true` in tsconfig, but we're now also seeing "type instantiation is infinitely deep" type of error with Hono, however 1.8.27 works fine.

**Comment by nethriis** [comment] 2024-03-20 13:42
> Same issue here. Fixed it with `allowJs: true` in tsconfig, but we're now also seeing "type instantiation is infinitely deep" type of error with Hono, however 1.8.27 works fine.

I'm already on v1.8.27

**Comment by DemonQilin** [comment] 2024-03-21 22:04
Same issue. Why did it happen?

`tsconfig.app.json`
```json
{
  "extends": "@vue/tsconfig/tsconfig.web.json",
  "include": ["declarations/**/*.d.ts", "src/**/*", "src/**/*.vue", "src/**/*.json"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "lib": ["ES2017", "DOM", "DOM.Iterable"],
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "types": ["vitest/globals"]
  }
}
```

`tsconfig.config.json`
```json
{
  "extends": "@vue/tsconfig/tsconfig.node.json",
  "include": ["vite.config.*", "vitest.config.*", "cypress.config.*", "playwright.config.*"],
  "compilerOptions": {
    "composite": true,
    "types": ["node"]
  }
}
```

`tsconfig.vitest.json`
```json
{
  "extends": "./tsconfig.app.json",
  "include": ["declarations/**/*.d.ts", "src/**/*", "src/**/*.vue", "src/**/*.json"],
  "exclude": [],
  "compilerOptions": {
    "composite": true,
    "types": ["node", "vitest/globals"]
  }
}
```

`tsconfig.json`
```json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.config.json"
    },
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.vitest.json"
    }
  ]
}
```

**Comment by BTBMan** [comment] 2024-03-25 06:39
I noticed that the Vue-official plugin load typescript config file is different from the built-in typescript plugin, If the `tsconfig.json` has `references` field, they're loaded in a different order.

I don't know how to explain... 

There are two tsconfig files, `tsconfig.app.json` and `tsconfig.vitest.json`, they both have `"include": ["src"]`, If the `tsconfig.app.json` is set before the `tsconfig.vitest.json`, then open the `.ts` file, It loaded `tsconfig.vitest.json` but the `.vue` file is loaded `tsconfig.app.json`, If change the order of the references, The config file that `.ts` file and `.vue` file is change, too.

**Comment by BTBMan** [comment] 2024-03-25 06:45
I find this #2548, But It's not support for v2

**Comment by catgoose** [comment] 2024-03-27 16:22
I fixed this by creating `vue.d.ts` in project root with the contents:

```
declare module '*.vue' {
  import type { DefineComponent } from 'vue';
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const component: DefineComponent<object, object, any>;
  export default component;
}
```

Source: https://stackoverflow.com/a/76286386

**Comment by michaelangeloio** [comment] 2024-05-28 18:10
this is also an issue for me

**Comment by BTBMan** [comment] 2024-05-29 03:06
@michaelangeloio Set the VSCode settings `vue.server.hybridMode` to `false`, That makes the order of loading the tsconfig in `.ts` and `.vue` the same.

**Comment by EtzBetz** [comment] 2024-06-19 09:43
I also have this issue in JetBrains WebStorm

**Comment by catgoose** [comment] 2024-06-19 22:49
I fixed this by creating `src/vue.d.ts` with:

```typescript
declare module '*.vue';
```

**Comment by davidmatter** [comment] 2024-08-07 07:14
Closing this one as many things have changed since 2.x. Feel free to create a new issue with a minimal reproduction if you're still having issues, thanks!

**Closed by davidmatter** 2024-08-07 07:14 UTC

**Comment by yowger** [comment] 2025-05-23 12:49
> I fixed this by creating `src/vue.d.ts` with:
> 
> declare module '*.vue';

thanks, u da real mvp
