### ISSUE TITLE
auto completion components in template section not working

### ISSUE THREAD

**Issue by bazuka5801** [vuejs/language-tools#2491] opened 2023-03-06 08:21 UTC
Project:
yarn v3 + workspaces
quasar v2 (Vue 3 + Script Setup + TypeScript)

Neovim 0.8.1 with volar lsp (v1.2.0)

## Script Section
![image](https://user-images.githubusercontent.com/11452353/223052595-5b68d815-4ea8-41fc-bc99-edbf4271c832.png)

## Template Section
![image](https://user-images.githubusercontent.com/11452353/223052785-736e9bbf-5e64-45c9-8319-87afa68a6ca1.png)

Only text, no info about component or it's path.
Sometimes I got completion options (1/100 chance) with tricky of changing template text.

## LSP Config (with takeover mode)
LSPInfo: volar attached
```lua
{
     filetypes = { 'typescript', 'javascript', 'javascriptreact', 'typescriptreact', 'vue', 'json', 'html' },
      capabilities = capabilities,
      on_attach = function(_, bufnr)
        on_attach(_, bufnr)
      end,
      on_new_config = function(new_config, new_root_dir)
        new_config.init_options.typescript.tsdk = get_typescript_server_path(new_root_dir)
      end,
      init_options = {
        languageFeatures = {
          references = true,
          definition = true,
          typeDefinition = true,
          callHierarchy = true,
          hover = false,
          rename = true,
          signatureHelp = true,
          codeAction = true,
          completion = {
            defaultTagNameCase = "both",
            defaultAttrNameCase = "kebabCase",
          },
          schemaRequestService = true,
          documentHighlight = true,
          codeLens = true,
          semanticTokens = true,
          diagnostics = true,
        },
        documentFeatures = {
          selectionRange = true,
          foldingRange = true,
          linkedEditingRange = true,
          documentSymbol = true,
          documentColor = true,
        },
      },
      settings = {
        volar = {
          codeLens = {
            references = true,
            pugTools = true,
            scriptSetupTools = true,
          },
          vueserver = { fullCompletionList = true }
        },
      },
      root_dir = require("lspconfig").util.root_pattern("package.json", "quasar.config.js"),

}
```

And something strange output from LSP Log
```log
...lsp/handlers.lua:113	"The language server volar triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

**Comment by johnsoncodehk** [comment] 2023-03-29 07:26
Duplicate of #2071

The second problem fixed by https://github.com/volarjs/volar.js/pull/18

**Closed by johnsoncodehk** 2023-03-29 07:26 UTC
