### ISSUE TITLE
模板语法中组件无法正常获取 ts 智能提示信息

### ISSUE THREAD

**Issue by guaijie** [vuejs/language-tools#4508] opened 2024-06-27 01:49 UTC
### Vue - Official extension or vue-tsc version

2.0.22

### VSCode version

1.90.2

### Vue version

3.4.29

### TypeScript version

5.4.5

### System Info

```shell
System:
    OS: Windows 11 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 18.09 GB / 31.86 GB
  Binaries:
    Node: 18.19.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.3 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (126.0.2592.68)
    Internet Explorer: 11.0.22000.120
```

### Steps to reproduce

能正常获取 ant-design-vue Form 组件的 ts 智能提示信息
![image](https://github.com/vuejs/language-tools/assets/30885718/87f587fd-411e-4e41-9ac8-b439b9150127)
但在模板语法中使用该组件时却无法正确获取，ts 提示为 any
![image](https://github.com/vuejs/language-tools/assets/30885718/b81a2df6-c24e-4bcd-8ceb-f2deff04cb6c)

**Comment by RayGuo-ergou** [comment] 2024-06-27 02:02
see https://github.com/vuejs/language-tools/issues/4501#issuecomment-2190384987

**Comment by guaijie** [comment] 2024-06-27 02:38
> see [#4501 (comment)](https://github.com/vuejs/language-tools/issues/4501#issuecomment-2190384987)

按照里面的做了， 重新执行了 pnpm install, 依然不行
![image](https://github.com/vuejs/language-tools/assets/30885718/f8c8ed22-df89-4b93-8592-19d769b4aaef)
![image](https://github.com/vuejs/language-tools/assets/30885718/14f67fdd-88ac-4034-b04a-0aecb5b1ba9e)
![image](https://github.com/vuejs/language-tools/assets/30885718/2a74817d-1674-4885-a4da-826bed0f4bf8)

**Comment by yeyuqh** [comment] 2024-06-27 02:46
我这 2.0.19 版本是正常的。之后的版本也是这种情况，template 中的组件标签无法高亮，类型为 any

**Comment by so1ve** [comment] 2024-06-27 09:07
Duplicate of https://github.com/vuejs/language-tools/issues/4501

**Closed by so1ve** 2024-06-27 09:07 UTC
Labels: pending triage
