### ISSUE TITLE
Formatting is pushing multi line comment tags

### ISSUE THREAD

**Issue by webdevnerdstuff** [vuejs/language-tools#2632] opened 2023-04-19 23:32 UTC
Volar v1.2.0
Vue v3.2.47
VSCode v1.77.3

**Issue**
When saving and/or formatting code, it will keep pushing a everything after the opening `<div>` tag in a multi-line comment indefinitely.  This causes major issues with Redo and losing the Redo's history.

**Example Code:**
```
<!-- <div>
  foo
</div> -->
```
after saving, and continues to do indent every save/format.
```
<!-- <div>
    foo
  </div> -->
```

**Steps to replicate:**
1. Add that code to a `.vue` file.
2. Format the code.
3. Notice the code after the `<div>` tag will keep indenting each time you save/format.

**Setting in VSCode:**
```
  "[vue]": {
    "editor.defaultFormatter": "Vue.volar"
  },
```

This is the same thing happening as another issue I submitted. https://github.com/vuejs/language-tools/issues/2520

**Comment by johnsoncodehk** [comment] 2023-04-20 11:24
Duplicate of #2520

**Closed by johnsoncodehk** 2023-04-20 11:24 UTC
