### ISSUE TITLE
Word highlight does not work for vue files

### ISSUE THREAD

**Issue by elfxby** [vuejs/language-tools#4995] opened 2024-11-08 06:17 UTC
### Vue - Official extension or vue-tsc version

v2.1.10

### VSCode version

1.95.1

### Vue version

3.5.12

### TypeScript version

5.6.3

### Steps to reproduce

install Vue - Official

### What is expected?

[see vscode editor colors](https://code.visualstudio.com/api/references/theme-color?title-bar-colors#editor-colors)

![Screenshot 2024-11-08 at 07-03-37 Theme Color Visual Studio Code Extension API](https://github.com/user-attachments/assets/5b52ee48-a2eb-41c0-a94e-8d9cd448b862)

### What is actually happening?

no word highlight

### Any additional comments?

other file types like json work

**Comment by KazariEX** [comment] 2024-11-08 07:10
Duplicate of #4850

**Closed by KazariEX** 2024-11-08 07:10 UTC
Labels: pending triage
