### ISSUE TITLE
When I open a vue file in vscode that has reported an error, the vscode console prints the corresponding error message, whether the file is closed or VSCODE is closed

### ISSUE THREAD

**Issue by cMing1997** [vuejs/language-tools#3875] opened 2024-01-25 03:21 UTC
I'm not sure if this is a problem with the VUE tool

When I open a vue file in vscode that has reported an error, the vscode console prints the corresponding error message, whether the file is closed or VSCODE is closed

It seems that the code detection within the file is not based on the workspace path currently opened in the vscode window, but rather retrieves files from the cached paths of all files opened in vscode.

For example: I currently have three vscode windows open, which are `C:/Users/wuxintongxue/Downloads/element-dev/`, `D:/code/tools/`, and `C:/Users/wuxintongxue/Desktop/vBen/main`. After opening the `main` and `element-dev` projects, I found some issues in the code. Then I closed these two vscode windows. Due to other plugins needing to restart vscode, the vscode window where the `tools` project was located was restarted. After that, I found error messages for the closed `main` and `element-dev` projects in the vscode console.

**Comment by so1ve** [comment] 2024-01-26 13:31
Duplicate of https://github.com/vuejs/language-tools/issues/1274

**Closed by so1ve** 2024-01-26 13:31 UTC
