### ISSUE TITLE
Regression in vue-tsc@2.0.15: dynamic argument type incorrect

### ISSUE THREAD

**Issue by mdoesburg** [vuejs/language-tools#4361] opened 2024-05-09 16:55 UTC
This bug was initially reported here: https://github.com/vuejs/language-tools/issues/2514

Slightly different TS error, but same result: `null` is not allowed to be used as a dynamic event name to remove the binding.

Reference: https://vuejs.org/guide/essentials/template-syntax.html#dynamic-argument-value-constraints

<img width="515" alt="image" src="https://github.com/vuejs/language-tools/assets/3763566/38e6a564-1d53-46b3-a6fd-d9d721d27ec1">

<img width="627" alt="image" src="https://github.com/vuejs/language-tools/assets/3763566/2c13c167-cce5-4ad4-973c-51ea7fc640af">

**Comment by johnsoncodehk** [comment] 2024-05-13 09:13
I cannot reproduce the issue, please provide minimal reproducible code or repo to help us be able to investigate it, thanks.

**Comment by mdoesburg** [comment] 2024-05-13 20:26
> I cannot reproduce the issue, please provide minimal reproducible code or repo to help us be able to investigate it, thanks.

Minimal reproducible code:

```vue
<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps<{ toggleEnter: boolean }>();

const eventName = computed(() => (props.toggleEnter ? 'enter' : null));

function handleEvent() {
    // noop
}
</script>

<template>
    <Transition @[eventName]="handleEvent" />
</template>
```

Error:

<img width="717" alt="image" src="https://github.com/vuejs/language-tools/assets/3763566/f5276414-61a4-4b69-8254-76b59f864563">

Seems to only be an issue with event handlers on components. Doesn't give me an error on HTML elements.

**Comment by johnsoncodehk** [comment] 2024-05-13 20:37
It should fixed by https://github.com/vuejs/language-tools/commit/2a3ea17c4ed37f35b6e89adc55996f92651b9a07.

**Closed by johnsoncodehk** 2024-05-13 20:37 UTC
Labels: bug, good reproduction ✨
