### ISSUE TITLE
Generic Components cannot utilize `InstanceType`

### ISSUE THREAD

**Issue by Shyam-Chen** [vuejs/language-tools#3292] opened 2023-06-16 01:44 UTC
### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-xhzw3g?file=src%2Fcomponents%2FFoo.vue,src%2FApp.vue&terminal=dev

### Steps to reproduce

```vue
<!-- Foo.vue -->
<script lang="ts" setup generic="T extends object">
defineProps<{
  rows?: T[];
}>();
</script>

<template>
  <div>Foo</div>
</template>
```

```vue
<!-- App.vue -->
<script lang="ts" setup>
import Foo from './components/Foo.vue';

type FooInstance = InstanceType<typeof Foo>;
</script>
```

```sh
$ npm run build

> vite-vue-typescript-starter@0.0.0 build
> vue-tsc && vite build

src/App.vue:5:33 - error TS2344: Type '<T extends object>(__VLS_props: { rows?: T[] | undefined; } & VNodeProps & AllowedComponentProps & ComponentCustomProps, __VLS_ctx?: Pick<...> | undefined, __VLS_setup?: { ...; }) => VNode<...> & { ...; }' does not satisfy the constraint 'abstract new (...args: any) => any'.
  Type '<T extends object>(__VLS_props: { rows?: T[] | undefined; } & VNodeProps & AllowedComponentProps & ComponentCustomProps, __VLS_ctx?: Pick<...> | undefined, __VLS_setup?: { ...; }) => VNode<...> & { ...; }' provides no match for the signature 'new (...args: any): any'.

5 type FooInstance = InstanceType<typeof Foo>;
```

**Comment by so1ve** [comment] 2023-06-16 09:19
Use `ReturnType`

**Comment by so1ve** [comment] 2023-06-27 12:02
Duplicate of #3206

**Closed by so1ve** 2023-06-27 12:02 UTC
