### ISSUE TITLE
In the vue file can't  trigger parameter hints

### ISSUE THREAD

**Issue by changk99** [vuejs/language-tools#4080] opened 2024-03-12 12:04 UTC
ctrl + shift + space in js or ts file can  trigger parameter hints, but in vue file this doesn't work
![360截图20240312031748586](https://github.com/vuejs/language-tools/assets/22978661/ed03f269-06d5-431f-985d-9136833dd8ad)
![360截图20240312031816798](https://github.com/vuejs/language-tools/assets/22978661/ed22163a-8d9b-4716-96a5-470bf07cf773)
the first picture is in ts file, the last is in vue file

vue-official 2.0.6
vscode 1.87.1

**Comment by so1ve** [comment] 2024-03-13 01:50
Duplicate of https://github.com/vuejs/language-tools/issues/3948

**Closed by so1ve** 2024-03-13 01:50 UTC
