### ISSUE TITLE
Pug class wrong underline 

### ISSUE THREAD

**Issue by abigale-dev** [vuejs/language-tools#3485] opened 2023-08-16 16:16 UTC
![image](https://github.com/vuejs/language-tools/assets/83122224/fda571a9-a531-40d6-9045-937d56591a11)
![image](https://github.com/vuejs/language-tools/assets/83122224/87ef8606-b37a-4fe7-adfd-8af85e59fa27)

What's wrong? Last versions

**Comment by Ericlm** [comment] 2023-08-25 04:57
The `div` declaration is in the script block, I think it causes the issue 🙂

**Comment by so1ve** [comment] 2023-09-02 05:57
Duplicate of #1767

**Closed by so1ve** 2023-09-02 05:57 UTC
Labels: bug
