### ISSUE TITLE
The Vue Semantic Setver crashed 5 tiles in the last 3minutes

### ISSUE THREAD

**Issue by wubianluoye** [vuejs/language-tools#2224] opened 2022-12-19 01:40 UTC
The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

Volar version: 1.0.14

**Comment by johnsoncodehk** [comment] 2022-12-20 02:14
Can you provide the error messages from output?

**Comment by tom-evaristo** [comment] 2022-12-23 07:15
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[Error - 3:10:41 PM] The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

**Comment by virgoheRomAn** [comment] 2023-01-09 09:53
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

Volar version: v1.0.24

**Comment by liutkin** [comment] 2023-01-10 12:58
```
<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [/home/volodymyr/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [/home/volodymyr/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node]
 3: 0xcf784e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/volodymyr/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node]
 4: 0xcf7bc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/volodymyr/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node]
 5: 0xeaf465  [/home/volodymyr/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node]
 6: 0xebf12d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/volodymyr/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node]
 7: 0xec1e2e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/volodymyr/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node]
 8: 0xe8336a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/volodymyr/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node]
 9: 0x11fc0b6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/volodymyr/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node]
10: 0x15f0b19  [/home/volodymyr/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node]
[Error - 2:40:17 PM] The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by johnsoncodehk** [comment] 2023-02-11 23:08
Duplicate of #1816

**Comment by virgoheRomAn** [comment] 2023-02-11 23:08
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Closed by johnsoncodehk** 2023-02-11 23:08 UTC
