### ISSUE TITLE
Incorrect type errors on nested generic components

### ISSUE THREAD

**Issue by scottbedard** [vuejs/language-tools#4220] opened 2024-04-05 19:43 UTC
### Vue version

3.4.21

### Link to minimal reproduction

https://play.vuejs.org/#eNq9U8Fu2zAM/RVCKJAECOzDdjK8YFsQDNthK7YcdfFk2lErU4YkewGK/Pto2UldtM2lQC9BSD6a75FPD+JL2yZ9hyITuVdOtwE8hq4FU1D9SYrgpdhI0k1rXYDtQZsSKmcbWCRpjIbmhSRJVUcqaEtgaWu0ul9W1mbgg9NUr+BBEoCy5K3BxNh6uVADCMvFGhi4knSSlKcjBR7IQcCmNUVAjgDyabS1TOqAxlgp4HP8BiemkZxKGZ2ns1axZg08uNJ1cuctsdDIRQplm1YbdL/agTbrzEaWQ63gAf9+xFxwHa7PeXVAdf9C/s4fh5wUtw49uh6luNRC4WoMY3n35yce+f+l2NiyM4y+UvyNvLRu4DjCvnZUMu0ZLrL9Hk/Ey9773TEg+bOogeiAPEW8FHyw7RXpj3Q/JB9jH9+Gt3i59jWrQI2ETisO98BikEo/eWDuo2+uoFI9MdNj6uKoEitNeOts6/NILzpqz3Q2SzbMGbBrdJgAS8xgNBbbqi8Mo1cZ9FaX56ZrFpuxykaj8e/cZjfIoybn8oAb7JHC6hXXPRX0lqW99x7+diHwO35NdnyuYhNfHDSYpyP+2QpO/wGZcHl8

### Steps to reproduce

1. Create nested generic components with same type, then emit that value back up with events
2. Render the component with valid prop value

### What is expected?

No type errors should be thrown

### What is actually happening?

The first child component will produce two type errors,
- The prop being provided to the grandchild
- The event value being emitted to the parent

The grandchild component will produce one type error
- The event value being emitted to the first child

### System Info

```shell
System:
  OS: macOS 13.2.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 1.57 GB / 32.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
  npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  pnpm: 8.7.1 - ~/Library/pnpm/pnpm
Browsers:
  Chrome: 123.0.6312.107
  Safari: 16.3
npmPackages:
  vue: 3.4.21 => 3.4.21
```

**Comment by so1ve** [comment] 2024-04-07 01:49
As a workaround you may use `:foo="props.foo"`

**Comment by so1ve** [comment] 2024-04-07 05:25
Duplicate of https://github.com/vuejs/language-tools/issues/3820

**Closed by so1ve** 2024-04-07 05:25 UTC
