### ISSUE TITLE
False positive errors at end-of-file

### ISSUE THREAD

**Issue by johnsoncodehk** [vuejs/language-tools#3942] opened 2024-03-03 06:11 UTC
TS plugin cannot be used with Vue files if the project does not contain tsconfig/jsconfig, or the Vue files are not included by tsconfig/jsconfig.

### Steps to reproduce

1. Clone https://github.com/johnsoncodehk/volar-starter
	Since it is just for demonstration purposes, node_modules will not be installed.
2. Delete the `tsconfig.json` file in repo
3. Open the repo in VSCode, and open `src/components/HelloWorld.vue`
4. You should see TS errors reported due to missing dependencies, as shown below:
	<img width="796" alt="image" src="https://github.com/vuejs/language-tools/assets/16279759/0d871b2a-1346-46d3-8aa6-4a66c6f87925">
5. Close `HelloWorld.vue`, open `src/main.ts`, then re-open `HelloWorld.vue`
6. Errors in the image above is now displayed in the wrong location (end of file)
	<img width="978" alt="image" src="https://github.com/vuejs/language-tools/assets/16279759/2f129b1b-3b1b-4f52-b0da-ec7eb9df61dd">

### Exploration

`@vue/typescript-plugin` calls `decorateLanguageService` and `decorateLanguageServiceHost` at following code to modify the original `languageService` and `languageServiceHost`:
https://github.com/vuejs/language-tools/blob/3efa52d3a1132c8a098bb35c7bd54b81ee93ee35/packages/typescript-plugin/index.ts#L62-L63

This works well for `ConfiguredProject`. But for `InferredProject`, if you open the TS file before opening the Vue file, the modification of `decorateLanguageService` is no longer valid, just like the original `languageService` is no longer used. Therefore the mapping behavior of `decorateLanguageService` is no longer valid.

### Temporary Solutions

1. Create a `jsconfig.json` file in project root with empty json object content `{}`
2. Downgrade to 1.8.27 for now

**Update:** If you have the "Svelte for VS Code" extension installed, disabling it may avoid this problem.

**Comment by wuhaohuang** [comment] 2024-03-03 07:39
The first temporary solution didn't work for me, I still crashed after 5 launches.

**Comment by eknkc** [comment] 2024-03-03 07:56
I've had issues with a brand new nuxt project also. 

It creates a tsconfig file however the tsconfig is just `"extends": "./.nuxt/tsconfig.json"`.

The main problem is with the default nuxt template, inference fails: 
![CleanShot 2024-03-03 at 10 53 54@2x](https://github.com/vuejs/language-tools/assets/1248453/dba61a9b-b995-471a-b77f-559cc30983c6)

I tried explicitly setting includes after seeing this issue in tsconfig:

```
{
  "extends": "./.nuxt/tsconfig.json",
  "include": [
    "./.nuxt/nuxt.d.ts",
    "./**/*",
    "./node_modules/@nuxt/devtools/runtime",
    "./node_modules/@nuxt/telemetry/runtime",
    "."
  ]
}
```

Which also fails the exact same way. 

However, if I remove `"./.nuxt/nuxt.d.ts",` from includes, things seem to work fine: 
![CleanShot 2024-03-03 at 10 55 47@2x](https://github.com/vuejs/language-tools/assets/1248453/561106e3-770a-46ce-9c51-a613544c9fbb)

```
{
  "extends": "./.nuxt/tsconfig.json",
  "include": [
    "./**/*",
    "./node_modules/@nuxt/devtools/runtime",
    "./node_modules/@nuxt/telemetry/runtime",
    "."
  ]
}
```

I am assuming it is related to this issue but might be a completely different thing.

**Comment by eknkc** [comment] 2024-03-03 08:20
Unfortunately 2.0.3 did not help with my latest comment. 

Repro:
- Create a new nuxt projext (`npx nuxi@latest init`). 
- `npm run dev` to set up the .nuxt folder
- Boot up vscode, inference fails, all components are `any`, basically you get this: 
![CleanShot 2024-03-03 at 11 17 20@2x](https://github.com/vuejs/language-tools/assets/1248453/334df2b1-9ad6-4dcc-8639-b44fa3c4f154)
- Edit `.nuxt/tsconfig.json` to remove `"./nuxt.d.ts",` from includes. Things start working fine.

No output on Vue Language Server output panel. Should I create a new issue for this?

**Comment by niclas-j** [comment] 2024-03-03 11:07
I also tried to migrate to 2.0 in an existing project, did all the steps mentioned in the instructions. I also do not get any typescript assistance in my templates. This results in script variables being marked as unused. Will downgrade to 1.x for now.

**Comment by yingside** [comment] 2024-03-03 13:31
This has been bothering me for two days...can't you fix this?
I have followed the steps below **but it doesn't do anything for me**

1、Remove TypeScript Vue Plugin (Volar)
2、Install Vue - Official
3、Enable TypeScript and JavaScript Language Features in Plugins > Search - @builtin typescript

**Comment by Bobakanoosh** [comment] 2024-03-03 21:43
This happens to me in a monorepo containing some nuxt projects as well.

**Comment by hi-reeve** [comment] 2024-03-04 03:30
using nuxt, now the autocomplete and suggestions does not work at all

**Comment by 9mm** [comment] 2024-03-04 14:31
I dont know if this is related but i used to use volar + neovim (lspconfig) a lot in single files, just writing quick scripts in TS and that no longer works. I do see it works when tsconfig is in the root however.

Not sure if there is a way to make this optional, im assuming its the same as original issue here

**Comment by ElYaiko** [comment] 2024-03-04 18:32
The only solution that worked for me for now is downgrading to `1.8.27`

**Comment by dfidalg0** [comment] 2024-03-05 14:58
Having a similar problem with Nuxt auto-imports. Here, `SDropdown` is an auto-imported component

![image](https://github.com/vuejs/language-tools/assets/39748697/a57d52e7-7b0a-40dc-bd7d-83aec8df5ee9)

### Relevant information
Extension version: v2.0.5
Svelte extension is disabled
`tsconfig.json` is Nuxt's default

**Comment by johnsoncodehk** [comment] 2024-03-05 19:01
After investigation from https://github.com/microsoft/TypeScript/issues/57630, this does appear to be an issue with the Svelte extension. If you don't have Svelte installed and this problem still occurs, please open a new issue and provide a reproduction.

**Comment by namhong2001** [comment] 2024-03-06 02:00
Yeap. It seems the extension crashes with some others. Thanks @johnsoncodehk I also disabled not using extensions and errors gone.

**Comment by johnsoncodehk** [comment] 2024-03-06 03:57
@namhong2001 Can you share which extension caused the conflict for you?

**Comment by IlyaSemenov** [comment] 2024-03-06 04:34
FWIW, I was having the same conflict with styled-components.vscode-styled-components. I double checked that installing it introduces "Block-scoped variable '__VLS_3' used before its declaration." and uninstalling removes the error instantly.

**Comment by johnsoncodehk** [comment] 2024-03-06 07:26
It seems that the problem is not specific to Svelte extension or `styled-components.vscode-styled-components`. As long as a runtime error occurs in a TS plugin extension you installed, tsserver will discard all changes made by TS plugins to the language service and fall back to the original language service instance. Svelte extension and `styled-components.vscode-styled-components` are two of the cases but not all

The solution is to manually find the TS plugin where the error occurred and disable the extension. You can execute the `TypeScript: Open TS Server log` command to find the relevant error log, or disable your extensions one by one. I will add some guidance in the doctor panel.

**Comment by edarblanco** [comment] 2024-03-06 08:47
I have this same problem, I tried to disable my extensions and it was the same result, I even created a simple repository, without typescript and still the error appears.

**Comment by thany** [comment] 2024-03-06 10:08
> I will add some guidance in the doctor panel.

What does this mean?

> You can execute the `TypeScript: Open TS Server log` command to find the relevant error log

No errors appear in the log, except for this entry:

```
Info 326  [11:01:15.829] event:
    {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"c:/Projects/vue-thing/src/components/TestComp3.vue","diagnostics":[{"start":{"line":10,"offset":10},"end":{"line":10,"offset":10},"text":"Block-scoped variable '__VLS_4' used before its declaration.","code":2448,"category":"error","relatedInformation":[{"span":{"start":{"line":52,"offset":5},"end":{"line":52,"offset":12},"file":"c:/Projects/vue-thing/src/components/TestComp3.vue"},"message":"'__VLS_4' is declared here.","category":"message","code":2728}]},{"start":{"line":10,"offset":10},"end":{"line":10,"offset":10},"text":"Element implicitly has an 'any' type because expression of type '\"keydown\"' can't be used to index type '{}'.\n  Property 'keydown' does not exist on type '{}'.","code":7053,"category":"error"},{"start":{"line":10,"offset":10},"end":{"line":10,"offset":10},"text":"Block-scoped variable '__VLS_9' used before its declaration.","code":2448,"category":"error","relatedInformation":[{"span":{"start":{"line":61,"offset":7},"end":{"line":61,"offset":14},"file":"c:/Projects/vue-thing/src/components/TestComp3.vue"},"message":"'__VLS_9' is declared here.","category":"message","code":2728}]},{"start":{"line":10,"offset":10},"end":{"line":10,"offset":10},"text":"Variable '__VLS_9' is used before being assigned.","code":2454,"category":"error"}]}}
```

I can't find this `semanticDiag` anywhere else, and I can't see (as in, I don't know how to look for) how this relates to a specific addon. I'm novice at diagnosing internal typescript related problems, so forgive me for not understanding what this means.

**Comment by joshuagraber** [comment] 2024-03-06 11:14
> This works well for ConfiguredProject. But for InferredProject, if you open the TS file before opening the Vue file, the modification of decorateLanguageService is no longer valid, just like the original languageService is no longer used. Therefore the mapping behavior of decorateLanguageService is no longer valid.

I don't think this is entirely correct:

- This is also occurring in my project with `tsconfig.json`, so I don't think it's just InferredProject. 

- I'm also getting these errors when opening vue files directly, no need to start with the ts file.

Good thing ya'll thoroughly tested this before delivering a major release... 😬 Downgrading to 1.8.27 for now, I'll check back in on v2 when this is properly resolved.

**Comment by atidivya** [comment] 2024-03-06 13:18
Facing similar issues, downgrading to 1.8.27 resolved my import errors.

**Comment by johnsoncodehk** [comment] 2024-03-06 13:59
> To reproduce: Clone [this repo](https://github.com/Police-Data-Accessibility-Project/design-system), observe batshit errors in all vue files.

I can't reproduce the problem in this repo. Can you share your extension list? (Execute `Help: Report Issue...` >> Click "show" at `Include my enabled extensions`)

**Comment by thany** [comment] 2024-03-06 14:12
For me, they are:

<details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
jsdoc-generator|cry|2.0.2
font-preview|ctc|2.2.1
vscode-autohotkey-plus|cwe|2.7.1
vscode-eslint|dba|2.4.4
overtype|DrM|0.5.0
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.102
auto-rename-tag|for|0.1.10
remotehub|Git|0.62.0
todo-tree|Gru|0.0.226
vscode-totalcommander|ipa|1.0.4
rainbow-csv|mec|3.11.0
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.29.0
csharp|ms-|2.18.16
vscode-dotnet-runtime|ms-|2.0.2
remote-wsl|ms-|0.86.0
azure-repos|ms-|0.38.0
powershell|ms-|2024.0.0
remote-repositories|ms-|0.40.0
gremlins|nho|0.26.0
vscode-versionlens|pfl|1.9.2
prettyxml|Pra|4.4.1
prisma|Pri|5.10.2
sqlite-viewer|qwt|0.3.13
LiveServer|rit|5.7.9
vscode-styled-components|sty|1.7.8
sass-indented|syl|1.8.29
vscode-mdx|uni|1.8.1
vscode-svg-previewer|vit|0.7.0
volar|Vue|1.8.27
vscode-typescript-vue-plugin|Vue|1.8.27
pretty-ts-errors|Yoa|0.5.3
</details>

**Comment by johnsoncodehk** [comment] 2024-03-06 14:20
@thany `vscode-styled-components` has been mentioned to cause conflicts, please try uninstall. Also make sure to uninstall vscode-typescript-vue-plugin when using 2.0.x.

**Comment by joshuagraber** [comment] 2024-03-06 14:37
@johnsoncodehk 

Here's the `ls` output from `$HOME/.vscode/extensions`. I don't have the time or inclination to check these 1 by 1 (nor should I have to, this should have been much more thoroughly tested before releasing...). Some of them are not active. (For instance, I have disabled `vscode-typescript-vue-plugin` when trying `2.x.x` etc.)

```
4ops.terraform-0.2.5                         hecate-theme                                 pkief.material-icon-theme-4.34.0
be5invis.vscode-icontheme-nomo-dark-1.3.6    irongeek.vscode-env-0.1.0                    prisma.prisma-5.10.2
bierner.markdown-checkbox-0.4.0              jock.svg-1.5.3                               ritwickdey.liveserver-5.7.9
bierner.markdown-emoji-0.3.0                 mgmcdermott.vscode-language-babel-0.0.40     rvest.vs-code-prettier-eslint-6.0.0
bradlc.vscode-tailwindcss-0.10.5             mikestead.dotenv-1.0.1                       salesforce.sfdocs-markdown-assistant-0.1.6
dbaeumer.vscode-eslint-2.4.4                 mquandalle.graphql-0.1.2                     streetsidesoftware.code-spell-checker-3.0.1
dracula-theme.theme-dracula-2.24.3           ms-azuretools.vscode-docker-1.29.0           stylelint.vscode-stylelint-1.3.0
dsznajder.es7-react-js-snippets-4.4.3        ms-python.autopep8-2023.8.0                  syler.sass-indented-1.8.29
eamodio.gitlens-14.8.2                       ms-python.black-formatter-2024.0.1           tyriar.sort-lines-1.11.0
extensions.json                              ms-python.debugpy-2024.2.0-darwin-arm64      vscode-icons-team.vscode-icons-12.7.0
firefox-devtools.vscode-firefox-debug-2.9.10 ms-python.isort-2023.10.1                    vue.volar-1.8.27
formulahendry.auto-rename-tag-0.1.10         ms-python.python-2024.2.1                    vue.volar-2.0.5
github.vscode-github-actions-0.26.2          ms-python.vscode-pylance-2024.2.3            vue.vscode-typescript-vue-plugin-1.8.27
graphql.vscode-graphql-0.9.3                 ms-vsliveshare.vsliveshare-1.0.5918          xabikos.javascriptsnippets-1.8.0
graphql.vscode-graphql-execution-0.2.6       oderwat.indent-rainbow-8.3.1                 yummygum.city-lights-icon-vsc-1.1.3
graphql.vscode-graphql-syntax-1.3.4          orsenkucher.vscode-graphql-0.3.18
```

**Comment by thany** [comment] 2024-03-06 15:13
@johnsoncodehk I did actually remove `vscode-typescript-vue-plugin`, but it's needed again after downgrading "Vue - Official" back to 1.8.

As for styled-components - I need that one for my React projects. Is some type of collaboration occurring between you folks to work towards a solution? I'm not sure in which of the two the solution should be, but I do know it's best when developers of both addons work directly together on it.

**Comment by davidmatter** [comment] 2024-03-06 17:04
> I don't have the time or inclination to check these 1 by 1 (nor should I have to, this should have been much more thoroughly tested before releasing...)

@joshuagraber this is an OpenSource repository. You haven't paid for it and haven't contributed to it. Therefore, nobody here owes you anything.

**Comment by joshuagraber** [comment] 2024-03-06 17:45
> You haven't paid for it and haven't contributed to it.  Therefore, nobody here owes you anything.

@davidmatter Fair enough. For what it's worth, though, I _am_ contributing in the only way I have the capacity to do at the moment, which is by participating in this discussion. I don't feel entitled to anything here but I also don't think it's a problem to point out that this is a pretty big bug to go unnoticed in a major release of a tool that a lot of people depend on and that (as far as I know) has no viable alternatives in the marketplace, open source or otherwise.

I take your point about the complexity of the thing, though. Maybe if I have the capacity at some point, I'll come back and contribute more to this.

**Comment by johnsoncodehk** [comment] 2024-03-06 18:14
> ```
> 4ops.terraform-0.2.5                         hecate-theme                                 pkief.material-icon-theme-4.34.0
> be5invis.vscode-icontheme-nomo-dark-1.3.6    irongeek.vscode-env-0.1.0                    prisma.prisma-5.10.2
> bierner.markdown-checkbox-0.4.0              jock.svg-1.5.3                               ritwickdey.liveserver-5.7.9
> bierner.markdown-emoji-0.3.0                 mgmcdermott.vscode-language-babel-0.0.40     rvest.vs-code-prettier-eslint-6.0.0
> bradlc.vscode-tailwindcss-0.10.5             mikestead.dotenv-1.0.1                       salesforce.sfdocs-markdown-assistant-0.1.6
> dbaeumer.vscode-eslint-2.4.4                 mquandalle.graphql-0.1.2                     streetsidesoftware.code-spell-checker-3.0.1
> dracula-theme.theme-dracula-2.24.3           ms-azuretools.vscode-docker-1.29.0           stylelint.vscode-stylelint-1.3.0
> dsznajder.es7-react-js-snippets-4.4.3        ms-python.autopep8-2023.8.0                  syler.sass-indented-1.8.29
> eamodio.gitlens-14.8.2                       ms-python.black-formatter-2024.0.1           tyriar.sort-lines-1.11.0
> extensions.json                              ms-python.debugpy-2024.2.0-darwin-arm64      vscode-icons-team.vscode-icons-12.7.0
> firefox-devtools.vscode-firefox-debug-2.9.10 ms-python.isort-2023.10.1                    vue.volar-1.8.27
> formulahendry.auto-rename-tag-0.1.10         ms-python.python-2024.2.1                    vue.volar-2.0.5
> github.vscode-github-actions-0.26.2          ms-python.vscode-pylance-2024.2.3            vue.vscode-typescript-vue-plugin-1.8.27
> graphql.vscode-graphql-0.9.3                 ms-vsliveshare.vsliveshare-1.0.5918          xabikos.javascriptsnippets-1.8.0
> graphql.vscode-graphql-execution-0.2.6       oderwat.indent-rainbow-8.3.1                 yummygum.city-lights-icon-vsc-1.1.3
> graphql.vscode-graphql-syntax-1.3.4          orsenkucher.vscode-graphql-0.3.18
> ```

@joshuagraber Only `Vue.volar` and `Vue.vscode-typescript-vue-plugin` from this list define the TypeScript Plugin, so your problem may be OS specific. (This is just speculation, I can't confirm it without being able to reproduce it.)

@thany You just need to disable `vscode-styled-components` in Vue workspaces.

**Comment by namhong2001** [comment] 2024-03-07 04:16
> @namhong2001 Can you share which extension caused the conflict for you?

To me, `styled-components.vscode-styled-components@v1.7.8` was the culprit. Only it coflicted with `vue.volar@v2.0.5` and others were fine.

**Comment by thany** [comment] 2024-03-07 08:41
@GCnomore From here:

![image](https://github.com/vuejs/language-tools/assets/152227/ea41e008-e2a9-4763-9a4c-ddd0ecbb2ba1)

This should also disable auto-updating this particular addon.

**Comment by atidivya** [comment] 2024-03-07 09:34
@GCnomore as show by @thany

**Comment by zby909** [comment] 2024-03-07 10:05
> > @namhong2001您能分享一下哪个扩展引起了您的冲突吗？
> 
> 对我来说，`styled-components.vscode-styled-components@v1.7.8`是罪魁祸首。只有它有冲突`vue.volar@v2.0.5`，其他都很好。

It’s true. If you disable vscode-styled-components, there will be no error.

**Comment by efezinoidisi** [comment] 2024-03-07 10:09
@thany  thanks. downgrading to v1.8.27 fixed my errors

**Comment by thany** [comment] 2024-03-07 12:38
Alright, so is any collaboration with the vscode-styled-components author occurring?

**Comment by ElYaiko** [comment] 2024-03-08 02:03
Getting same error in `2.0.6`:

````
2024-03-07 22:57:03.693 [info] Starting TS Server
2024-03-07 22:57:03.693 [info] Using tsserver from: /Applications/VSCodium.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-07 22:57:03.693 [info] <syntax> Forking...
2024-03-07 22:57:03.693 [info] <syntax> Starting...
2024-03-07 22:57:03.693 [info] <semantic> Forking...
2024-03-07 22:57:03.693 [info] <semantic> Starting...
2024-03-07 22:57:06.534 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-07 22:57:06.534 [info] Starting TS Server
2024-03-07 22:57:06.534 [info] Using tsserver from: /Applications/VSCodium.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-07 22:57:06.534 [info] <syntax> Forking...
2024-03-07 22:57:06.534 [info] <syntax> Starting...
2024-03-07 22:57:06.534 [info] <semantic> Forking...
2024-03-07 22:57:06.534 [info] <semantic> Starting...
2024-03-07 22:57:08.057 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-07 22:57:08.057 [info] Starting TS Server
2024-03-07 22:57:08.057 [info] Using tsserver from: /Applications/VSCodium.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-07 22:57:08.057 [info] <syntax> Forking...
2024-03-07 22:57:08.057 [info] <syntax> Starting...
2024-03-07 22:57:08.057 [info] <semantic> Forking...
2024-03-07 22:57:08.057 [info] <semantic> Starting...
2024-03-07 22:57:10.048 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-07 22:57:10.048 [info] Starting TS Server
2024-03-07 22:57:10.048 [info] Using tsserver from: /Applications/VSCodium.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-07 22:57:10.048 [info] <syntax> Forking...
2024-03-07 22:57:10.048 [info] <syntax> Starting...
2024-03-07 22:57:10.048 [info] <semantic> Forking...
2024-03-07 22:57:10.048 [info] <semantic> Starting...
2024-03-07 22:57:11.869 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-07 22:57:11.869 [info] Starting TS Server
2024-03-07 22:57:11.869 [info] Using tsserver from: /Applications/VSCodium.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-07 22:57:11.869 [info] <syntax> Forking...
2024-03-07 22:57:11.869 [info] <syntax> Starting...
2024-03-07 22:57:11.869 [info] <semantic> Forking...
2024-03-07 22:57:11.869 [info] <semantic> Starting...
2024-03-07 22:57:13.842 [error] TSServer exited. Code: null. Signal: SIGSEGV
2024-03-07 22:57:13.842 [info] Starting TS Server
2024-03-07 22:57:13.842 [info] Using tsserver from: /Applications/VSCodium.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-07 22:57:13.842 [info] <syntax> Forking...
2024-03-07 22:57:13.842 [info] <syntax> Starting...
2024-03-07 22:57:13.842 [info] <semantic> Forking...
2024-03-07 22:57:13.842 [info] <semantic> Starting...
2024-03-07 22:57:15.370 [error] TSServer exited. Code: null. Signal: SIGBUS
````


Also, this extension is ultra EXTREMELY SLOW for big projects, hope this is fixed in the lastest versions.

**Comment by emojiiii** [comment] 2024-03-11 03:12
same error in 2.0.6:

Extension | Author (truncated) | Version
-- | -- | --
iconify | ant | 0.7.5
unocss | ant | 0.58.5
postcss | css | 1.0.9
dart-code | Dar | 3.84.0
flutter | Dar | 3.84.0
vscode-eslint | dba | 2.4.4
gitlens | eam | 14.9.0
prettier-vscode | esb | 10.1.0
copilot | Git | 1.172.0
copilot-chat | Git | 0.13.0
gc-excelviewer | Gra | 4.2.59
debugpy | ms- | 2024.2.0
python | ms- | 2024.2.1
vscode-pylance | ms- | 2024.2.3
sqlite-viewer | qwt | 0.3.13
autoimport | ste | 1.5.4
svga-perview | svg | 1.0.0
intellicode-api-usage-examples | Vis | 0.2.8
vscodeintellicode | Vis | 1.2.30
volar | Vue | 2.0.6
vscode-import-cost | wix | 3.3.0

**Comment by DanielLemosGebit** [comment] 2024-03-12 18:59
> @thany `vscode-styled-components` has been mentioned to cause conflicts, please try uninstall. Also make sure to uninstall `vscode-typescript-vue-plugin` when using 2.0.x.

I'm removed `vscode-styled-components`  and worked, thanks!

**Comment by cooldevdotcodes** [comment] 2024-03-14 08:48
I have same problem but with styled-jsx Language Server (https://marketplace.visualstudio.com/items?itemName=Divlo.vscode-styled-jsx-languageserver) extension. Disable it and the error is gone..

**Comment by Ernildo** [comment] 2024-03-16 14:44
I don't know what the relationship is, but when the **styled-componets** extension was enabled, the **Vue - Oficial** plugin stopped working correctly from version 2.x onwards. Therefore, until the problem is fixed, there are two possible paths:

1. Downgrade of "Vue - Oficial" to version 1.8.x
or
2. Disable the styled-components plugin

**Comment by xak2000** [comment] 2024-03-17 00:58
In my case only the option 1 has helped. I don't know what `styled-components` plugin is. Never installed it, so nothing to disable, but Vue extension v2.x has still stopped to work after several minutes after each restart of VS Code. Dowgrading to 1.x has helped.

**Comment by brendomaciel** [comment] 2024-03-18 12:24
I have a specific VS Code profile for Vue projects and never installed `vscode-styled-components` on it. Found out after uninstalling `redhat.vscode-xml` **it worked**!

I'd say what these two have in common is the fact they both add **syntax highlighting**.

So, If you're still having trouble and have any extensions adding extra syntax highlighting, try to disable them.

**Comment by XxGodmoonxX** [comment] 2024-03-19 06:54
Wouldn't it work if I increased the version of TypeScript I'm using?

**Closed** 2024-03-20 01:41 UTC

**Comment by thany** [comment] 2024-03-20 14:55
@johnsoncodehk You closed this issue, which is fine, but are we absolutely sure the problem wasn't in this addon? The problem only occurred with a combination of this addons, and the styled-components one, and just telling people not to install the latter one, is not a solution, even if the problem is in that addon.

By closing this issue, it feels like you're sure the problem (and solution) is in the styled-components addon. So one more time then: is some type of collaboration with them being done to get to an actual proper solution?

**Comment by adufr** [comment] 2024-03-20 15:05
@thany I think this issue has been closed because the change that caused it has been reverted -> so it's now fixed.

**Comment by so1ve** [comment] 2024-03-21 02:08
@thany Don't you understand what is "closed via"?

![image](https://github.com/vuejs/language-tools/assets/58381667/c925db83-4276-4378-b6cf-4e3d823e857e)

**Comment by thany** [comment] 2024-03-21 08:42
That PR just reverts back to the same thing the old addon version did, so the issue only *appears* solved. When going into hybrid mode (presumably, from the looks of the PR) it will still break in the exact same way.

This is why I keep asking to collaborate with the author of the addon that it is breaking on. Working together might *actually* solve the problem.

**Comment by thany** [comment] 2024-03-21 13:53
> You should only enable hybrid mode when you have a tsconfig and have ts 5.3+ installed.

This can easily be autodetected, can't it?

**Comment by sharifzadesina** [comment] 2024-04-01 19:06
I have this problem with Nuxt. there is a tsconfig. but for every newly created file, I get the same behaviour unless I restart vscode.

**Comment by johnsoncodehk** [comment] 2024-04-04 21:42
#4206 implements the detection of installed extensions to determine whether to enable Hybrid Mode automatically. If you find a compatible extension ID that is not added to the whitelist, please leave a comment in the PR.

**Comment by sharifzadesina** [comment] 2024-04-04 21:54
@johnsoncodehk Why it is not able to find auto generated tsconfig Nuxt projects?! is there something wrong?

**Comment by yveeven** [comment] 2024-04-09 07:12
![CleanShot 2024-04-09 at 15 10 01@2x](https://github.com/vuejs/language-tools/assets/76424723/9ef91885-4c44-4724-a945-b23d3f5378ef)

I see the comments understand that the full TS server has been restored, so it would be best to be able to turn on Takeover mode to improve performance, but he still detects warnings every time I open the project, should I use some way to turn off the warnings or is there no need to disable the built-in server?

**Comment by so1ve** [comment] 2024-04-09 07:50
There is no need to disable the built-in server. If hybrid mode is enabled, both typescript and vue files' language services are provided by the built-in server. If disabled, vue's language service is provided by an external language server.

**Comment by yveeven** [comment] 2024-04-09 08:40
> There is no need to disable the built-in server. If hybrid mode is enabled, both typescript and vue files' language services are provided by the built-in server. If disabled, vue's language service is provided by an external language server.

thank you

**Comment by yveeven** [comment] 2024-04-10 03:07
![CleanShot 2024-04-10 at 11 02 19@2x](https://github.com/vuejs/language-tools/assets/76424723/34ee476c-8cba-4e7f-be94-5e82b3cc79f4)
![CleanShot 2024-04-10 at 11 02 31@2x](https://github.com/vuejs/language-tools/assets/76424723/4bea3a24-297d-4e10-b45a-9b29e8084402)

On mac vs code open multiple windows at the same time may occasionally saving stuck out, forgive can not be determined to float, the situation is like this

System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 62.98 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
IDEs
    VSCode: 1.88.0 - /usr/local/bin/code
   
node@v18.19.0
pnpm@8.10.2

vscode Volar@2.0.11

**Comment by patriktoth67** [comment] 2024-06-17 16:36
Disabling svelte.svelte-vscode seems to have solved it for me

**Comment by JonasPalms** [comment] 2024-08-15 08:41
Disabling astro-build.astro-vscode solved the issue for me.

**Comment by langej** [comment] 2024-10-08 08:12
For me it was the [Marko VSCode](https://marketplace.visualstudio.com/items?itemName=Marko-JS.marko-vscode) Plugin which caused this issue

**Comment by alecStewart1** [comment] 2024-11-20 22:12
I can 2nd @patriktoth67 suggestion. Seems either this extension conflicts with other or VS Code has some outstanding bug that causes this issue.

Considering people suggest downgrading to a earlier version works as well, it might be with this extension. _Or_ the newer versions of this extension uses some API code from VS Code that's causing the bug, and not the extension itself.
