### ISSUE TITLE
Non-null assertions can only be used in TypeScript files.ts(8013). vue 2

### ISSUE THREAD

**Issue by Lumexio** [vuejs/language-tools#3272] opened 2023-06-13 03:52 UTC
Type: <b>Bug</b>

<template v-slot:[`item.active`]="{ item }">

Extension version: 1.6.4
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:31:03.317Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|8.00GB (0.55GB free)|
|Process Argv|--crash-reporter-id 7c72167b-ac7b-45f6-8498-cbcaec5c3c77|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
showsbindicator:30760979
pythongtdpath:30739704
dh2dc718:30763024
pythonnosmt12:30765603

```

</details>

**Comment by so1ve** [comment] 2023-06-13 09:30
Upgrade to v1.6.5 at least

Duplicate of #3121

**Closed** 2023-06-13 17:32 UTC
