### ISSUE TITLE
tags colored not similar from group of components

### ISSUE THREAD

**Issue by wildwind123** [vuejs/language-tools#4702] opened 2024-08-17 07:46 UTC
### Vue - Official extension or vue-tsc version

v2.0.28

### VSCode version

Version: 1.92.2

### Vue version

^3.4.37

### TypeScript version

^5.5.3

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 7.25 GB / 15.37 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 21.4.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.11.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 127.0.6533.88
```

### Steps to reproduce

clone this repo
https://github.com/wildwind123/vue3group

open in vscode

will be like 

![image](https://github.com/user-attachments/assets/99bd0985-53e8-4a72-a9f8-1dbb13917d74)

### What is expected?

</Examples.Bar> and </Examples.Foo> should be same color of start tag

### What is actually happening?

wrong color start and end tags

### Link to minimal reproduction

https://stackblitz.com/~/github.com/wildwind123/vue3group

### Any additional comments?

maybe this feature request ? i don't know

**Comment by KazariEX** [comment] 2024-08-17 08:22
Duplicate of #3341

**Closed** 2024-08-17 14:30 UTC
Labels: duplicate
