### ISSUE TITLE
[Bug] The keyword  `type`  should not be used as a keyword for parsing

### ISSUE THREAD

**Issue by Siykt** [vuejs/language-tools#3562] opened 2023-09-15 02:18 UTC
In the  `<template>`  section, the keyword  `type`  should not be used as a keyword for parsing, as it can cause code styling issues in the vscode editor.

> like this

<img width="941" alt="image" src="https://github.com/vuejs/language-tools/assets/44022526/aa1132b7-c619-4a3f-bfa5-47b47e3b6404">

A minimal reproduction:

```vue
<script setup lang="ts">
import { ref } from 'vue'

const types = ref(['a', 'b', 'c'])
</script>

<template>
  <div>
    <select>
      <option v-for="type in types" :key="type" :value="type">
        {{ type }}
      </option>
    </select>
  </div>
</template>
```

**Comment by so1ve** [comment] 2023-09-15 04:24
Duplicate of #854

**Closed by so1ve** 2023-09-15 04:24 UTC
