### ISSUE TITLE
Can't use project references without building depended project first

### ISSUE THREAD

**Issue by harveylee** [vuejs/language-tools#2296] opened 2023-01-09 06:59 UTC
We want to import API types from the `api` project into the `app` project in a monorepos without having to build the `.d.ts` files. We use project references so that path mappings in the `api` project can be resolved when imported into the `app` project. Without using project references (in `app`) the types are imported as `any`.

When using Volar in takeover mode, we get:
`Output file '/fleetseer/packages/api/lib/index.d.ts' has not been built from source file '/fleetseer/packages/api/src/index.ts'.` in our `app` project, when importing `@fleetseer/api`. 

However, this use case appears to be supported by the built-in VS Code TypeScript support. If we turn on TypeScript and JavaScript Language Features in VS Code, the types are correctly resolved by the built-in thing for `*.ts` files (but no change for `*.vue` files, as expected).

This may be related / a duplicate of #1815 

Activating the workspace setting "Volar > Vueserver: No Project References" makes the "Output file has not been built" error go away, however the path mappings in `api` don't resolve correctly.
- One workaround here without project references is to use relative paths in `api` (e.g. `../../../../my-api-thing.ts` in some cases) which is quite painful

Notes:
- Using Volar 1.0.24 in VS Code in takeover mode
- Using Typescript project references in a PNPM monorepos
- `@fleetseer/api` is a added as a pnpm workspace dependency (i.e. in `package.json`: `"@fleetseer/api": "workspace:*"`) to the `app` project.
- The `api` project is a `composite: true` project referred to by the `app` project
- This error appears for both `*.ts` and `*.vue` files in the `app` project
- In `api` we have a path mapping in `tsconfig.json` to map `"~/*": ["./*"]` with `"baseUrl": "./src"`

Also both vite (using `vite-tsconfig-paths`) and esbuild (using `@esbuild-plugins/tsconfig-paths`) seem to be able to resolve the `~/*` alias correctly on build, with the help of the plugins - perhaps there's a similar plugin for Volar?

In the end, I think we either:
A. Resolve the reason why the project references don't resolve the same way as the built-in TS services; or
B. Find a way to get the path mapping (e.g. `~/*`) in depended projects (i.e. `api` in our case) to work without using project references, as a workaround (perhaps using something like a tsconfig-paths plugin?)

Versions
- Typescript 4.9.4
- Volar 1.0.24
- Vue 3.2.45
- VS Code 1.74.2
- Windows 11 (WSL Debian)

**Comment by everhardt** [comment] 2023-01-13 16:33
I ran into the same thing a while back and also have not been able to fix it yet, see https://github.com/johnsoncodehk/volar-starter/issues/7

**Comment by johnsoncodehk** [comment] 2023-01-13 16:35
Can you try enable [noProjectReferences](https://github.com/johnsoncodehk/volar/issues/1344#issuecomment-1279639493)?

**Comment by everhardt** [comment] 2023-01-13 16:52
Yes, awesome, that works for me! Should that maybe also be added to the volar-starter repo? See https://github.com/johnsoncodehk/volar-starter/issues/7

**Comment by harveylee** [comment] 2023-01-23 22:08
noProjectReferences doesn't work for me.

If I enable noProjectReferences, path aliases don't work in the dependency.

**Comment by johnsoncodehk** [comment] 2023-01-23 23:47
If you can provide minimal reproduction, I will be able to narrow down the problem.

**Comment by harveylee** [comment] 2023-01-29 01:34
I created a bare-bones pnpm monorepo based on `pnpm create vite` here: https://github.com/harveylee/volar-path-alias

A description of the setup is in the README along with some steps to follow to reproduce the various states and error messages. Hopefully that helps.

**Comment by blake-newman** [comment] 2023-03-29 09:16
Should be resolved with: https://github.com/volarjs/volar.js/pull/24

**Closed** 2023-04-02 14:14 UTC
Labels: enhancement, good reproduction ✨
