### ISSUE TITLE
Why remove pug and script converters? May be publish it as an add-on extension?

### ISSUE THREAD

**Issue by davay42** [vuejs/language-tools#2486] opened 2023-03-04 12:24 UTC
I really depend on pug conversion in my collaboration workflow. I'm a deep fan of pug, but this conversion tool made me sure that other people are not forced to use that more condensed syntax. Yeah, there are always tradeoffs and I really don't know what's the idea behind the removal of the converters.

May be these features can be published as a separate add-on for VSCode? Or even returned back as an option?

**Comment by johnsoncodehk** [comment] 2023-03-29 06:38
Duplicate of #2444

**Closed by johnsoncodehk** 2023-03-29 06:39 UTC
