### ISSUE TITLE
Vue-tsc not excluding node_modules even when it is set in the config

### ISSUE THREAD

**Issue by marhyn** [vuejs/language-tools#2328] opened 2023-01-20 10:21 UTC
## Minimal repo
I made a minimal reproduction repo: https://github.com/marhyn/vue-tsc-not-ignoring-node_modules

## Description
Even when "node_modules" are excluded from the tsconfig.json, type-check report those errors. I would like to type-check only the source code of the project. "skipLibCheck" compiler option is also turned on.

**Comment by johnsoncodehk** [comment] 2023-02-19 18:55
Duplicate of #2018

**Closed by johnsoncodehk** 2023-02-19 18:55 UTC
