### ISSUE TITLE
Version 1.8.22 of the Vue Language Features (Volar) plugin cannot obtain custom component types

### ISSUE THREAD

**Issue by wjw020206** [vuejs/language-tools#3724] opened 2023-11-09 16:01 UTC
in the same project

Vue Language Features (Volar) 1.8.22 shows that the component is of type `any` and cannot jump to the component definition
<img width="804" alt="image" src="https://github.com/unplugin/unplugin-vue-components/assets/59106659/cd7fcd55-fe3a-4fc8-b764-d439e1c516da">

Vue Language Features (Volar) 1.8.21 displays normally and can jump to the component definition
 ![image](https://github.com/unplugin/unplugin-vue-components/assets/59106659/79035a82-0014-463e-bd83-f14ad826942e)

**Comment by so1ve** [comment] 2023-11-10 01:50
Could you please provide a minimal reproduction?

**Comment by wjw020206** [comment] 2023-11-10 02:42
> Could you please provide a minimal reproduction?

This problem occurs in any project. I also have this problem in the project that created `Vue + Vite + TypeScript` using `pnpm create vite`
minimal reproduction：https://github.com/wjw020206/demo

> Please note: Be sure to make sure that the version of the `Vue Language Features (Volar)` plugin is 1.8.22. Otherwise, the BUG cannot be reproduced. Other versions are normal.

In `App.vue`, using version 1.8.22 displays the `any` type
![image](https://github.com/vuejs/language-tools/assets/59106659/0174a567-6003-4ca1-92d4-d3beac933bc7)


In `App.vue`, it is normal to use version 1.8.21
![image](https://github.com/vuejs/language-tools/assets/59106659/829b17ca-6e51-4548-94ec-6b2f29e5fc3c)

**Comment by heiyehk** [comment] 2023-11-10 07:57
@wjw020206 @so1ve I also encountered this bug when installing vscode and the latest version 1.8.22 on a brand new windows. You can first switch to the pre-release version of 1.8.23 to temporarily solve this bug, but there may be some bugs where the syntax is not prompted. At this time, restarting vscode will solve it. I'm guessing that other people didn't have this problem and maybe it was caused by caching.

**Comment by wjw020206** [comment] 2023-11-10 08:01
> @wjw020206 @so1ve I also encountered this bug when installing vscode and the latest version 1.8.22 on a brand new windows. You can first switch to the pre-release version of 1.8.23 to temporarily solve this bug, but there may be some bugs where the syntax is not prompted. At this time, restarting vscode will solve it. I'm guessing that other people didn't have this problem and maybe it was caused by caching.

Yes, I found that in VScode when I install a version below 1.8.22. `Vue Language Features (Volar)` does not show the update button and does not automatically update. I think others did not encounter this problem because they did not Update `Vue Language Features (Volar)`. The solution can be to upgrade to 1.8.23 as you mentioned or downgrade to 1.8.21. Everything is normal in 1.8.21.

**Comment by davidmatter** [comment] 2024-08-05 21:02
Closing this one as many things have changed since 2.x. Feel free to create a new issue with a minimal reproduction if you're still having issues, thanks!

**Closed by davidmatter** 2024-08-05 21:02 UTC
Labels: need info
