### ISSUE TITLE
feat: can take over mode support ts's problemMatcher?

### ISSUE THREAD

**Issue by dongwa** [vuejs/language-tools#2295] opened 2023-01-09 06:50 UTC
The buildin typescript language extension has a problemMatcher,but the take over mode of volar can not provide it.

![image](https://user-images.githubusercontent.com/38457491/211253161-77cf7275-37fb-4f1b-a605-10d94416625d.png)
So debugging a vscode extension will get a warning like:
 
![image](https://user-images.githubusercontent.com/38457491/211253575-f04fa577-c83c-4893-bf23-473039ada869.png)

**Comment by johnsoncodehk** [comment] 2023-02-11 09:33
Duplicate of #1277

**Closed by johnsoncodehk** 2023-02-11 09:33 UTC
