### ISSUE TITLE
Volar misbehaves after creating new folder on VS Code

### ISSUE THREAD

**Issue by oissevalt** [vuejs/language-tools#3837] opened 2024-01-02 07:47 UTC
1. This is when Volar works correctly. `NuxtWelcome` is identified as a component (in blue color). Autocompletion and IntelliSense all function as intended.
    <img width="1440" alt="Screenshot 2024-01-02 at 15 26 38" src="https://github.com/vuejs/language-tools/assets/57583509/d87f8842-a63c-4471-9aef-144dbd89f0b1">

2. After creating a new folder `assets` and a file `assets/main.scss`, Volar becomes irresponsive (`NuxtWelcome` is no longer blue, which indicates that code analysis has stopped working). IntelliSense and auto-completion work neither in `.vue` files or `.ts` files.
    <img width="1440" alt="Screenshot 2024-01-02 at 15 39 34" src="https://github.com/vuejs/language-tools/assets/57583509/70190f3d-0f76-49ab-a85e-16589c9b4a64">
    <img width="475" alt="Screenshot 2024-01-02 at 15 40 08" src="https://github.com/vuejs/language-tools/assets/57583509/cec2a4b0-79d0-4072-aa56-2152ccbf0bdf">

3. This is not bound to happen, but VS Code then creates infinite pop-up windows asking to access other programs' data. From Activity Monitor we can see there are numerous Code Helper processes, presumably created by Volar, and they resulted in increased memory usage.
    <img width="1440" alt="Screenshot 2024-01-02 at 15 32 31" src="https://github.com/vuejs/language-tools/assets/57583509/f9ec7fe4-a9e6-4c6e-98ce-6eca05a1932d">
    <img width="845" alt="Screenshot 2024-01-02 at 15 32 52" src="https://github.com/vuejs/language-tools/assets/57583509/298d0ef0-35a1-47e7-98bd-7cc336a274be">

My specs:

- VS Code: 1.85.1 (Universal)
- OS: Darwin arm64 23.2.0
- Node: 21.5.0
- TypeScript Vue Plugin (Volar): 1.8.27, takeover mode
- Vue Language Features (Volar): 1.8.27

I have found similar issues like https://github.com/vuejs/language-tools/issues/3801 and #3816. This glitch can seriously damage user experience and I would appreciate it if the cause could be found and fixed.

**Comment by so1ve** [comment] 2024-01-02 08:07
Could you please try https://github.com/vuejs/language-tools/discussions/3789?

**Comment by oissevalt** [comment] 2024-01-02 08:16
> Could you please try #3789?

<img width="558" alt="image" src="https://github.com/vuejs/language-tools/assets/57583509/39e1fdbc-6022-4c4a-a93e-41429a1c19c8">

Still, it cannot detect components and infers their types as `(property) any`. The autocompletion works but imports components, which 1) is not needed in Nuxt; 2) inserts import statements in the wrong place; 3) still cannot correctly identifies components as they are.

Performance issue is solved and `.ts` files are no longer affected, as I observe.

**Comment by so1ve** [comment] 2024-01-02 11:44
Duplicate of https://github.com/vuejs/language-tools/issues/3832?

**Comment by oissevalt** [comment] 2024-01-02 11:50
> Duplicate of #3832?

Actually, I edited the project with WebStorm and then when I open it in VS Code, it's the same old issue again.

<img width="478" alt="image" src="https://github.com/vuejs/language-tools/assets/57583509/4940f503-26f8-4579-a1eb-f7f54e436576">
<img width="463" alt="image" src="https://github.com/vuejs/language-tools/assets/57583509/7b52eddc-f289-465f-93fc-a2dc1a6ba46c">
<img width="559" alt="image" src="https://github.com/vuejs/language-tools/assets/57583509/666a3a53-4149-450a-b1ef-c13d804da9c9">

Using the dev version in #3789 now.

**Comment by douglasg14b** [comment] 2024-03-20 05:37
Also have this issue, if I create a new folder I have to reload my editor with Volar/Vue Extension.

**Comment by davidmatter** [comment] 2024-07-07 13:51
Please track in https://github.com/vuejs/language-tools/issues/4424

**Closed by davidmatter** 2024-07-07 13:51 UTC
