### ISSUE TITLE
Vue Official extension not working on Microsoft VSCode 1.88

### ISSUE THREAD

**Issue by cdenadai** [vuejs/language-tools#4255] opened 2024-04-11 17:48 UTC
I am simplifying this report as this is my first issue opened.

Yesterday, the Vue Official extension stopped working on my VS Code. It seems like it can't recognize Vue in my project:
![image](https://github.com/vuejs/language-tools/assets/51721735/a699b97e-a7dd-4eff-a2d0-0c60b13d57bb)

Vue Official: v2.0.12
Microsoft VS Code:

Version: 1.88.0
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:25:57.039Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-27-generic snap

Initially, I thought the problem could be related to the extension version, but nothing solved it. The only solution was to install another version of VS Code. However, Microsoft VS Code does not allow me to install previous versions on Ubuntu, so I had to install the older version of Codium.

This is the result:
![image](https://github.com/vuejs/language-tools/assets/51721735/11564e34-b7d8-4651-bb2a-61139d38633e)

Codium:

Version: 1.87.2
Release: 24072
Commit: f7ed6417a7cfae92f98129384c13b505bb9cfc53
Date: 2024-03-12T18:30:28.994Z
Electron: 27.3.2
ElectronBuildId: undefined
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-27-generic

This is my report.

**Comment by so1ve** [comment] 2024-04-12 01:59
Duplicate of https://github.com/vuejs/language-tools/issues/4237

**Closed by so1ve** 2024-04-12 01:59 UTC
