### ISSUE TITLE
Volar can not find tsconfig and module when made a new folder and vue file

### ISSUE THREAD

**Issue by shavenfeng** [vuejs/language-tools#3520] opened 2023-08-31 02:13 UTC
![image](https://github.com/vuejs/language-tools/assets/38979696/410c9d82-dedd-4b0b-b8fb-b0105dd24234)

**Comment by so1ve** [comment] 2023-08-31 03:22
Duplicate of #3329

**Closed by so1ve** 2023-08-31 03:22 UTC
