### ISSUE TITLE
Types problem when using `<script setup>` alongside normal `<script>` since `v1.8.14`

### ISSUE THREAD

**Issue by Yizack** [vuejs/language-tools#3612] opened 2023-09-30 16:57 UTC
Hello, I have a types problem in vue projects where `<script setup>` is being used alongside the normal `<script>`. Since `v1.8.14` and `v1.8.15`, property types inside the normal `<script>` aren't being recognized. Before `v1.8.14` using both at the same time used to work without any problem and properties were all recognized, I don't know if the changes in recent versions broke something or if this is intended to encourage not using both definitions. I'll be looking forward to your response thanks <3

![image](https://github.com/vuejs/language-tools/assets/16264115/42603733-f9e3-4bd2-aa4f-438835367423)

And when removing  `<script setup>`  the problem disappears 
![image](https://github.com/vuejs/language-tools/assets/16264115/f411c8c8-d3e3-4286-8832-0109d2e90c6d)

Example code:
```vue
<script setup lang="ts">
// some code
</script>

<template>
  {{ hello_world }}
</template>

<script lang="ts">
export default {
  data () {
    return {
      hello_world: "Hello World!"
    };
  }
};
</script>
```

**Comment by so1ve** [comment] 2023-09-30 17:08
Duplicate of #3598

**Closed by so1ve** 2023-09-30 17:08 UTC
