### ISSUE TITLE
vscode vue-Official升到2.1.2之后，unplugin-vue-components自动导入的组建没有提示了

### ISSUE THREAD

**Issue by zhonguanping** [vuejs/language-tools#4760] opened 2024-08-30 10:38 UTC
### Vue - Official extension or vue-tsc version

vue-Official 2.1.2; vue-tst1.8.27

### VSCode version

1.92

### Vue version

3

### TypeScript version

5.4.4

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 70.83 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.4/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
    pnpm: 9.7.0 - ~/Library/pnpm/pnpm
  Browsers:
    Edge: 128.0.2739.42
    Safari: 17.5
```

### Steps to reproduce

vue-Official 2.0.28类型提示正常，升到2.1.2后类型提示any

### What is expected?

类型提示恢复正常

### What is actually happening?

vue-Official 2.0.28类型提示正常，升到2.1.2后类型提示any，回退版本恢复正常

**Comment by KazariEX** [comment] 2024-08-30 10:59
duplicate of #4747

**Closed by KazariEX** 2024-08-30 10:59 UTC
Labels: pending triage
