### ISSUE TITLE
TS2307: Cannot find module when pure ESM packages with Vue SFC files

### ISSUE THREAD

**Issue by yoyo930021** [vuejs/language-tools#1662] opened 2022-08-02 01:54 UTC
```
{
  "name": "test-a",
  "version": "1.0.0",
  "exports": {
    ".": "./index.js",
    "./components/date-picker": "./components/date-picker/index.vue"
  }
}
```
```
// GET TS2307 error
import DatePicker from 'test-a/components/date-picker'
```

Repro case:
https://github.com/yoyo930021/volar-pure-esm-project-bug/blob/main/src/app.vue#L17

**Comment by azat-io** [comment] 2022-08-25 23:51
Same issue

**Comment by jf-paradis** [comment] 2022-11-10 06:08
@yoyo930021, change the path to:
```js
import DatePicker from 'test-a/components/date-picker/index.vue'
```

Since you are using an SFC, maybe you don't need a directory for that component?

**Comment by yoyo930021** [comment] 2022-11-10 07:12
> @yoyo930021, change the path to:
> 
> ```js
> import DatePicker from 'test-a/components/date-picker/index.vue'
> ```
> 
> Since you are using an SFC, maybe you don't need a directory for that component?

This is unsafe code. It is broken when package internal changed.
It also does not meet the ESM.

**Comment by jf-paradis** [comment] 2022-11-12 00:25
> > @yoyo930021, change the path to:
> > ```js
> > import DatePicker from 'test-a/components/date-picker/index.vue'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since you are using an SFC, maybe you don't need a directory for that component?
> 
> This is unsafe code. It is broken when package internal changed. It also does not meet the ESM.

Then why resolve to the index file in your `package.json`?

```
{
  "name": "test-a",
  "version": "1.0.0",
  "exports": {
    ".": "./index.js",
    "./components/date-picker": "./components/date-picker/index.vue"
  }
}
```

**Comment by yoyo930021** [comment] 2022-11-12 09:21
> > > @yoyo930021, change the path to:
> > > ```js
> > > import DatePicker from 'test-a/components/date-picker/index.vue'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Since you are using an SFC, maybe you don't need a directory for that component?
> > 
> > 
> > This is unsafe code. It is broken when package internal changed. It also does not meet the ESM.
> 
> Then why resolve to the index file in your `package.json`?
> 
> ```
> {
>   "name": "test-a",
>   "version": "1.0.0",
>   "exports": {
>     ".": "./index.js",
>     "./components/date-picker": "./components/date-picker/index.vue"
>   }
> }
> ```

It have same problem. They are the temp workrounds.

**Comment by elevatebart** [comment] 2023-05-18 01:50
Also, even it's a Vue2 documentation using exports to publish SFC [ready versions of your components is the documented way](https://v2.vuejs.org/v2/cookbook/packaging-sfc-for-npm.html#How-does-npm-know-which-version-to-serve-to-a-browser-build-process)

**Comment by johnsoncodehk** [comment] 2024-05-13 11:19
The repro case seems to be invalid as this setup does not work even in .ts files.

Steps to reproduce:

1. Create `test-a/components/date-picker/foo.ts` with empty export `export { };`.

2. Update `test-a/package.json`
```diff
{
  "name": "test-a",
  "version": "1.0.0",
  "exports": {
    ".": "./index.js",
+    "./components/date-picker2": "./components/date-picker/foo",
    "./components/date-picker": "./components/date-picker/index.vue"
  }
}
```

3. Add `import {} from 'test-a/components/date-picker2'` to `src/main.ts`, `test-a/components/date-picker2` failed to resolve to `test-a/components/date-picker/foo.ts`.

Closed as this is expected behavior.

**Closed by johnsoncodehk** 2024-05-13 11:19 UTC
Labels: bug, good reproduction ✨
