### ISSUE TITLE
1.4.2 

### ISSUE THREAD

**Issue by a2734961** [vuejs/language-tools#2672] opened 2023-04-22 09:58 UTC
Vue Semantic Server client: couldn't create connection to server.
VSCODE vue language features

Go to output
[Error - 17:56:53] Vue Semantic Server client: couldn't create connection to server.
  Message: Request initialize failed with message: Can't find typescript.js or tsserverlibrary.js in /Users/mac/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230421/extensions/node_modules/typescript/lib
  Code: -32603 

help!!!!
Now we can only rollback to version 1.4.1

**Comment by johnsoncodehk** [comment] 2023-04-22 10:13
Duplicate of #2663

**Closed by johnsoncodehk** 2023-04-22 10:13 UTC
