### ISSUE TITLE
Argument of type '{}' is not assignable to parameter of type 'never' | Interferency of property and component names

### ISSUE THREAD

**Issue by evgenii-code** [vuejs/language-tools#3374] opened 2023-07-06 15:37 UTC
After updating Volar to version v1.8.4, I got an error related to the interferency of property and component names.
```
Argument of type '{ class: string; }' is not assignable to parameter of type 'never'
```

<details>
  <summary>Image of the error</summary>

![image](https://github.com/vuejs/language-tools/assets/56561823/055f3060-a928-44b0-af7a-a8f618cb2bd6)

</details>
  
  
This happens when I use the property name almost the same as the component name. despite the casing

Code of the components:
<details>
  <summary>Parent</summary>

```
<template>
  <div>
    <foo-bar class="class" />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import FooBar from '~/components/FooBar.vue'

export default defineComponent({
  name: 'SameComponent',

  components: {
    FooBar,
  },

  props: {
    fooBar: { // Almost the same name as component's name
      type: Boolean,
      default: false,
    },
  },
})
</script>
```

</details>

<details>
  <summary>Child</summary>

```
<template>
  <div>Foo Bar</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'FooBar',
})
</script>
```

</details>

Versions:
node v16.17.1
vue 2.7.10
nuxt 2.15.8
volar v1.8.4 - error
volar v1.8.3 - without error

Minimal repo
[https://github.com/evgenii-code/volar-test/tree/naming-conflict](https://github.com/evgenii-code/volar-test/tree/naming-conflict)

**Comment by rchl** [comment] 2023-07-06 21:54
Appears to be caused by #3350

**Comment by rchl** [comment] 2023-07-26 17:46
It looks like with Options API local properties can not override global or local components unlike with `script setup` where local variables override global components.

With a global `HeaderTest` component, in `script setup` local variable `HeaderTest` overrides global component:

```vue
<script setup lang="ts">
import { defineComponent } from 'vue';
const HeaderTest = defineComponent({ render() { return 'yyy'}})
</script>

<template>
    <HeaderTest />
</template>
```

With Options API even local `components` definition doesn't override global component:

```vue
<template>
    <HeaderTest />
</template>

<script lang="ts">
import { defineComponent } from 'vue';

const HeaderTest = defineComponent({ render() { return 'yyy'}})

export default defineComponent({
    components: {
        HeaderTest
    },
})
</script>
```

So perhaps the logic introduced in https://github.com/vuejs/language-tools/pull/3350 needs to consider the script type and apply different logic there.

**Comment by xuzuodong** [comment] 2023-08-29 09:08
Will this be fixed soon? 👀

**Comment by Sn0wCrack** [comment] 2023-09-21 01:15
I seem to be encountering a similar issue now as of the 1.8.12 release when using the Options API.

Release 1.8.11 and prior seem to work fine for me.

I believe the issue may be related to this PR: https://github.com/vuejs/language-tools/pull/3565/files

As enabling strictTemplates within my tsconfig.json seems to remove these errors.

**Comment by so1ve** [comment] 2023-09-21 03:39
@Sn0wCrack Could you please provide a minimal reproduction then open a new issue?

**Comment by Sn0wCrack** [comment] 2023-09-22 02:06
I'll try and see if I can replicate the specific issue and provide you with some code for it, currently trying narrow down what specific cause of it and am having trouble actually replicating it in a fresh project.

I've attached the exact output I receive of vue-tsc and my related tsconfig.json files:
[vue-tsc-issue.zip](https://github.com/vuejs/language-tools/files/12695890/vue-tsc-issue.zip)

When I place some of these components that produce this error into similarly setup projects (same dependencies, typescript version and vue-tsc version), I don't end up receiving these errors from vue-tsc, so my assumption is this is related to some kind of configuration difference.

I'll keep trying on my end to replicate and see what I come up with.

If it makes any difference, this is a [Laravel](https://github.com/laravel/laravel/) project using [Inertia.js](https://github.com/inertiajs/inertia) and is compiled using Vite.

**Comment by tung-nguyen-kinexon** [comment] 2024-03-09 15:30
> Also just ran into this myself when updating vue-tsc to 1.8.15, on a custom component and RouterLink. Couldn't turn on strictTemplates (didn't like data-testid attributes), but downgrading to 1.8.11 did the trick.

I have the same problem with data-testid from Cypress after turning strictTemplates, but you can add dataAttributes: ["data-testid"] under vueCompilerOptions in tsconfig.json to fix the error.

**Comment by gnut-neygun** [comment] 2024-03-09 15:31
> Also just ran into this myself when updating vue-tsc to 1.8.15, on a custom component and RouterLink. Couldn't turn on strictTemplates (didn't like data-testid attributes), but downgrading to 1.8.11 did the trick.

I have the same problem with data-testid from Cypress after turning strictTemplates, but you can add dataAttributes: ["data-testid"] under vueCompilerOptions in tsconfig.json to fix the error.

**Comment by gnut-neygun** [comment] 2024-03-09 15:32
> @Sn0wCrack Could you please provide a minimal reproduction then open a new issue?

Very strangely enough I can also not reproduce this issue on a fres project. But it's still present on 1.8.27 (and fixed by turning on strictTemplates)

**Comment by johnsoncodehk** [comment] 2024-05-13 20:28
Closed due to unable to reproduce in latest version.

**Closed by johnsoncodehk** 2024-05-13 20:28 UTC
Labels: bug, good reproduction ✨
