### ISSUE TITLE
Syntax highlighting is broken

### ISSUE THREAD

**Issue by Rusinas** [vuejs/language-tools#4110] opened 2024-03-17 17:00 UTC
![image](https://github.com/vuejs/language-tools/assets/42975143/f6913b24-2817-4d57-bb32-d49dd94109d3)

Custom components are now highlighted weirdly (only the first letter is highlighted with proper color), but should be like this:
![image](https://github.com/vuejs/language-tools/assets/42975143/d96432e9-a3bd-420b-90d6-b4e9eaadcf3d)

Weird behavior in html too:
![image](https://github.com/vuejs/language-tools/assets/42975143/f1c87141-dac1-4fe7-a7a3-ccb76a50884c)

Custom components (MutationMatchBadge and BiomarkerMatchBadge) should be red, but after removing Volar and installing Vue official plugin they became yellow. The craziest part is that highlighting depens on scroll for some reason. You can see it on minimap:

Out of view:
![image](https://github.com/vuejs/language-tools/assets/42975143/72f5908c-bc64-45e9-acad-c06b55b6e469)

In view:
![image](https://github.com/vuejs/language-tools/assets/42975143/e0d22107-77e4-4426-967f-36602df674c4)

It can be seen while scrolling fast up and down.

**Comment by so1ve** [comment] 2024-03-18 01:48
Duplicate of https://github.com/vuejs/language-tools/issues/4070

**Comment by so1ve** [comment] 2024-03-18 01:48
And https://github.com/vuejs/language-tools/issues/3935

**Closed by so1ve** 2024-03-18 01:48 UTC
