### ISSUE TITLE
Always getting runtime errors

### ISSUE THREAD

**Issue by gabrielmaxgb** [vuejs/language-tools#3982] opened 2024-03-05 02:46 UTC
I've tried everything I could already, I don't even know exactly what these errors means. Its breaking my local env, a lot of things not working anymore:
- auto import vue components and other things
- I cant hold command + click to go to definition anymore

Can someone pls help?

<img width="455" alt="Screenshot 2024-03-04 at 23 44 07" src="https://github.com/vuejs/language-tools/assets/38226225/f83b1ebf-f958-4d6e-8b46-d52d8baf2712">
<img width="691" alt="Screenshot 2024-03-04 at 23 44 16" src="https://github.com/vuejs/language-tools/assets/38226225/dcf18ba2-ace9-4179-be2c-3e180c27460f">

**Comment by johnsoncodehk** [comment] 2024-03-05 03:36
Duplicate of #3962

**Closed by johnsoncodehk** 2024-03-05 03:36 UTC
