### ISSUE TITLE
"CTRL+ Mouse Click" with a CSS class-name is not working in VS code

### ISSUE THREAD

**Issue by Oneway2live** [vuejs/language-tools#4328] opened 2024-04-30 08:45 UTC
version: 2.0.14

I got this issue when I used the "CTRL +  Mouse Click" operation with a CSS class-name.
In usual,the editor should show the definition and go to it. Like:
![有](https://github.com/vuejs/language-tools/assets/19347108/d48a8bf1-b0c1-470e-bcab-476a479b5aa2)

![image](https://github.com/vuejs/language-tools/assets/19347108/8d89bbe8-6cb1-4b14-b3b5-d7caf550dc46)

but now it's not working. When I pressed the CTRL button and hovered on the class-name it showed nothing,  and when I clicked the class-name,I can't go to the definition too. Like:
![无](https://github.com/vuejs/language-tools/assets/19347108/827c4d20-da73-4c8a-b492-1e84474bdb45)

Not all of the vue file got this problem, it occured in some of it but I cannot figured it out.

Is it the bug of Vue Official or my configuration is wrong in some places ?  

Wishing somebody can answer and help me to find the reason.

**Comment by so1ve** [comment] 2024-04-30 09:21
Duplicate of https://github.com/vuejs/language-tools/issues/3986

**Closed by so1ve** 2024-04-30 09:21 UTC
