### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by Polarisbare** [vuejs/language-tools#4135] opened 2024-03-21 09:07 UTC
![1711012038758](https://github.com/vuejs/language-tools/assets/102842279/e6133c16-89fd-4d0c-941b-be5ae5e08aa8)
![1711012038758](https://github.com/vuejs/language-tools/assets/102842279/0bae261d-bbb0-424c-bfbb-b8a203b91d34)

**Comment by so1ve** [comment] 2024-03-21 10:12
Duplicate of https://github.com/vuejs/language-tools/issues/3962

**Closed** 2024-03-21 10:11 UTC
