### ISSUE TITLE
[bug] the autocomplete functionality does not seem to be working properly in newly created Vue files.

### ISSUE THREAD

**Issue by 2giosangmitom** [vuejs/language-tools#4440] opened 2024-06-04 01:58 UTC
Code completion is not working properly when creating new Vue files in VS Code. When opening a fresh Vue file, the auto-complete suggestions do not appear as expected when typing within the `<script>` or other tags. The Vue language features provided by the official Vue extension seem to not be initializing for new files. Closing and reopening the files and VS Code as suggested did not resolve the issue. This prevents efficient editing of Vue components, since inline documentation and predefined templates are not available during coding. The issue needs to be investigated to ensure code completion is functioning correctly for Vue development in VS Code.

**Comment by davidmatter** [comment] 2024-06-04 10:33
Same as https://github.com/vuejs/language-tools/issues/4424

**Comment by so1ve** [comment] 2024-06-04 10:50
Duplicate of #4424

**Closed by so1ve** 2024-06-04 10:50 UTC
