### ISSUE TITLE
Pug wrong "reserved" keyword in v-for

### ISSUE THREAD

**Issue by DKhalil** [vuejs/language-tools#4277] opened 2024-04-17 11:41 UTC
Using `type` as a variable name in loops causes the syntax highlighting to break down:

![image](https://github.com/vuejs/language-tools/assets/497250/0f2c5f7f-706f-47b4-a381-ae12c731e265)

```vue
<template lang="pug">
div.first

div(v-for="type in types" :key="type")

div.second
</template>

```

**Comment by so1ve** [comment] 2024-04-17 14:02
Duplicate of #520

**Closed by so1ve** 2024-04-17 14:02 UTC
