### ISSUE TITLE
props documentation tips missing for some plugin components

### ISSUE THREAD

**Issue by jlmartz** [vuejs/language-tools#4098] opened 2024-03-14 14:23 UTC
When using a custom vue plugin including components having documented props.

In the client project, Typescript information appears correctly in vscode tips but documentation comments appear only for a few components.

It seems to be related to the use of WithDefaults or DefineExpose (?).

As example:
tips display documentation comments for VkForm
tips display only type information for VkFrame

Generated d.ts files:
VkForm:
![image](https://github.com/vuejs/language-tools/assets/126171174/d6443a14-0d8a-4774-b4ff-812278c66a96)
VkFrame:
![image](https://github.com/vuejs/language-tools/assets/126171174/61a2e481-5c03-4d45-9a38-5487f112128b)

**Comment by davidmatter** [comment] 2024-08-05 21:43
Closing this one due to lack of a minimal reproduction. Feel free to create a new issue if you’re still having problems, thanks!

**Closed by davidmatter** 2024-08-05 21:43 UTC
Labels: pending triage
