### ISSUE TITLE
Indentation of <template/> code broken on v2.0.7

### ISSUE THREAD

**Issue by robsonsobral** [vuejs/language-tools#4160] opened 2024-03-26 14:59 UTC
The last update made the indentation on HTML goes crazy.

Version 2.0.6:

![image](https://github.com/vuejs/language-tools/assets/931642/0d310a00-feb2-4482-81f0-62b4789520a5)

Version 2.0.7

![image](https://github.com/vuejs/language-tools/assets/931642/09ec382b-4f32-48a7-bd18-b55fef8e96e5)

**Comment by Severino** [comment] 2024-03-28 10:49
I have a similar problem. Always happens inside double curly brackets over multiple lines. I created a minimal example that I could reproduce:
```vue
<template>
    <div>
        <i class="icon"></i>
        {{
            "Test"
        }}
        :
        {{
                "Other Test"
            }}
    </div>
</template>
``` 

When trying to fix it, the formatter always brings it into this weird form.

**Comment by johnsoncodehk** [comment] 2024-03-28 20:02
Duplicate of #3973

**Closed by johnsoncodehk** 2024-03-28 20:02 UTC
