### ISSUE TITLE
Wrong highlighting when using "type" as alias in v-for directive

### ISSUE THREAD

**Issue by yoshi0202** [vuejs/language-tools#3389] opened 2023-07-10 15:25 UTC
hello 👋

I have found that when I use the alias name "type" for the alias name in a v-for directive, the subsequent highlighting goes wrong.

<img width="765" alt="スクリーンショット 2023-07-11 0 07 53" src="https://github.com/vuejs/language-tools/assets/38803026/724de658-8484-4823-98f8-c1712166c89a">

By the way, if I change the alias in the v-for directive to a different name, it will be highlighted correctly

<img width="766" alt="スクリーンショット 2023-07-11 0 10 16" src="https://github.com/vuejs/language-tools/assets/38803026/23639c3a-1de9-470b-bf52-44be2785d0de">

Could it be a false positive with the typeof operator?
Or is it incorrect with the type attribute of input?

The version of Volar installed is 1.8.4. 

Thank you

**Comment by so1ve** [comment] 2023-07-10 17:47
Duplicate of #3240

**Closed by so1ve** 2023-07-10 17:47 UTC
