### ISSUE TITLE
Template intellisense won't work when data() returns non-empty object

### ISSUE THREAD

**Issue by pstatham-exp** [vuejs/language-tools#3872] opened 2024-01-22 20:24 UTC
When using Volar + Vite + Quasar, the intellisense inside the `<template>` tags suddenly disables whenever values are supplied to `data()`. Below is my `jsconfig.json` (not using TypeScript):

```
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@/*": ["./src/*"],
      "@assets/*": ["./src/assets/*"],
      "@api/*": ["./src/api/*"]
    }
  },
  "include": ["src/**/*"]
}
```
I am using Vue 3 with the Options API and have both Volar extensions installed.

See the images below:

![image](https://github.com/vuejs/language-tools/assets/152638732/3338c490-12cb-4726-8808-7b3b15859890)

![image](https://github.com/vuejs/language-tools/assets/152638732/30509404-95a2-4df3-b1bb-74a0a446b1a8)

**Comment by so1ve** [comment] 2024-01-23 01:52
Duplicate of #3690

**Closed by so1ve** 2024-01-23 01:52 UTC
