### ISSUE TITLE
vue-tsc gives different results in CI vs running it locally

### ISSUE THREAD

**Issue by lassesteffen** [vuejs/language-tools#4009] opened 2024-03-06 07:09 UTC
I am not sure if this is the right place to put it, but I noticed that for our CI setup (Github Actions with self hosted runners on Amazon Linux 2023) gives different results than running it locally. In our CI setup apparently some (or all?) errors in .vue files aren't detected properly, errors in normal .ts files are detected. We run the exact same commands, install the same dependencies from lock file and couldn't find any differences in setup. Is there anything that could be missing on CI that leads to those differences? Happy for any help or any resources that can help me dig deeper!

**Comment by so1ve** [comment] 2024-03-06 08:51
Could you please provide a minimal reproduction?

**Comment by lassesteffen** [comment] 2024-03-06 16:42
Hey, thanks for the ping. It's really hard for me as it might be super specific to our CI system. I was wondering if vue-tsc relies on some things that might not be installed on a CI system and stops it from scanning vue files?

**Comment by davidmatter** [comment] 2024-08-05 21:10
Closing this one due to lack of a minimal reproduction. Feel free to create a new discussion or a new issue if you’re still having issues, thanks!

**Closed by davidmatter** 2024-08-05 21:10 UTC
Labels: need info
