### ISSUE TITLE
好用，爱用

### ISSUE THREAD

**Issue by Flysky12138** [vuejs/language-tools#4856] opened 2024-09-19 03:26 UTC
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

1.92.2

### Vue version

3.5.4

### TypeScript version

5.6.2

### System Info

```shell
System:
  OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  Memory: 12.81 GB / 15.50 GB
  Container: Yes
  Shell: 5.9 - /usr/bin/zsh
Binaries:
  Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
  npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
  pnpm: 9.9.0 - ~/.nvm/versions/node/v20.16.0/bin/pnpm
```

### package.json dependencies

```json
"dependencies": {
  "@vitejs/plugin-vue-jsx": "^4.0.1",
  "@vueuse/core": "^11.0.3",
  "@vueuse/router": "^11.0.3",
  "axios": "^1.7.7",
  "dayjs": "^1.11.13",
  "pinia": "^2.2.2",
  "pinia-plugin-persistedstate": "^3.2.3",
  "vant": "^4.9.5",
  "vue": "^3.5.4",
  "vue-hooks-plus": "^2.2.1",
  "vue-router": "^4.4.4"
},
"devDependencies": {
  "@commitlint/cli": "^19.5.0",
  "@commitlint/config-conventional": "^19.5.0",
  "@eslint/js": "^9.10.0",
  "@types/node": "^20.16.5",
  "@vitejs/plugin-vue": "^5.1.3",
  "autoprefixer": "^10.4.20",
  "eslint": "^9.10.0",
  "eslint-config-prettier": "^9.1.0",
  "eslint-plugin-prettier": "^5.2.1",
  "eslint-plugin-vue": "^9.28.0",
  "globals": "^15.9.0",
  "husky": "^9.1.6",
  "lint-staged": "^15.2.10",
  "postcss": "^8.4.45",
  "postcss-nested": "^6.2.0",
  "prettier": "^3.3.3",
  "prettier-plugin-organize-imports": "^4.0.0",
  "prettier-plugin-tailwindcss": "^0.6.6",
  "tailwindcss": "^3.4.11",
  "typescript": "^5.6.2",
  "typescript-eslint": "^8.5.0",
  "vite": "^5.4.4",
  "vue-tsc": "^2.0.29"
}
```

### Steps to reproduce

![bug1](https://github.com/user-attachments/assets/e0e62a44-589b-4683-8acb-73e702749d11)
![bug2](https://github.com/user-attachments/assets/75060d65-a85c-4ebe-af81-6e73deb4b7cd)

### What is expected?

无

### What is actually happening?

无

**Comment by KazariEX** [comment] 2024-09-19 03:51
Duplicate of #4593

**Comment by KazariEX** [comment] 2024-09-19 03:51
第一个问题是由于 `<Input>` 被识别为原生自闭合标签，请尽可能使用前缀以作区分。

**Closed by KazariEX** 2024-09-19 03:51 UTC
Labels: pending triage
