### ISSUE TITLE
Getting ts.dumpTracingLegend is not a function when using alternate tsconfig file

### ISSUE THREAD

**Issue by demariaw** [vuejs/language-tools#2384] opened 2023-02-14 20:40 UTC
I'm using vue-tsc to run an alternate tsconfig file by specifying with  -b flag 

Package.json:

```
  "tsc": "vue-tsc -b ./tsconfig/local.json",
```

tsconfig:
```
{
  "extends" : "../tsconfig.json",
  "compilerOptions": {
    "moduleResolution": "node",
    "noEmit": true
  },
  "exclude": [],
  "include": [
    "../**/*"
  ],
}

```

Whenever  i run `yarn tsc` It does the compilation but I also get this error:

```
Found 121 errors.

/home/node/node_modules/vue-tsc/bin/vue-tsc.js:46
                        throw err;
                        ^

TypeError: ts.dumpTracingLegend is not a function
    at performBuild (/home/node/node_modules/typescript/lib/tsc.js:104519:12)
    at Object.executeCommandLine (/home/node/node_modules/typescript/lib/tsc.js:104463:24)
    at Object.<anonymous> (/home/node/node_modules/typescript/lib/tsc.js:104765:4)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at main (/home/node/node_modules/vue-tsc/bin/vue-tsc.js:39:3)
```

How can I resolve this?

**Comment by johnsoncodehk** [comment] 2023-02-14 21:45
Duplicate of #2316

**Closed by johnsoncodehk** 2023-02-14 21:45 UTC
