### ISSUE TITLE
Volar offers to add a new required prop when v-model is used with modelValue

### ISSUE THREAD

**Issue by theolavaux** [vuejs/language-tools#2412] opened 2023-02-17 22:47 UTC
Using Vue.volar version 1..1.2, I run into the following problem:

Volar offers me to auto complete a prop when I have a v-model such as `update:modelValue` in a custom component.

<img width="209" alt="CleanShot 2023-02-17 at 23 36 00@2x" src="https://user-images.githubusercontent.com/25274586/219809307-f3ad17db-a1b4-452c-b7db-31cbfdbcc1b7.png">

The prop is defined as such in the `UiInput` component

<img width="266" alt="CleanShot 2023-02-17 at 23 45 55@2x" src="https://user-images.githubusercontent.com/25274586/219811701-4e86b608-58a7-4067-ae18-f3350b611809.png">

I tried manually adding `v-model:model-value` but it doesn't solve the problem either.
Would it be possible to check before showing the warning if a v-model with the required prop is already added?

Here is the rest of my Nuxt setup if needed
------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `pnpm@7.27.0`
- Builder:          `vite`
- User Config:      `ssr`, `modern`, `head`, `typescript`, `css`, `vite`, `loading`, `plugins`, `components`, `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.8`, `@pinia/nuxt@0.4.6`, `@pinia-plugin-persistedstate/nuxt@1.0.0`
- Build Modules:    `-`
------------------------------

**Comment by johnsoncodehk** [comment] 2023-02-17 22:50
Duplicate of #2407

**Closed by johnsoncodehk** 2023-02-17 22:50 UTC
