### ISSUE TITLE
Nuxt3 global component do not have props type

### ISSUE THREAD

**Issue by baixiaoyu2997** [vuejs/language-tools#3304] opened 2023-06-19 04:55 UTC
https://stackblitz.com/edit/nuxt-starter-p28a3j?file=pages%2Findex.vue

i can't see any type notice on `y-test` component, and i already use takeover mode

<img width="493" alt="image" src="https://github.com/vuejs/language-tools/assets/9149999/deb1914c-99f1-45c5-9c70-86e63f76825e">

**Comment by so1ve** [comment] 2023-06-26 16:57
Duplicate of #3188

**Closed by so1ve** 2023-06-26 16:57 UTC
Labels: duplicate

**Comment by johnsoncodehk** [comment] 2024-05-13 17:34
Fixed by https://github.com/nuxt/nuxt/pull/26541
