### ISSUE TITLE
v2.0.11 Is missing from VS marketplace

### ISSUE THREAD

**Issue by yoavbls** [vuejs/language-tools#4227] opened 2024-04-07 23:11 UTC
Hello dear @johnsoncodehk  and team!  

This is the last available version in my VSCode:

![CleanShot 2024-04-08 at 01 58 35@2x](https://github.com/vuejs/language-tools/assets/5693018/0ff3b8ee-f9e2-4854-8951-1f67be1619c0)

Even though I see 2.0.11 on their website, Reloads/restarts didn't help.
I'm not sure why that is, but my guess is that Microsoft distributes every release to buckets/CDNs in different regions, and in mine, the previous version arrived before the last one because they released in 6 seconds between each other.

Maybe releasing another one will solve it 🤷🏼‍♀️

**Comment by johnsoncodehk** [comment] 2024-04-08 00:34
@isidorn It seems that republishing has broken the VSCode Marketplace. Now, when searching for `Vue.volar`, two identical extensions appear, but with versions 2.0.10 and 2.0.11 respectively. (I didn't encounter this issue when testing `vscode unpublish` with another extension earlier.)

<img width="669" alt="image" src="https://github.com/vuejs/language-tools/assets/16279759/da9ec655-7e98-48a0-ad22-158fa1bdcd84">

**Comment by isidorn** [comment] 2024-04-08 08:05
I can reproduce this issue.
This seems to have uncovered a bug in the marketplace. Thanks for letting us know.

@seaniyer can you look into this please?

**Comment by seaniyer** [comment] 2024-04-08 18:18
> It might be related to me republishing the extension through `vsce unpublish`. I just redo it, now with a 5-minute gap between each version, let's see if it resolves the issue.

@johnsoncodehk 
I'm trying to understand the steps for repro.  How was vsce unpublish used in this case? I'd expect vsce unpublish to delete the entire extension and associated stats from the Marketplace. So probably shouldn't use that in this situation.

**Comment by Ky6uk** [comment] 2024-04-08 21:13
Hmm, I see the new package appeared under the same ID.

<img width="368" alt="Screenshot 2024-04-09 at 00 10 59" src="https://github.com/vuejs/language-tools/assets/46930/3e7d09d9-2e01-4de0-9dae-012b1bd4b593">

The old one did not have any versions to select, so I've uninstalled the old one and installed the new one. The new one has the version selection.

<img width="214" alt="Screenshot 2024-04-09 at 00 12 16" src="https://github.com/vuejs/language-tools/assets/46930/1df6e9d6-660b-4be0-979d-fd9f3fc034b9">

**Comment by johnsoncodehk** [comment] 2024-04-09 00:52
@seaniyer I executed `vsce unpublish Vue.volar` and then executed `vsce publish` for 4 versions: 1.8.27, 2.0.6, 2.0.10, 2.0.11. Since we recently suffered a lot of malicious attacks as the reason mentioned in #4148, I indeed want to completely remove the old data and publish a new extension.

**Comment by angelhdzmultimedia** [comment] 2024-04-11 07:05
Hello! 👋

Which one to keep? `2.0.10` with 7,291,213
 downloads, or `2.0.12` with 52,558 downloads?

**Comment by johnsoncodehk** [comment] 2024-04-12 16:58
@angelhdzmultimedia Please use `2.0.12` one, the `2.0.10`(with 7,291,213 downloads) one should be removed. (Need @seaniyer helps.)

**Comment by madhurivadaligithub** [comment] 2024-04-15 11:55
Hi @yoavbls 

Thanks for reporting the issue, we are following up to determine how best to address it.

 -VS Marketplace Team

**Comment by johnsoncodehk** [comment] 2024-04-16 04:19
<img width="1212" alt="image" src="https://github.com/vuejs/language-tools/assets/16279759/991c337c-325e-4cef-8d28-bbff9df99b7e">

@madhurivadaligithub Since the VS Marketplace team is also here, I would like to request the addition of a setting to disable extension ratings. One of reason I removed the ~7m downloads extension because we recently received a large number of offensive reviews, but half of the reasons may not be on our side, such as:

- [Node.js bugs in the VSCode bundle.](https://github.com/vuejs/language-tools/issues/3962)
- [Performance regression in Unocss extension in .vue files.](https://github.com/vuejs/language-tools/issues/4239)
- After Vue extension v2, Vue TS support is integrated with TS LS plugin and tsserver, and some errors actually come from tsserver itself.

Most users will not understand these reasons and will simply blame the Vue extension because the issues occur in `.vue` files. The rating feature is of no help in improving the extension; it is just a means of punishing the extension author, this is particularly problematic for an extension that is 100k downloads per week. This has caused me psychological problems and greatly reduced my motivation to continue maintaining it, which is unfair to authors providing free tools. If it is not possible to disable ratings, I will need to regularly republish the extension to clear the reviews and alleviate the psychological problems caused by continued maintenance.

Thank you for your consideration. 🙏

**Comment by DrJume** [comment] 2024-04-16 06:43
Being able to reset the reviews after a new update release could be a transparent middle ground. 
(e.g. the App Store handles it this way https://developer.apple.com/help/app-store-connect/monitor-ratings-and-reviews/reset-an-app-summary-rating/)

The Vue extension totally deserves 5⭐️ 💚

**Comment by seaniyer** [comment] 2024-04-16 15:24
@johnsoncodehk

Thanks for sharing. Please post your ask as an issue on https://github.com/microsoft/vsmarketplace which is the best place for the Marketplace team to track it and the community to weigh in with additional input.

**Comment by johnsoncodehk** [comment] 2024-04-16 15:34
@seaniyer I missed this place, thanks for letting me know!

**Comment by ericcirone** [comment] 2024-04-16 19:17
Doesn't look like 2.0.13 is in the marketplace either

**Comment by johnsoncodehk** [comment] 2024-04-16 20:18
@ericcirone v2.0.13 only has changes specific to `vue-tsc`, so the VSCode extension is not released.

**Comment by Real-Gecko** [comment] 2024-04-24 12:48
> Doesn't look like 2.0.13 is in the marketplace either

There're two extensions currently, one is `2.0.10` and another is `2.0.14`

![image](https://github.com/vuejs/language-tools/assets/2231969/034d7deb-2a61-48b2-971d-db4c823edfd7)
![image](https://github.com/vuejs/language-tools/assets/2231969/a671d341-4515-43bd-9255-693035e38131)

Both have same extension ID `Vue.volar`, I guess until issue is resolved on marketplace side you have to manually check for both.

**Comment by seaniyer** [comment] 2024-04-25 19:41
@johnsoncodehk  
We are planning to remove the older version v2.0.10 as a one-off fix while the investigation for root cause proceeds. If that won't work for you for any reason, please let us know.

**Comment by paraboul** [comment] 2024-04-25 19:56
> @johnsoncodehk We are planning to remove the older version v2.0.10 as a one-off fix while the investigation for root cause proceeds. If that won't work for you for any reason, please let us know.

Isn't this going to uninstall the plugin for all the user base (which is probably stuck on 2.0.10) and also reset the download counter?

**Comment by johnsoncodehk** [comment] 2024-04-25 20:30
@seaniyer A timeout occurred when I executed `vsce unpublish` for `Vue.volar` for the first time. I guess the reason is that there are too many versions that need to be deleted. Maybe this caused the extension to not be completely cleaned up.

Anyway thanks again for your help! Don't worry about download counter as we plan to re-publish regularly to clean up reviews.

**Comment by isidorn** [comment] 2024-04-26 10:10
> as we plan to re-publish regularly to clean up reviews.

I would recommend against this, as this might cause other issues like the one we are experiencing right now.
This flow is not fully supported by the marketplace.

**Comment by johnsoncodehk** [comment] 2024-04-26 10:51
> I would recommend against this, as this might cause other issues like the one we are experiencing right now. This flow is not fully supported by the marketplace.

Unfortunately the psychological issues I am facing are more serious than what I am describing and this is something that needs to be dealt with and a reset is the only approach we can take at the moment. (We just received another personal attack comment again)

The next scheduled reset is in June, if you wish to postpone it please let me know. I'll also open a request to disable reviews at https://github.com/microsoft/vsmarketplace.

**Comment by seaniyer** [comment] 2024-04-26 21:11
@johnsoncodehk Sorry to hear about personal attacks. There is no place for it on Marketplace. As a way of helping to mitigate the issue, we'll keep a closer eye on reviews posted to the extension and moderate as needed.

**Comment by seaniyer** [comment] 2024-04-29 17:06
> > I would recommend against this, as this might cause other issues like the one we are experiencing right now. This flow is not fully supported by the marketplace.
> 
> Unfortunately the psychological issues I am facing are more serious than what I am describing and this is something that needs to be dealt with and a reset is the only approach we can take at the moment. (We just received another personal attack comment again)
> 
> The next scheduled reset is in June, if you wish to postpone it please let me know. I'll also open a request to disable reviews at https://github.com/microsoft/vsmarketplace.

@johnsoncodehk, Our team is planning to frequently check and moderate reviews on the extension between now and June. Should we miss something, as always reach out to vsmarketplace@microsoft.com to report/remove a review. Let's see if we can help you avoid unpublishing.

**Comment by seaniyer** [comment] 2024-05-01 02:20
@johnsoncodehk 
Only the latest version 

> @seaniyer A timeout occurred when I executed `vsce unpublish` for `Vue.volar` for the first time. I guess the reason is that there are too many versions that need to be deleted. Maybe this caused the extension to not be completely cleaned up.
> 
> Anyway thanks again for your help! Don't worry about download counter as we plan to re-publish regularly to clean up reviews.

The old version has been removed from the search results. Only v2.0.15 shows for me now.

**Comment by isidorn** [comment] 2024-05-01 16:12
I have confirmed that me as a user of the zombie version got updated to the latest 2.0.15.
So we are good now and I think we can go ahead and close this issue.

@johnsoncodehk all your users should be auto-updated to your latest version.

**Comment by PizzaConsole** [comment] 2024-05-08 07:19
@isidorn I did not get auto-updated I had to uninstall the extension and reinstall. I was stuck on 2.0.7 and was not aware of this thread until I troubleshooted by myself.

**Comment by isidorn** [comment] 2024-05-08 08:14
@PizzaConsole interesting. This is not what happened to me. Let's see if other users see this. And we can also double check by looking at our data (extension version usage).

**Comment by wrejcodes** [comment] 2024-05-09 22:09
I was stuck on version 2.0.8 with no update button when I looked at the extension. After searching for "Vue - Official" in the Extension Marketplace I was able to update to the new version. Just leaving that here in case anyone finds it useful.

**Comment by GabrielHangor** [comment] 2024-05-25 09:10
How is the current's version (2.0.19) performance? I am still on 1.8.27 where i have no issue, is it time to update?

**Comment by johnsoncodehk** [comment] 2024-07-03 11:32
@seaniyer Thanks for your help with this, I just opened a request at https://github.com/microsoft/vsmarketplace/discussions/949 to disable ratings for extensions, if it lands we can avoid having to resort to republishing extensions.

@isidorn I found that the `2.0.7` I installed in github.dev failed to prompt for update (the latest version is `2.0.24`), and since I have reinstalled `Vue.volar` in `github.dev` I can't reproduce it again, if you need to For more information, I might try if I can find an old computer with an older version installed.

**Comment by johnsoncodehk** [comment] 2024-08-09 21:50
Please note https://github.com/microsoft/vsmarketplace/issues/979 now. 🙏

**Closed by johnsoncodehk** 2024-08-09 21:50 UTC
Labels: upstream
