### ISSUE TITLE
question: what is the meaning of `??=` in line 678 of `/vue-language-core/src/generators/template.ts` file?

### ISSUE THREAD

**Issue by kagol** [vuejs/language-tools#2693] opened 2023-04-24 02:43 UTC
In the file:

https://github.com/vuejs/language-tools/blob/eef20830f89ab91059aa302d4fc3e3fb68baf54e/packages/vue-language-core/src/generators/template.ts#L678

There is a `??=`, what the meaning of this? 

Can anyone help me to answer this question? Thanks!

```
localVars[varName] ??= 0;
```

**Comment by johnsoncodehk** [comment] 2023-04-24 02:47
Duplicate of #2643

**Closed by johnsoncodehk** 2023-04-24 02:47 UTC

**Comment by kagol** [comment] 2023-04-24 02:53
> Duplicate of #2643

Thank you for helping me solve the problem.
