### ISSUE TITLE
Directive arg is resolved as props

### ISSUE THREAD

**Issue by wxpwxpwxp** [vuejs/language-tools#2717] opened 2023-04-26 10:00 UTC
directive arg is been resolved as props

### Versions:
- valor(vue): v1.4.1
- valor(ts): v1.4.4

### Snapshot
<img width="988" alt="image" src="https://user-images.githubusercontent.com/51726580/234541705-3f72044a-81f3-4e1c-a1ea-97ac7a37c0f0.png">

**Comment by johnsoncodehk** [comment] 2023-04-26 21:05
Duplicate of #2678

**Closed by johnsoncodehk** 2023-04-26 21:05 UTC
Labels: duplicate

**Comment by sovietspaceship** [comment] 2023-04-27 01:13
For anyone having issues with types not being inferred for inline events: update vue-tsc to 1.6.0 or downgrade the extension
