### ISSUE TITLE
[vue-tsc] kebab-cased prop beginning with "delete-" emits false positives TS2362 and TS2703 with vue 3.4 shortcut syntax

### ISSUE THREAD

**Issue by jacobtylerwalls** [vuejs/language-tools#3901] opened 2024-02-21 19:15 UTC
With a prop like:

```vue
<DeleteText :delete-label :delete-label-alternate />
```
Get false positives:
```
error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.
error TS2703: The operand of a 'delete' operator must be a property reference.
```

See [playground](https://play.vuejs.org/#eNqFUsFOwzAM/ZUol4G0tQc4jTI0YAcQgmnsRjiU1hsdaRIlaZnU9d9xEm3rtGncYr9n+zl+DR0rFdUV0CFNTKYLZYkBW6kRE0WppLbkEThYmMPakoWWJelF8T7lSns3TDCRSWEsyT3ykn4BJ7ekF4h3jnGEj7kFLVILjjiDUtaBmMRBByrAwEKpOJIwIiTpaBmGVgPuZx1Eg3TXOsa6JO40oX1qDWpZFMtoZaTAvRvXmtFMlqrgoN+ULVAro0PiEYelnMvfZ5+zuoL+Np99Q/ZzIr8ya5djdKrBgK6B0R1mU70EG+DJ+yvu0gFLmVcc2WfAGRjJK6cx0O4rkaPsDs+rffLXK8RybiZrC8Jsl3JCHbP1fEbxgg9nVt/LvYqufR0TLf7ioQdO2CccXGmpDF44h0UhYOqiiw9GOz5A4TjmlDEY/bz8xxB5UfsHPo1KxahpwsSoa8TN5ji5d1/b4gBX6xvGoeOhZ9o/Dr8Upw==)

**Comment by so1ve** [comment] 2024-02-22 06:34
Duplicate of https://github.com/vuejs/language-tools/issues/3830

**Closed by so1ve** 2024-02-22 06:34 UTC
