### ISSUE TITLE
Volar tread input of attribute as adding element (添加html 元素属性默认被认为是添加子元素

### ISSUE THREAD

**Issue by extrame** [vuejs/language-tools#2368] opened 2023-02-09 01:10 UTC
样例（example)：
![image](https://user-images.githubusercontent.com/2107188/217688305-b47a552d-7f05-4428-a659-83edd3b039f8.png)

上述输入后，会默认展开为(auto expanded as)

```  
  <el-card <head></head>>

   </el-card>
```

这不符合语法吧？

在元素的这个位置，应该直接可以判定成为输入属性啊，不应该是展开了子元素的逻辑

Apparently, It should be a location of attribute, I don't think sub-element is legal in here, why volar prefered it should be expanded as element definition?

**Comment by johnsoncodehk** [comment] 2023-02-19 21:55
Duplicate of #1329

**Closed by johnsoncodehk** 2023-02-19 21:55 UTC
