### ISSUE TITLE
Cannot find module `*.vue` or its corresponding type declarations when components live in hidden directories

### ISSUE THREAD

**Issue by nekomeowww** [vuejs/language-tools#3349] opened 2023-07-02 04:08 UTC
## Summary

![image](https://github.com/vuejs/language-tools/assets/11081491/e1f2c386-b4e3-4b9f-9079-8c66c986ab5d)

Encountered `Cannot find module './C2.vue' or its corresponding type declarations.` issue when opening a component that lives in a hidden directory (with `.` prefixed) in Visual Studio Code with Volar with the following behaviors:

- `vue-tsc --noEmit` with no errors.
- can navigate to the correct component when holding CMD and clicked the imported path in source code files.
- the components lives in the non-hidden directories (without `.` prefixed) directories are fine, such as `src`, `dot`.
- can be compiled, bundled successfully and working properly when in development, production modes, previews.

Such issue was initially appeared when I was developing some extension components for my VitePress site and the components was lived in `.vitepress` directory.

### Reproduction

GitHub Reproduction Repo: https://github.com/nekomeowww/reproduction_volar_cannot_find_vue_module
Stackblitz Reproduction: https://stackblitz.com/github/nekomeowww/reproduction_volar_cannot_find_vue_module

### Already done troubleshooting

1. I almost checked every issues, webpages that appeared under GitHub, StackOverflow and Google with the term `"Cannot find module" "vue"` with no luck.
2. Tried different content, filenames of `shims.d.ts` for `declare module '*.vue'` statement:

```typescript
declare module '*.vue' {
  import type {DefineComponent} from 'vue'
  const component: DefineComponent<object, object, any>
  export default component
}
```

```typescript
declare module "*.vue" {
  import Vue from 'vue';
  export default Vue;
}
```

3. Tried configure more includes path for `tsconfig.json` with `**/*.d.ts, **/*.vue` with no luck.
4. Tried to copy and paste the `tsconfig.json` from either [antfu/vitesse](https://github.com/antfu/vitesse) and [vuejs/vitepress](https://github.com/vuejs/vitepress) with no luck.
5. Tried to globally or workspace partially disable `@builtin typescript` JavaScript and TypeScript language feature extension within VSCode with no luck.
6. Tried the latest Vue StackBlitz playground and default configuration with no luck.

#### Extensions

```
Visual Studio Code

Version: 1.79.2 (Universal)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z (2 wks ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

##### Extensions

```
TypeScript Vue Plugin (Volar) v1.8.3
Vue Language Features (Volar) v1.8.3
```

#### Runtime and package manager

```
Node.js v18.16.1
Pnpm v7.0.0
```

#### Dependencies

`package.json`:

```json
{
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.2.3",
    "typescript": "^5.1.6",
    "vite": "^4.3.9",
    "vue": "^3.3.4",
    "vue-tsc": "^1.8.3"
  },
  "type": "module"
}
```

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "ESNext",
    "target": "ESNext",
    "strict": false,
    "esModuleInterop": true,
    "jsx": "preserve",
    "skipLibCheck": true,
    "isolatedModules": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
  },
  "exclude": [
    "**/node_modules/**",
    "**/dist/**",
  ]
}
```

**Comment by nekomeowww** [comment] 2023-07-16 03:11
Any updates?

**Comment by sfe-efficy** [comment] 2023-07-19 08:03
Same problem here jumping from 1.8.1 to 1.8.5 (I didn't check versions between them)

**Comment by rchl** [comment] 2023-07-19 12:03
This is a duplicate of See https://github.com/vuejs/language-tools/issues/3328

As should be clear from the linked issue you can explicitly state which vue files to process by adding `include` to `tsconfig.json`:

```
  "include": [
    "./.dot/**/*.vue",
    "./dot/**/*.vue",
    "./src/**/*.vue",
  ]
```

or something more generic.

**Comment by so1ve** [comment] 2023-07-28 12:46
Duplicate of #3328

**Closed by so1ve** 2023-07-28 12:46 UTC
Labels: pending triage, good reproduction ✨

**Comment by csh0101** [comment] 2024-01-25 05:31
> And should be fixed by #3450并且应该由#3450修复

volar 1.82.7 is not fix it.

**Comment by catgoose** [comment] 2024-04-10 16:19
I fixed this by creating `vue.d.ts` in src with the contents:

```typescript
declare module '*.vue';
```

**Comment by mystic3333** [comment] 2024-05-13 06:11
helpful, it has solve the problem,

**Comment by Dante-sanatorium** [comment] 2025-01-30 17:08
> Any updates?





https://javascripter.space/questions/vue-alert-the-element-app-is-missing-vuejs-2
