### ISSUE TITLE
TypeScript server crashes ad infinitum when using v2 and above

### ISSUE THREAD

**Issue by Vanilagy** [vuejs/language-tools#4043] opened 2024-03-07 09:51 UTC
There seem to be issues with v2. In one of our projects, having the extension "Vue - Official" on v2 causes the the TypeScript server to repeatedly crash upon startup. After it does so 5 times, it gives up:

![CleanShot 2024-03-07 at 10 47 29](https://github.com/vuejs/language-tools/assets/1696106/cd0a3fc0-a047-4db8-91ce-2e86b4c7ab90)

Downgrading to the latest sub-2 version fixes the problem, so a temporary solution for us would be to use the old version and reenable takeover mode until this is fixed.

I wish I could provide more debugging info, but I'm not sure where to look. This is the only thing I could find:

<details>
  <summary>TypeScript output</summary>

  ```log
  2024-03-07 10:44:39.336 [info] Starting TS Server
2024-03-07 10:44:39.337 [info] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-07 10:44:39.337 [info] <syntax> Forking...
2024-03-07 10:44:39.337 [info] <syntax> Starting...
2024-03-07 10:44:39.337 [info] <semantic> Forking...
2024-03-07 10:44:39.337 [info] <semantic> Starting...
2024-03-07 10:44:41.197 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-07 10:44:41.197 [info] Starting TS Server
2024-03-07 10:44:41.197 [info] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-07 10:44:41.197 [info] <syntax> Forking...
2024-03-07 10:44:41.197 [info] <syntax> Starting...
2024-03-07 10:44:41.197 [info] <semantic> Forking...
2024-03-07 10:44:41.197 [info] <semantic> Starting...
2024-03-07 10:44:42.677 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-07 10:44:42.678 [info] Starting TS Server
2024-03-07 10:44:42.678 [info] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-07 10:44:42.678 [info] <syntax> Forking...
2024-03-07 10:44:42.678 [info] <syntax> Starting...
2024-03-07 10:44:42.678 [info] <semantic> Forking...
2024-03-07 10:44:42.678 [info] <semantic> Starting...
2024-03-07 10:44:44.070 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-07 10:44:44.070 [info] Starting TS Server
2024-03-07 10:44:44.070 [info] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-07 10:44:44.070 [info] <syntax> Forking...
2024-03-07 10:44:44.070 [info] <syntax> Starting...
2024-03-07 10:44:44.070 [info] <semantic> Forking...
2024-03-07 10:44:44.070 [info] <semantic> Starting...
2024-03-07 10:44:45.491 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-07 10:44:45.491 [info] Starting TS Server
2024-03-07 10:44:45.491 [info] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-07 10:44:45.491 [info] <syntax> Forking...
2024-03-07 10:44:45.491 [info] <syntax> Starting...
2024-03-07 10:44:45.491 [info] <semantic> Forking...
2024-03-07 10:44:45.491 [info] <semantic> Starting...
2024-03-07 10:44:46.873 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-07 10:44:46.873 [info] Starting TS Server
2024-03-07 10:44:46.873 [info] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
2024-03-07 10:44:46.873 [info] <syntax> Forking...
2024-03-07 10:44:46.873 [info] <syntax> Starting...
2024-03-07 10:44:46.873 [info] <semantic> Forking...
2024-03-07 10:44:46.873 [info] <semantic> Starting...
2024-03-07 10:44:48.228 [error] TSServer exited. Code: null. Signal: SIGBUS
  ```
</details>

**Comment by Gumper-x** [comment] 2024-03-07 11:03
The same problem

**Comment by mlodyoskar** [comment] 2024-03-07 11:58
Until they fix it you can use older version of extension with: `>Extensions: Disable Auto Update for All Extensions` in vs-code    and than on extension view you can choose older version, choose one that starts with 1 and you'll be fine 😃

**Comment by brc-dd** [comment] 2024-03-07 17:41
Duplicate of #3962

Please use v1.8 for now or try using vscode insiders.

**Comment by so1ve** [comment] 2024-03-08 04:07
Duplicate of https://github.com/vuejs/language-tools/issues/3962

**Closed by so1ve** 2024-03-08 04:07 UTC

**Comment by Vanilagy** [comment] 2024-03-08 08:48
Sorry lads 🙏
