### ISSUE TITLE
@click ,no code prompt

### ISSUE THREAD

**Issue by DZHAPPY** [vuejs/language-tools#2661] opened 2023-04-21 13:07 UTC
When using versions 1.4.0 to 1.4.2 to enter @, there will be no prompt for shortcut codes such as @ click, and using 1.2.0 does not have this issue

**Comment by roydukkey** [comment] 2023-04-21 15:56
I'm hitting a similar issue today after updating from 1.2.0 to newer. The issue seems that vscode extension is not resolving template types correctly.

**1.2.0 (working)**

https://user-images.githubusercontent.com/1509616/233681136-cd725145-48e5-48f4-b1a7-89751e4f7c53.mov

**1.4.2 (not working)**

https://user-images.githubusercontent.com/1509616/233681177-fcd8971c-6c74-4c7a-a5a6-525acb4022d3.mov

 I also have a `vsc-tsc` script checking types during build. `vsc-tsc` it continue to work properly in the templates.

**Comment by johnsoncodehk** [comment] 2023-04-21 23:21
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by roydukkey** [comment] 2023-04-22 03:05
No, actually. I tried with this repo, and the only difference is that I tried this on a different computer.

**Comment by johnsoncodehk** [comment] 2023-04-22 12:00
Can you provide repro case?

**Comment by roydukkey** [comment] 2023-04-22 17:44
Okay. Here are some more diagnostic info.

**Attempt 1**
1. Using the same machine that originally had the issue
2. Updated `Vue.volar` VSCode extension to `v1.4.3`
3. Rebuild _my_ mono repo. **Still have issue.**

**Attempt 2**
1. Continuing from where "Attempt 1" ended.
1. Update macOS from Ventura 13.2 to 13.3.1
2. Rebuild _my_ mono repo. **Issue is fixed**.

**VScode Info**
Version: 1.77.3 (Universal)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:19:37.325Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

**Computer Info**
MacBook Pro
Chip: Apple M1 Pro

My mono repo is private so I can share a reproduction, and I'm not able to give time and attention to downgrading my macOS version to see if the issue returns. If there is anything else I can do to help, let me know.

@DZHAPPY I'm curious if any of this lines up with your experience. Do other items in your templates have `any` types like I show in my video?

**Comment by roydukkey** [comment] 2023-04-24 19:17
Okay. I've been able to lock this down to a reproduction. It turns out my brain on the weekend is lazy sometimes, because my previous comment is not accurate at all. 😅

https://github.com/roydukkey/moist/tree/vuejs/language-tools%232661

There are several commits on this branch that show the progression through the issue and the [README](https://github.com/roydukkey/moist/tree/vuejs/language-tools%232661#readme) has more videos.

**Closed** 2023-04-25 20:46 UTC
Labels: need info
