### ISSUE TITLE
An object passed to @click function in <template> is considered possibly undefined despite v-if check

### ISSUE THREAD

**Issue by Kolobamanacas** [vuejs/language-tools#2349] opened 2023-01-31 08:20 UTC
Repro steps:

1. Initialize new project with:
`npm init vue@latest`

2. Make sure to choose these options:

```
TypeScript - Yes
JSX - No
Vue Router - No
Pinia - No
Vitest - No
End-to-End Testing - No
ESLint - Yes
Prettier - Yes
```

3. Go to new project's folder and run:
`npm i`

4. Make sure the latest versions of these apps and plugins are installed:
    - VS Code (1.74.3)
    - Vue Language Features (Volar) (1.0.24)
    - TypeScript Vue Plugin (Volar) (1.0.25)

5. Open project with VS Code and replace text in `App.vue` with the following code:

``` vue
<template>
  <div v-if="messageObject !== undefined">
    <div>{{ messageObject.message }}</div>
    <button @click="print(messageObject.message)">Click me</button>
  </div>
</template>

<script setup lang="ts">
import { type Ref, ref } from 'vue';

const messageObject: Ref<{ message: string } | undefined> = ref({
  message: 'Hello',
});

const print = (text: string) => {
  console.log(text);
};
</script>
```

6. Expected result:

`messageObject.message` is passed to `print()` without any warnings.

7. Actual result:

The error `'__VLS_ctx.messageObject' is possibly 'undefined'.ts(18048)` is shown.

![2023-01-31_10-17-10](https://user-images.githubusercontent.com/20444060/215704525-4d14e44d-f910-47d8-add9-05ec8c0ede4a.png)

**Comment by Fnxxxxo** [comment] 2023-02-07 07:42
Meet it in vite project with vue-tsc checking. If type checking is not ready in template, hope a way to close it.

**Comment by johnsoncodehk** [comment] 2023-02-19 19:39
Duplicate of #2144

**Closed by johnsoncodehk** 2023-02-19 19:39 UTC
