### ISSUE TITLE
With vue-i18n it gives types error of $t and $i18n usage

### ISSUE THREAD

**Issue by dhavalt091** [vuejs/language-tools#3760] opened 2023-11-29 14:31 UTC
As soon as i enable/install `Vue Language Features (Volar)` in VS code, i get type errors in html wherever `$t` and `$i18n` is used.

`<template>
    <h1>{{ $t('views.home.title') }}</h1>
    <h1>{{ $i18n.locale }}</h1>
</template>
`
Above is my html.

And below is how i get errors/warnings by volar.

![volar-html](https://github.com/johnsoncodehk/volar-starter/assets/137805101/4dfc3df1-80a8-4e70-880b-28fee3317a21)

What am i missing here?

**Comment by UfukUstali** [comment] 2023-11-29 19:34
It might be related to this I am not sure tough.

https://github.com/nuxt-modules/i18n/issues/2483#issuecomment-1791671709

**Comment by Nick-Hopps** [comment] 2023-11-30 08:01
the same issue #3735

**Comment by rchl** [comment] 2023-11-30 08:07
There was issues with types unrelated to Volar, as the linked issue states.
Please provide a repo that reproduces and also make sure you are using latest versions of the module.

**Comment by so1ve** [comment] 2023-11-30 08:43
Duplicate of https://github.com/vuejs/language-tools/issues/3735

**Comment by so1ve** [comment] 2023-11-30 09:10
Sorry, didn't notice that 😅 I'll reopen this issue to investigate further

**Comment by rchl** [comment] 2023-11-30 09:12
We should wait for reproduction instead of investigating as there were known issues with types in i18n nuxt module that might be fixed already.

**Comment by UfukUstali** [comment] 2023-11-30 09:28
The issue mentioned in that comment was caused by Vue i18n which nuxt i18n does also use under the hood.

**Comment by dhavalt091** [comment] 2023-11-30 09:28
Using below versions. 
```
 "vue": "^3.2.47",
 "vue-i18n": "^9.2.2",
```

`Vue Language Features (Volar)
v1.8.24`

In `Home.vue` with just simple usage it's reproducible.
```
<template>
    <h1>{{ $t('views.home') }}</h1>
    <h1>{{ $i18n.locale }}</h1>
</template>
```

This is nothing related to `nuxt`

**Comment by rchl** [comment] 2023-11-30 09:31
> In Home.vue with just simple usage it's reproducible.

Provide a repo that reproduces.
It's relevant how the project is set up. The specific component you are showing is not enough.
And if vue-i18n itself doesn't extend Vue types then it would be your responsibility to do that, not Volar's.

It might be a better question for the `vue-i18n` repo, to be honest.

**Comment by dhavalt091** [comment] 2023-11-30 09:39
If error highlights without this extension then it would be `vue-i18n` repo.
I have just above template in `Home.vue` file. No script ta as well. This is enough to reproduce the issue.
How can i create reproduction repo? Online tools like stackblitz doesn't provide a way to add extension in it.

**Comment by rchl** [comment] 2023-11-30 09:41
No, just a snippet of code is not enough. It's also relevant which packages are installed and in what versions. And the `tsconfig.json` configuration. And many other variables...

Just create a project that reproduces and put it on stackblitz or github. Then someone can download it locally and check with Volar.

**Comment by Nick-Hopps** [comment] 2023-12-01 13:08
I don't know how to configure npm workspace to force installing sub package's vue inside their respective node_modules, so I just remove workspaces config in the root package.json and run npm install then add the config back and run npm install -w packages/*, once the "@vue/runtime-core" version under root project is ok, the issue will be gone.

**Closed** 2024-08-13 15:25 UTC
Labels: pending triage
