### ISSUE TITLE
Using  2.0+ version in vue 2.7 project reports error about ts-plugin

### ISSUE THREAD

**Issue by AfireHong** [vuejs/language-tools#3992] opened 2024-03-05 13:49 UTC
![image](https://github.com/vuejs/language-tools/assets/51915214/b9506de4-6989-493a-ab4b-6b8edb9acf63)

demo: https://github.com/AfireHong/VLS-error-demo

**Comment by Finki007** [comment] 2024-03-05 15:28
Same for me

**Comment by jwolinsky** [comment] 2024-03-05 18:55
same

**Comment by kkarasek** [comment] 2024-03-05 20:27
same for Vue 3 + other errors when Volar for TS got deprecated

<img width="965" alt="image" src="https://github.com/vuejs/language-tools/assets/30701167/ad927ce1-c2f7-4b01-ae44-a0eb73acefae">

**Comment by so1ve** [comment] 2024-03-06 04:18
Duplicate of #3942

**Closed by so1ve** 2024-03-06 04:18 UTC
