### ISSUE TITLE
Slots hack (`v-for="(_, slot) of $slots" #[slot]="scope"`) started showing errors

### ISSUE THREAD

**Issue by 0x00A1FA** [vuejs/language-tools#3216] opened 2023-05-22 13:19 UTC
Hi,

Here's the issue:

![image](https://github.com/vuejs/language-tools/assets/110613761/509ccb14-f02e-4e8e-96c7-633465cd16e0)

Text:
```
Element implicitly has an 'any' type because expression of type 'string | number' can't be used to index type 'Readonly<{ message?: ((args_0: VMessageSlot) => VNode<RendererNode, RendererElement, { [key: string]: any; }>[]) | undefined; clear?: (() => VNode<...>[]) | undefined; ... 12 more ...; 'no-data'?: (() => VNode<...>[]) | undefined; }> & MakeSlots<...>'.
  No index signature with a parameter of type 'string' was found on type 'Readonly<{ message?: ((args_0: VMessageSlot) => VNode<RendererNode, RendererElement, { [key: string]: any; }>[]) | undefined; clear?: (() => VNode<...>[]) | undefined; ... 12 more ...; 'no-data'?: (() => VNode<...>[]) | undefined; }> & MakeSlots<...>'.ts(7053)
const slot: string | number
```

Isn't this the way I'm supposed to go through all the slots?

Thank you.

**Comment by laterdayi** [comment] 2023-05-22 15:27
Same error, when v-for I say undefined cannot be assigned to #scope

**Comment by maitlandmarshall** [comment] 2023-05-24 00:27
Same error as well.

```
<template
            v-for="slotName of Object.keys($slots)"
            v-slot:[slotName]
        >
            <slot :name="slotName" />
        </template>
```

**Comment by Hawxy** [comment] 2023-05-24 11:29
The latest version of Vuetify (3.3.1) includes some internal changes to resolve this issue, but you do need an additional type to cast the union:

```ts
<template>
  <v-input>
    <template v-for="(_, slotName) in slots" :key="slotName" #[slotName]="slotProps">
      <slot :name="slotName" v-bind="(slotProps as UnionToIntersection<typeof slotProps>) || {}" />
    </template>
  </v-input>
</template>

<script setup lang="ts">
  import { VInput } from '@/components/VInput'

  type Slots = VInput['$slots'];
  type UnionToIntersection<U> =
    (U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never

  const slots = defineSlots<Slots>()
</script>
```

**Comment by KaelWD** [comment] 2023-05-29 09:24
You're better off using JSX for this, it should just be

```js
import { defineComponent, type SlotsType } from 'vue'
import { VInput } from 'vuetify/components/VInput'

defineComponent({
  slots: Object as SlotsType<VInput['$slots']>,
  setup (props, { slots }) {
    return () => <VInput v-slots={ slots } />
  }
})
```

**Comment by IlCallo** [comment] 2023-05-29 16:36
We apparently have a similar problem with Quasar, when creating a transparent wrapper around a Quasar own component
I published a repro here: https://github.com/IlCallo/ts5-vue3.3-defineslots

You can see Volar errors into all SFC into `src/components` folder, even if they differ depending on the component
It looks like that it gets particularly angry if all slots don't have a scope parameter
Only the error in `ExampleComponentOne` is actually correct

**Comment by IlCallo** [comment] 2023-05-30 08:09
No need to get sarcastic, that's kind of disrespectful for who is working for free (or underpaid at best) on a product you use for free
Go on and switch to React if you like that, you're encouraged to use the framework with which you feel more productive :)

If you want to, but are not able to, that's still not a good reason to shit on a whole ecosystem work

**Comment by laterdayi** [comment] 2023-05-30 08:15
`impotent rage`

**Comment by KaelWD** [comment] 2023-05-30 08:17
This is a somewhat common scenario when extending other components, should we add `v-slots` to template syntax too to go with `v-on` and `v-bind`?

https://github.com/vuejs/core/issues/575

**Comment by laterdayi** [comment] 2023-05-31 09:19
I hope you're offering advice, not sarcasm

**Comment by johnsoncodehk** [comment] 2023-06-07 21:40
> We apparently have a similar problem with Quasar, when creating a transparent wrapper around a Quasar own component
> I published a repro here: [IlCallo/ts5-vue3.3-defineslots](https://github.com/IlCallo/ts5-vue3.3-defineslots)

Thanks for that, very clear!

**Comment by johnsoncodehk** [comment] 2023-06-07 22:07
This issue is a bit confusing, the original issue is similar to `ExampleComponentOne` in the reproduction, it is expected, I will close this issue and solve `ExampleComponentTwo`, `ExampleComponentThree` separately. @IlCallo It would be nice if you could open a new issue.

In order to prevent rude people from continuing to harass, I will lock this issue.

**Closed by johnsoncodehk** 2023-06-07 22:07 UTC
Labels: bug
