### ISSUE TITLE
Vue-ts fails in pipelines and fresh modules install with error: Search string not found: "/supportedTSExtensions = .*(?=;)/"

### ISSUE THREAD

**Issue by jaxenvisuals** [vuejs/language-tools#5025] opened 2024-12-04 14:50 UTC
### Vue - Official extension or vue-tsc version

Vue tsc 2.1.10

### VSCode version

1.95.3 (user setup)

### Vue version

3.3.4

### TypeScript version

5.0.2

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 1.30 GB / 15.70 GB
Binaries:
    Node: 18.20.5 - ~\AppData\Local\Volta\tools\image\node\18.20.5\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\Volta\tools\image\yarn\1.22.22\bin\yarn.CMD
    npm: 10.8.2 - ~\AppData\Local\Volta\tools\image\node\18.20.5\npm.CMD
```

### package.json dependencies

```json
{
  "dependencies": {
    "@jamescoyle/vue-icon": "^0.1.2",
    "@mapbox/togeojson": "^0.16.2",
    "@mdi/font": "^7.4.47",
    "@mdi/js": "^7.4.47",
    "@remixicon/vue": "^4.2.0",
    "@tanstack/vue-query": "^5.12.2",
    "@tanstack/vue-query-devtools": "^5.13.3",
    "axios": "^1.7.2",
    "circle-to-polygon": "^2.2.0",
    "element-plus": "^2.7.6",
    "jwt-decode": "^4.0.0",
    "keycloak-js": "^25.0.0",
    "leaflet": "1.9.4",
    "leaflet-draw": "1.0.2",
    "leaflet-geosearch": "^4.0.0",
    "leaflet.vectorgrid": "^1.3.0",
    "lodash": "^4.17.21",
    "moment": "^2.30.1",
    "pinia": "^2.1.7",
    "pinia-plugin-persistedstate": "^3.2.1",
    "pubsub-js": "^1.9.4",
    "remixicon": "^4.2.0",
    "swiper": "^10.3.0",
    "tokml": "^0.4.0",
    "uuid": "^9.0.1",
    "vue": "^3.3.4",
    "vue-router": "4"
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.13",
    "@types/axios": "^0.14.0",
    "@types/circle-to-polygon": "^2.2.3",
    "@types/jwt-decode": "^3.1.0",
    "@types/keycloak-js": "^3.4.1",
    "@types/leaflet": "^1.9.12",
    "@types/leaflet-draw": "^1.0.11",
    "@types/moment": "^2.13.0",
    "@types/pubsub-js": "^1.8.6",
    "@types/uuid": "^9.0.8",
    "@vitejs/plugin-vue": "^4.2.3",
    "autoprefixer": "^10.4.15",
    "concurrently": "^8.2.2",
    "husky": "^9.0.11",
    "postcss": "^8.4.29",
    "prettier": "3.3.0",
    "sass": "^1.66.1",
    "tailwindcss": "^3.3.3",
    "typescript": "^5.0.2",
    "unplugin-auto-import": "^0.16.6",
    "unplugin-element-plus": "^0.8.0",
    "unplugin-vue-components": "^0.25.2",
    "vite": "^4.4.5",
    "vitest": "^1.6.0",
    "vue-tsc": "^2.1.10"
  }
}
```

### Steps to reproduce

This is a vue 3 project. With these present in my package json
```javascript
"lint": "vue-tsc",
"lint:watch": "vue-tsc --watch",
``` 
Run yarn lint. It doesn't lint the files. It just breaks with error

### What is expected?

Files should be linted. Errors should be returned if files with wrong types or typescript errors exist.

### What is actually happening?

Script breaks
```powershell
Script breaks
```powershell
✓ src/utility/functions/tests/validator.test.ts (1)
   ✓ Email validation

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  13:27:04
   Duration  677ms (transform 103ms, setup 0ms, collect 130ms, tests 4ms, environment 0ms, prepare 173ms)


> project@2.22.0 build:css
> tailwindcss -i ./src/assets/scss/tailwind/tailwind.css -o ./src/assets/scss/tailwind/tailwind-purged.css -m


Rebuilding...

Done in 995ms.

> project@2.22.0 lint
> vue-tsc


C:\Users\user\Documents\_project\fix-yarn\node_modules\vue-tsc\index.js:34
            throw err;
            ^
Search string not found: "/supportedTSExtensions = .*(?=;)/"
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.14.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` 
``` 

### Link to minimal reproduction

_No response_

### Any additional comments?

It seems some recent updates is causing this. My pipelines would usually run successfully and linting with vue-tsc in pre commit hook also worked. Now it fails all of a sudden.
For existing projects, no issue. For new fresh node module installations (including pipelines), it breaks

**Comment by rchl** [comment] 2024-12-04 17:53
Duplicate of #5018

**Closed by rchl** 2024-12-04 17:53 UTC
Labels: pending triage
