### ISSUE TITLE
Type casting with "as" breaks syntax highlighting in VSCode

### ISSUE THREAD

**Issue by evur** [vuejs/language-tools#3220] opened 2023-05-23 10:25 UTC
Doing a type cast with the `as`-syntax inside a computed attribute breaks the syntax highlighting like an unclosed string:

![Screenshot of broken syntax highlighting](https://github.com/vuejs/language-tools/assets/63237520/a9451b27-1f43-44eb-b3e4-9ecdd336cd26)

But it works when angle brackets are used:

![Screenshot of the same code with an angle bracket type cast](https://github.com/vuejs/language-tools/assets/63237520/13fdbcd5-90b5-4451-9e73-143e39da68f9)

## Reproduction
```vue
<div>
  <MyComponent :foo="test as string" :bar="1" />
</div>
```
In the `<script>`-tag:
```typescript
const test = "";
```

**Comment by so1ve** [comment] 2023-06-14 05:14
Duplicate of #2104

**Comment by evur** [comment] 2023-06-14 18:24
As it compiles and runs, syntax highlighting should not break. I consider this a bug.

**Comment by so1ve** [comment] 2023-06-14 23:28
I remembered Johnson said this is a vscode's textmate file's bug but I can't find it now

**Comment by evur** [comment] 2023-06-17 11:03
I just accidentally stumbled upon the issue you probably meant: #520
There are also a lot of other similar problems.
This needs to be fixed upstream.

**Comment by evur** [comment] 2023-06-17 11:07
The problem seems to only appear in combination with the extension. This needs to be investigated.
@johnsoncodehk

**Comment by so1ve** [comment] 2023-07-10 17:58
Duplicate of #520

**Closed by so1ve** 2023-07-10 17:58 UTC
Labels: duplicate, upstream
