### ISSUE TITLE
Formatting of Vue file constantly tabs away part of <table> element

### ISSUE THREAD

**Issue by webJose** [vuejs/language-tools#2478] opened 2023-03-02 02:43 UTC
Hello.  This one is a weird one.  The `<template>` section I have defines the table shown below.  Every time I format, the first 24 lines are tabbed away for no reason.  Every format request adds a new tabulation.

```html
<template>
        <table v-if="peopleStore.people" class="data people">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Birth Date</th>
                    <th>Country</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="p in peopleStore.people">
                    <td>{{ p.id }}</td>
                    <td>{{ p.first_name }}</td>
                    <td>{{ p.last_name }}</td>
                    <td>{{ p.email }}</td>
                    <td>{{ p.birth_date }}</td>
                    <td>
                        <img :src="flagsUrl({ countryCode: p.country_code })" :alt="p.country_code" crossorigin="anonymous"
                            class="flag" />&nbsp;
                        <span v-if="peopleStore.countries">{{ peopleStore.countries[p.country_code] }} ({{ p.country_code
                        }})</span>
                    <LoadingSpinner v-else text="Loading countries..." :block="false" />
                </td>
            </tr>
        </tbody>
    </table>
    <LoadingSpinner text="Loading people..." :block="true" v-else />
</template>
```

To be clear, from the `<table v-if...>` line to the `<LoadingSpinner v-else text...` line.

I can provide the complete .vue file if needed.

## UPDATE

It seems that it only happens when formatting on save.  If I format using Alt+Shift+F, then the behavior is not shown.

Also funning thing:  If I move `v-else` in the last `<LoadingSpiiner />` element to be the first attibute, then the behavior extends to that line, pretty much affecting all of the template contents.

**Comment by pierresaid** [comment] 2023-03-02 21:49
After testing different version of the vscode plugins this bug seems to have been introduced in the 1.1.0 version.

Duplicate of #2470

**Comment by johnsoncodehk** [comment] 2023-03-25 17:51
I can't reproduce this problem. Since you mentioned it only happens on save, do you have codeActionOnSave enabled? If so, does disabling it avoid the problem?

**Comment by webJose** [comment] 2023-04-05 16:46
Hi.  Try the Vue files in [this example](https://github.com/WJSoftware/wj-config/tree/main/examples/VueJS/v2.0.0).

**Comment by johnsoncodehk** [comment] 2023-04-15 02:16
@webJose thanks for the repro case, I have set`"editor.formatOnSave": true` and I try to save on all .vue file in that example, but still can't reproduce the problem. Can you confirm you have updated Volar to the latest version? (v1.2.0 / v1.3.14)

**Comment by webJose** [comment] 2023-04-15 14:24
Hi!  I have Volar 1.2.0.  In the example folder I provided, open `src/components/InsideConfig.vue`.  Now go to line 114:

```html
        <table className="data config">
```

Now add some spaces using the spacebar at the left.  Now Ctrl + S repeatedly:  The issue appears.

**Closed** 2023-04-17 11:24 UTC
Labels: need more info / repro
