### ISSUE TITLE
VS Code suggestion for custom components is broken

### ISSUE THREAD

**Issue by Archetipo95** [vuejs/language-tools#4146] opened 2024-03-22 12:05 UTC
This is the repo for reproduction: https://github.com/Archetipo95/test-formkit-theme

System: 
macOS 14.4 with M1 
Node v20
pnpm v8.15.5

As you see in the screenshot if I hover on my custom component `HelloWorld` these are the suggestions 
![Screenshot 2024-03-22 at 12 55 20](https://github.com/vuejs/language-tools/assets/11798239/eb807fa8-3adc-4abd-b6f6-21f7e27882fd)

But if I hover on a external component (FormKit in this case) it's working as intended
![Screenshot 2024-03-22 at 13 01 00](https://github.com/vuejs/language-tools/assets/11798239/ab08e040-cd81-4702-8ec9-e539b2d3e04e)

**Comment by Archetipo95** [comment] 2024-03-22 12:12
NB: I'm using export type in the props.ts file because it's a good way of sharing props types with the rest of the app.

**Comment by rijenkii** [comment] 2024-03-23 07:56
I'm pretty sure this is working as intended, as both of the types are correct.
It's just your component is defined using `script setup`, and `FormKitKitchenSink` is defined with `defineComponent`: https://github.com/formkit/formkit/blob/02cacdfb25e23001aeb8da9f85325c2e58329af7/packages/vue/src/FormKitKitchenSink.ts#L181

See [this playground](https://play.vuejs.org/#eNq1VE1v2zAM/SucTimQOGi2XTKvwNb1sGEfRRPsJCAwHCZTa0uaJKcpDP/3UZLtOelHTg0QWCSfKD6KTzX7pHWyq5DNWWpzI7QDi67SUGRy+5EzZzm74FKUWhkHl6rU57AxqgTOkmkw/W7OPhxgZoeYWcRwmU7jGZSRDIelLjKHZAGkMbfMSqRj/eecM5jG2JvJxH8BRtoojcY9nMVa5vAFN0KiN5RE6dLV6vf3xWr5oPGaoHapbirpRBmttI5pIJwzB+uMkFuq3buaizHUzRgqeSfVvYyG//fJf2knlLQ/xF5Q+Bl3kiTwHkpl0C99hsBhMgmkW6KzIdHZaaKzx0SPqPQmgCPyc1gEbpdUmDNV7pRpafqfwb+VMLieA8WwCzRdIwY9eMVmpNPBALAxjVqu5EZsk1urJM1jYMRZTplFgaZNzFnPlbOsKNT9t+DzRMadP/+D+d0T/lu79z7Org1aNDsayj7mMrNFF8NXi5+4p3UfLNW6Kgj9QvAGrSoqX2OEfa7kmsoe4EK1X4NK6GaW9mrvUNqOlC/UI5uA54wk45v6HPX/5b5N3oV9XDbUxV6TJxS9DuPUquJADiSE0RmNwktiXYtdWADUcTM0dD4FpjFyfLf9KzCo6skXpoZYWD9P0HRvSffOcIn7gCVkVhXhO9wxCj3y+rF9v440MlRIez3HomjdgZVv7YmODNswIM+af5/VyJs=) for a demo.

**Comment by davidmatter** [comment] 2024-08-07 07:15
Closing this one as many things have changed since 2.x. Feel free to create a new issue with a minimal reproduction if you're still having issues, thanks!

**Closed by davidmatter** 2024-08-07 07:15 UTC
