### ISSUE TITLE
Property '$t' does not exist on type 'Vue3Instance'

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/language-tools#3621] opened 2023-10-04 23:59 UTC
We have a Nuxt2/Vue2 project, but for some reason, in certain components, Volar reports the following error:
```
Property '$t' does not exist on type 'Vue3Instance<{}, Readonly<ExtractPropTypes<{}>>, Readonly<ExtractPropTypes<{}>>, {}, {}, true, ComponentOptionsBase<any, any, any, any, ... 5 more ..., any>> & ... 4 more ... & Readonly<...>'.ts(2339)
```

Why is it thinking it should be a `Vue3Instance`, when the project is vue 2?
It also doesn't happen everywhere, which is odd.

Weird error:
<img width="1079" alt="image" src="https://github.com/vuejs/language-tools/assets/1668207/1b89dd37-6b42-4a66-a152-05d29c3566ab">

This seems fine:
<img width="416" alt="image" src="https://github.com/vuejs/language-tools/assets/1668207/257b8910-bf65-4d97-ad5a-ed17a6dcb420">

**Comment by so1ve** [comment] 2023-10-05 02:27
Could you please provide a minimal reproduction?

**Comment by so1ve** [comment] 2023-10-05 09:25
Are you using vue 2.7? The exported type name from `vue` package is called `Vue3Instance` to tell users its began will be like vue 3, and this doesn't matter.

**Comment by rchl** [comment] 2023-10-05 10:00
Did you do this https://i18n.nuxtjs.org/v7/setup#typescript ?

**Comment by TheDutchCoder** [comment] 2023-10-05 10:29
We're not using Typescript and the Volat TS extension is disabled as well, this comes from the Volar Language Server one.

**Comment by so1ve** [comment] 2023-10-05 10:30
Please provide a minimal reproduction to help debug, thanks!

**Comment by rchl** [comment] 2023-10-05 10:35
It doesn't matter if you are using typescript or not you have to configure it as per nuxt-i18n module documentation.

**Comment by sebu10n** [comment] 2023-12-05 09:37
I came across the same error, also with nuxt2, vue2 and no ts.

It only occurs in .vue files without `<script>` tags. Even an empty `<script></script>` "resolves" the error.

I don't think that counts as a solution or is a `<script>` tag a must in .vue files?

**Comment by Suniron** [comment] 2024-05-13 08:54
Same problem in a Nuxt Bidge app

**Comment by davidmatter** [comment] 2024-08-05 20:59
Closing this one due to lack of a minimal reproduction. If this is still an issue in version 2.x, feel free to create a new issue with a minimal reproduction.

**Closed by davidmatter** 2024-08-05 20:59 UTC
Labels: need info
