### ISSUE TITLE
bug: parsed script tag's highlight isn't right 

### ISSUE THREAD

**Issue by tsukuha** [vuejs/language-tools#5092] opened 2024-12-27 13:53 UTC
### Vue - Official extension or vue-tsc version

2.2.0

### VSCode version

1.96.2 (Universal)

### Vue version

3.5.13

### TypeScript version

5.7.2

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 156.50 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.0 - ~/.nodenv/versions/21.6.0/bin/node
    Yarn: 1.22.22 - ~/.nodenv/versions/21.6.0/bin/yarn
    npm: 10.2.4 - ~/.nodenv/versions/21.6.0/bin/npm
    pnpm: 9.1.0 - ~/.nodenv/versions/21.6.0/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 17.6
```

### package.json dependencies

```json
{ 
  "dependencies": {
    "vue": "^3.5.13",
    "vue-tsc": "^2.2.0"
  }
}
```

### Steps to reproduce

It is parsed fail.
this file
```vue
<script setup lang="ts">
const a = {}

type ErrorPoint = {}
</script>

<template>
    <div></div>
</template>
```

### What is expected?

it cloud be parsed.

### What is actually happening?

it is bug about parsed script tag's highlight isn't right.

### Any additional comments?

![スクリーンショット 2024-12-27 22 57 04](https://github.com/user-attachments/assets/c5ad07d9-b90e-4738-8969-6c0241e6c21d)

**Comment by tsukuha** [comment] 2024-12-27 14:17
It is possible to refer to parsed semicolon.

This program is no problem.
```.vue
<script setup lang="ts">
const a = {};

type ErrorPoint = {};
</script>

<template>
    <div></div>
</template>
```

**Comment by KazariEX** [comment] 2024-12-27 14:40
Duplicate of #2060

**Closed by KazariEX** 2024-12-27 14:40 UTC
Labels: pending triage
