### ISSUE TITLE
vue-tsc checks are much slower than they used to be

### ISSUE THREAD

**Issue by k983551019** [vuejs/language-tools#4238] opened 2024-04-09 09:32 UTC
vue-tsc checks are much slower than they used to be

**Comment by MikeLP** [comment] 2024-04-11 01:33
I have the same issue.

**Comment by skywalker512** [comment] 2024-04-11 03:00
<img width="1688" alt="image" src="https://github.com/vuejs/language-tools/assets/12960906/d36b9701-7265-40ee-91a1-c6f5e6b1ea0e">

I have the same problem. After using --generateTrace, I found that there are still a lot of createSourceFile processes **（Occupied half of the time）** after checkfile is completed.

[trace2.json](https://github.com/vuejs/language-tools/files/14940691/trace2.json)

https://github.com/skywalker512/volar-2-reproduced

@johnsoncodehk

**Comment by MarcelKlammer** [comment] 2024-04-11 11:36
Same here. 2.0.7 was the last fast version, .10, .11, .12 all are extremely slow.

**Comment by smh000809** [comment] 2024-04-12 02:43
Version: 2.0.12, my project has 1029 files, and it took more than 30 minutes to execute `vue-tsc --build --force`

**Comment by so1ve** [comment] 2024-04-12 02:59
@smh000809 Should be resolved by https://github.com/vuejs/language-tools/pull/4245

**Closed** 2024-04-12 07:29 UTC
Labels: upstream, performance

**Comment by blake-newman** [comment] 2024-04-12 08:56
FYI we found the root cause of the issue and further PR to ammend to fix the cause:

https://github.com/vuejs/language-tools/pull/4260

Assuming its released thought i'd make you aware again incase there is another regression (shouldn't be tho).
