### ISSUE TITLE
template with v-for and index does not recognise :key="index"

### ISSUE THREAD

**Issue by jfrs** [vuejs/language-tools#3139] opened 2023-05-06 18:58 UTC
Doing something like this
```vue
  <template v-for="(test, index) in ['a', 'b', 'c']" :key="index">
    <div>{{ test }}</div>
  </template>
```
results in `'index' is declared but its value is never read.ts(6133)` and there is no IntelliSense on `:key="index"`.

Vue 3.2.47, Volar 1.6.4

**Comment by dockfries** [comment] 2023-05-08 05:59
```vue
<template>
  <div>
    <!-- similar intellisense problem -->
    <!-- Although v-for is recommended for evaluating attributes or variables -->
    <!-- v-for uses index and calls function, exception -->
    <div v-for="(item, index) in foo('bar')" :key="item.id"></div>
    <!-- v-for uses string array, exception -->
    <div v-for="(item, index) in ['foo']" :key="item.id"></div>
    <!-- v-for without index, normal -->
    <div v-for="item in foo('bar')" :key="item.id"></div>
    <div v-for="item in ['foo']" :key="item.id"></div>
  </div>
</template>
```

VSCode Version: 1.78.0, Volar 1.6.4

**Comment by NathanAP** [comment] 2023-06-27 19:37
Actually happening for me as well but only if I use `v-for` in a `template`.

```
<template
    v-for="(column, index) in myArray" // -> I get ts6133 in index
    :key="index" 
>
```

Other elements works fine.

**Comment by johnsoncodehk** [comment] 2023-06-28 03:34
Duplicate of #329

**Closed by johnsoncodehk** 2023-06-28 03:34 UTC
