### ISSUE TITLE
Extension produces nonsense errors at the end of Vue files

### ISSUE THREAD

**Issue by joshuagraber** [vuejs/language-tools#4002] opened 2024-03-06 02:07 UTC
This is happening in every single one of my Vue files since upgrading to `2.0.5`. 

Note in screenshot: 
- vars from the built components in my `dist` directory appearing in the source file.
- random router-link errors that seem to have nothing to do with the source file.
- All errors appearing at the final line of the component (line 70 in this case) at absurd column numbers.

 I've rolled back to `1.8.27` for now, as this is pretty annoying.

<img width="752" alt="Screenshot 2024-03-05 at 8 56 49 PM" src="https://github.com/vuejs/language-tools/assets/68428039/025a4f93-eab6-44a5-b00e-def3c7d86945">

**Comment by 2439340964** [comment] 2024-03-06 02:19
the same

**Comment by guozijia** [comment] 2024-03-06 02:20
Every huge update of the tool causes me torture...

**Comment by so1ve** [comment] 2024-03-06 04:10
Duplicate of #3942

**Closed by so1ve** 2024-03-06 04:10 UTC
