### ISSUE TITLE
Vue Language Server crashes

### ISSUE THREAD

**Issue by urbnjamesmi1** [vuejs/language-tools#4190] opened 2024-04-01 15:22 UTC
Type: <b>Bug</b>

Opening any .vue single file component files in VSCode results in these errors in the Vue Language Server's output:

```
Error - 11:16:07 AM] Server process exited with signal SIGBUS.
[Info  - 11:16:07 AM] Connection to server got closed. Server will restart.
true
[Error - 11:16:08 AM] Server process exited with signal SIGBUS.
[Info  - 11:16:08 AM] Connection to server got closed. Server will restart.
true
[Error - 11:16:09 AM] Server process exited with signal SIGBUS.
[Info  - 11:16:09 AM] Connection to server got closed. Server will restart.
true
[Error - 11:16:10 AM] Server process exited with signal SIGBUS.
[Info  - 11:16:10 AM] Connection to server got closed. Server will restart.
true
[Error - 11:16:11 AM] Server process exited with signal SIGBUS.
[Error - 11:16:11 AM] The Vue server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

Extension version: 2.0.8
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:57.520Z)
OS version: Darwin arm64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 12, 9|
|Memory (System)|32.00GB (0.99GB free)|
|Process Argv|--crash-reporter-id 6a45503c-100e-45a3-b62f-d6532e877cb7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:30996668
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by so1ve** [comment] 2024-04-02 04:04
Duplicate of #4130

**Closed by so1ve** 2024-04-02 04:04 UTC
