### ISSUE TITLE
TS inlay hints disappear in Vue files

### ISSUE THREAD

**Issue by stone-zeng** [vuejs/language-tools#4057] opened 2024-03-09 08:19 UTC
In `.vue` files, the TS inlay hints disapper inside the `<script setup lang="ts">`:

<img width="583" alt="Screenshot 2024-03-09 at 16 16 28" src="https://github.com/vuejs/language-tools/assets/18233088/7190d0b5-48bc-460b-93d2-743aadc6c27f">

But in `.ts` files they are correctly shown:

<img width="337" alt="Screenshot 2024-03-09 at 16 17 00" src="https://github.com/vuejs/language-tools/assets/18233088/5c25005c-77c7-47d8-91e6-4fc0c4431634">

Related settings:

```json
{
  "editor.inlayHints.enabled": "onUnlessPressed",
  "typescript.inlayHints.functionLikeReturnTypes.enabled": true,
  "typescript.inlayHints.parameterNames.enabled": "all",
  "typescript.inlayHints.parameterTypes.enabled": true,
  "typescript.inlayHints.propertyDeclarationTypes.enabled": true,
  "typescript.inlayHints.variableTypes.enabled": true,
  "vue.inlayHints.inlineHandlerLeading": true,
  "vue.inlayHints.missingProps": true,
  "vue.inlayHints.optionsWrapper": true,
  "vue.inlayHints.vBindShorthand": true,
}
```

Version info:

```
Version: 1.87.1 (Universal)
Commit: 1e790d77f81672c49be070e04474901747115651
Date: 2024-03-06T00:23:16.418Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0

Name: Vue - Official
Id: Vue.volar
Description: Language Support for Vue
Version: 2.0.6
Publisher: Vue
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Vue.volar
```

**Comment by rchl** [comment] 2024-03-09 08:22
For configuring javascript use equivalent `typescript.*` settings.

**Comment by stone-zeng** [comment] 2024-03-09 08:33
> For configuring javascript use equivalent `javascript.*` settings.

Is this a little bit confusing (since I'm using typescript here)?

**Comment by rchl** [comment] 2024-03-09 08:36
True. `lang=ts` script blocks should follow `typescript.*` settings.

**Comment by davidmatter** [comment] 2024-08-07 07:07
Closing this one as many things have changed since 2.x. Feel free to create a new issue with a minimal reproduction if you're still having issues, thanks!

**Closed by davidmatter** 2024-08-07 07:07 UTC
