### ISSUE TITLE
InstanceType doesn't work for components with generic

### ISSUE THREAD

**Issue by avinean** [vuejs/language-tools#3593] opened 2023-09-26 07:39 UTC
There are 2 components.
One with generic and another one without generic.

Some parent component tries to take an instance type.
The one with generic throws an error 
<img width="980" alt="image" src="https://github.com/vuejs/language-tools/assets/22274408/7cefac7e-efb3-4c32-81d3-3a3626aacbe7">

Reproduction
https://play.vuejs.org/#eNqdUk1P4zAQ/SsjX7oroaKKWzZUYlc9sAdAkBvmYCWTYEjGlu2URlX/O2MnLR/iQ+ISxfPeG7/xvK04s3a+7lFkIvel0zaAx9BbaBU1p1IEL8VSku6scQG24LCGHdTOdDBj2ezPAftnOjsB8+N4iG1nb+DFG3wxESSVhnwAzR9FJcJpvCU/n47FYDEP/DF1arJc/vr9XrL4RrMYRZLy43FIHkkc8XDcptbN/MEb4hfYSgKQomSFbtFd2qD5GikySEjEVNuap/+pFlyPR/t6eY/l4wf1B7+JNSmuHHp0a5TigAXlGgwjvLq5wA3/H8DOVH3L7C/Aa/Sm7aPHkfa3p4ptv+Ilt+dpAZqawq82Acnvh4pGI3OX+FLwOuJjfTb6i92T+UnSSdrxK+53/VWEoEFCp0s+FilQFdaa8MoZ6/PpBhVPGRTcNW1rpKw6HV4o3WqNFDK4tWpojaoyuEZVGWqHvFje7ZWHLU/uUtK+SXhMC5zF4HCWXjtCF4YMFA3cPUboc+dJ/UP3SfvRBLtnZ2c66w==

**Comment by so1ve** [comment] 2023-09-26 08:48
Duplicate of https://github.com/vuejs/language-tools/issues/3206

**Comment by so1ve** [comment] 2023-09-26 08:48
Solution: You should use `ComponentExposed` from the `vue-component-type-helpers` packages instead of TypeScript's built-in `ReturnType` or `InstanceType` utilities since volar defines generic components as functional components.

**Closed** 2023-09-26 08:48 UTC

**Comment by avinean** [comment] 2023-09-26 09:32
@so1ve 
This worths to be mentioned in docs

**Comment by CernyMatej** [comment] 2023-12-01 13:56
@so1ve Why not include the `ComponentExposed` type in vue? Since it already has some utility types, I don' think it would be a bad idea... https://vuejs.org/api/utility-types
