### ISSUE TITLE
开发微信小程序，view标签会类型错误提示

### ISSUE THREAD

**Issue by xy0908** [vuejs/language-tools#4390] opened 2024-05-16 03:55 UTC
![image](https://github.com/vuejs/language-tools/assets/81454465/d48b93ed-dac8-4934-a394-e72679488e16)

**Comment by so1ve** [comment] 2024-05-16 04:06
Duplicate of https://github.com/vuejs/language-tools/issues/4370

**Closed by so1ve** 2024-05-16 04:06 UTC

**Comment by xy0908** [comment] 2024-05-16 04:45
> #4370的重复[](https://github.com/vuejs/language-tools/issues/4370)

谢谢
