### ISSUE TITLE
some mistakes

### ISSUE THREAD

**Issue by wlonghaha** [vuejs/language-tools#4346] opened 2024-05-06 12:47 UTC
## Enviroment

`Operating System`: Windows 11

`VsCode`: 1.89.0

`Vue - Official`: 2.0.16

`Hybrid Mode`: true

## Create a `vue` + `typescript` project using `pnpm create vite`, and run the following test

> When typing a property with the mouse to the left of `/`, the `/` is lost.

![error-close-tag](https://github.com/vuejs/language-tools/assets/33210369/059f10c4-3e0b-4f9d-8a2f-d163ad3b9ca5)

> When the `script` block is in front of the `template` block, the highlighting is lost when code is folded, and normal when the `template` is in front of the `script`.

![miss-high-light](https://github.com/vuejs/language-tools/assets/33210369/54731680-4091-4bd9-9b8b-0325b74abef1)

> If you enter a variable prefix (e.g. `va`), you won't be prompted, only if you enter `val` in full.

![tips-lost](https://github.com/vuejs/language-tools/assets/33210369/9129127c-790d-445e-bfb9-62c7648d904f)

> When typing `import`, the code will be expanded automatically.

![auto-expand](https://github.com/vuejs/language-tools/assets/33210369/044b4f8d-74bc-4e9d-87a8-51a27747c861)

> When typing attributes (e.g. `vue directive`, `class`), the prompt is a bit slow, but it's better than the previous version.

![tips-alittle-slow](https://github.com/vuejs/language-tools/assets/33210369/26130618-19f4-4509-a31b-fee563c1c909)

> Create a new vue file, when lang is `tsx`, the code highlighting error, prompt is missing, execute `vscode reload window` after displaying normal !

![template-tsx-error](https://github.com/vuejs/language-tools/assets/33210369/d3f44e7b-3391-477f-8cf6-79bccb4338d1)

> Other errors (occasional)
  - template block collapsing code arrows missing
  - typescript service crashes

**Comment by so1ve** [comment] 2024-05-07 01:45
Duplicate of https://github.com/vuejs/language-tools/issues/4342

**Closed by so1ve** 2024-05-07 01:45 UTC
