### ISSUE TITLE
after v1.4, could not load typescript version

### ISSUE THREAD

**Issue by quachquesh** [vuejs/language-tools#2645] opened 2023-04-21 02:45 UTC
- Volar v1.2.0

![image](https://user-images.githubusercontent.com/39927333/233528200-292b1f77-c27f-4320-8a0b-c736b1ad12b1.png)

- After updating Volar v1.4.0

![image](https://user-images.githubusercontent.com/39927333/233528281-8444e2f6-1ef0-45ce-a4d6-934c124ea763.png)

![image](https://user-images.githubusercontent.com/39927333/233528320-fc381383-6621-4aa3-bc68-a4e2e2206ec7.png)

**Comment by johnsoncodehk** [comment] 2023-04-21 02:57
Duplicate of #2637

**Closed by johnsoncodehk** 2023-04-21 02:57 UTC
