### ISSUE TITLE
[VSCode syntax highlighting bug] Code coloring borks with the `satisfies` keyword

### ISSUE THREAD

**Issue by matthew-dean** [vuejs/language-tools#4027] opened 2024-03-06 16:19 UTC
<img width="756" alt="Screenshot 2024-03-06 at 8 14 51 AM" src="https://github.com/vuejs/language-tools/assets/414752/d292ad0c-b7ee-4db3-bbb9-7f508e32e4d4">

Small bug - while there are no TS issues or Vue issues with this code, if you use the `satisfies` keyword on an object, then the syntax coloring gets confused. In this case, you can see it tries to start the closing quote as a new starting quote? The opening span then gets inverted before the closing span. Eventually it resolves. (Sometimes it takes much longer in a file for coloring to get resolved.)

**Comment by ascott18** [comment] 2024-03-06 16:36
The `instanceof` operator also breaks coloring in the same way.

![image](https://github.com/vuejs/language-tools/assets/5017521/bd6d3337-3454-489f-82ad-41d0a5f3ecaf)

I've found that wrapping the expression in parens works around this (both `instanceof` and `satisfies`, but prettier does not allow parens to be used like that, so this workaround isn't really viable.

**Comment by webdevnerdstuff** [comment] 2024-03-06 18:03
Might be related to this issue I submitted. I first noticed it because my syntax highlighting was off.

https://github.com/vuejs/language-tools/issues/3999

**Comment by so1ve** [comment] 2024-03-07 04:26
Duplicate of #520

**Closed by so1ve** 2024-03-07 04:26 UTC
