### ISSUE TITLE
Server initialization failed.

### ISSUE THREAD

**Issue by phpmac** [vuejs/language-tools#2673] opened 2023-04-22 10:11 UTC
```
[Error - 18:10:50] Server initialization failed.
  Message: Request initialize failed with message: Can't find typescript.js or tsserverlibrary.js in /Users/a/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230421/extensions/node_modules/typescript/lib
  Code: -32603 
[Error - 18:10:50] Vue Semantic Server client: couldn't create connection to server.
  Message: Request initialize failed with message: Can't find typescript.js or tsserverlibrary.js in /Users/a/.vscode/extensions/ms-vscode.vscode-typescript-next-5.1.20230421/extensions/node_modules/typescript/lib
  Code: -32603 
```

**Comment by johnsoncodehk** [comment] 2023-04-22 10:13
Duplicate of #2663

**Closed by johnsoncodehk** 2023-04-22 10:13 UTC

**Comment by luckyonion** [comment] 2023-04-22 14:02
I also encountered this problem
