### ISSUE TITLE
[`vue-tsc`] `v1.6.0` throws error for `<component />`

### ISSUE THREAD

**Issue by Ky6uk** [vuejs/language-tools#2743] opened 2023-04-27 12:13 UTC
Code that throws the error:

```vue
<template>
  <component
    :is="as"
    :class="$style.component"
  >
    <slot />
  </component>
</template>
```

```ts
2:4 - error TS2345: Argument of type '{ class: string; }' is not assignable to parameter of type 'string & Record<string, unknown>'.
  Type '{ class: string; }' is not assignable to type 'string'.
```

`vue-tsc` `v1.2.0` handles it correctly.

**Comment by johnsoncodehk** [comment] 2023-04-27 12:14
Duplicate of #2725

**Closed by johnsoncodehk** 2023-04-27 12:14 UTC
