### ISSUE TITLE
Symbols view stopped working for js files

### ISSUE THREAD

**Issue by EzeFSpa** [vuejs/language-tools#2404] opened 2023-02-17 08:28 UTC
Until version 1.0.24 the symbols view in javascript babel files (.js) worked, but from later versions (up to and including v1.1.2) it stopped working.

(it works in files with vue extension and others except .js files)

**v1.1.2:**

![image](https://user-images.githubusercontent.com/16340729/219590641-29862761-0011-4250-9102-ed467d8b1392.png)
![image](https://user-images.githubusercontent.com/16340729/219590803-496269a6-81da-4421-afad-0a1c76494e11.png)

**version v1.0.24:**

![image](https://user-images.githubusercontent.com/16340729/219591383-fa3d7d3d-c1fd-435a-a1ed-c4cc7d98b5ff.png)
![image](https://user-images.githubusercontent.com/16340729/219591442-d6170304-7cc9-45a7-9e59-bb9d39847c4b.png)

**Comment by quadmachine** [comment] 2023-02-17 20:52
I can confirm I have the same issue since upgrading to 1.1.2. Issue is present in both JS and TS files. Seems to be working as expected in Vue files.

**Comment by johnsoncodehk** [comment] 2023-02-17 21:07
Thanks for the report, fixed by https://github.com/volarjs/plugins/commit/6c65de30a01b5f598c92acb74cd6e8708c3e5f13.

**Closed by johnsoncodehk** 2023-02-17 21:07 UTC
