### ISSUE TITLE
Syntax highlighting seems to break when using type assertions in props

### ISSUE THREAD

**Issue by KaiErikNiermann** [vuejs/language-tools#4927] opened 2024-10-16 00:44 UTC
### Vue - Official extension or vue-tsc version

v2.1.6

### VSCode version

1.94.2

### Vue version

^3.5.12

### TypeScript version

~5.5.4

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 19.74 GB / 31.05 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 22.9.0 - /home/linuxbrew/.linuxbrew/bin/node
    npm: 10.8.3 - /home/linuxbrew/.linuxbrew/bin/npm
    pnpm: 9.6.0 - /home/linuxbrew/.linuxbrew/bin/pnpm
```

### Steps to reproduce

With any component that takes props just try and use an `as` assertion. For example in the template project.
```vue
<script setup lang="ts">
import TheWelcome from '../components/TheWelcome.vue'
import HelloWorld from '../components/HelloWorld.vue'
</script>

<template>
  <main>
    <TheWelcome />
    <HelloWorld v-bind:msg="'Hello Vue 3 + Vite' as string" />
  </main>
</template>
```

### What is expected?

That syntax highlighting parses everything normally

### What is actually happening?

Syntax highlighting appears to break past the assertion.

![Screenshot 2024-10-16 024327](https://github.com/user-attachments/assets/69238e26-d3e3-4062-8b67-7e0f7ca2a61d)

### Any additional comments?

If this is a duplicate or I'm misusing something here then apologies.

**Comment by samiashi** [comment] 2024-10-16 05:22
+1

**Comment by KazariEX** [comment] 2024-10-16 05:25
Duplicate of #520

**Closed by KazariEX** 2024-10-16 05:25 UTC
Labels: pending triage
