### ISSUE TITLE
he Vue server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by JImumu** [vuejs/language-tools#4179] opened 2024-03-30 05:49 UTC
Trace - 13:49:12] Sending request 'initialize - (0)'.
[Trace - 13:49:12] Received response 'initialize - (0)' in 271ms.
[Trace - 13:49:12] Sending notification 'initialized'.
[Trace - 13:49:12] Sending notification 'textDocument/didOpen'.
[Trace - 13:49:12] Received request 'client/registerCapability - (0)'.
[Trace - 13:49:12] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
[Trace - 13:49:12] Received request 'workspace/configuration - (1)'.
[Trace - 13:49:12] Sending response 'workspace/configuration - (1)'. Processing request took 1ms
[Trace - 13:49:12] Received request 'client/registerCapability - (2)'.
[Trace - 13:49:12] Sending response 'client/registerCapability - (2)'. Processing request took 0ms
[Trace - 13:49:12] Sending notification 'workspace/didChangeWorkspaceFolders'.
[Trace - 13:49:12] Received request 'client/registerCapability - (3)'.
[Trace - 13:49:12] Sending response 'client/registerCapability - (3)'. Processing request took 0ms
[Trace - 13:49:12] Sending request 'textDocument/documentSymbol - (1)'.
[Trace - 13:49:12] Received notification 'textDocument/publishDiagnostics'.
[Trace - 13:49:12] Sending request 'textDocument/codeAction - (2)'.
[Trace - 13:49:13] Sending request 'textDocument/documentColor - (3)'.
[Trace - 13:49:13] Sending request 'textDocument/documentLink - (4)'.
[Trace - 13:49:13] Sending request 'textDocument/inlayHint - (5)'.
[Trace - 13:49:13] Sending request 'textDocument/semanticTokens/range - (6)'.
[Trace - 13:49:13] Sending request 'textDocument/documentSymbol - (7)'.
[Trace - 13:49:13] Sending request 'textDocument/foldingRange - (8)'.
[Trace - 13:49:13] Sending request 'textDocument/codeLens - (9)'.
[Error - 13:49:13] Server process exited with signal SIGBUS.

**Comment by WhaleFell** [comment] 2024-03-30 12:52
Me error:
```log
TypeError: Cannot read properties of undefined (reading 'getProjectVersion')
    at synchronizeHostData (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:142751:16)
    at Object.getProgram (d:\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:142923:7)
    at c:\Users\WhaleFall\.vscode\extensions\vue.volar-2.0.8\dist\server.js:989:23793
    at x (c:\Users\WhaleFall\.vscode\extensions\vue.volar-2.0.8\dist\server.js:989:24781)
    at async d (c:\Users\WhaleFall\.vscode\extensions\vue.volar-2.0.8\dist\server.js:989:23729)
    at async c:\Users\WhaleFall\.vscode\extensions\vue.volar-2.0.8\dist\server.js:3:55237
    at async hk (c:\Users\WhaleFall\.vscode\extensions\vue.volar-2.0.8\dist\server.js:3:18551)
    at async qj (c:\Users\WhaleFall\.vscode\extensions\vue.volar-2.0.8\dist\server.js:3:18009)
    at async f (c:\Users\WhaleFall\.vscode\extensions\vue.volar-2.0.8\dist\server.js:3:54856)
    at async Object.doValidation (c:\Users\WhaleFall\.vscode\extensions\vue.volar-2.0.8\dist\server.js:3:54576)

```

**Comment by so1ve** [comment] 2024-03-31 14:29
What's your typescript's version? @WhaleFell

**Comment by johnsoncodehk** [comment] 2024-03-31 22:35
Duplicate of #4130

**Closed by johnsoncodehk** 2024-03-31 22:35 UTC
