### ISSUE TITLE
TypeError: a is not a function

### ISSUE THREAD

**Issue by grofzer0** [vuejs/language-tools#4762] opened 2024-08-30 11:14 UTC
### Vue - Official extension or vue-tsc version

2.1.2

### VSCode version

1.92.2

### Vue version

3.4.15

### TypeScript version

5.5.4

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 22.01 GB / 31.09 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.12.0 - ~/.volta/tools/image/node/20.12.0/bin/node
    npm: 10.5.0 - ~/.volta/tools/image/node/20.12.0/bin/npm
  Browsers:
    Chrome: 128.0.6613.113
```

### Steps to reproduce

install extension

### What is expected?

to work cirrectly without errors

### What is actually happening?

showing an error on the output tab: 
[Vue Named Pipe Client] Deleting: /tmp/vue-named-pipe-2.1.2-configured-1
[Vue Named Pipe Client] Deleting: /tmp/vue-named-pipe-2.1.2-inferred-1
[Vue Named Pipe Client] Connected: /tmp/vue-named-pipe-2.1.2-configured-0 in 74ms
[Vue Named Pipe Client] Connected: /tmp/vue-named-pipe-2.1.2-inferred-0 in 70ms
[Vue Named Pipe Client] Ready: /tmp/vue-named-pipe-2.1.2-configured-0 in 75ms
[Vue Named Pipe Client] Ready: /tmp/vue-named-pipe-2.1.2-inferred-0 in 71ms
[Vue Named Pipe Client] Connected: /tmp/vue-named-pipe-2.1.2-inferred-1 in 3ms
[Vue Named Pipe Client] Ready: /tmp/vue-named-pipe-2.1.2-inferred-1 in 5ms
[Vue Named Pipe Client] Connected: /tmp/vue-named-pipe-2.1.2-configured-1 in 1ms
[Vue Named Pipe Client] Ready: /tmp/vue-named-pipe-2.1.2-configured-1 in 2ms
TypeError: a is not a function
    at fwe (/home/kornel/.vscode/extensions/vue.volar-2.1.2/dist/server.js:220:4828)
    at fwe.next (<anonymous>)
    at hB (/home/kornel/.vscode/extensions/vue.volar-2.1.2/dist/server.js:220:2167)
    at hB.next (<anonymous>)
    at rB (/home/kornel/.vscode/extensions/vue.volar-2.1.2/dist/server.js:220:1243)
    at rB.next (<anonymous>)
    at ki (/home/kornel/.vscode/extensions/vue.volar-2.1.2/dist/server.js:219:5773)
    at ki.next (<anonymous>)
    at EA (/home/kornel/.vscode/extensions/vue.volar-2.1.2/dist/server.js:219:4566)
    at EA.next (<anonymous>)

**Comment by KazariEX** [comment] 2024-08-30 11:46
duplicate of #4759

**Closed by KazariEX** 2024-08-30 11:46 UTC
Labels: pending triage
