### ISSUE TITLE
vue语法不解析，不太稳定，影响开发体验

### ISSUE THREAD

**Issue by zll11** [vuejs/language-tools#4684] opened 2024-08-13 03:23 UTC
### Vue - Official extension or vue-tsc version

2.0.28

### VSCode version

new

### Vue version

3

### TypeScript version

new

### System Info

```shell
vue语法不解析，不太稳定，影响开发体验
```

### Steps to reproduce

1

### What is expected?

1

### What is actually happening?

![11723519164_ pic](https://github.com/user-attachments/assets/ef504d4e-f712-4125-a792-7f418b9baf1a)

**Comment by KazariEX** [comment] 2024-08-13 03:36
Duplicate of #4665

**Closed** 2024-08-13 03:58 UTC
Labels: duplicate
