### ISSUE TITLE
<template> not getting intellisense help when used on :key attribute in a v-for

### ISSUE THREAD

**Issue by robokozo** [vuejs/language-tools#2485] opened 2023-03-03 14:48 UTC
As instructed [here](https://vuejs.org/guide/essentials/list.html#maintaining-state-with-key), I lose intellisense on the `:key` attribute when I use the `<template>` tag in conjunction with `v-for`

When used with a template:
![image](https://user-images.githubusercontent.com/1719221/222750105-6b0f3a2b-985a-4dc4-80a2-1eb917c273d5.png)

When used on a v-for with another element: 
![image](https://user-images.githubusercontent.com/1719221/222750339-997266d9-f90c-4b35-ad1b-0f5dc64ae193.png)

**Comment by johnsoncodehk** [comment] 2023-03-29 06:47
Duplicate of #329

**Closed by johnsoncodehk** 2023-03-29 06:47 UTC
