### ISSUE TITLE
Cannot use `InstanceType<typeof Comp<any>>>` on generic components

### ISSUE THREAD

**Issue by pikax** [vuejs/language-tools#3206] opened 2023-05-19 16:40 UTC
Since the push of adding generic components on Vue 3.3.0, we don't seem able to get the `InstanceType` aka `public instance` anymore.

```html
<script setup lang="ts" generic="T">
const props = withDefaults(defineProps<{
	value?: T | null;
	list: T[];
}>(), {
	value: null,
});
</script>

<template>
    <select>
       // code
    </select>
</template>
```

```html
<script lang="ts">
import MyComp from './MyComp.vue'

// This has error
const el = ref<null | InstanceType<typeof MyComp<any>>>( null )

</script>
<template>
   <my-comp ref="el" list="[]"/>
</template>
```

**Comment by zf1998** [comment] 2023-05-25 02:17
I aslo!!!

**Comment by johnsoncodehk** [comment] 2023-05-25 19:23
When using `generic`, Volar defines the component as a functional component, so you should use `ReturnType` instead of `InstanceType`:

```ts
import MyComp from './MyComp.vue'

const el = ref<null | ReturnType<typeof MyComp<any>>>( null )
```

Another option is to use `ComponentExposed` from [`vue-component-type-helpers`](https://github.com/vuejs/language-tools/tree/master/packages/vue-component-type-helpers):

```ts
import MyComp from './MyComp.vue'
import type { ComponentExposed } from 'vue-component-type-helpers'

const el = ref<null | ComponentExposed<typeof MyComp<any>>>( null )
```

**Comment by varlamov88** [comment] 2023-05-29 09:22
Vue 3.3.4
Volar 1.7.8
Without generic and with InstanceType
![Screenshot_2](https://github.com/vuejs/language-tools/assets/10114765/9d1bdde8-3ce2-4f7c-b631-344ff3b84150)

With generic and ReturnType/ComponentExposed
![Screenshot_1](https://github.com/vuejs/language-tools/assets/10114765/88b50d6c-c815-423d-aecf-a20ce4422e16)

**Comment by oddcelot** [comment] 2023-06-21 11:28
@varlamov88 Depends on how badly you need it, but I deconstructed the type into a new one based on `DefineComponent` just to get it to work at the moment over here https://github.com/vuejs/core/issues/8373#issuecomment-1597800113

**Comment by johnsoncodehk** [comment] 2023-06-23 05:02
I can confirm that `ComponentExposed` is not working, and `ReturnType` not working is correct behavior.

**Comment by satrong** [comment] 2023-07-07 02:10
This is my temporary solution, but it's not perfect😂. I'm looking forward to the official release of the final solution.
```ts
import { type DefineComponent } from 'vue'

type ComponentInstance<T> = T extends new (...args: any[]) => infer R
  ? InstanceType<R>
  : T extends (...args: any[]) => infer R
    ? R extends { __ctx?: infer K }
      ? Exclude<K, void> extends { expose: (...args: infer K) => void }
        ? K[0] & InstanceType<DefineComponent>
        : any
      : any
    : any
```

**Comment by Bernard-Borg** [comment] 2023-07-15 17:57
bump - need this please

**Comment by so1ve** [comment] 2023-07-15 17:58
@Bernard-Borg #3271, please be patient :)

**Comment by f3oall** [comment] 2023-09-05 10:27
Hey guys, it's really blocking the use of generic components, any chance that it will be fixed soon?

Thanks for the great tools btw :)

**Comment by so1ve** [comment] 2023-09-06 06:46
Hey folks 👋 Could you please checkout #3536? Does it work for you?

**Closed** 2023-09-06 07:46 UTC
Labels: bug

**Comment by joris-gallot** [comment] 2023-11-28 15:10
Hey! how I'm supposed to do, when I want for example `$el` from a generic component?

**Comment by CernyMatej** [comment] 2023-12-01 13:57
For some reason, I am getting `{}` type from the `ComponentExposed` utility. Have any of you encountered something similar?

**Comment by szulcus** [comment] 2024-02-05 11:12
Why this issue is closed?

**Comment by so1ve** [comment] 2024-02-06 02:22
https://github.com/vuejs/language-tools/issues/3206#issuecomment-1707764955

**Comment by arthaali** [comment] 2024-02-15 16:22
> ```ts
> ComponentExposed
> ```

Hello, I am still facing this issue and the fix is not really clear.
the link you provided does not exist and I can't find how to use `ComponentExposed`
can you please report the fix?
Can you maybe support here? @so1ve 
Thank you

**Comment by so1ve** [comment] 2024-02-16 05:44
Install `vue-component-type-helpers`, `import { ComponentExposed } from 'vue-component-type-helpers'`, then replace `InstanceType` with `ComponenttExposed`.

**Comment by danielrw7** [comment] 2024-02-16 19:47
I am using VS code, Volar 1.8.27 (with takeover), Vue 3.4.19. Here's a modified version of `ComponentExposed` that works for me for generic components:

```ts
import type { ShallowUnwrapRef } from 'vue'

type ComponentExposed<T> =
    T extends new () => infer E ? E :
    T extends (props: any, ctx: any, expose: ((exposed: ShallowUnwrapRef<infer E>) => void) | undefined, ...args: any) => any ? NonNullable<E> :
    {};
```

The reason why the original doesn't seem to be working for me is that the second argument of the functional component, `ctx`, doesn't have the expected `expose` property, which is instead found as its own 3rd argument

[Original definition](https://github.com/vuejs/language-tools/blob/abacb375557b7a736d975cc44fb7a3e2622e1cca/packages/component-type-helpers/index.js#L24-L27):
```ts
export type ComponentExposed<T> =
	T extends new () => infer E ? E :
	T extends (props: any, ctx: { expose(exposed: infer E): any; }, ...args: any) => any ? NonNullable<E> :
	{};
```

Here's an example generic component:
```vue
<script setup lang="ts" generic="T">
// ExampleGenericComponent.vue
const modelValue = defineModel<T>()

defineExpose({
    getModelValue() {
        return modelValue.value
    },
})
</script>
```

If I inspect its arguments, here is what I find:
```vue
<script setup lang="ts">
// ParentComponent.vue
import ExampleGenericComponent from './ExampleGenericComponent.vue';

type Param0 = Parameters<typeof ExampleGenericComponent<number>>[0]
type Param1 = Parameters<typeof ExampleGenericComponent<number>>[1]
type Param2 = Parameters<typeof ExampleGenericComponent<number>>[2]
type FullParams = Parameters<typeof ExampleGenericComponent<number>>

/*
When hovering over types:

type Param0 = {
    modelValue?: number | undefined;
} & VNodeProps & AllowedComponentProps & ComponentCustomProps

type Param1 = {
    attrs: any;
    emit: any;
    slots: {};
} | undefined

type Param2 = ((exposed: ShallowUnwrapRef<{
    getModelValue(): number | undefined;
}>) => void) | undefined

type FullParams = [__VLS_props: {
    modelValue?: number | undefined;
} & VNodeProps & AllowedComponentProps & ComponentCustomProps, __VLS_ctx?: {
    attrs: any;
    emit: any;
    slots: {};
} | undefined, __VLS_expose?: ((exposed: ShallowUnwrapRef<...>) => void) | undefined, __VLS_setup?: Promise<...> | undefined]
*/
</script>
```

**Comment by szulcus** [comment] 2024-02-27 11:33
@so1ve I have wrong `vuelidate` type. It should be available without `.value` 🤔

**Comment by LeoKun1231** [comment] 2024-04-07 16:11
Looking forward to your update

**Comment by mauroviniciussilva** [comment] 2024-06-25 11:30
> This is my temporary solution, but it's not perfect😂. I'm looking forward to the official release of the final solution.
> 
> ```ts
> import { type DefineComponent } from 'vue'
> import MyComp from './MyComp.vue'
> 
> type ComponentInstance<T> = T extends new (...args: any[]) => infer R
>   ? R
>   : T extends (...args: any[]) => infer R
>     ? R extends { __ctx?: infer K }
>       ? Exclude<K, void> extends { expose: (...args: infer K) => void }
>         ? K[0] & InstanceType<DefineComponent>
>         : any
>       : any
>     : any
> 
> const el = ref<null | ComponentInstance<typeof MyComp<any>>>(null)
> ```

I've just tried this solution and for some reason Typescript were complaning about `K` being duplicated, so I had to use this way:

```ts
import { type DefineComponent } from 'vue'

export type GenericComponentInstance<T> = T extends new (...args: any[]) => infer R
  ? R
  : T extends (...args: any[]) => infer R
    ? R extends { __ctx?: infer K }
      ? Exclude<K, void> extends { expose: (...args: infer Y) => void }
        ? Y[0] & InstanceType<DefineComponent>
        : any
      : any
    : any;
```

**Comment by TheDutchCoder** [comment] 2024-07-30 12:47
`ComponentExposed` still doesn't work properly. I have opened an issue on the Vue repo for this, unless it's purely a language tool issue, then maybe it should be re-opened here? https://github.com/vuejs/core/issues/11459

Reproduction: https://play.vuejs.org/#eNqFU01v2zAM/SuEMCApkNjY2pPnBNiGHDagW9HlVhVDYNOOOlkSJNlL4Pm/j5LztWJrDwZIPvLxkZR79sGYpGuRZSx3hRXGg0PfGpAbVS84846zJVeiMdp66MFiNYN7rGCAyuoGJlQ7OeG3+0+6MQckSUc30J9T/N4g8QRAK1R+tTPaYXnJNy+O4Dxkz7coDVo3eX+hQ6tb3Sr/d2HI4KrQynlo9qQyC1Lz573ywKqrg9ol/AbVSrmERZhuGuyrwHNqMZ1ewWIJPVcAgVxLTKSup7FF0m1ki8kbDEUDfXk67pG2Ro7HxsiNR/IA8sN+qA2tNpZzBlmlNbkPPYgyg7cwzGi+YL6D4ZHwlGrz9IKIzegsJKQSdfLktKLbRW2chcUJifab8YKEcpaNqgO2kVL/+hJj3rY4O8aLLRY//xF/crsQ4+zOokPbIWcnzG9sjX6EV9+/4o7sE9jospWU/QJ4j7TENmgc0z62qiTZF3lR7ed4baHqtVvtPCp3HCoIDZlDzOeMbh8W+7/Rz3Kvk5tYR6eiLZ7f50vPH2pUaEVB7jr+DCVWQuGd1cblsQcdMIP1wyOxLqevPIFSdNEg00A3r7QNbbY0JAgVmKhF38MYGYY8NWNdOhY+fwg/OvozaGAagGZLrm/Y8AeQ1kpf

**Comment by so1ve** [comment] 2024-07-31 12:54
`ComponentExposed` is not suitable for you usecase. It is used to get things exposed by `defineExposed`.

**Comment by TheDutchCoder** [comment] 2024-07-31 13:08
> `ComponentExposed` is not suitable for you usecase. It is used to get things exposed by `defineExposed`.

Am I not running into the same issue though? IntstanceType not working with components that have a generic?
It'd also what you recommended here: https://github.com/vuejs/language-tools/issues/3206#issuecomment-1707764955

**Comment by ethanchristensen01** [comment] 2024-09-20 23:43
> Another option is to use `ComponentExposed` from [`vue-component-type-helpers`](https://github.com/vuejs/language-tools/tree/master/packages/vue-component-type-helpers)


For anybody checking this issue in the future, it's worth noting that this URL is incorrect. The correct URL is https://github.com/vuejs/language-tools/tree/master/packages/component-type-helpers
