### ISSUE TITLE
:bug: Volar format vue app error on tailwindcss breakpoint classes

### ISSUE THREAD

**Issue by forinda** [vuejs/language-tools#2484] opened 2023-03-03 12:57 UTC
## Expected
The formatter should format these tailwind classes without changing how they are structured
![Screenshot from 2023-03-03 15-46-08](https://user-images.githubusercontent.com/55891685/222723888-6941b233-68f4-4c6c-b1a0-3ff7676297fd.png)
Outcome after formatting with volar on line `102`
![Screenshot from 2023-03-03 15-47-38](https://user-images.githubusercontent.com/55891685/222724609-9d3bd5dd-e86c-4574-9e8f-079e60d0f22a.png)
# component not rendering on browser afterwards
![Screenshot from 2023-03-03 15-53-52](https://user-images.githubusercontent.com/55891685/222725285-7112d138-44b1-47d1-8b6a-e660cf0d28f5.png)

**Comment by boussadjra** [comment] 2023-03-24 21:18
I've the same issue

**Comment by johnsoncodehk** [comment] 2023-04-14 23:10
Duplicate of #1448

**Closed by johnsoncodehk** 2023-04-14 23:10 UTC
