### ISSUE TITLE
TS Language Server Crashes

### ISSUE THREAD

**Issue by nzamski** [vuejs/language-tools#4055] opened 2024-03-08 18:32 UTC
Type: <b>Bug</b>

The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: Vue.volar. Please try disabling these extensions before filing an issue against VS Code.

Extension version: 2.0.6
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:51.279Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.69GB free)|
|Process Argv|--crash-reporter-id 09a2a0f1-b696-4dbe-8c52-e7c49f11eaee|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30968132
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
8f97e687:30977000
dsvsc020:30976470

```

</details>

**Comment by jiacheng-coder** [comment] 2024-03-09 02:41
use 18.x plug-in
<img width="596" alt="image" src="https://github.com/vuejs/language-tools/assets/105594189/139024b0-b837-4374-8521-b94eb3ecddc1">

**Comment by viktorkrepak** [comment] 2024-03-13 21:49
Have the same issues, can't use any versions starting from 2 major. Reverted setup to 1.8.27 + old TS plugin, otherwise It's impossible to work with vue projects

**Comment by mahmoudsaeed** [comment] 2024-03-18 10:33
+1 I also encounter this issue with the new Vue.volar extension.

**Comment by zWingz** [comment] 2024-03-19 09:00
Have the same issues at 2.0.x. But work on 1.8.27

**Comment by davidmatter** [comment] 2024-03-19 11:25
Guys, seriously, have you tried using vscode insiders edition? https://code.visualstudio.com/insiders/

**Comment by viktorkrepak** [comment] 2024-03-19 11:49
@davidmatter, if you propose to use the insiders edition, does it mean there is a problem in the VS code itself? if so I can just wait the next release, because I prefer using stable edition instead of LTS insiders with possible other buggies.
Thanks for your answer!

**Comment by zWingz** [comment] 2024-03-19 11:53
> Guys, seriously, have you tried using vscode insiders edition?

I won't switch to the Insiders version for this bugs. So I prefer to install 1.8.27.  
Thanks for your answer!

**Comment by davidmatter** [comment] 2024-03-19 12:22
@viktorkrepak yeah it's probably an issue with a specific Node version shipped with the current version of vscode. I'm running on insiders with vue-official 2 without any problems 🙂

**Comment by gaterking** [comment] 2024-03-21 07:39
2.0.7
not fix

**Comment by so1ve** [comment] 2024-03-21 10:12
Duplicate of https://github.com/vuejs/language-tools/issues/3962

**Closed by so1ve** 2024-03-21 10:12 UTC
