### ISSUE TITLE
How do I support Stylus?

### ISSUE THREAD

**Issue by q77763429** [vuejs/language-tools#4330] opened 2024-04-30 11:08 UTC
If both less and scss are supported, why not stylus? No code prompts either? How can I support Stylus?
<img width="292" alt="image" src="https://github.com/vuejs/language-tools/assets/26376628/7620b185-1571-4eaa-8e1d-c0c74aef9895">
<img width="374" alt="image" src="https://github.com/vuejs/language-tools/assets/26376628/2807abda-fb7e-471c-be03-ca14d22a4799">

**Comment by RayGuo-ergou** [comment] 2024-04-30 12:05
https://github.com/vuejs/language-tools/blob/997bdad50e29dac0ba9399e395f4c520986dc9e2/packages/language-service/scripts/update-html-data.js#L178-L183

It's not supported at the moment I am afraid. 

Found a "dead" PR related to this from seven years ago: https://github.com/stylus/stylus/issues/2307

From what I can see I guess it would not be supported any time soon unfortunately.

**Comment by johnsoncodehk** [comment] 2024-05-14 05:15
Duplicate of https://github.com/volarjs/services/issues/14

**Closed by johnsoncodehk** 2024-05-14 05:15 UTC
