### ISSUE TITLE
Syntax highlighting, intellisense, go-to-definiton...etc stop working and extension crashes after some time

### ISSUE THREAD

**Issue by douglasg14b** [vuejs/language-tools#4122] opened 2024-03-20 05:46 UTC
- `v 2.0.6`
- `script-setup, typescript`

It seems that the volar extension has recently become rather fragile, it crashes regularly now. Go to definition, autocompletion, syntax highlighting...etc all stop functioning after some time.

> service 5 crashed on file:///[SNIP]/client/src/features/campaigns/components/CreateCampaignFinalize.vue?virtualCodeId=template SyntaxError: Unexpected non-whitespace character after JSON at position 518 (line 18 column 3)
    at JSON.parse (<anonymous>)
    at IZ (c:\Users\Douglas\.vscode\extensions\vue.volar-2.0.6\dist\server.js:10029:9539)
    at Wu (c:\Users\Douglas\.vscode\extensions\vue.volar-2.0.6\dist\server.js:10029:9233)
    at Object.YNe [as getComponentNames] (c:\Users\Douglas\.vscode\extensions\vue.volar-2.0.6\dist\server.js:10029:9052)
    at s (c:\Users\Douglas\.vscode\extensions\vue.volar-2.0.6\dist\server.js:469:18792)
    at J7 (c:\Users\Douglas\.vscode\extensions\vue.volar-2.0.6\dist\server.js:469:18559)
    at Mw (c:\Users\Douglas\.vscode\extensions\vue.volar-2.0.6\dist\server.js:469:18042)
    at Object.provideInlayHints (c:\Users\Douglas\.vscode\extensions\vue.volar-2.0.6\dist\server.js:10027:992)
    at async c:\Users\Douglas\.vscode\extensions\vue.volar-2.0.6\dist\server.js:19:610
    at async ck (c:\Users\Douglas\.vscode\extensions\vue.volar-2.0.6\dist\server.js:3:18551)

This happens **regardless of the component I'm in**, the component name int he error is whichever one I'm looking at.

Even if I remove the entirety of my template contents so it's just a `div` the error persists. If I remove all my code, same deal.

After some time the extension just stops working entirely and I have to reload vscode.

**Comment by douglasg14b** [comment] 2024-03-20 05:51
Seems related to #4060 

![image](https://github.com/vuejs/language-tools/assets/1400380/d405bde7-09d5-483a-a302-784998505ade)

**Comment by so1ve** [comment] 2024-03-20 08:48
Duplicate of https://github.com/vuejs/language-tools/issues/4060

**Closed by so1ve** 2024-03-20 08:48 UTC
