### ISSUE TITLE
SASS variables not accessible via Intellisense

### ISSUE THREAD

**Issue by ennioVisco** [vuejs/language-tools#3263] opened 2023-06-09 07:54 UTC
When importing sass variables from external modules, they are not autocompleted.
<img width="490" alt="image" src="https://github.com/vuejs/language-tools/assets/740025/f75d398d-fbd8-4a2c-bd57-22f245eedbcb">

In contrast, this works for the local ones:
<img width="489" alt="image" src="https://github.com/vuejs/language-tools/assets/740025/0684afdf-a97d-4a08-b3cf-b05556c55069">

**Comment by so1ve** [comment] 2023-11-21 08:30
More info: this problem is caused by Volar isn't resolving `@` alias correctly

**Comment by johnsoncodehk** [comment] 2024-05-13 18:57
Please track https://github.com/microsoft/vscode-css-languageservice/issues/156

**Closed by johnsoncodehk** 2024-05-13 18:57 UTC
