### ISSUE TITLE
VSCode "occurrencesHighlight" feature doesn't work for .vue files (regression)

### ISSUE THREAD

**Issue by alexchexes** [vuejs/language-tools#4895] opened 2024-09-28 13:06 UTC
### Vue - Official extension or vue-tsc version

Vue - Official extension

### VSCode version

1.93.1

### Vue version

3.4.29

### TypeScript version

0

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 42.38 GB / 63.67 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.11.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
```

### package.json dependencies

```json
{
  "dependencies": {
    "vue": "^3.4.29"
  },
  "devDependencies": {
    "@rushstack/eslint-patch": "^1.8.0",
    "@vitejs/plugin-vue": "^5.0.5",
    "@vue/eslint-config-prettier": "^9.0.0",
    "eslint": "^8.57.0",
    "eslint-plugin-vue": "^9.23.0",
    "prettier": "^3.2.5",
    "vite": "^5.3.1"
  }
}
```

### Steps to reproduce

1. Create a new Vue project with `pnpm create vue@latest`
2. Observe that the `editor.occurrencesHighlight` VSCode feature in VSCode does not work in `.vue` files

### What is expected?

Symbols should be highlighted like this:

![2024-09-28--13-46-27--498](https://github.com/user-attachments/assets/2a67f233-77a5-4674-9331-8e3ca4a793ea)

### What is actually happening?

Symbols are not highlighted:

![2024-09-28--13-46-19--966](https://github.com/user-attachments/assets/0c39c663-a515-40b5-8967-c1c198f7a2fa)

### Any additional comments?

This feature worked fine in late 2023 with the then-current and officially recommended Vue extension. Unfortunately, I can't pinpoint the exact version of the extension that introduced this regression.

I haven’t used Vue for a while, but now that I’m returning to it, I’ve noticed this essential feature isn’t functioning anymore. If no fix exists yet, I’m asking the community to suggest the latest version of the extension where this feature was still working, so I (and others) can roll back until a solution is found. Thank you!

**Comment by KazariEX** [comment] 2024-09-28 15:22
Duplicate of #4850

**Closed by KazariEX** 2024-09-28 15:22 UTC
Labels: pending triage
