### ISSUE TITLE
Syntax highlighting is broken with `type` variable in v-for

### ISSUE THREAD

**Issue by elfjes** [vuejs/language-tools#2560] opened 2023-03-30 06:31 UTC
When using a `v-for` and calling the variable `type`, syntax highlighting is broken:
![image](https://user-images.githubusercontent.com/7681923/228748591-635af5d1-02aa-4c43-8d5d-c5c36cf55574.png)

Reproduction

```
<template>
  <div v-for="type in someArray"></div>
</template>
<script setup>
  const someArray = []
</script>
```

**Comment by so1ve** [comment] 2023-04-02 02:16
Put script block above template block and use a type alias (type Foo = {}) also breaks

**Comment by johnsoncodehk** [comment] 2023-04-14 23:58
Duplicate of #1290

**Closed by johnsoncodehk** 2023-04-14 23:58 UTC
