### ISSUE TITLE
扩展老是崩溃

### ISSUE THREAD

**Issue by 6543qq** [vuejs/language-tools#3660] opened 2023-10-14 07:40 UTC
Type: <b>Bug</b>

win10 64位

Extension version: 1.8.19
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (3.89GB free)|
|Process Argv|--crash-reporter-id add8841b-4627-4a3a-a85b-51e13f3545f0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
962ge761:30841074
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pythonregdiag:30859691

```

</details>
`const actionAPI={//默认给予每个参数一个空值，还有一个对象要给匹配模式
    apiurl:"../../yijida/testphp/get_json.php",  //此为测试链接
    apiupload:"../../yijida/aipublic/uploader_sys.php",
    api17track:"https://res.17track.net/asset/carrier/info/apicarrier.all.json",//17track 运输商 编码
    apicomserial:"http://127.0.0.1:8999/read/", //本地读取电子称com串口服务地址
    apihttpwlh:"http://127.0.0.1:8777/read/", //本地读取电子称com串口服务地址
    api_public:"../../yijida/aiadmin/main.php",  //社区 API 请求参数
    api_wuliu_excel_moban:"../../yijida/aiservice/jiyun/api/excel/moban.xls",  //社区 API 请求参数
    api_plugin_print:"../plugin/print/CLodop_Setup_for_Win64NT_6.572EN.zip",
    api_wuliu_excel_upload:"../../yijida/aipublic/upload_excel.php",
    api_BI:"../bi/index.html",  //BI大数据

    daofupkg_status:[   
           {val: '0',label:'未处理'},
           {val: '1',label:'直接拒签处理'},
           {val: '2',label:'顾客通知拒签'},
           {val: '3',label:'未联系到顾客拒签'},
           {val: '4',label:'顾客超时未支付拒签'},
           {val: '5',label:'顾客已支付待入库'},
           {val: '6',label:'已支付快递员待入库'},
           {val: '7',label:'已入库'},
         ],  
   zhifuValue:[             //------------------这里的网站要从后台fetch异步加载
           {val: '0',label:'未支付'},
           {val: '1',label:'微信在线支付'},
           {val: '2',label:'支付宝在线支付'},
           {val: '3',label:'淘宝天猫支付'},
           {val: '4',label:'拼多多订单支付'},
           {val: '5',label:'微信转账支付'},
           {val: '6',label:'支付宝转账支付'},
           {val: '7',label:'银行卡支付'},
        ],
   aiuser_come : [             //------------------这里的网站要从后台fetch异步加载
           {val: '1',label:'淘宝'},
           {val: '2',label:'微信'},
           {val: '3',label:'天猫'},
           {val: '4',label:'拼多多'},
           {val: '5',label:'抖音'},
           {val: '6',label:'小红书'},
           {val: '7',label:'今日头条'},
           {val: '8',label:'百度'},
           {val: '9',label:'360'},
           {val: '10',label:'谷歌'},
           {val: '11',label:'脸书'},
           {val: '12',label:'推特'},
        ],
    action:{ //对应 API接口模块的逻辑
            "getlist":['page','pagesize'], //对应函数api发起请求的参数,数组长度，对应函数形参的个数
            "ailogin":['aiuser','aipassword'], //登录模块
            "setSystem":['make'], //make:{'addgroup','grouplist'}  //系统权限配置模块
            },
     set:{//必须参数，必须传值 参数a
     "ailogin":['aiuser','aipassword'], //公共登录模块 //   Object.keys(actionAPI['set]["ailogin"]).length === 0;  判断对象是否为空
     "exit":[],
     "checkstatus":[],
     "groupstatus":[],
     "jiyun":{
        "action":{ //必须参数，必须传值 参数 b
                "setSystem":{
                      "make":{ //必须参数，必须传值 参数 c
                           "editgroup":[],
                           "addgroup":[],
                           "get_level_or_id":[],
                           "aisaferead":[],
                           "wxformread":[],
                           "wxv3read":[],
                           "albabaread":[],
                           "emailformread":[],
                           "aikfpw_r":[],
                           "aielse_r":[],
                           "getouttime":['type','store_type','noman_time',' in_out','weight_price','time_price','account'],
                           "getconfig":[],
                           "countscheme":[],
                           "allcountry":[],
                           "groupstatus":[],
                           "addeditaccount":['id','account','accounttype','accountprice'],
                           "grouplist":['page','pagesize'],
                           "adminlist":['page','pagesize'],
                           "countrygrouplist":['page','pagesize'],
                           "accountlist":['page','pagesize'],
                           "companylist":['page','pagesize'],
                           "countrylist":['page','pagesize'],
                           "arealist":['page','pagesize'],
                           "storelist":['page','pagesize'],
                           "orderstatuslist":['page','pagesize'],
                           "loglist":['page','pagesize'],
                           "w_wxv2":['aipay_v2[wx_mchid]','aipay_v2[wx_appid]','aipay_v2[wx_key]','aipay_v2[wx_appsecret]', 'aipay_v2[token_server]','aipay_v2[msg_moban_id]'],
                           "w_wxv3":['aipay_v3[wx_mch_id]','aipay_v3[wx_appid]','aipay_v3[serial_no]','aipay_v3[wx_APIv3]','aipay_v3[wx_appSecret]'],
                           "alibaba":['aipay_alibaba[alipartner]','aipay_alibaba[alikey]','aipay_alibaba[aliemail]'],
                           "email":['aimail[on]','aimail[smtphost]','aimail[smtpport]','aimail[frommail]','aimail[smtpuser]','aimail[smtppassword]','aimail[subject]'],
                           "aisafe":['aisafe[on]','aisafe[banip]'],
                           "aikfpw_w":['aikf_pw[on]','aikf_pw[ktime]'],
                           "aielse_w":['aielse_w[pricelu]'],
                           "addeditstore":['aistoreid','aistorename'],
                           "addcountry":['countryid','countryname'],
                           "addorderstatus":['orderstatusid','orderstatusname'],
                           "addeditarea":['areaid','areacountry','areaname'],
                           "addeditcompany":['companyid','companymark','companyname','logurl','account_plan_id','channel_status','price_level'],
                           "addeditadmin":['id','userid','username','password','powergroup','company','storehouse','countrygroup','powerweight'],
                           "getinoutcountry":['userid'],
                           "inoutcountry":['id','groupname','countrys'],
                           "getjiyunfunpower":['groupid'],
                           "jiyungroupdel":['groupid'],
                           "addjiyunfunpower":['groupid','groupname','apipower','liepower','funcpower'],
                           "getapipower":[],
                           "addapipower":['groupid','api'],
                           "editpwd":['user','oldpwd','newpwd'],
                           "else":["val1","val2","val3"],
                              }
                           },
                "sanbaoOrder":{
                       "make":{
                              "vipconfig":[],
                              "getsanbaonotes":['id'],
                              "toexcel":[],
                              "toexceldaofu":[],
                              "delpacklogs":['aiaddstime_start'],
                              "deldaofu":['aiaddstime_start'],
                              "daofuresult":['aidel','aiyes','id'],
                              "test":['test'],
                              "getpkglist":['page','pagesize','aiuserid','aikdno','aiipadd'],
                              "daofulist":['page','pagesize','aiuserid','aikdno','ai_applyman'],
                              "applygetpackage":['types','aiuserid','wxid','taobaoid','aiproductname','aicaizhi','ainature','aiidcard','storehouse_id','aikdno','ai_reserve'],
                              "userinfo":['word','wordvalue'],
                              "sanbaodel":['deltype','id'],
                              "sanbaodiedel":['diedeltype','id'],
                              "sanbaonotes":['notes','id'],
                              "sanbaoimg":['aikdno'],
                              "sanbaolist":['page','pagesize','status','aiuserid','aikdno','wxid','taobaoid','aiidcard','sanbao_action','ai_reserve','ai_applyman','aiaddpackage','aiaddstime_start','aiaddstime_end','ainature','storehouse_id','orderid'],
                        }
                    },
                    "StoreHouse":{
                        "make":{
                            "store_id":[],
                            "instore_edit":['type','kuaidi','userid','pkg_num','olduserid'],
                            "comestore":['store_zuobiao','ai_kuai_num','userid','aiweight','pkg_num','ailong','aiwidth','aiheight','aiv_weight','store_notes','store_id','aipkgimg'],
                            "comestore2":['store_zuobiao','ai_kuai_num','userid','aiweight','pkg_num','ailong','aiwidth','aiheight','aiv_weight','store_notes','store_id','aipkgimg','type_ceng'],
                            "instoreconfig":['types','word','wordvalue','ai_huojia_id','storehouse_id','special','row_lie','area_type'],
                            "storeconfig":[],
                            "delbigareaid":['big_area','id','deltype','storeid'],
                            "delsmallareaid":['small_area','small_huojia','ai_special_id','ceng_count','id','deltype','storeid'],
                            "addbigareaid":['ai_big_area_id'],
                            "addsmallareaid":['ai_small_area_id','types'],
                            "bigarealist":['page','pagesize','status','search_value','ai_big_type'],
                            "addsmall_zuobiao":['ai_area','ai_huojia_id','ai_ceng_count','ai_special_id','ai_zuobiao_count','ai_zuobiao_pkg_count','ai_teshu_count','ai_teshu_pkg_count','types','storeid'],
                            "small_zuobiao_list":['page','pagesize','status','search_value','ai_small_type','types'],
                            "bigarearesult":['id','bigcount','nowcunt','status'],
                            "smallzuobiaoedit":['id','zongcount','nowcunt','status'],
                            "addbigarea_p":['id','bigarea','addcount','zongcount'],
                            "addsmallarea_h":['id','smallhuojia','addcount','ceng_count','teshu_num','types','storeid'],//增加一个区域分类
                            "bigarea_id_list":['page','pagesize'],
                            "small_huojia_list":['page','pagesize','types'],
                            'edit_areapkg_count':['area_id','area_ceng','pkg_count','storehouse','types'],
                            "smallarealist":['page','pagesize','types'],
                            "userinfo":['word','wordvalue'],
                            "likeuser":['wordvalue'],
                            "vipconfig":[],
                            "zuobiao_leave":['zuobiao_leave'],
                            "zuobiao_leave_get":[],
                            "store_q_status":[],
                            "store_service":['type','huojia'],
                            "dafujieguo":['word','wordvalue'],
                            "daofucreate":['ai_kuai_num','form_userid','aizuobiao','companyValue','storehouseValue','aimoney','addman','datetime','aimoneytype'],
                       }
                    },
                    "JiyunOrder" : {
                        "make" : {
                            "storeconfig":[],
                            "vipconfig":[],
                            "pinming":[],
                            "price_else_conf":[],
                            "wuliucode":['id'],
                            "rpricegroupx":['id'],
                            "fahuoidlist":['orderid'],
                            "makeselfkd":['id','ai_wuliu','orderid','ai_channel_code'],
                            "makeselfelsekd":['id','aikdno2','types'],
                            "channelapi":['id','orderid','aikdno','kdapi','do','types','data'],
                            "waitprint":['id','orderid','aipayment'],
                            "fahuostatus":['id','orderid','status_fa','status_zhu','aiuserid'],
                            "printstatus":['id','orderid','aistatus'],
                            "ordersanbao":['orderid','aiguest'],
                            "getwuliutype":['id','aikdno'],
                            "updatepkgfahuoid":['id','orderid','newfahuoid','oldfahuoid'],
                            "upfahuoids":['ids','orderid','newfahuoid','oldfahuoids'],
                            "addpkg":['pkgnum','orderid','fahuoid','aiidcard'],
                            "del":['id','types','orderid','aikd_index'],
                            "selfcompany":[],
                            "moreaddress":['userid'],
                            "test":[],
                            "pkgzong":['orderid','aikd_index'],
                            "editpkg":['id','orderid','aiidcard','aikdno2','aikd_index','son_num','aistatus','aiposition','ainature','ailwh','aiv_weight','aiweight','aiw_price','aiprice','ai_goods_name'],
                            "editfahuodan":['id','orderid','aiidcard','ai_channel_id','ai_channel_area_id','aiis_chaibao','aikd_index','ai_wuliu','aikdno','aikdno2','aiprice_type','notes_status','aiv_weight','aiweight','aiwprice','aiprice','aibaoxian_price','aizengzhi_price','aifujia_price','aizong_price','aishenbao_jiazhi','aipayment','ai_getway','ainame','aiphone','aiaddress','aiprovince','aicity','ai_zipcode','ai_in_company','ai_goods_name','ai_egoods_name','ai_go_types','aistatus','ainature','aiemail','aiuserid'],
                            "fahuoorder":['orderid'],
                            "pkgorder":['orderid'],
                            "country":[],
                            "w_ordernotes":['orderid','ai_notes','aibignotes','aiguest'],
                            'bignotes':['orderid'],
                            "orderdetails":["orderid"],
                            "userinfo":['word','wordvalue'],
                            "userlist":["userid","types"],
                            "useradress":["userid"],
                            "orderlist":['page','pagesize','aiidcard','orderstatus','order_action','aiuserid','wxid','orderid','taobaoid','aiphone','aiemail','ai_reserve','ai_ordercheck_id','storehouse_id','ai_country_id','order_come','aiaddstime_start','aiaddstime_end'],
                            "creatorder":["form_userid","aicountry","form_province","form_city","form_address","get_package_type","ainature","aichannel","storehouseid","aiuser_come","form_bao","pkg_ask","notes_orderx","give_order","zhu_order","notes_bytes_type","ids","ids_nums","order_type","dabaoman"],
                            "zhuorder":["zhu_order"],
                            "getdabaoimg":["orderid"],
                            "readexcel":["type"],
                            "emailto":["aiemail","msg","title","href_a"],
                            "wx_msg_send":['openid','orderid','aistatus','href_a'],
                            "order_service":['type'],
                            "kf_getorder":['orderid'],
                            "vweightxishu":['fahuoid'],
                            "priceaccount":['id','aiidcard','ai_channel_id','ai_area_id','price_weight'],
                            "pricebaojia":['aiidcard','shenbaojiazhi'],
                            "saveaccount":['id','elsestatus','yunfeitext'],
                            "readaccount":['id'],
                        }
                    },
                    "WuliuChannel":{
                    "make": {
                     "allgoods":['ai_price_type'],
                     "usechannel":[],
                     "wpricegroup":['id','pricestr'],
                     "rpricegroup":['id'],
                     "del":['id','types'],
                     "price_else_config":[],
                     "price_vipconfig":[],
                     "setusechannel":['type','price_level'],
                     "elsetype":[],
                     "copyconfig":['copyid','id'],
                     "vipconfig":[],
                     "selfcompany":[],
                     "wuliucode":['code'],
                     "addchannelprice":['id','ai_area_id','aiisdel','aiidcard','ai_channel_id','goods_type','long_time','weight_init','weight_add','weight_start','weight_end','ai_p_startprice','ai_p_endprice','ai_z_startprice','ai_z_endprice','else_price_type','notes_status'],
                     "addChannel":['id','ai_channel_name','aiidcard','aistartstime','aiendtime','ai_goods_type','ai_formula','ai_illustrate','ai_insure','ai_limitation','ai_wuliu','ai_channel_code'],
                     "addgoodsGroup":['id','goods','groupname','price','start1','start2','start3','start4','ai_price_type'],
                     "goodslist":['page','pagesize','ai_price_type','load_type','word','wordvalue'],
                     "goodsgrouplist":['page','pagesize','ai_price_type','load_type','word','wordvalue'],
                     "channelpricelist":['page','pagesize','load_type','word','wordvalue','ai_area_id','aiidcard','ai_channel_id','goods_type','long_time','aiisdel'],
                     "channellist":['page','pagesize','load_type','word','wordvalue'],
                     "addgoods":['goodsname','goodsid','goodstype'],
                    },
                    },
                    "UserInfo":{
                       "make":{
                        'selfcompany':[],
                        'addresslist':['userid'],
                        'deluserinfo':['id','types'],
                        'userpubliclist':['userid'],
                        'addressdefault':['id','userid'],
                        'adduserpublic':['id','aiuserid','aiidcard','ai_base','ai_get','ai_kefu','ai_reserve'],
                        'addaddress':['id','userid','aiphone','ainame','ai_country_id','aiprovince','aicity','aiaddress','aizipcode','aistatus','aiidcard'],
                        'userinfo':['word','wordvalue'],
                        'makeuserlist':['page','pagesize','load_type','word','wordvalue'],
                        'addedituser':['id','wxid','taobaoid','aiemail','aiphone','aiusername','aitaobao','aiweixin','ai_country_id','ai_department','aiidcard','ai_types'],
                       }
                    },
                },
            },
         },

    toUrlParmer:function(b,Parameter){//参数模式组装 只组装参数 将 参数拼接成url字符串 带有action的参数 不带 api_url
        if(this.action[b].length!=Parameter.length){alert("数组中给予的参数数量不匹配，请重新填写")}
        let urlparmer="action="+b;
        for (let i = 0; i < Parameter.length; i++) {
            urlparmer=urlparmer+"&"+this.action[b][i]+"="+Parameter[i]
        }
     return urlparmer
    },
   
    toNoActionParmer:function(b,Parameter){//参数模式 只组装参数 不加参数 action 的组装 不带 api_url
        if(this.action[b].length!=Parameter.length){alert("数组中给予的参数数量不匹配，请重新填写")}
        let urlparmer="";
        if(this.action[b].length>0){
        for (let i = 0; i < Parameter.length; i++) {
            if(i==0){urlparmer=urlparmer+this.action[b][i]+"="+Parameter[i]}else{urlparmer=urlparmer+"&"+this.action[b][i]+"="+Parameter[i]}
        }}
     return urlparmer
    },
    GetApiFun:function(apiurl,b,Parameter){  //组装完整链接 加  action参数,api链接不带有初始参数如 set
       return `${apiurl}?${this.toUrlParmer(b,Parameter)}` //当c为1时，为参数模式组装
    },

    Set_Pulic_Pos:function(apiurl,b){ //post只组装set  post数据由上面参数组装函数组装  toUrlParmer()
        let urlparmer="set="+b;
        return apiurl+"?"+urlparmer; //当c为1时，为参数模式组装
    },

    Set_module_Get:function(apiurl,a,b,c,Parameter){ //根据a,b,c找到 附加参数列表 // Jiyun  shop  shequ模块调用  
        if(this.set[a]["action"][b]["make"][c].length!=Parameter.length){alert("数组中给予的参数数量不匹配，请重新填写")}
        let urlparmer="set="+a+"&action="+b+"&make="+c;
        if(Parameter.length!=0){
        for (let i = 0; i < Parameter.length; i++) {
            urlparmer=urlparmer+"&"+this.set[a]["action"][b]["make"][c][i]+"="+Parameter[i]
        }}
          return apiurl+"?"+urlparmer;
       },

   Set_module_post_url:function(apiurl,a,b,c){ //根据a,b,c找到 附加参数列表 // Jiyun  shop  shequ模块调用  
    let geturlparmer="set="+a+"&action="+b+"&make="+c;
      return apiurl+"?"+geturlparmer;
   },
   Set_module_post_parmer:function(a,b,c,Parameter){ //根据a,b,c找到 附加参数列表 // Jiyun  shop  shequ模块调用  
    if(this.set[a]["action"][b]["make"][c].length!=Parameter.length){alert("数组中给予的参数数量不匹配，请重新填写")}
    let posturlparmer="";
    if(Parameter.length!=0){
    for (let i = 0; i < Parameter.length; i++) {
        posturlparmer=posturlparmer+"&"+this.set[a]["action"][b]["make"][c][i]+"="+Parameter[i]
    }}
      return posturlparmer.substring(1);
   },

}

export default actionAPI`

**Comment by so1ve** [comment] 2023-10-15 04:10
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by so1ve** 2023-10-15 04:10 UTC
