### ISSUE TITLE
[Bug] `instanceof` syntax highlighting is broken

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/language-tools#3400] opened 2023-07-14 02:30 UTC
**Code**
https://github.com/wenfangdu/vite-vue-3/blob/instanceof/src/App.vue#L7-L18
![image](https://github.com/microsoft/TypeScript-TmLanguage/assets/28700378/75d3139a-af42-449f-9c84-86c3a14581f7)

This isn't covered by the grammar in [`TypeScript-TmLanguage`](https://github.com/microsoft/TypeScript-TmLanguage/issues/985#issuecomment-1634713188).
If it's not caused by Volar, please give an upstream repo, so I file this there.

**Comment by so1ve** [comment] 2023-07-14 05:29
Duplicate of #656

**Comment by so1ve** [comment] 2023-07-14 05:30
Upstream: https://github.com/microsoft/TypeScript-TmLanguage

**Comment by wenfangdu** [comment] 2023-07-14 06:20
@so1ve In which post did they say that they don't want to support this? Prettier automatically removes parens, so that's not viable.

**Comment by so1ve** [comment] 2023-07-14 06:22
microsoft/TypeScript-TmLanguage#985, your issue. The guy just said this is not covered and closed your issue.

**Comment by Mettbrot** [comment] 2024-02-07 15:54
Is there any status update on this? Should we try to open something again at microsoft/TypeScript-TmLanguage ?

**Comment by douira** [comment] 2024-02-07 16:48
Presumably JS/TS highlighting within string literals within JSX isn't something the TS grammar wants to deal with because it's not usually encountered unless the code in question happens to be using Vue. The solution is to either convince the upstream grammar that this is relevant, fork it (unlikely to happen because it needs editor support), or implement a fix in the vue language tools if that's somehow possible.

**Comment by Mettbrot** [comment] 2024-02-08 09:04
@mesqueeb did you at some point find a way to work around this on the volar side? Could you open a Pull Request for it?

**Comment by johnsoncodehk** [comment] 2024-05-23 20:51
See https://github.com/microsoft/TypeScript-TmLanguage/issues/985#issuecomment-2127996567

**Closed by johnsoncodehk** 2024-05-23 20:51 UTC
Labels: pending triage, good reproduction ✨
