### ISSUE TITLE
Strange situation after 2.0 where syntax highlighting and scrolling go together

### ISSUE THREAD

**Issue by lvzhenbo** [vuejs/language-tools#4062] opened 2024-03-10 07:51 UTC
I want to use a GIT image to illustrate the problem, please pay attention to the color (in order to prevent the interference of third-party themes, I have switched to vscode's built-in theme)
![动画](https://github.com/vuejs/language-tools/assets/32427677/4407935b-60fd-4901-98b6-418401bb1fbe)

**Comment by mybearworld** [comment] 2024-03-10 08:47
Is this #3935?

**Comment by so1ve** [comment] 2024-03-10 12:31
Duplicate of https://github.com/vuejs/language-tools/issues/3935

**Closed by so1ve** 2024-03-10 12:31 UTC
