### ISSUE TITLE
Auto import component does not work

### ISSUE THREAD

**Issue by alex-lihachiov** [vuejs/language-tools#2071] opened 2022-10-28 09:11 UTC
Auto import component does not work anymore typing < and pressing ctrl+space
![изображение](https://user-images.githubusercontent.com/52136905/198550550-bd25b0ea-f605-4f67-96a3-0edb0019297e.png)

**Comment by simonknittel** [comment] 2022-12-30 10:24
I noticed the same. I figured out that the last working version of the VSCode extension is 1.0.8. The auto import of components broke with 1.0.9. I suspect the following commit as the cause since that where the `volar.completion.autoImportComponent` setting got changed/removed.

https://github.com/johnsoncodehk/volar/commit/0779ae2d5c2bf17d0909cbf58e8d4abe61bbd2b8#diff-e38db040908417b4291b2bfad8d46d0d9f972cfa9bdf79997624aa414b372dee

**Comment by johnsoncodehk** [comment] 2023-01-03 19:39
As a workaround you can input `<Vue` to trigger it for now.
<img width="641" alt="螢幕截圖 2023-01-04 03 39 30" src="https://user-images.githubusercontent.com/16279759/210429122-306ac18d-b575-473b-8b64-b098cc750acc.png">

**Comment by chadanuk** [comment] 2023-01-06 14:18
A somewhat related bug is that even using the workaround, the behaviour for components structured like `ComponentName/index.vue` the resulting import is incorrect.
```js
import Index from '@/Components/Charts/RareLineChart/index.vue';
```

**Comment by g1ronn1mo** [comment] 2023-08-04 10:32
for me it autofills `import AutocompletePersonsOfSpace from 'components/APIComponents/AutocompletePersonsOfSpace.vue';`

but I need `import AutocompletePersonsOfSpace from '@/components/APIComponents/AutocompletePersonsOfSpace.vue';`

Does anybody know how to do this?

**Comment by davidmatter** [comment] 2024-08-06 07:36
Closing this one as many things have changed since 2.x. Feel free to create a new issue with a minimal reproduction if you're still having issues, thanks!

**Closed by davidmatter** 2024-08-06 07:35 UTC
Labels: bug
