### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by pot-code** [vuejs/language-tools#4068] opened 2024-03-11 07:09 UTC
For the environment:
- Win11
- Vscode 1.87.1
- Vue-official 2.0.6

The syntax highlighting gets reduced when i scroll to a certain point, which found out to be the template part. 

For a .vue file, when i scroll over the script code till the line `</script>` appears,  syntax highlighting will become half functional, not colorful as before

could it be relavant to the feature of split editing?

**Comment by so1ve** [comment] 2024-03-11 07:56
Duplicate of https://github.com/vuejs/language-tools/issues/3935

**Closed by so1ve** 2024-03-11 07:56 UTC
