### ISSUE TITLE
Vue Language Features (Volar) 1.8.7 "Server initialization failed"

### ISSUE THREAD

**Issue by maxoyed** [vuejs/language-tools#3454] opened 2023-07-26 20:07 UTC
I just update to the latest version 1.8.7, with builtin JS/TS support plugin disabled, still can not start server.

```shell
node:internal/modules/cjs/loader:1013
  throw err;
  ^

Error: Cannot find module 'typescript/lib/tsserverlibrary'
Require stack:
- c:\Users\maxoy\.vscode\extensions\vue.volar-1.8.7\dist\server.js
- c:\Users\maxoy\.vscode\extensions\vue.volar-1.8.7\server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)
    at Module._load (node:internal/modules/cjs/loader:858:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at c:\Users\maxoy\.vscode\extensions\vue.volar-1.8.7\dist\server.js:430:7188
    at c:\Users\maxoy\.vscode\extensions\vue.volar-1.8.7\dist\server.js:1:348
    at c:\Users\maxoy\.vscode\extensions\vue.volar-1.8.7\dist\server.js:440:9692
    at c:\Users\maxoy\.vscode\extensions\vue.volar-1.8.7\dist\server.js:1:348
    at c:\Users\maxoy\.vscode\extensions\vue.volar-1.8.7\dist\server.js:441:14115 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\maxoy\\.vscode\\extensions\\vue.volar-1.8.7\\dist\\server.js',
    'c:\\Users\\maxoy\\.vscode\\extensions\\vue.volar-1.8.7\\server.js'
  ]
}
[Error - 04:05:23] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 04:05:23] Connection to server got closed. Server will restart.
true
[Error - 04:05:23] Vue Syntactic Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

Downgrade to `1.8.6` works for me.

My environment:
- OS: Windows11 Pro Edition 22H2 22621.1992
- Node.js: 18.16.1

**Comment by jerome-benoit** [comment] 2023-07-26 20:18
Exactly the same error with the same extension version under GNU/Linux and MacOSX.

**Comment by TiagoRibeiro25** [comment] 2023-07-26 20:19
same

**Comment by gustavoconter** [comment] 2023-07-26 20:28
Same error here

**Comment by HugeLetters** [comment] 2023-07-26 20:34
same

**Comment by johnsoncodehk** [comment] 2023-07-26 20:49
Duplicate of #3453

**Closed by johnsoncodehk** 2023-07-26 20:49 UTC

**Comment by maxoyed** [comment] 2023-07-27 04:33
Thx, latest version 1.8.8 works
