### ISSUE TITLE
[Bug] Excess props aren't checked 

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/language-tools#3273] opened 2023-06-13 06:01 UTC
Repro: https://github.com/wenfangdu/vite-vue-3/tree/excess-prop-check

`foo` is an excess prop, but no error was thrown:
![image](https://github.com/vuejs/language-tools/assets/28700378/29f5035d-eea3-4069-bde0-0753c2590e8d)
Compared to the same logic in react, excess prop was not allowed:
![image](https://github.com/vuejs/language-tools/assets/28700378/65275906-2afc-4beb-bd52-332d3aa42bf9)
Repro: https://github.com/wenfangdu/vite-react/tree/excess-prop-check

**Comment by so1ve** [comment] 2023-06-13 09:29
Can you share `HelloWorld`'s type? Just hover on it.

Maybe related: #3268

**Comment by wenfangdu** [comment] 2023-06-13 15:19
@so1ve 
![image](https://github.com/vuejs/language-tools/assets/28700378/0ff675f1-149d-4107-85c4-d7e7f4fdda8c)

**Comment by so1ve** [comment] 2023-06-13 15:25
Well not duplicate =v=

**Comment by sadeghbarati** [comment] 2023-06-14 06:28
Off-topic:
Hi @wenfangdu 🔥 what tool you used for generating rounded images like this

**Comment by so1ve** [comment] 2023-06-14 07:16
@sadeghbarati carbon.sh or codesnap I guess

**Comment by sadeghbarati** [comment] 2023-06-14 07:24
That's for coding stuff something like [`ray.so`](https://ray.so/) and [`carbon`](https://carbon.now.sh/)
It's a rounded image that contains more data

**Comment by so1ve** [comment] 2023-06-14 07:33
I see. It is a screen shot application

**Comment by wenfangdu** [comment] 2023-06-15 05:37
@sadeghbarati iShot Pro, the coolest feature IMO is highlighting:
<img width="957" alt="image" src="https://github.com/vuejs/language-tools/assets/28700378/8830a909-2e28-4f85-a766-370a60a4a09e">

**Comment by so1ve** [comment] 2023-06-25 04:49
Well, this is the intended behavior - to enable excess props checking, you have to set `vueCompilerOptions.strictTemplates` to `true`.

**Comment by so1ve** [comment] 2023-06-25 09:01
Closed as working as intended.

**Closed by so1ve** 2023-06-25 09:01 UTC
Labels: question, good reproduction ✨
