### ISSUE TITLE
`export type` on last line of normal script (without semicolon) alongside script setup will break <script> colors

### ISSUE THREAD

**Issue by sadeghbarati** [vuejs/language-tools#3707] opened 2023-11-04 09:59 UTC
This is a low priority and can be closed
I'm using `@antfu/eslint-config` which remove semicolons

[Vue Playground](https://play.vuejs.org/#eNp9kc9LwzAUx/+VZy5VmBuy2+gGKgP1oKKCB+OhdG9dZ5qE5GVWSv93XzI2ZYzdmu+P9z5JO3Ft7XATUExE7ktXWwJV6GoqBXkpZlJLja01joB+LMK8LRqrEKbw8Sl1PtpWUmxX90jBHgypmzSiA4dL6GHpTAMZb81isTTaEzS+4qnsn2d3qJSBd+PU4iy7OFxDyAQFIZ8A8tXVrOtSue/zEZ+SWmsbCDaXjVmgYgz2E0c+2rfFgOF49bKuhmtvND9AF7tSlKaxtUL3ZKlmNCkmkJzoFUz2/ZA0cgEHO71cYfl1RF/7NmpSPDv06DYoxd6jwlVIW3v++ogtf+9NJg+K0yfMF/RGhci4jd0EvWDsf7lEe5/evtbVm5+3hNrvLhVBY7JPeSn4f9yeuPof7ng4Tj2pe9H/AgdhwMM=)

<details><summary>VSCode (Night Owl)</summary>
<p>

![image](https://github.com/vuejs/language-tools/assets/17789047/d96eebc1-7a6e-46c7-a131-b66392d2dace)

</p>
</details> 

<details><summary>VSCode (Default Theme)</summary>
<p>

![image](https://github.com/vuejs/language-tools/assets/17789047/c772abbd-5302-405c-b55f-f25fdb73b6f5)

</p>
</details>

**Comment by so1ve** [comment] 2023-11-05 03:53
Duplicate of #3468

**Closed by so1ve** 2023-11-05 03:53 UTC
