### ISSUE TITLE
Error: selectionRange must be contained in fullRange

### ISSUE THREAD

**Issue by yxw007** [vuejs/language-tools#4962] opened 2024-10-30 03:46 UTC
### Vue - Official extension or vue-tsc version

v2.0.8

### VSCode version

1.95.0

### Vue version

3.5.12

### TypeScript version

none

### System Info

```shell
win10
```

### package.json dependencies

```json
{
"dependencies": {
    "@dcloudio/uni-app": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-app-plus": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-components": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-h5": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-mp-alipay": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-mp-baidu": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-mp-lark": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-mp-qq": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-ui": "^1.5.6",
    "lodash.clonedeep": "^4.5.0",
    "vue": "^3.5.12",
    "vue-i18n": "^9.1.9",
    "vuex": "^4.1.0"
  },
  "devDependencies": {
    "@dcloudio/types": "^3.4.12",
    "@dcloudio/uni-automator": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/uni-cli-shared": "^3.0.0-alpha-4030120241009001",
    "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-4030120241009001",
    "@uni-helper/unocss-preset-uni": "^0.2.10",
    "autoprefixer": "^10.4.20",
    "commitizen": "^4.3.1",
    "cross-env": "^7.0.3",
    "cz-conventional-changelog": "^3.3.0",
    "eslint": "^8.10.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-vue": "^8.5.0",
    "husky": "^7.0.4",
    "json5": "^2.2.3",
    "less": "^4.1.2",
    "lint-staged": "^12.3.7",
    "postcss-comment": "^2.0.0",
    "prettier": "^2.5.1",
    "sass": "1.77.8",
    "standard-version": "^9.3.2",
    "unocss": "^0.63.4",
    "unocss-applet": "^0.8.4",
    "vite": "5.4.9"
  },
}
```

### Steps to reproduce

1. Make the style content empty, and </style> make the end tag and start tag on one line
2. Feel free to delete a line of spaces and save to reproduce it

![issue](https://github.com/user-attachments/assets/ade2f24d-f7e1-4fe0-8129-96a1f4a52db4)

### What is expected?

Don’t pop up the box to report an error

### What is actually happening?

![image](https://github.com/user-attachments/assets/188236ce-0176-425e-8085-659c3a55aded)

```text
[Error - 11:42:01 AM] Request textDocument/documentSymbol failed.
Error: selectionRange must be contained in fullRange
	at Hd.validate (file:///c:/Users/Administrator/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:33675)
	at new Hd (file:///c:/Users/Administrator/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:33883)
	at dn (c:\Users\Administrator\.vscode\extensions\vue.volar-2.1.8\dist\client.js:37:46612)
	at o (c:\Users\Administrator\.vscode\extensions\vue.volar-2.1.8\dist\client.js:37:21036)
	at Object.NS [as map] (c:\Users\Administrator\.vscode\extensions\vue.volar-2.1.8\dist\client.js:37:21122)
	at Object.pr [as asDocumentSymbols] (c:\Users\Administrator\.vscode\extensions\vue.volar-2.1.8\dist\client.js:37:46579)
	at c (c:\Users\Administrator\.vscode\extensions\vue.volar-2.1.8\dist\client.js:41:56059)
	at async OC.provideDocumentSymbols (file:///c:/Users/Administrator/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:125496)
[Error - 11:42:01 AM] Request textDocument/documentSymbol failed.
Error: selectionRange must be contained in fullRange
	at Hd.validate (file:///c:/Users/Administrator/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:33675)
	at new Hd (file:///c:/Users/Administrator/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:33883)
	at dn (c:\Users\Administrator\.vscode\extensions\vue.volar-2.1.8\dist\client.js:37:46612)
	at o (c:\Users\Administrator\.vscode\extensions\vue.volar-2.1.8\dist\client.js:37:21036)
	at Object.NS [as map] (c:\Users\Administrator\.vscode\extensions\vue.volar-2.1.8\dist\client.js:37:21122)
	at Object.pr [as asDocumentSymbols] (c:\Users\Administrator\.vscode\extensions\vue.volar-2.1.8\dist\client.js:37:46579)
	at c (c:\Users\Administrator\.vscode\extensions\vue.volar-2.1.8\dist\client.js:41:56059)
	at async OC.provideDocumentSymbols (file:///c:/Users/Administrator/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:125496)
```

### Any additional comments?

Style does not fill in the content, and then keeps the start tag and end tag on one line, and then operates other codes at will, and an error will be reported when saving.

**Comment by KazariEX** [comment] 2024-10-30 04:37
Duplicate of #4959

**Closed by KazariEX** 2024-10-30 04:37 UTC
Labels: pending triage
