### ISSUE TITLE
Feature request: project-wide error check

### ISSUE THREAD

**Issue by rodrigocfd** [vuejs/language-tools#3700] opened 2023-11-01 23:37 UTC
When working with pure TypeScript projects (not Vue), it is possible to make VSCode instantly highlight errors in **all files** in the project, with the [following setting](https://github.com/microsoft/vscode/issues/13953#issuecomment-583179315):

```
"typescript.tsserver.experimental.enableProjectDiagnostics": true
```

It would be really handy if this TypeScript feature could be extended to Vue files as well.

**Comment by so1ve** [comment] 2023-11-02 02:06
Since volar 2.0 no longer requires take over mode, please wait for version 2.0 to be released, thanks!

**Comment by so1ve** [comment] 2023-11-02 02:06
Duplicate of #2490.

**Closed** 2023-11-02 02:06 UTC
Labels: duplicate

**Comment by rodrigocfd** [comment] 2024-01-13 01:56
@so1ve Is there an estimated release date for Volar 2.0?

Where can I follow its development progress?

**Comment by so1ve** [comment] 2024-01-13 04:04
There is no exact timing as Volar.js 2.0 is not yet complete.
