### ISSUE TITLE
Optional chaining ignored in event handler

### ISSUE THREAD

**Issue by DamianGlowala** [vuejs/language-tools#4261] opened 2024-04-12 13:03 UTC
![image](https://github.com/vuejs/language-tools/assets/48835293/919c2c50-f9c1-4a58-a3c3-f383a6adad5f)
![image](https://github.com/vuejs/language-tools/assets/48835293/d04940e9-c492-4ffb-b0fc-2036a59a8ef3)

**Comment by johnsoncodehk** [comment] 2024-04-22 00:57
Duplicate of #4209

**Closed by johnsoncodehk** 2024-04-22 00:57 UTC
