### ISSUE TITLE
[Bug] Settings are not respected when using Volar Takeover Mode

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/language-tools#2684] opened 2023-04-23 05:51 UTC
With:

```json
{
  "javascript.suggestionActions.enabled": false,
  "typescript.suggestionActions.enabled": false
}
```

Code suggestions (the three dots) are still showing up:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/28700378/233822085-97a7b1d2-d0ba-4afa-8f9d-bed18ebe78fc.png">
Also, if the builtin TS plugin is disabled, its settings are shown as unknown, but [TypeScript Vue Plugin](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin) is supposed to use them, so they shouldn't be shown as unknown:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/28700378/233822173-25bdb3fe-cfd3-4115-b083-064c355e5f4f.png">

**Comment by so1ve** [comment] 2023-09-05 04:12
Duplicate of #2490

**Closed** 2023-09-05 04:12 UTC
Labels: duplicate, design limitation
