### ISSUE TITLE
Pug Typescript validation messed up after update from Volar

### ISSUE THREAD

**Issue by timsayshey** [vuejs/language-tools#4094] opened 2024-03-13 21:56 UTC
This wasn't happening before the update, if I switch to tags it works but does not work for Pug:

<img width="571" alt="image" src="https://github.com/vuejs/language-tools/assets/1148940/2fbe49d3-8b13-40cf-b04b-554e74983921">

This started as soon as TypeScript Vue Plugin (Volar) was deprecated. My guess is not all features were ported into the main extension.

**Comment by timsayshey** [comment] 2024-03-13 22:06
Incase anyone ends up in this situation, you can downgrade back to the working extensions by downloading and installing the previously working Volar VSIX extensions here:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/volar/0.17.6/vspackage
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Vue/vsextensions/vscode-typescript-vue-plugin/1.8.27/vspackage

**Comment by so1ve** [comment] 2024-03-14 02:00
Have you installed the `@vue/language-plugin-pug` plugin?

**Comment by timsayshey** [comment] 2024-03-14 02:04
@so1ve Yes, here are my Vue packages:
```
"@volar/vue-language-plugin-pug": "^1.6.5",
"@vue/language-plugin-pug": "^2.0.6",
"@vueuse/core": "^10.2.1",
"vue": "^3.3.4",
"vue-router": "^4.0.0",
"vue-tsc": "^1.8.4",
"eslint-plugin-vue": "^9.23.0",
```

**Comment by so1ve** [comment] 2024-03-14 02:06
Could you please share your `tsconfig.json`?

**Comment by timsayshey** [comment] 2024-03-14 02:18
```
{
  "extends": "@quasar/app-vite/tsconfig-preset",
  "vueCompilerOptions": {
    "target": 3,
    "skipTemplateCodegen": false, // For Volar Extension
    "plugins": [
      "@volar/vue-language-plugin-pug"
    ],
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"],
      "*": ["node_modules/*", "path/to/your/modules/*"]
    },
  },
  "compilerOptions": {
    "baseUrl": ".",
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "allowJs": true
  },
  "include": [
    "./src/**/*"
  ],
}

```

**Comment by so1ve** [comment] 2024-03-14 02:59
Your `vueCompilerOptions` is outdated. Replace

```json
"skipTemplateCodegen": false, // For Volar Extension
"plugins": [
  "@volar/vue-language-plugin-pug"
],
```

with

```json
"plugins": [
  "@vue/language-plugin-pug"
],
···

**Comment by so1ve** [comment] 2024-03-14 03:08
And the latest version of Volar is 2.0.6 (v1 is 1.8.27). Please make sure the plugin version matches your Volar version.

**Comment by timsayshey** [comment] 2024-03-14 17:43
Thanks - oddly enough there was no pop up message warning me about the upgrades or deprecation or that I needed to up my tsconfig to keep things working - but I'll try that out when I get some time

**Comment by SolidKane** [comment] 2024-04-05 10:17
good day! I can't figure out why it doesn't work, everything is installed in accordance with the recommendations

![image](https://github.com/vuejs/language-tools/assets/8104308/763f3b8d-8bb6-4a42-9e9a-a81f179ec0c8)
![image](https://github.com/vuejs/language-tools/assets/8104308/d3d7fd48-2246-4397-88ae-556212c60c14)
![image](https://github.com/vuejs/language-tools/assets/8104308/1c8843e0-32ef-4279-9363-eab9abeca2ca)


> And the latest version of Volar is 2.0.6 (v1 is 1.8.27). Please make sure the plugin version matches your Volar version.

**Comment by johnsoncodehk** [comment] 2024-05-14 05:22
Closed as answered at https://github.com/vuejs/language-tools/issues/4094#issuecomment-1996302793.

The problem is template lang set to pug, but template code is html. And eslint errors is not related to this project.

**Closed by johnsoncodehk** 2024-05-14 05:22 UTC

**Comment by jlsilva1994** [comment] 2025-01-13 13:59
hello, i still have the same porblem as @timsayshey, and have configured everyting as recommended and with the last version

**Comment by mateuszkordek** [comment] 2025-02-10 12:47
yes, the problem still occurs and is not caused by html code in pug template. solution provided in [#4049 (comment)](https://github.com/vuejs/language-tools/issues/4094#issuecomment-1996302793) does not work.

**Comment by diogoterremoto** [comment] 2025-02-19 15:03
I had this issue. Everything is setup (`<template lang="pug">`, official Vue.js plugin, `@vue/language-plugin-pug` installed and configured), but still not working. Tried changing `vue.server.hybridMode` from `auto` to `typeScriptPluginOnly` and started working. Not sure why but would like to know!
