### ISSUE TITLE
Error with name of a prop while using v-model in Vue 2.7

### ISSUE THREAD

**Issue by evgenii-code** [vuejs/language-tools#3367] opened 2023-07-05 07:26 UTC
I have a custom component with `v-model` and I want to use different name for a prop instead of a default `value` name.  

For example I want to set prop name as `foo` for a model.  
Also I define `model` options like this:  
```
model: {
    prop: 'foo',
    event: 'update:foo',
},
```

but in the parent component I get the following error:  

```
Argument of type '{ value: string; }' is not assignable to parameter of type 'Readonly<Partial<{}> & Omit<Readonly<ExtractPropTypes<{ foo: { type: StringConstructor; required: true; }; }>>, never>> & Record<...>'.
  Property 'foo' is missing in type '{ value: string; }' but required in type 'Readonly<Partial<{}> & Omit<Readonly<ExtractPropTypes<{ foo: { type: StringConstructor; required: true; }; }>>, never>>'.ts(2345)
```

<details>
  <summary>Screenshot of an error</summary>

![image](https://github.com/vuejs/language-tools/assets/56561823/4fb9492f-85b6-4798-817e-246319422c97)

</details>
  
But if I change prop name back to default `value` then error is gone.  
There are two identical components but with different prop names.  

<details>
  <summary>Screenshot of both components</summary>

![image](https://github.com/vuejs/language-tools/assets/56561823/2a3b909c-90d3-458b-8993-0b58a64a6b77)

</details>

  
Code of the custom component:
<details>
<summary>Expand</summary>

```
<template>
  <input v-model="fooLocal" />
</template>

<script lang="ts">
import { defineComponent } from 'vue'

const EVENT_NAME_V_MODEL = 'update:foo'

export default defineComponent({
  name: 'BaseInput',

  model: {
    prop: 'foo',
    event: EVENT_NAME_V_MODEL,
  },

  props: {
    foo: {
      type: String,
      required: true,
    },
  },

  computed: {
    fooLocal: {
      get(): string {
        return this.foo
      },
      set(value: string) {
        this.$emit(EVENT_NAME_V_MODEL, value)
      },
    },
  },
})
</script>
```

</details>

Versions:  
node v16.17.1
vue 2.7.10
nuxt 2.15.8
volar v1.8.4

Minimal repo:  
[https://github.com/evgenii-code/volar-test](https://github.com/evgenii-code/volar-test)

**Comment by so1ve** [comment] 2023-07-05 07:29
Duplicate of #3113

**Closed by so1ve** 2023-07-05 07:29 UTC
