### ISSUE TITLE
HTML attributes are not allowed when strictTemplates is enabled

### ISSUE THREAD

**Issue by adoin** [vuejs/language-tools#3152] opened 2023-05-10 01:39 UTC
As default, inheritAttrs is true.
So most of components implement class and style without no announce.
But now vue-tsc tell me:
![image](https://github.com/vuejs/language-tools/assets/20517172/8da77e78-b40a-4919-a4d8-22e220a11f28)
PLS allow style and class at least.

**Comment by so1ve** [comment] 2023-06-27 14:32
@adoin Hi, could you please check if you have enabled strictTemplates?

**Comment by rchl** [comment] 2023-07-02 13:50
This is a Vue 2 project?
Are you able to provide a reproduction?

**Comment by adoin** [comment] 2023-07-03 09:55
> This is a Vue 2 project? Are you able to provide a reproduction?

Vue3.3...

**Comment by rchl** [comment] 2023-07-03 10:10
You have to provide more info. Ideally a repo that reproduces.
Since it works in most cases, there is likely something special about your code that we can't see.

**Comment by dten** [comment] 2023-08-04 08:41
it's pretty easy to reproduce. simple app with a input wrapping component

https://play.vuejs.org/#eNp9UstOwzAQ/BXjS0BCyaG3EpAAVaJIPASVuPgSkm1wcWzLXpeiKv/O2m3TIlBv2ZnJ7uyO1/za2nwZgI956WsnLTIPGOyV0LKzxiFbMwdz1rO5Mx3LSJoN1MP3VNuAWyovtnXsl10ILXRttEfW+ZZdxi6n2R0oZdibcao5yc6ELovNUBpHBUJnVYVAFWPlrnsjffWuoGEF4WUxiPg5R08T5rLNF95oWmEdfxS8Np2VCtyTRUkOBB+zxESuIgNf9wlDF+B8h9cfUH/+gy/8KmKCPzvw4JYg+MBh5VrADT15fYQVfQ9kZ5qgSH2EfAFvVIgeN7KboBuyfaBLbqfp2lK3Mz9ZIWi/Wyoajco+6QWnu98eWX1vd5SPhhEenaxxtr3q775C93Tlg1j/PhN3GCIVCdgHSRVFKVOQlF9S7xPsfwA/49eH

**Comment by rchl** [comment] 2023-08-04 08:48
There are other issues for that. The specific case of `class` failing is what I was asking about since that should work unless it's a Vue 2 project but that's a Vue 2 types issue.

**Comment by dten** [comment] 2023-08-04 10:27
Ah nice, I found my way here searching for an issue that matches the title and the repro I gave. Do you happen to know which issue is that one 😅 ?

**Comment by so1ve** [comment] 2023-09-08 05:00
Fixed by #3487

**Comment by johnsoncodehk** [comment] 2024-05-13 17:12
Closed due to unable to reproduce in latest version.

**Closed by johnsoncodehk** 2024-05-13 17:12 UTC
Labels: bug
