### ISSUE TITLE
Generic Prop Type is incompatible with `defineModel` and Typed Slots

### ISSUE THREAD

**Issue by sxzz** [vuejs/language-tools#3179] opened 2023-05-12 11:31 UTC
Reproduction: https://github.com/artsmp0/vue-generic-type-bug

See `src/components/HelloWorld.vue` and `src/components/model-with-props-bug.vue`.

**Comment by so1ve** [comment] 2023-05-17 09:06
Found a bug here:

![](https://github.com/vuejs/language-tools/assets/58381667/0fb8f2c0-4c69-44a6-86f8-dd990790e568)

![](https://github.com/vuejs/language-tools/assets/58381667/f64058ce-1101-4b3e-940c-f699ba5d05d2)

![](https://github.com/vuejs/language-tools/assets/58381667/8c9cef72-d7e1-436a-81e7-b38cad1ab1b5)

It seems to be buggy here 👆

If we add a type assertion

![](https://github.com/vuejs/language-tools/assets/58381667/a75d8066-2192-45d1-b631-03a0a7c0fd5a)

It works perfectly.

**Comment by so1ve** [comment] 2023-05-21 05:44
Hi @pikax, could you please confirm if it is a vue core issue? The BooleanKey type does not play well with generics.

**Comment by pikax** [comment] 2023-05-21 08:11
`BooleanKey` does not play nicely with generics as you can see the fix to work with `withDefault` was to remove that https://github.com/vuejs/core/pull/8335/files 


For me (not that familiar with Language Tools) this is a bug with Language tools looking at the generated code (after update the dependencies): 
```ts
// 当使用 defineModel 时，在模板中访问 msg 报错
const count = defineModel<number>("count", {
  local: true,
  default: 999,
});
const __VLS_publicComponent = (await import('vue')).defineComponent({
props: {} as { 
"count": import('vue').PropType<number>,
},
props: ({} as __VLS_TypePropsToRuntimeProps<typeof __VLS_props>),
setup() {
return {
};
},
});
```
props is declared twice instead of merged in.

**Comment by johnsoncodehk** [comment] 2023-06-08 18:25
Duplicate of #3164

**Closed by johnsoncodehk** 2023-06-08 18:25 UTC
Labels: enhancement
