### ISSUE TITLE
When I was just using these two plugins, I couldn't load javascript language services in the vue2 project

### ISSUE THREAD

**Issue by Allisonzw** [vuejs/language-tools#3924] opened 2024-03-02 01:52 UTC
![image](https://github.com/vuejs/language-tools/assets/106040367/9f743f5b-2fe6-4e1c-8767-93055e2dfaa0)
![image](https://github.com/vuejs/language-tools/assets/106040367/165b520d-1170-4f3b-a882-5357d49f34c1)

**Comment by mseeley** [comment] 2024-03-02 02:42
Here as well. I'm testing an upgrade to `vue-tsc@2.0.1`. Local type checking is fine but VSCodes JS/TS language server is dying. VSCode (1.8.7) is using the workspace's TypeScript at `"typescript.tsdk": "node_modules/typescript/lib",`

[vue-tsc](https://github.com/vuejs/language-tools/tree/HEAD/packages/tsc)	1.8.27	2.0.1

<img width="488" alt="image" src="https://github.com/vuejs/language-tools/assets/30019/77099a83-31d3-42d8-b34b-f2dcff3a236b">

The `exthost/vscode.typescript-language-features` logs contain only this after the server starts and exits 5 times.

```
2024-03-01 16:37:53.398 [info] Starting TS Server
2024-03-01 16:37:53.398 [info] Using tsserver from: /Users/komodo/Development/komodo-book/node_modules/typescript/lib/tsserver.js
2024-03-01 16:37:53.398 [info] <syntax> Forking...
2024-03-01 16:37:53.398 [info] <syntax> Starting...
2024-03-01 16:37:53.398 [info] <semantic> Forking...
2024-03-01 16:37:53.398 [info] <semantic> Starting...
2024-03-01 16:37:54.656 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-01 16:37:54.656 [info] Starting TS Server
2024-03-01 16:37:54.656 [info] Using tsserver from: /Users/komodo/Development/komodo-book/node_modules/typescript/lib/tsserver.js
2024-03-01 16:37:54.656 [info] <syntax> Forking...
2024-03-01 16:37:54.656 [info] <syntax> Starting...
2024-03-01 16:37:54.656 [info] <semantic> Forking...
2024-03-01 16:37:54.656 [info] <semantic> Starting...
2024-03-01 16:37:55.916 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-01 16:37:55.916 [info] Starting TS Server
2024-03-01 16:37:55.916 [info] Using tsserver from: /Users/komodo/Development/komodo-book/node_modules/typescript/lib/tsserver.js
2024-03-01 16:37:55.916 [info] <syntax> Forking...
2024-03-01 16:37:55.916 [info] <syntax> Starting...
2024-03-01 16:37:55.916 [info] <semantic> Forking...
2024-03-01 16:37:55.916 [info] <semantic> Starting...
2024-03-01 16:37:57.104 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-01 16:37:57.104 [info] Starting TS Server
2024-03-01 16:37:57.104 [info] Using tsserver from: /Users/komodo/Development/komodo-book/node_modules/typescript/lib/tsserver.js
2024-03-01 16:37:57.104 [info] <syntax> Forking...
2024-03-01 16:37:57.104 [info] <syntax> Starting...
2024-03-01 16:37:57.104 [info] <semantic> Forking...
2024-03-01 16:37:57.104 [info] <semantic> Starting...
2024-03-01 16:37:58.290 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-01 16:37:58.290 [info] Starting TS Server
2024-03-01 16:37:58.290 [info] Using tsserver from: /Users/komodo/Development/komodo-book/node_modules/typescript/lib/tsserver.js
2024-03-01 16:37:58.290 [info] <syntax> Forking...
2024-03-01 16:37:58.290 [info] <syntax> Starting...
2024-03-01 16:37:58.290 [info] <semantic> Forking...
2024-03-01 16:37:58.290 [info] <semantic> Starting...
2024-03-01 16:37:59.464 [error] TSServer exited. Code: null. Signal: SIGBUS
2024-03-01 16:37:59.464 [info] Starting TS Server
2024-03-01 16:37:59.464 [info] Using tsserver from: /Users/komodo/Development/komodo-book/node_modules/typescript/lib/tsserver.js
2024-03-01 16:37:59.464 [info] <syntax> Forking...
2024-03-01 16:37:59.464 [info] <syntax> Starting...
2024-03-01 16:37:59.464 [info] <semantic> Forking...
2024-03-01 16:37:59.464 [info] <semantic> Starting...
2024-03-01 16:38:00.635 [error] TSServer exited. Code: null. Signal: SIGBUS
```

Disabling the `vue.volar` plugin resolves the issue.

Anything else we can provide?

**Comment by mseeley** [comment] 2024-03-02 02:58
[Volar Takeover Mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) is not enabled.

<img width="1305" alt="image" src="https://github.com/vuejs/language-tools/assets/30019/14afbf38-f4c1-41ba-9782-b4300d39e3ce">

**Comment by jamesWongAigniter** [comment] 2024-03-11 08:19
Downgrade "Vue - Official" extension to 1.8.27 (the latest non 2.x.x version) and the error no longer appears for me.

**Comment by so1ve** [comment] 2024-03-11 08:34
Duplicate of https://github.com/vuejs/language-tools/issues/3962

**Comment by so1ve** [comment] 2024-03-11 08:35
https://github.com/vuejs/language-tools/issues/3962 has more detailed info. Let's track at #3962.

**Closed by so1ve** 2024-03-11 08:34 UTC
