### ISSUE TITLE
<template v-for> key should be placed on the <template> tag. vue(33)

### ISSUE THREAD

**Issue by nklowns** [vuejs/language-tools#3978] opened 2024-03-04 17:25 UTC
Type: Bug

Extension version: 2.0.4
Vscode Version: 1.87.0 (user setup)
Confirmar: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Data: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
SO: Windows_NT x64 10.0.22631

Vue@2.7.16
```json
{
  "vueCompilerOptions": {
    "target": 2.7
  }
}
```

Hello, my vue2 project is showing errors that conflict with the eslint rules.
In Vue.js 2.x, disallows key attribute on <template> elements. ref: https://eslint.vuejs.org/rules/no-v-for-template-key.html

Is it possible to configure and disable the error that the language server passes to vscode? since we have a preference for eslint rules

**Comment by c0lt** [comment] 2024-03-05 07:47
See #3959

**Comment by so1ve** [comment] 2024-03-06 02:06
Duplicate of https://github.com/vuejs/language-tools/issues/3959

**Closed by so1ve** 2024-03-06 02:06 UTC
