### ISSUE TITLE
I hope to add type hint support for Vue directives

### ISSUE THREAD

**Issue by MyDataHouse** [vuejs/language-tools#4854] opened 2024-09-18 07:22 UTC
### What problem does this feature solve?

![image](https://github.com/user-attachments/assets/38e3988b-2678-490a-8d26-5d9e37b03389)

I hope to add type hint support for Vue directives.
It feels strange without type hints.

### What does the proposed solution look like?

没有建议

**Comment by KazariEX** [comment] 2024-09-18 07:55
Duplicate of #4810

**Comment by KazariEX** [comment] 2024-09-18 07:55
Duplicate of #4810

**Closed by KazariEX** 2024-09-18 07:55 UTC
Labels: feature request
