### ISSUE TITLE
Syntax highlighting broken with dynamic slot name from template literal

### ISSUE THREAD

**Issue by jf-paradis** [vuejs/language-tools#2666] opened 2023-04-21 20:54 UTC
**Problem**
When using dynamic slot names generated from a template literal, Volar's syntax highlighting gets confused.

**Actual Result**
Line 7 surfaces the issue. Notice the syntax highlighting is off for lines > 7:

<img width="516" alt="Screenshot 2023-04-21 at 1 46 12 PM" src="https://user-images.githubusercontent.com/89814003/233731996-5560bfe0-ce5e-480d-9a9f-f0917914397e.png">

**Workaround** 
Use a method to return the slot name. Moving the back tik out of the template improves syntax highlighting (although other unrelated minor issues persist):

<img width="561" alt="Screenshot 2023-04-21 at 1 45 32 PM" src="https://user-images.githubusercontent.com/89814003/233731663-74813224-d3bf-4643-b5ca-c8a10bb18133.png">

**Comment by so1ve** [comment] 2023-11-20 09:15
Duplicate of https://github.com/vuejs/language-tools/issues/854

**Closed by so1ve** 2023-11-20 09:15 UTC
