### ISSUE TITLE
When I save my Vue file, Volar insert a blank line at the second line,why?

### ISSUE THREAD

**Issue by MothWillion** [vuejs/language-tools#2386] opened 2023-02-16 02:37 UTC
![7fe9018b64d2eb1485fb72377c85fe9](https://user-images.githubusercontent.com/19945659/219253638-eeafd4d1-aa43-4081-b1d4-ef4018eda389.png)

**Comment by johnsoncodehk** [comment] 2023-02-16 02:41
Duplicate of #2385

**Closed by johnsoncodehk** 2023-02-16 02:41 UTC
