### ISSUE TITLE
Volar does not recognize component is not imported in Vue 2.7

### ISSUE THREAD

**Issue by tomaszs** [vuejs/language-tools#2324] opened 2023-01-19 11:17 UTC
Steps to reproduce:

1. Create component HelloWorld
2. Put the component into another component:

```<HelloWorld />```

Expected result:

Volar shows an error in VSCode that the component is not registered

Actual result:

Volar does not show the information.

**Comment by johnsoncodehk** [comment] 2023-02-19 19:03
Duplicate of #2291

**Closed by johnsoncodehk** 2023-02-19 19:03 UTC
