### ISSUE TITLE
Typescript linting broken for global components and third party components when using latest extension version

### ISSUE THREAD

**Issue by jaxenvisuals** [vuejs/language-tools#4525] opened 2024-07-03 13:48 UTC
### Vue - Official extension or vue-tsc version

Vue Official v2.0.24

### VSCode version

1.90.2

### Vue version

3.3.4

### TypeScript version

5.0.2

### System Info

```shell
Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor


Edition	Windows 11 Pro
Version	23H2
Installed on	‎15/‎02/‎2023
OS build	22631.3737
Experience	Windows Feature Experience Pack 1000.22700.1009.0
```

### Steps to reproduce

![image](https://github.com/vuejs/language-tools/assets/42275320/2cfca3e7-c6ab-457b-b198-399d61db70c5)
The linting you see above stopped working all of a sudden. Now it shows:
![image](https://github.com/vuejs/language-tools/assets/42275320/2027e554-53d6-4168-bc60-2a8c24111d1f)

I noticed the latest version of the Vue - Official is causing the issue.

When I downgrade the extension to v2.0.19, it begins to work again.

### What is expected?

![image](https://github.com/vuejs/language-tools/assets/42275320/2cfca3e7-c6ab-457b-b198-399d61db70c5)

### What is actually happening?

![image](https://github.com/vuejs/language-tools/assets/42275320/2027e554-53d6-4168-bc60-2a8c24111d1f)

**Comment by so1ve** [comment] 2024-07-03 15:05
Duplicate of https://github.com/vuejs/language-tools/issues/4501

**Closed by so1ve** 2024-07-03 15:05 UTC
Labels: pending triage
