### ISSUE TITLE
It keeps increasing indent when I wrap lines in script block

### ISSUE THREAD

**Issue by otomad** [vuejs/language-tools#2396] opened 2023-02-16 12:25 UTC
When `volar.format.initialIndent` is set to true and `editor.formatOnType` is set to true, like:
```json
{
	"volar.format.initialIndent": {
		"javascript": true,
		"typescript": true,
	},
	"editor.formatOnType": true,
}
```
Then when I wrap lines in script block, it keeps increasing indentation. Setting them false will work properly, but this will not match our code style.

As shown in the video:

https://user-images.githubusercontent.com/56647156/219363648-86a29d96-2071-4f21-ba75-05e45789c47b.mp4

**Comment by johnsoncodehk** [comment] 2023-02-16 12:26
Duplicate of #2394

**Closed by johnsoncodehk** 2023-02-16 12:26 UTC
