### ISSUE TITLE
vue-tsc don't see use of variable in Named Slots

### ISSUE THREAD

**Issue by DaniilIsupov** [vuejs/language-tools#2515] opened 2023-03-16 16:18 UTC
**Information about software versions:**
`vue@3.2.47`
`vue-tsc@1.2.0`
`typescript@4.9.5`
`Visual Studio Code` Version: `1.76.2`

**Problem**
"bug" variable is used, but typescript thinks otherwise
![image](https://user-images.githubusercontent.com/23086234/225684724-7e1eb07e-7906-4c82-b7c9-a60db40bb3de.png)

`vue-tsc` also gives an error
![image](https://user-images.githubusercontent.com/23086234/225683257-92046f4f-f812-454d-8d1e-3bbcba8e9917.png)

**Comment by DaniilIsupov** [comment] 2023-03-17 12:21
solution turned out to be following construction

```
        <template #content>
            <template v-if>
            </template>

            <template v-else-if>
            </template>

            <template v-else>
            </template>
        </template>
```

but problem must be solved one way or another

**Comment by johnsoncodehk** [comment] 2023-03-29 10:10
Duplicate of #625

**Closed by johnsoncodehk** 2023-03-29 10:10 UTC
