### ISSUE TITLE
[Bug] Syntax highlighting is broken when using two separate `<script>`

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/language-tools#2529] opened 2023-03-20 08:14 UTC
![image](https://user-images.githubusercontent.com/28700378/226282593-2bfa6289-e1a6-47d4-bb9d-213ce7a6df0e.png)

[Repro Link](https://github.com/wenfangdu/vite-vue-3/tree/two-scripts)

**Comment by johnsoncodehk** [comment] 2023-03-30 01:44
Duplicate of #2060

**Closed by johnsoncodehk** 2023-03-30 01:44 UTC
