### ISSUE TITLE
CSCode 插件 解构 props 染色（高亮）错误

### ISSUE THREAD

**Issue by WangJincheng4869** [vuejs/language-tools#4935] opened 2024-10-21 08:02 UTC
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

1.94.2

### Vue version

3.5.12

### TypeScript version

5.6.3

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 10.62 GB / 31.56 GB
  Binaries:
    Node: 20.16.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - D:\Users\jcwang\AppData\Roaming\npm\yarn.CMD
    npm: 10.4.0 - D:\Users\jcwang\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.3527
```

### package.json dependencies

```json
"dependencies": {
    "@babel/parser": "^7.25.8",
    "@better-scroll/core": "^2.5.1",
    "@better-scroll/mouse-wheel": "^2.5.1",
    "@better-scroll/pull-down": "^2.5.1",
    "@better-scroll/scroll-bar": "^2.5.1",
    "@ckeditor/ckeditor5-vue": "^7.2.0",
    "@designable/core": "1.0.0-beta.45",
    "@designable/formily-transformer": "1.0.0-beta.45",
    "@designable/shared": "1.0.0-beta.45",
    "@element-plus/icons-vue": "^2.3.1",
    "@formily/core": "^2.3.2",
    "@formily/grid": "^2.3.2",
    "@formily/json-schema": "^2.3.2",
    "@formily/path": "^2.3.2",
    "@formily/reactive": "^2.3.2",
    "@formily/reactive-vue": "^2.3.2",
    "@formily/shared": "^2.3.2",
    "@formily/vue": "^2.3.2",
    "@guolao/vue-monaco-editor": "^1.5.4",
    "@logicflow/core": "^2.0.6",
    "@logicflow/extension": "^2.0.10",
    "@logicflow/vue-node-registry": "^1.0.7",
    "@vueuse/components": "^11.1.0",
    "@vueuse/core": "^11.1.0",
    "@vueuse/integrations": "^11.1.0",
    "axios": "^1.7.7",
    "ckeditor5-simperfect-build": "^43.1.1",
    "classnames": "^2.5.1",
    "cropperjs": "2.0.0-rc.0",
    "dayjs": "^1.11.13",
    "decimal.js": "^10.4.3",
    "echarts": "^5.5.1",
    "echarts-wordcloud": "^2.1.0",
    "element-plus": "^2.8.6",
    "jsencrypt": "^3.3.2",
    "jwt-decode": "^4.0.0",
    "lodash": "^4.17.21",
    "lodash-es": "^4.17.21",
    "lodash-unified": "^1.0.3",
    "mark.js": "^8.11.1",
    "minimatch": "^10.0.1",
    "monaco-editor": "^0.50.0",
    "nanoid": "^5.0.7",
    "nprogress": "^0.2.0",
    "photoswipe": "^5.4.4",
    "pinia": "^2.2.4",
    "pinyin-pro": "^3.25.0",
    "prismjs": "^1.29.0",
    "recorder-core": "^1.3.24102001",
    "resize-observer-polyfill": "^1.5.1",
    "sortablejs": "^1.15.3",
    "spark-md5": "^3.0.2",
    "sql-formatter": "10.1.1",
    "video.js": "^8.18.1",
    "videojs-wavesurfer": "^3.10.0",
    "vue": "^3.5.12",
    "vue-i18n": "^10.0.4",
    "vue-router": "^4.4.5",
    "vuedraggable": "^4.1.0",
    "wavesurfer.js": "^7.8.7",
    "xlsx": "^0.20.0"
  },
  "devDependencies": {
    "@intlify/unplugin-vue-i18n": "^5.2.0",
    "@types/lodash": "^4.17.12",
    "@types/lodash-es": "^4.17.12",
    "@types/mark.js": "^8.11.12",
    "@types/node": "^20.16.13",
    "@types/nprogress": "^0.2.3",
    "@types/prismjs": "^1.26.4",
    "@types/spark-md5": "^3.0.4",
    "@vitejs/plugin-vue": "^5.1.4",
    "@vitejs/plugin-vue-jsx": "^4.0.1",
    "@vue/tsconfig": "^0.5.1",
    "@vuepress/bundler-vite": "2.0.0-rc.17",
    "@vuepress/plugin-redirect": "2.0.0-rc.52",
    "@vuepress/plugin-register-components": "2.0.0-rc.52",
    "@vuepress/plugin-shiki": "2.0.0-rc.52",
    "autoprefixer": "^10.4.20",
    "less": "^4.2.0",
    "mermaid": "^11.3.0",
    "postcss": "^8.4.47",
    "prettier": "^3.3.3",
    "rollup-plugin-visualizer": "^5.12.0",
    "sass": "~1.79.5",
    "tailwindcss": "^3.4.14",
    "typescript": "^5.6.3",
    "unplugin-auto-import": "^0.18.3",
    "unplugin-vue-components": "^0.27.4",
    "vite": "^5.4.9",
    "vite-plugin-compression2": "^1.3.0",
    "vite-plugin-prismjs": "^0.0.11",
    "vite-svg-loader": "^5.1.0",
    "vue-component-type-helpers": "^2.1.6",
    "vue-tsc": "^2.1.6",
    "vuepress": "2.0.0-rc.17",
    "vuepress-plugin-search-pro": "2.0.0-rc.57",
    "vuepress-theme-hope": "2.0.0-rc.58"
  }
```

### Steps to reproduce

```
const { type } = defineProps<{
  type: 'records' | 'pending_shipments' | 'pending_approvals' | 'your_proxy_created' | 'your_requests';
}>();
```

### What is expected?

正常染色（高亮）

### What is actually happening?

为正确染色（高亮）
![图片](https://github.com/user-attachments/assets/4d1e651a-b2d2-49ee-aacd-35496d736000)

**Comment by KazariEX** [comment] 2024-10-21 08:08
Duplicate of #4811

**Closed by KazariEX** 2024-10-21 08:08 UTC
Labels: pending triage
