### ISSUE TITLE
volar 1.4.1  element plus error

### ISSUE THREAD

**Issue by UDDDDD** [vuejs/language-tools#2655] opened 2023-04-21 06:59 UTC
<img width="913" alt="image" src="https://user-images.githubusercontent.com/54108789/233563731-839d6d80-ef30-4693-861d-7e7b6c727a16.png">

**Comment by hansonfang** [comment] 2023-04-21 07:03
same here

**Comment by KBzhu** [comment] 2023-04-21 07:08
same question，we shoule back toV1.2.0

**Comment by Tanimodori** [comment] 2023-04-21 07:17
Duplicate of #2647

**Comment by warmthsea** [comment] 2023-04-21 07:39
https://github.com/element-plus/element-plus/issues/12529

**Comment by coderwyd** [comment] 2023-04-21 08:01
Roll back the Volar version to 1.2.0 and you're good to go!

**Closed** 2023-04-21 08:31 UTC
