### ISSUE TITLE
The Vue server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information

### ISSUE THREAD

**Issue by ccf-zeno** [vuejs/language-tools#4176] opened 2024-03-29 02:24 UTC
/.vscode/extensions/vue.volar-2.0.8/dist/server.js:80
: `.concat(new Error("").stack))}}function S(D,A){return m[D]=A,A}function C(D){try{return function(A){var P=w(u.join(A,"nls.metadata.json")),j=Object.create(null);for(var N in P){var I=P[N];j[N]=I.messages}return j}(D)}catch(A){return void console.log("Generating default bundle from meta data failed.",A)}}function _(D,A){var P;if(f.languagePackSupport===!0&&f.cacheRoot!==void 0&&f.languagePackId!==void 0&&f.translationsConfigFile!==void 0&&f.translationsConfig!==void 0)try{P=function(N,I){var F,z,W,U=u.join(f.cacheRoot,"".concat(N.id,"-").concat(N.hash,".json")),q=!1,H=!1;try{return F=JSON.parse(c.readFileSync(U,{encoding:"utf8",flag:"r"})),z=U,W=new Date,c.utimes(z,W,W,function(){}),F}catch(J){if(J.code==="ENOENT")H=!0;else{if(!(J instanceof SyntaxError))throw J;console.log("Syntax error parsing message bundle: ".concat(J.message,".")),c.unlink(U,function(re){re&&console.error("Deleting corrupted bundle ".concat(U," failed."))}),q=!0}}if(F=function(J,re){var he=f.translationsConfig[J.id];if(he){var xe=w(he).contents,je=w(u.join(re,"nls.metadata.json")),ge=Object.create(null);for(var me in je){var Ae=je[me],Ne=xe["".concat(J.outDir,"/").concat(me)];if(Ne){for(var ot=[],Ue=0;Ue<Ae.keys.length;Ue++){var Qe=Ae.keys[Ue],ht=Ne[y(Qe)?Qe:Qe.key];ht===void 0&&(ht=Ae.messages[Ue]),ot.push(ht)}ge[me]=ot}else ge[me]=Ae.messages}return ge}}(N,I),!F||q)return F;if(H)try{c.writeFileSync(U,JSON.stringify(F),{encoding:"utf8",flag:"wx"})}catch(J){if(J.code==="EEXIST")return F;throw J}return F}(D,A)}catch(N){console.log("Load or create bundle failed ",N)}if(!P){if(f.languagePackSupport)return C(A);var j=function(N){for(var I=f.language;I;){var F=u.join(N,"nls.bundle.".concat(I,".json"));if(c.existsSync(F))return F;var z=I.lastIndexOf("-");I=z>0?I.substring(0,z):void 0}if(I===void 0&&(F=u.join(N,"nls.bundle.json"),c.existsSync(F)))return F}(A);if(j)try{return w(j)}catch(N){console.log("Loading in the box message bundle failed.",N)}P=C(A)}return P}function k(D){if(!D)return h.localize;var A=u.extname(D);if(A&&(D=D.substr(0,D.length-A.length)),f.messageFormat===h.MessageFormat.both||f.messageFormat===h.MessageFormat.bundle){var P=function(q){for(var H,J=u.dirname(q);H=u.join(J,"nls.metadata.header.json"),!c.existsSync(H);){var re=u.dirname(J);if(re===J){H=void 0;break}J=re}return H}(D);if(P){var j=u.dirname(P),N=m[j];if(N===void 0)try{var I=JSON.parse(c.readFileSync(P,"utf8"));try{var F=_(I,j);N=S(j,F?{header:I,nlsBundle:F}:null)}catch(q){console.error("Failed to load nls bundle",q),N=S(j,null)}}catch(q){console.error("Failed to read header file",q),N=S(j,null)}if(N){var z=D.substr(j.length+1).replace(/\\/g,"/"),W=N.nlsBundle[z];return W===void 0?(console.error("Messages for file ".concat(D," not found. See console for details.")),function(){return"Messages not found."}):b(W)}}}if(f.messageFormat===h.MessageFormat.both||f.messageFormat===h.MessageFormat.file)try{var U=w(function(q){var H;if(!(f.cacheLanguageResolution&&H)){if(h.isPseudo||!f.language)H=".nls.json";else for(var J=f.language;J;){var re=".nls."+J+".json";if(c.existsSync(q+re)){H=re;break}var he=J.lastIndexOf("-");he>0?J=J.substring(0,he):(H=".nls.json",J=null)}f.cacheLanguageResolution}return q+H}(D));return Array.isArray(U)?b(U):(0,h.isDefined)(U.messages)&&(0,h.isDefined)(U.keys)?b(U.messages):(console.error("String bundle '".concat(D,"' uses an unsupported format.")),function(){return"File bundle has unsupported format. See console for details"})}catch(q){q.code!=="ENOENT"&&console.error("Failed to load single file bundle",q)}return console.error("Failed to load message bundle for file ".concat(D)),function(){return"Failed to load message bundle. See console for details."}}function E(D){return D&&(y(D.locale)&&(f.locale=D.locale.toLowerCase(),f.language=f.locale,m=Object.create(null)),D.messageFormat!==void 0&&(f.messageFormat=D.messageFormat),D.bundleFormat===h.BundleFormat.standalone&&f.languagePackSupport===!0&&(f.languagePackSupport=!1)),(0,h.setPseudo)(f.locale==="pseudo"),k}(function(){if(f={locale:void 0,language:void 0,languagePackSupport:!1,cacheLanguageResolution:!0,messageFormat:h.MessageFormat.bundle},y(process.env.VSCODE_NLS_CONFIG))try{var D=JSON.parse(process.env.VSCODE_NLS_CONFIG),A=void 0;if(D.availableLanguages){var P=D.availableLanguages["*"];y(P)&&(A=P)}if(y(D.locale)&&(f.locale=D.locale.toLowerCase()),A===void 0?f.language=f.locale:A!=="en"&&(f.language=A),function(N){return N===!0||N===!1}(D._languagePackSupport)&&(f.languagePackSupport=D._languagePackSupport),y(D._cacheRoot)&&(f.cacheRoot=D._cacheRoot),y(D._languagePackId)&&(f.languagePackId=D._languagePackId),y(D._translationsConfigFile)){f.translationsConfigFile=D._translationsConfigFile;try{f.translationsConfig=w(f.translationsConfigFile)}catch{if(D._corruptedFile){var j=u.dirname(D._corruptedFile);c.exists(j,function(I){I&&c.writeFile(D._corruptedFile,"corrupted","utf8",function(F){console.error(F)})})}}}}catch{}(0,h.setPseudo)(f.locale==="pseudo"),m=Object.create(null)})(),a.loadMessageBundle=k,a.config=E,p.default.install(Object.freeze({loadMessageBundle:k,config:E}))},374:(o,a)=>{function l(){}Object.defineProperty(a,"__esModule",{value:!0}),a.default=function(u){return l}},491:o=>{"use strict";o.exports=require("assert")},361:o=>{"use strict";o.exports=require("events")},147:o=>{"use strict";o.exports=require("fs")},685:o=>{"use strict";o.exports=require("http")},687:o=>{"use strict";o.exports=require("https")},808:o=>{"use strict";o.exports=require("net")},17:o=>{"use strict";o.exports=require("path")},404:o=>{"use strict";o.exports=require("tls")},310:o=>{"use strict";o.exports=require("url")},796:o=>{"use strict";o.exports=require("zlib")}},n={},r=function o(a){var l=n[a];if(l!==void 0)return l.exports;var u=n[a]={exports:{}};return e[a].call(u.exports,u,u.exports,o),u.exports}(539),i=t;for(var s in r)i[s]=r[s];r.__esModule&&Object.defineProperty(i,"__esModule",{value:!0})})()}}),jL={};eae(jL,{config:()=>lae,t:()=>NL});FL.exports=nae(jL);var iae=require("fs"),sae=require("fs/promises"),AL=tae(rae());async function oae(t){if(t.protocol==="file:")return await(0,sae.readFile)(t,"utf8");if(t.protocol==="http:"||t.protocol==="https:")try{let e=await(0,AL.xhr)({url:t.toString(),followRedirects:5,headers:{"Accept-Encoding":"gzip, deflate",Accept:"application/json"}});return new TextDecoder().decode(e.body)}catch(e){throw new Error(e.responseText??(0,AL.getErrorStatusDescription)(e.status)??e.toString())}throw new Error("Unsupported protocol")}function aae(t){return(0,iae.readFileSync)(t,"utf8")}var vm;function lae(t){if("contents"in t){typeof t.contents=="string"?vm=JSON.parse(t.contents):vm=t.contents;return}if("fsPath"in t){let e=aae(t.fsPath),n=JSON.parse(e);vm=DL(n)?n.contents.bundle:n;return}if(t.uri){let e=t.uri;return typeof t.uri=="string"&&(e=new URL(t.uri)),new Promise((n,r)=>{let i=oae(e).then(s=>{try{let o=JSON.parse(s);vm=DL(o)?o.contents.bundle:o}catch(o){r(o)}}).catch(s=>{r(s)});n(i)})}}function NL(...t){let e=t[0],n,r,i;if(typeof e=="string")n=e,r=e,t.splice(0,1),i=!t||typeof t[0]!="object"?t:t[0];else if(e instanceof Array){let o=t.slice(1);if(e.length!==o.length+1)throw new Error("expected a string as the first argument to l10n.t");let a=e[0];for(let l=1;l<e.length;l++)a+=`{${l-1}}`+e[l];return NL(a,...o)}else r=e.message,n=r,e.comment&&e.comment.length>0&&(n+=`/${Array.isArray(e.comment)?e.comment.join(""):e.comment}`),i=e.args??{};let s=vm?.[n];return s?typeof s=="string"?_y(s,i):s.comment?_y(s.message,i):_y(r,i):_y(r,i)}var uae=/{([^}]+)}/g;function _y(t,e){return t.replace(uae,(n,r)=>e[r]??n)}function DL(t){return typeof t?.contents?.bundle=="object"&&typeof t?.version=="string"}});var OL=L(Ey=>{"use strict";Object.defineProperty(Ey,"__esModule",{value:!0});Ey.createConfigurationHost=void 0;var cae=La();function pae(t,e){let n=new Set,r=new Map;return e.onDidChangeConfiguration(async()=>{r.clear();for(let s of n)s()}),{ready(){t.capabilities.workspace?.didChangeConfiguration?.dynamicRegistration&&e.client.register(cae.DidChangeConfigurationNotification.type)},async getConfiguration(s,o){return!o&&t.capabilities.workspace?.d[Error - 10:20:34] Server process exited with code 1.
[Error - 10:20:34] The Vue server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

<img width="569" alt="image" src="https://github.com/vuejs/language-tools/assets/31329597/7c46b834-17a7-4fd5-ae4d-f2e16bec94be">

**Comment by lecepin** [comment] 2024-03-29 08:39
Fallback to v2.0.7

**Comment by johnsoncodehk** [comment] 2024-03-29 15:24
Duplicate of #4130

**Closed by johnsoncodehk** 2024-03-29 15:24 UTC
