### ISSUE TITLE
Auto-import breaks constantly

### ISSUE THREAD

**Issue by Tenrys** [vuejs/language-tools#3730] opened 2023-11-13 14:43 UTC
Hello, I don't really know how to formulate this issue as I don't understand where it could be coming from and haven't really found a pattern to it.

I'm developing an application using the Quasar Framework with Volar, and whether or not I use Takeover Mode, I am constantly irritated by the fact that whenever I call Intellisense with Ctrl+Space, more often than not, there will be no suggestions for me to use for auto-importing, whether it's from an node_module (even from `vue`) or some local file in my project. Typically, I have to use the `Volar > Reload project` command for it to start working again, only for the same issue to reoccur in another file again anyways.

I haven't done anything specific to my `tsconfig.json`, following the exact same configuration settings as Quasar Framework recommends. I install my dependencies using yarn v1, so there isn't any particular magic to how my modules are being installed to my project. I don't have a `volar.config.js` file, and even if I wanted to create one to test out things, I can't figure out where the documentation for that file can be found. I looked as far as I could into every configuration setting possible, and I can't see anything that looks to be out of the ordinary. I don't think it's any extension of mine, either.

As far as I can remember, I've only ever encountered this issue in Vue files. I have to assume this is because Volar likely works differently from the normal TypeScript server, since it doesn't follow the same configuration settings, and creates its own separate server.

I have been hearing about an upcoming v2 of the language tools that would reuse the VSCode TypeScript server, do I have to wait for that to come out to hope for a more stable experience? Or is there some other way to fix this? Of course, I can provide any other details that could be of any help as needed.

**Comment by sadeghbarati** [comment] 2023-11-15 06:25
Install this extension and see how many target files you have, if some targets are **redundant** exclude them in `tsconfig.json`

https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-tsconfig-helper

**Comment by desaroger** [comment] 2023-11-15 10:31
Using VSCode with this extension, when I open a `*.vue` file and I manually run `Volar: Restart Vue server`, I can see all the types of all the global components that were auto-imported (I am using Nuxt 3 with `@bg-dev/nuxt-naiveui` module), all components show up in green, mouse hover shows types info, etc. As soon as I change anything in that file, types are gone, components shows in blue instead of green, and types are now `any`.

**Comment by Tenrys** [comment] 2023-11-15 13:06
> Install this extension and see how many target files you have, if some targets are **redundant** exclude them in `tsconfig.json`
> 
> [marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-tsconfig-helper](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-tsconfig-helper)
> 
> Also, try VSCode profile features I don't know how many extensions you have, but you can create a Vue profile and install Vue-specific extensions
> 
> ![image](https://user-images.githubusercontent.com/17789047/283023673-98dd3543-ea56-4cd5-9d2a-5a051beb20bd.png)

I'm not sure what you mean by "redundant", after installing the extension.

I made a separate profile just for Vue development to see if trimming down unnecessary extensions would help, but that doesn't seem to be the case.

**Comment by Tenrys** [comment] 2023-11-15 13:51
I don't get it... I made another profile without any extensions, with my usual settings, and started installing some extensions, can't reproduce. However, with that other profile I made where I uninstalled some extensions and kept others, if I do an extension bisect, even with *just* Volar enabled, I can reproduce. Is it possible that a disabled extension can affect the plugin??

**Comment by Tenrys** [comment] 2023-11-15 14:15
Okay, so I've reduced the "bugged" profile down, which had imported all of my installed extensions, to just Volar installed. The bug consistently happens there.

With another profile that hasn't imported my extensions, I installed just Volar as well, and I can't reproduce. 

I can't even begin to imagine what the issue is... I'll try and compare both exports of the profiles, and if I really can't figure out anything I might reset everything.

**Comment by Tenrys** [comment] 2023-11-15 14:21
Oh... Well this is stupid. I figured out after checking the diffs that I was using the pre-release versions of the extension all this time, for some reason. The default versions work just fine...

**Comment by sadeghbarati** [comment] 2023-11-15 14:23
I have these extensions

- https://marketplace.visualstudio.com/items?itemName=Vue.volar
- https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin

[and disabled VSCode's built-in TS language](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode)

**Comment by Tenrys** [comment] 2023-11-15 14:27
> Oh... Well this is stupid. I figured out after checking the diffs that I was using the pre-release versions of the extension all this time, for some reason. The default versions work just fine...

With this in mind, maybe it's worth it to try out versions past 1.2.0 to see where the breaking change happened?

**Comment by Tenrys** [comment] 2023-11-15 14:31
Seems like using 1.4.0 which is the version that is available right after 1.2.0 causes the issue to rise up once more, though it looks a little different.

**Comment by hardeath950** [comment] 2023-11-20 20:45
> Using VSCode with this extension, when I open a `*.vue` file and I manually run `Volar: Restart Vue server`, I can see all the types of all the global components that were auto-imported (I am using Nuxt 3 with `@bg-dev/nuxt-naiveui` module), all components show up in green, mouse hover shows types info, etc. As soon as I change anything in that file, types are gone, components shows in blue instead of green, and types are now `any`.

exact same problem here, but using nuxt 3 + nuxtUI

**Comment by hardeath950** [comment] 2023-11-20 21:27
@Tenrys @desaroger 
do you use i18n nuxt module?

apparently my problem resolved after removing the import

**Comment by UfukUstali** [comment] 2023-11-21 18:33
I was able to create a [minimal reproduction](https://github.com/UfukUstali/minimal-reproduction)  derived from the modules that i had installed.

Clone the minimal reproduction above and run `pnpm i` or if you want to do it yourself:

For pnpm:

1. Start a new project with `pnpm dlx nuxi@latest init <project-name>`
2. Install \@nuxtjs/i18n with `pnpm add -D @nuxtjs/i18n@next` and add it in `modules`
3. Install \@nuxt/ui with `pnpm add @nuxt/ui` and add it in `modules`
4. Run `pnpm postinstall` to generate the types
5. `Ctrl/⌘ + Shift + P` search for `Volar: Restart Vue server`
6. Open a file that you haven't already opened or change something in the current file

I still haven't found the reason why but I am leaving this one here for those that are interested.

**Comment by hardeath950** [comment] 2023-11-21 19:23
@UfukUstali 

There is a recommendation in the nuxt i18n repository about using the Edge channel.

by doing this it worked.

It appears that the error is being corrected and will soon arrive in a new RC


[i18n-edge-release-channel](https://github.com/nuxt-modules/i18n#edge-release-channel)

![image](https://github.com/vuejs/language-tools/assets/21207498/7734d895-2299-4cc1-bfa9-6a022720c9d5)

**Comment by Tenrys** [comment] 2023-12-01 10:01
> @Tenrys @desaroger do you use i18n nuxt module?
> 
> apparently my problem resolved after removing the import

I use Quasar Framework.

Now it seems like the release version is 1.8.24, and the issue still persists. I'm going to keep using 1.2.0 for the time being...

**Comment by AntonioDell** [comment] 2023-12-11 10:03
I have the same problem like @Tenrys and reverting to Volar 1.2.0 is the only solution. I tried all major versions (11.4.0, 1.6.0 and 1.8.0/1.8.25) and I only get auto import for 1.2.0.
This is sad, because I 'd like to be up to date to benefit from new features and fixes...

Since the project it happens in doesn't use nuxt nor nuxt/i18n I don't think that this is the issue.

**Comment by so1ve** [comment] 2023-12-11 10:54
Could you please try https://github.com/vuejs/language-tools/discussions/3789?

**Comment by AntonioDell** [comment] 2023-12-11 12:59
@so1ve I managed to get it back working with 1.8.25 by using Typescript 5.2.2.

Previously I used TS 5.3.2 and that broke the auto import. See my reply [here](https://github.com/nuxt/nuxt/discussions/22284#discussioncomment-7819500) also.

**Comment by gilney-canaltelecom** [comment] 2023-12-21 18:03
Tried version 1.2.0 and 1.8.25 + ts 5.2.2 and still no luck... If i reload the vscode window -> create a vue file -> import the component in another component, then the auto-complete works!, but after that, if i create another vue file and try to import it, puff, no auto-complete and i get no error in any of the OUTPUT 'channels'. ;/

I just created a vue project using 'npm create vue@latest', but i'm using options API, so there is nothing too fancy that is causing the problem... 

I guess i will have to give up on vue+ts, hum? 🤔

**Comment by SvenSchoene** [comment] 2024-01-09 21:52
I also have this issue, extensively. `Volar: Restart Vue Server` or `Volar: Reload Project` are things I have to trigger constantly.

My naive observation: It gets progressively worse as our codebase grows. (We currently have 123 *.vue-files and 117 *.js-files in 196 directories our project.)

I'm not too motivated right now to try https://github.com/vuejs/language-tools/discussions/3789 this out, but I'm eagerly awaiting the outcome of this.

**Comment by davidmatter** [comment] 2024-07-07 13:23
Please check if this issue has been resolved in version 2.x. If not, feel free to create a new one.

**Closed by davidmatter** 2024-07-07 13:23 UTC
